### ISSUE TITLE
registrants list is inconsistent

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#100]
1. load an SRM
2. users "Hung", "ksmith", "lightspeed" and "user" all registered in the SRM
3. login as user, go into the room, see Registrants list

expected: registrants list should be consistent.
actual: see screenshot.
![list](https://cloud.githubusercontent.com/assets/4590317/3348739/a71dde0e-f93d-11e3-8461-811552c62bca.jpg)

**Comment by skyhit** [comment]
The registrants list is for users assigned to this room.
