### ISSUE TITLE
Practice Problem Feedback after submitting

### ISSUE THREAD

**Issue by singhns** [cloudspokes/arena-web#1006]
1.  After submitting I dont know what to do, how do I see I was right ?
2.  There is no indication I actually have submitted (there is the dialog, but afterwards, you cant tell if you ever submitted - ie if you go back to it after a while).

**Comment by skyhit** [comment]
1. after submission，your solution will get a temp score， but your solution
   Still need to pass the system testing
2. Yes, we should put some info in Coding page too.

**Comment by skyhit** [comment]
1. You mean for practice problem, we will add system testing and more functions and info

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#80
