### ISSUE TITLE
Can't open others' code from "Challenges & Leaderboard" view

### ISSUE THREAD

**Issue by pivanof** [cloudspokes/arena-web#1008]
I competed first time using web arena and during the challenge phase I couldn't open others' code to challenge. Later I found that I can open code from "Match Summary" panel, but it shows only top 4 contestant in the room. For all others I can't view their code at all.
If that matters my browser is Chrome on Chrome OS.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#82
