### ISSUE TITLE
timezone is displayed differently in different platforms

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#101]
1. login as Yoshi in Mac+Chrome 35 
2. login as ksmith in win8 + IE11
3. go into an SRM room, observe the time

expected: the timezone should be in both "CST"
actual: see screenshots. one is "GMT +0800", the other is "CST".

![tm](https://cloud.githubusercontent.com/assets/4590317/3348809/3346d8a0-f942-11e3-839c-e9692eede50a.jpg)
![k](https://cloud.githubusercontent.com/assets/4590317/3348811/6a12d9ec-f942-11e3-96e1-ad6ccc942331.jpg)

**Comment by delemach** [comment]
@winterflame which is which please?

**Comment by winterflame** [comment]
Hi delemach, 
If I remember correctly - 
The first screenshot is from Win 8 + IE11, the second one is from Mac + Chrome.
