### ISSUE TITLE
Web-Arena: System messages are not displayed in the Chat (Common)

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1014]
Env: Windows7 Chrome39 

Steps:
1. Go to https://arena.topcoder.com and login with valid user account
2. In Chat Room 1, send a general chat message
3. In another browser go to the same site but login with a different account (say user2)
4. In Chat Room 2, send a general chat message (as user 2)
5. Then Logout the user2
6. observe the chat room messages in User1

Actual:

User one cannot see any System Generated messages like, “user 2 joined the chat” or “user 2 left the chat”

Expected:

System generated messages should be displayed in General Chat.

Bughunt: Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
this is revised to use animation in the who's here section
