### ISSUE TITLE
Web-Arena: There is no space after “:” [Common]

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1016]
Env: Windows7 Chrome39

Steps:
1. Go to https://arena.topcoder.com and login with valid user account
2. In the Active Matches screen -> Profile Overview & Important messages,  observe each entry

Actual:

There is no space after “:”. Please see the screenshot

Expected:

There should be space after “:”

Screenshot:

![1](https://cloud.githubusercontent.com/assets/5114190/5213384/1690e65c-7632-11e4-95ad-0ef867986502.png)

**Comment by skyhit** [comment]
that is fine. no change needed.
