### ISSUE TITLE
[Common] Feedback pop up overlap with the Match Schedule items

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1017]
## Description

[Common] Feedback pop up overlap with the Match Schedule items
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
Click 'Match Schedule'
Now click 'Feedback'

Check the Layout
## Expected result

Must fix the Issue
- Must not overlap
## Actual result

Feedback pop up overlap with the Match Schedule items
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
screenshot?

**Comment by skyhit** [comment]
close this. #1036
