### ISSUE TITLE
[Light Theme]Layout Issue in the 'Sys. Test' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1018]
## Description

Layout Issue in the 'Sys. Test' section
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
Click 'ENTER' from the 'Active Matches'
Check the right hand side panel
## Expected result

Must fix the Issue
- Must display in line
## Actual result

Layout Issue in the 'Sys. Test' section
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/5178361/0c4a3084-7490-11e4-82f3-e626fcb53178.png)

![2 1](https://cloud.githubusercontent.com/assets/4592712/5178367/1b53c09a-7490-11e4-8764-2cea7d4d2a83.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#85
