### ISSUE TITLE
[Common][Orange Theme] 'Rating Key' Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1019]
## Description

[Common][Orange Theme] 'Rating Key' Layout Issue
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Rating Key' in Chat Room

Scroll the list using mouse
## Expected result

Must fix the Issue
- Must not display double entried while scrolling
## Actual result

'Rating Key' Layout Issue
## Image

![5](https://cloud.githubusercontent.com/assets/4592712/5178416/4dd5b81a-7491-11e4-9d0d-98d62fbafd41.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
duplicate.
