### ISSUE TITLE
[Common] Filter section overlap with the Top Menu section when we scroll up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1020]
## Description

[Common] Filter section overlap with the Top Menu section when we scroll up
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
Click 'ENTER' from the 'Active Matches'
Now click 'Challenges & Leaderboard'
Expand any table from 'Summary'
Click on Filter
Scroll up
## Expected result

Must fix the Issue
- Must not overlap
## Actual result

[Common] Filter section overlap with the Top Menu section when we scroll up
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/5178337/ffdfb242-748f-11e4-9352-154d34796a7b.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#86
