### ISSUE TITLE
[Common][Light Theme] Filter icon is not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1021]
## Description

[Common][Light Theme] Filter icon is not visible
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'ENTER' from the Contest
Click 'Challenges & Leaderboard'

Check the Filter icon in the 'Room Leaderboard'
## Expected result

Must fix the Issue
- Must use another color
## Actual result

Filter icon is not visible
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
invalid, because of missing image.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#44
