### ISSUE TITLE
[Common][Orange Theme] 'Activate Users (x)' section below border issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1022]
## Description

[Common][Orange Theme] 'Activate Users (x)' section below border issue
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Activate Users (x)'

Check the bottom border Layout
## Expected result

Must fix the Issue
- Must display the below birder fully
## Actual result

'Activate Users (x)' section below border issue
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/5178376/36157ea0-7490-11e4-9d1b-cd2e98636463.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#45
