### ISSUE TITLE
[Common][Orange Theme] Yellow color used to represent 'Points' is not clear

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1023]
## Description

[Common][Orange Theme] Yellow color used to represent 'Points' is not clear
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Practice Problem'

Check the 250, 300, 500 problem point colors
## Expected result

Must fix the Issue
- Must use another color
## Actual result

Yellow color used to represent 'Points' is not clear
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/5178380/49ac6e88-7490-11e4-9085-dfe76c803242.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
no change needed. as it follows the design.
