### ISSUE TITLE
[Common]Feedback form won't close when we change the pages

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1024]
## Description

[Common]Feedback form won't close when we change the pages
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Match Schedule'
Click 'Feedback Form'
Click 'Lobby' again

Feedback form won't close/hide
## Expected result

Must fix the Issue
- Must hide the feedback form
## Actual result

Feedback form won't close when we change the pages
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/5178402/d9303fee-7490-11e4-8aa0-60d7d04cd0e7.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#46
