### ISSUE TITLE
[Common]Feedback form overlap with the scroll bar in IE

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1025]
## Description

[Common]Feedback form overlap with the scroll bar in IE
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Feedback Form'
## Expected result

Must fix the Issue
## Actual result

Feedback form overlap with the scroll bar in IE
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/5178430/89e77cda-7491-11e4-89ca-3d7312cca2df.png)
## Environment

IE 10,11 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#47
