### ISSUE TITLE
[Common] When we close the notification pop up, message pop up also closed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1027]
## Description

[Common] When we close the notification pop up, message pop up also closed
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'ENTER' from the Active Matches
Wait till notification displayed
If displayed, click on message icon
It will open the message pop up from the behind
Now close the pop up notification baloon by (x)

Message pop up also closed
## Expected result

Must fix the Issue
- Must close only the notification baloon
## Actual result

When we close the notification pop up, message pop up also closed
## Image

![11](https://cloud.githubusercontent.com/assets/4592712/5178485/ce1876ec-7492-11e4-9404-3020b56cd839.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#48
