### ISSUE TITLE
[Common] Refresh button of 'Active Users' overlap with the Feedback pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1028]
## Description

[Common] Refresh button of 'Active Users' overlap with the Feedback pop up
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Active Users' and expand it
Now Click Feedback icon

check the Refresh button
## Expected result

Must fix the Issue
- Must not overlap
## Actual result

Refresh button of 'Active Users' overlap with the Feedback pop up
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/5178499/57b3429c-7493-11e4-9208-ae01354c832b.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#49
