### ISSUE TITLE
[Common] Text in the Feedback pop up won't clear when we go to another page

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1029]
## Description

[Common] Text in the Feedback pop up won't clear when we go to another page
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Now Click Feedback icon
Enter any text to it
Click Feedback button to hide it
Go to another page
Click Feedback icon

Check the content
## Expected result

Must fix the Issue
- Must clear the content
## Actual result

Text in the Feedback pop up won't clear when we go to another page
## Image

![13](https://cloud.githubusercontent.com/assets/4592712/5178497/53455e16-7493-11e4-9f18-b49523467e21.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#50
