### ISSUE TITLE
[Common] No Twitter icon in the 'Profile Overview & Important Messages' in IE

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1030]
## Description

[Common] No Twitter icon in the 'Profile Overview & Important Messages' in IE
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Expand the 'Profile Overview & Important Messages'

Check the twitter icon
## Expected result

Must fix the Issue
- Must have twitter account icon
## Actual result

No Twitter icon in the 'Profile Overview & Important Messages' in IE
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/5178551/20e559e8-7494-11e4-90c2-8acd25d44d31.png)
## Environment

IE 10,11 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#51
