### ISSUE TITLE
[Common] Active Users sort by 'R' Even users won't have rating

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1031]
## Description

[Common] Active Users sort by 'R' Even users won't have rating
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Expand the 'Active Users (X)'

Click 'Handle' to sort the list
Now click 'R' to sort the list
## Expected result

Must fix the Issue
- Must not sort from 'R' If users in the list won't have Ratings
## Actual result

Active Users sort by 'R' Even users won't have rating
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/5178661/5d318334-7496-11e4-9908-95913da4c055.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
this is a special case, let's leave it.
