### ISSUE TITLE
[Common] When user click Twitter icon, it already have "I" on it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1032]
## Description

[Common] When user click Twitter icon, it already have "I" on it
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Contest Registration Phase is ON
Click Register

Now in the 'Active Matches' Section
Click Twitter Icon

Check the content
## Expected result

Must fix the Issue
- Must display complete message or must remove the "I"
## Actual result

When user click Twitter icon, it already have "I" on it
## Image

![16](https://cloud.githubusercontent.com/assets/4592712/5178676/cc564074-7496-11e4-824c-ef07d7c12631.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#52
