### ISSUE TITLE
'Event Registration' Pop up Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1033]
## Description

'Event Registration' Pop up Layout Issue
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Contest Registration Phase is ON
Click Register

Check the 'Event Registration' Pop up
## Expected result

Must fix the Issue
- The Information box is not aligned properly from left and right
## Actual result

'Event Registration' Pop up Layout Issue
## Image

![17](https://cloud.githubusercontent.com/assets/4592712/5178696/42fe802e-7497-11e4-8cd4-17fbf2a58e2b.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#53
