### ISSUE TITLE
[Common] All the Pop up models are not aligned properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1034]
## Description

[Common] All the Pop up models are not aligned properly
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Contest Registration Phase is ON
Click Register

Check the 'Event Registration' Pop up

OR

Click Messages Icon
Click on a Message
Check the pop up

OR

Any other occurance
## Expected result

Must fix the Issue
- All the pop up boxes are not aligned properly from left and right sides
- They must center aligned when opened
## Actual result

All the Pop up models are not aligned properly
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/5178709/83ff86f4-7497-11e4-90f7-87d507b4b0a3.png)

![18 1](https://cloud.githubusercontent.com/assets/4592712/5178746/1150c14e-7498-11e4-96ce-32b86bdb35ee.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#54
