### ISSUE TITLE
Layout Issue in the scroll bar in 'Match Plan'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1035]
## Description

Layout Issue in the scroll bar in 'Match Plan'
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click '24' from the 'Match Plan'
check the scroll bar
## Expected result

Must fix the Issue
- Scroll bar must display with in the container
## Actual result

Layout Issue in the scroll bar in 'Match Plan'
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/5178771/7ea60a24-7498-11e4-8b0c-704dcbed1aec.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#55
