### ISSUE TITLE
Feedback overlap with the 'Match Plan' items

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1036]
## Description

Feedback overlap with the 'Match Plan' items
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click '24' from the 'Match Plan'
Now expand the Feedback form
## Expected result

Must fix the Issue
- Must not overlap
## Actual result

Feedback overlap with the 'Match Plan' items
## Image

![20 1](https://cloud.githubusercontent.com/assets/4592712/5178885/e2bf05ae-749a-11e4-93ef-38395365ef67.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#56
