### ISSUE TITLE
Room leaderboard top section hides

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1037]
## Description

Room leaderboard top section hides
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
Click on Room Leaderboard

Check the title bar
## Expected result

Must fix the Issue
- Must display them
## Actual result

Room leaderboard top section hides
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/5179052/7172cbb2-749d-11e4-90c6-7c6212f4832d.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#57
