### ISSUE TITLE
Filter box layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1038]
## Description

Filter box layout Issue
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
Click on Room Leaderboard

Click Expand
Now click on the Filter
Scroll up/Down
Check the Filter box
## Expected result

Must fix the Issue
## Actual result

Filter box layout Issue
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/5179050/6ae38f02-749d-11e4-842a-94d41f631085.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#58
