### ISSUE TITLE
Layout Issue when we click on the 'Room #' column

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1039]
## Description

Layout Issue when we click on the 'Room #' column
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
Click on Room Leaderboard

Click on the 'Room #' column
## Expected result

Must fix the Issue
- Must display the Sort icon inline with the text
## Actual result

Filter box layout Issue
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/5178955/3f0f41d8-749c-11e4-80f8-1f8755c1eb31.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#59
