### ISSUE TITLE
Scroll Bar overlap with the 'Room Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1040]
## Description

Scroll Bar overlap with the 'Room Leaderboard'
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
In the Coding area enter some code
Click on Room Leaderboard

Check the Scroll bar
## Expected result

Must fix the Issue
- Scroll bar Must display below the 'Room Leaderboard'
## Actual result

Scroll Bar overlap with the 'Room Leaderboard'
## Image

![24](https://cloud.githubusercontent.com/assets/4592712/5179041/3bb18fd6-749d-11e4-9ba4-6ad065de0b93.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#60
