### ISSUE TITLE
Test Panel overlap with the 'Room Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1041]
## Description

Test Panel overlap with the 'Room Leaderboard'
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
In the Coding area enter some code
Click compile and Submit
Now click 'Test Panel'
## Expected result

Must fix the Issue
- Must not overlap
## Actual result

Test Panel overlap with the 'Room Leaderboard'
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/5179198/b4d8b91e-749f-11e4-8b9d-afec59037839.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#88
