### ISSUE TITLE
Can't chat when we expand the pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1043]
## Description

Can't chat when we expand the pop up
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
In the Coding area enter some code
Click compile and Submit
Click on the Chat window
Expand it
try to chat
## Expected result

Must fix the Issue
- Able to chat when we expand the pop up
## Actual result

Can't chat when we expand the pop up
## Image

![27 1](https://cloud.githubusercontent.com/assets/4592712/5179619/c34931c6-74a5-11e4-80db-55a3cc1bae92.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#62
