### ISSUE TITLE
Room Leaderboard is not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1044]
## Description

Room Leaderboard is not visible
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
In the Coding area enter some code
Click compile and Submit
Do it to all the problems

When the Coding phase ends
Go to Room Leaderboard

Check the standings
## Expected result

Must fix the Issue
- Must display the room leaderboard
## Actual result

Room Leaderboard is not visible
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/5179653/4d467e56-74a6-11e4-9f10-a19625fcd8d8.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#63
