### ISSUE TITLE
TestCase#a4350000000CwkoAAC: Username information is not displayed when Clicked on Handle name in Chat section 

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1045]
Testcase:#a4350000000CwkoAAC (Point 3)
1. Go to  https://arena.topcoder.com and login with valid credentials
2. Go to Chat Room 1
3. In the Chat Area, Click any of the handle
4. Observe

Actual:

Clicking on handle name in the Chat Area is not showing user's info.

Expected:

As per the test case# a4350000000CwkoAAC , step:3, User should be able to view the user's info by clicking on the handle name.

Also the test case title says, "user information is visible when click on handle names **throughout the arena**"

Screencast: https://www.dropbox.com/s/3a1fzsq9ey4cvry/RowNo07-a4350000000CwkoAAC.swf?dl=0

**Comment by nithyaasworld** [comment]
Even I tried double-clicking. It not working in the chat area!. It works in "Who's here" section.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#64
