### ISSUE TITLE
[a4350000000CwONAA0, a4350000000CwOMAA0, a4350000000CwOLAA0, a4350000000CwkvAAC,a4350000000CwkrAAC]  Pop up saying "You cannot submit unless you have successfully compiled first." should be displayed is not displaying

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1046]
## Description

[a4350000000CwONAA0, a4350000000CwOMAA0, a4350000000CwOLAA0, a4350000000CwkvAAC,a4350000000CwkrAAC]  Pop up saying "You cannot submit unless you have successfully compiled first." should be displayed is not displaying
## Steps
1. Hit url : https://arena.topcoder.com/#/a/home
2. Login using your email or social sites
3. Register for a contest
4. Once the coding phase starts, click Enter
5. From the problems list given in right sidebar click the link "Unopened"
6. Once reading through the problem, click gear icon from coding area
7. Choose the language as VB.NET and click OK
8. Enter your code in coding area with a missing, say "}" or ";"
9. Click Compile
10. Now click Submit and click Yes on the confirmation window
11. Correct the code and then click Compile
12. Once successfull click Submit and click Yes on the confirmation window
## Expected result

Must fix the Issue
- Must display the pop up
## Actual result

[a4350000000CwONAA0, a4350000000CwOMAA0, a4350000000CwOLAA0, a4350000000CwkvAAC,a4350000000CwkrAAC]  Pop up saying "You cannot submit unless you have successfully compiled first." should be displayed is not displaying
## Image

![29](https://cloud.githubusercontent.com/assets/4592712/5182317/bed6860e-74c6-11e4-96eb-0d6575f904a5.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#65
