### ISSUE TITLE
[a4350000000CwO4AAK]  Not able to register through existing Facebook account

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1047]
## Description

[a4350000000CwO4AAK]  Not able to register through existing Facebook account
## Steps
1. Hit url : https://arena.topcoder.com/#/a/home
2. Click "Click here to Register" link
3. Once the page redirects to "http://www.topcoder.com/?action=callback" and hit enter
4. Click Facebook icon
5. Enter facebook credentials and login
## Expected result

Must fix the Issue
- Must able to register via Facebook
## Actual result

Not able to register through existing Facebook account
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/5184050/23e4bbfc-74da-11e4-8369-76adc2791d97.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
should be setup issue.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#23
