### ISSUE TITLE
New message popup is not closed and overlapping with the message dropdown

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1049]
Env: Mac OS10.10.1 Chrome39
1. Go to https://arena.topcoder.com and login with valid user account
2. Wait until a new message popup comes
3. When it appears, click on the Message icon and observe

Actual:

Message dropdown is opened and at the same time pop-up is also displayed. So the Messages are hidden behind the pop-up displayed. Please find the screenshot below.

![11](https://cloud.githubusercontent.com/assets/5114190/5185974/4bfff5d4-74e9-11e4-907b-ccc0c3d17682.png)

Expected:

Popup should be closed when user clicks Message icon.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#25
