### ISSUE TITLE
[Common] 'Registrants (x)' Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1050]
## Description

[Common] 'Registrants (x)' Layout Issue
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Registrants (x)' in Chat Room
MUST HAVE 6-10 Registered users in the List

Scroll the list using mouse
## Expected result

Must fix the Issue
- Must not display double entried while scrolling
## Actual result

'Registrants (x)' Layout Issue
## Image

![32](https://cloud.githubusercontent.com/assets/4592712/5186297/6b69b246-74eb-11e4-842e-da4fd0c1b382.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#26
