### ISSUE TITLE
[a4350000000CwO4AAK] Can't register through facebook.

### ISSUE THREAD

**Issue by macs054** [cloudspokes/arena-web#1051]
Go to https://arena.topcoder.com
Click "Click here to register"
Wait for the page to redirect to http://www.topcoder.com/?action=callback
Click the Facebook icon

It shows this error:
![fb error](https://cloud.githubusercontent.com/assets/1199534/5187792/a5026eb6-750a-11e4-9842-21253469bc2a.PNG)

Expected result:
User should be able to enter Facebook credentials and login

Environment: Win 7 32-bit Firefox Developer Edition 35.0a2

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#27
