### ISSUE TITLE
Scroll bar layout issue 

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1052]
Scroll bar in Chat footer drop down should be changed

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
Scroll down and in the chat area click on General drop down and observe the scroll bar

actual - it stands out and doesnt get aligned to the rignt end of the drop down box.

expected - this layout issue should be fixed

Environment - FF 33

Web Arena QA for 201411 Release

**Comment by kaygee1** [comment]
![1](https://cloud.githubusercontent.com/assets/5115050/5188313/1e7459a0-74fa-11e4-96bb-7cad05864bea.png)

**Comment by skyhit** [comment]
this is current implementation.
