### ISSUE TITLE
Eligibility Answer Text box size is small compared to other fields

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1053]
Env: Mac OSX 10.10.1 Chrome 39

Step:
1. Go to https://arena.topcoder.com and login with valid user account
2. Click Register on a contest which has "Eligibility" criteria
3. Observe the Eligibility Answer Text box size

Actual:

The Eligibility Answer text box size is not equal to all other text box sizes. Hence it does not look good.

Expected:

It should be equal to all other text box/field sizes.

Screenshot: 
![eligibility text field not aligned](https://cloud.githubusercontent.com/assets/5114190/5188533/d20ac7d2-74fb-11e4-848a-fd1f69eb8256.png)

**Comment by skyhit** [comment]
this is for input.
