### ISSUE TITLE
R data field next to Handle in Active Users doesent make a lot of sense

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1054]
![2](https://cloud.githubusercontent.com/assets/5115050/5188863/ca90f4e2-74fe-11e4-9cff-626adc072e3c.png)

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
Register to a new challenge
In the right section 
Tap on Active Users and See the headers

actual - R and Handle is displayed. Not sure what R is, it is confusing.
e
xpectd - to use a much more meaningful label for R

FF 33 Win 7

**Comment by kaygee1** [comment]
Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
it is for rating indicator, but for current system, new users are not having any rating.
