### ISSUE TITLE
Not able to Enter into Coding Phase

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1055]
Env: Mac OS10.10.1 Chrome 39
1. Go to https://arena.topcoder.com and login with valid user account
2. Register for a contest which has Eligibility Criteria
3. Once the coding phase is started, Look for "Enter" button to enter into the contest

Actual:

Enter button does not appear though the coding phase has started. So not able to enter into the contest.

Expected:

Enter button should appear as the coding phase is started.

Screencast: https://www.dropbox.com/s/x4dpewntnt1asdr/Not%20able%20to%20Enter%20into%20contest%20%28Web%29.mp4?dl=0

Screenshot: 
![33](https://cloud.githubusercontent.com/assets/5114190/5189275/4130a0f4-7502-11e4-9654-d49aa7f6640d.png)

**Comment by nithyaasworld** [comment]
There is another contest which had the same issue as above. Please see the screenshot:  
![31](https://cloud.githubusercontent.com/assets/5114190/5223525/f23774a6-76e0-11e4-8ed7-f91325969cde.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#28
