### ISSUE TITLE
Contest is not closed even after the System Test Phase is over

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1057]
Env: Mac OS 10.10.1 Chrome39

These were the steps performed before encountering this issue:
1. Go to https://arena.topcoder.com and login with valid user account
2. Enter into the contest "Arena 14.11 take2 SRM 6"
3. Observe

Actual:

After the System Test Phase is over, the Contest is still Alive!

Expected:

Contest should not be live after its End Time.

Screenshot:
![55](https://cloud.githubusercontent.com/assets/5114190/5189695/f2e4b49a-7505-11e4-9bb2-8fa7051df3f4.png)

**Comment by skyhit** [comment]
it needs manual operation in the admin side
