### ISSUE TITLE
Activate Users are not displaying

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1058]
## Description

Activate Users are not displaying
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Expand the 'Active Users' section
Refresh
## Expected result

Must fix the Issue
- This is displayed during the other contests
- But now it is not displaying; Must display the active users
## Actual result

Activate Users are not displaying
## Image

![33](https://cloud.githubusercontent.com/assets/4592712/5195280/eb4a1272-753f-11e4-8ed1-8285609f42b9.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#30
