### ISSUE TITLE
'Match Summary' Table data is not aligned properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1059]
## Description

'Match Summary' Table data is not aligned properly
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click ENTER from the 'Active Matches'
Check the 'Match Summary' Table data
## Expected result

Must fix the Issue
- Must align the data with the Table column headings
## Actual result

'Match Summary' Table data is not aligned properly
## Image

![34](https://cloud.githubusercontent.com/assets/4592712/5195477/674175e8-7543-11e4-914f-cd7af2ddfe0c.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#31
