### ISSUE TITLE
'Room Leaderboard' scroll bar overlaps with the content

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1060]
## Description

'Room Leaderboard' scroll bar overlaps with the content
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click ENTER from the 'Active Matches'
When the Coding Phase is ON
Click on a problem
In the Code editor
Expand the 'Room Leaderboard' 

Check the scroll bar and last column 'Score'
## Expected result

Must fix the Issue
- Data must not overlap with the Scroll bar
## Actual result

'Room Leaderboard' scroll bar overlaps with the content
## Image

![35](https://cloud.githubusercontent.com/assets/4592712/5195860/a028494e-7549-11e4-93df-5cb71c83eff2.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#32
