### ISSUE TITLE
If there is only one page pagination not required

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1061]
## Description

If there is only one page pagination not required
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click ENTER from the 'Active Matches'
When the Coding Phase is ON
Click on a problem
In the Code editor
Expand the 'Room Leaderboard' 

Click 'Room' there is only one page --> NO Pagination displayed
Click 'Division II' there is only one page --> Pagination displayed
Click 'Division I' there is only one page --> Pagination displayed
## Expected result

Must fix the Issue
- If there is only one page pagination not required
## Actual result

If there is only one page pagination is displayed
## Image

![36 1](https://cloud.githubusercontent.com/assets/4592712/5195904/5dca529e-754a-11e4-9f97-87d8cc46f1d8.png)
![36 2](https://cloud.githubusercontent.com/assets/4592712/5195905/5e39a630-754a-11e4-971a-4d135b564944.png)
![36 3](https://cloud.githubusercontent.com/assets/4592712/5195909/6f67522c-754a-11e4-9e16-bd169f8001bb.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#33
