### ISSUE TITLE
"OK" button should be aligned center

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#1062]
Windows 8, FF33
1. login, register for SRM
2. do coding and testing
3. observe 

expected: the "OK" button should be aligned center.

actual: see screenshot
![qq20141126-2](https://cloud.githubusercontent.com/assets/4590317/5196099/67addd90-7562-11e4-9f64-281e13b2fba5.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#34
