### ISSUE TITLE
should only show single message on top right when the phase is changed

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#1064]
windows 8
1. login and register for an SRM
2. when a phase changes, e.g. from intermission to challenge, observe the top right

expected: it should show a single message which tells the current change.

actual: it will show some other messages which are unread before. And there are duplicate messages (the bottom two).

See screenshot.
![qq20141126-4](https://cloud.githubusercontent.com/assets/4590317/5196186/79436b86-7564-11e4-8328-b3d52ba2b621.jpg)

**Comment by skyhit** [comment]
no.
