### ISSUE TITLE
Message(s) should be Messages

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#1065]
windows 8
1. login, observe the top right

expected: Message(s) should be Messages. 

actual: see screenshot, it looks a bit weird - Message(s)(17).
![qq20141126-5](https://cloud.githubusercontent.com/assets/4590317/5196378/3ba59204-7569-11e4-96d1-620f7a42018a.jpg)

**Comment by skyhit** [comment]
Message(s) is fine.
