### ISSUE TITLE
'Loading' animation pop up is not center align with in the Match Plan calender

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1066]
## Description

'Loading' animation pop up is not center align with in the Match Plan calender
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Check the 'Loading' animation pop up Match Plan calender
## Expected result

Must fix the Issue
- Must center aligned with in the Match Plan calender
## Actual result

'Loading' animation pop up is not center align with in the Match Plan calender
## Image

![37](https://cloud.githubusercontent.com/assets/4592712/5196465/317eb03e-7556-11e4-81d4-63970129c10f.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#36
