### ISSUE TITLE
Contest Start time Timer is based on Coding Phase Start Time 

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1067]
Env: Mac 10.10.1 Chrome 39
1. Go to https://arena.topcoder.com and login with valid user account
2. Observe the "contest Start time timer" and Registration Phase Start Time

Actual:

Contest Start Time Timer is shown against the Coding Phase Start Time. 

Expected:

The Timer shows like 1 hour 30 mins for the contest to start. So user might think, still there is another 1 hour and 30 mins for the contest to start. 

If the user comes back after 1 hour 30 mins, he wont be able to participate in the Match as the contest Registration Phase starts before it.

(I happened to miss a contest because of this Timer and wait for another 4 hours)

It would be good to show the Timer based on the Registration Phase rather than Coding Phase.

Screenshot:

![66](https://cloud.githubusercontent.com/assets/5114190/5196609/eeee0fe0-7559-11e4-85b1-1408fdbcae9a.png)

**Comment by skyhit** [comment]
yes. this is purposed.
