### ISSUE TITLE
Outer circles are not very sharp.

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1068]
Outer circles are not very sharp.

Arena Applet QA for 201411 Release

Open applet and login with valid credentials
Click on summary and see the outer circles for On Off and status and points

actual -the outer circles are not sharp enough

expected - they should be sharper

Win 7 
![outer circles not sharp](https://cloud.githubusercontent.com/assets/5115050/5196680/b0f00ebc-755b-11e4-8f1c-d41a3b3007ca.png)

Arena applet QA for 201411 Release

**Comment by mdesiderio** [comment]
@skyhit this is in the wrong repo, can you please check if we have the same issue in the applet repo?
