### ISSUE TITLE
Top border lines not present in summary table

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1069]
Top border lines not present in summary table

Arena Applet QA for 201411 Release

Open applet and login with valid credentials
Click on summary and see the border lines for the table 

actual -the top border line is not present

expected - they should be present

Win 7 

![top border lines not present](https://cloud.githubusercontent.com/assets/5115050/5196694/0f16a9e2-755c-11e4-843c-bb730afdbdb9.png)

**Comment by mdesiderio** [comment]
@skyhit this issue is in the wrong repo, can you check if we have it in the applet repo?
