### ISSUE TITLE
No 'System Test Phase' Start Time in the 'Contest Schedule' Section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#107]
## Description

No 'System Test Phase' Start Time in the 'Contest Schedule' Section
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Click 'Contest Schedule'
Check the 'System Test Phase' Start Time
## Expected result

Must fix the Issue. Must have 'System Test Phase' Start Time
## Actual result

No 'System Test Phase' Start Time in the 'Contest Schedule' Section
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/3413419/3e579374-fe0b-11e3-99df-d1d2d6f077c2.png)

**Comment by skyhit** [comment]
this is the right results, the data didn't contain Starts date.
