### ISSUE TITLE
No need to have the logged in user name present in the drop down for chat for certain options

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1070]
Arena Applet QA for 201411 Release

Open applet and login with valid credentials
Cick on Lobbies >> Chat Room 1 
Click on >>
Select Reply to from the first drop down and then click on the second drop down

Observe

the logged in user is also found with the rest of the other users

expected - kaygkayg24 should not be included.

Win 7

**Comment by kaygee1** [comment]
![same user in reply to](https://cloud.githubusercontent.com/assets/5115050/5196782/bb5073a4-755d-11e4-8022-cef8e158e0d1.png)

**Comment by mdesiderio** [comment]
@skyhit this issue is in the wrong repo, can you check if we have it in the applet repo?
