### ISSUE TITLE
Double clicking on the user name in the left in chat room should initiate a reply to that user in the chat window.

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1071]
Arena Applet QA for 201411 Release

Open applet and login with valid credentials
Cick on Lobbies >> Chat Room 1 
Double click on any user in the left 

actual - the coder info window opens
In the website - double clicking on a username in the left in chat room initiates a reply-to that user in the chat window

expected - the same should be replicated in the applet also.

Win 7

**Comment by kaygee1** [comment]
![double click in chat](https://cloud.githubusercontent.com/assets/5115050/5196837/e2b43006-755e-11e4-980f-064fbf9277ec.png)

**Comment by mdesiderio** [comment]
@skyhit this issue is in the wrong repo, can you check if we have it in the applet repo?
