### ISSUE TITLE
Validation message won't clear even we click Cancel button

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1072]
## Description

Validation message won't clear even we click Cancel button
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'Feedback'
Click 'Submit'
When the Validation message comes
Click Cancel

Click 'Feedback' again
## Expected result

Must fix the Issue
- Must clear the validation 
## Actual result

Validation message won't clear even we click Cancel button
## Image

![38](https://cloud.githubusercontent.com/assets/4592712/5196945/82b3a054-7560-11e4-8d16-34655a91944f.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#37
