### ISSUE TITLE
At some scenario "will start in" does not have a valid value

### ISSUE THREAD

**Issue by kaygee1** [cloudspokes/arena-web#1073]
At some scenario "will start in" does not have a valid value

Open site https://arena.topcoder.com/#/u/dashboard
Click on any challenge that has just ended

See the time display on top

actual - SRM 9 will start in .

expected - sine this has already ended the time text should be accordingly changed.

sometimes the value of minutes /hours is completely blank. This should be fixed to have a proper time.
Win 7 FF 33

Web Arena QA for 201411 Release

**Comment by kaygee1** [comment]
![no value](https://cloud.githubusercontent.com/assets/5115050/5197245/e76bcf68-7564-11e4-8fc0-8a5ed39cacab.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#38
