### ISSUE TITLE
Long user handle creates layout issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1074]
## Description

Long user handle creates layout issue
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the coding phase starts
Click ENTER
Go to the code editor
Enter code and compile it
Then click on the Leaderboard 
Check the long user handle --> it is displayed in 3 lines
## Expected result

Must fix the Issue
- Must display in one line
## Actual result

Long user handle creates layout issue
## Image

![39](https://cloud.githubusercontent.com/assets/4592712/5197522/af1a8c8a-7569-11e4-834d-96e77bc2c9d4.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by skyhit** [comment]
known issue, this is a current solution.
