### ISSUE TITLE
When we click on the user handle nothing happens

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1075]
## Description

When we click on the user handle nothing happens
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the coding phase starts
Click ENTER
Go to the code editor
Enter code and compile it
Then click on the Leaderboard 
Click on a user handle --> Nothing happens
## Expected result

Must fix the Issue
- Must open the user info pop up
- If not must remove the hand cursor (hyperlink) option from the user handle
## Actual result

When we click on the user handle nothing happens
## Image

![40](https://cloud.githubusercontent.com/assets/4592712/5197552/33a243c6-756a-11e4-8ced-e937d66ab4b3.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#39
