### ISSUE TITLE
Can't challenge to others

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1076]
## Description

Can't challenge to others
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the coding phase starts
Click ENTER
Go to the code editor
Enter code and compile it
Wait till the challenge phase is ON
Go to Leaderboard
Click on others score
Check the challenge Option
There is no challenge Option
## Expected result

Must fix the Issue
- Must display the option to challenge others in the code editor
## Actual result

Can't challenge to others
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#40
