### ISSUE TITLE
Challenge not working

### ISSUE THREAD

**Issue by macs054** [cloudspokes/arena-web#1077]
ID: a4350000000CwORAA0, a4350000000CwOSAA0

Description:
1. Web Arena : To verify user1 is able to challenge user2's solution for a problem successfully
2. Web Arena : To verify user1 is able to challenge user2's solution for a problem unsuccessfully

Steps:
You should be registered in a contest and inside the contest room.
You should have a submitted code accepted.
Once the Challenge phase starts click view detail link and go to leaderboards.
Click on any user's score points.
Click the Challenge link on the top-right side of the coding area.
Select some or all test and click Challenge.
A pop up window will appear that shows the arguments, click Ok.

Result:
Nothing happens when the user clicked the Ok button.

Expected result:
1. Challenge should be successful and points should be distributed accordingly
2. Challenge should be unsuccessful and points should be distributed accordingly

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#41
