### ISSUE TITLE
C++ solutions not compiling

### ISSUE THREAD

**Issue by macs054** [cloudspokes/arena-web#1078]
ID 
[a4350000000CwOJAA0]
[a4350000000CwOMAA0]
[a4350000000CwOPAA0]

Steps:
Register and Enter to an active challenge.
Select one of the problems on the right sidebar.
Click the gear icon on the coding area and choose the language C++.
Enter your code in the coding area.
Remove one part of your code then compile, the compile will fail.
Fix the code and hit compile, the compile still fails.

Result:
All C++ solutions in all problems does not compile.
![capture](https://cloud.githubusercontent.com/assets/1199534/5198572/ca36afac-758d-11e4-9f35-6204a6be6451.PNG)

Expected Result:
Code compilation should be succesful.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#42
