### ISSUE TITLE
[a4350000000CwOBAA0] "remember me" does not work

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#1079]
Windows 8 + Chrome 35
1. Hit url : https://arena.topcoder.com
2. Enter username and password in topcoder credentails
3. Check the remember me checkbox and click Login
4. Now click Logout link and close the browser/tab
5. Open the above arena url in a new tab
6. Start typing the username, observe

expected: arena should remember the matching username.

actual: it can not remember the username.

**Comment by skyhit** [comment]
the remember is not for this purpose. it is about caching the sso credential for revisit.
