### ISSUE TITLE
'Registration is now open for Test SRM - Test SRM Round.' is displayed twice in Chat Room window

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#108]
## Description

'Registration is now open for Test SRM - Test SRM Round.' is displayed twice in Chat Room window
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Chat Room' Widget
Check the System Messages
## Expected result

Must fix the Issue. Must display only once
## Actual result

'Registration is now open for Test SRM - Test SRM Round.' is displayed twice in Chat Room window
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/3413461/bf75e640-fe0b-11e3-920b-001ebce2f8a0.png)

**Comment by skyhit** [comment]
can not reproduce.
