### ISSUE TITLE
[a4350000000CwONAA0] [a4350000000CwOLAA0] [a4350000000CwkvAAC] [a4350000000CwkrAAC] Pop up saying "You cannot submit unless you have successfully compiled first." is not showing

### ISSUE THREAD

**Issue by macs054** [cloudspokes/arena-web#1080]
Test ID:
[a4350000000CwONAA0]
[a4350000000CwOLAA0]
[a4350000000CwkvAAC]
[a4350000000CwkrAAC]

Steps:
Register to an active contest.
Click Enter when coding phase starts.
Enter to one of the problems given on the right side-bar.
Click the gear icon from the coding area.
Choose a language and click Ok.
Enter your solution for the chosen language on the coding area.
Remove a part of your code.
Hit compile, and the compile result window should generate a compilation error.
Now click the Submit button.
A warning window should appear saying: "You have made a change to your code since the last time you compiled. Do you want to continue to submit?" Click Yes.
Another warning window will appear: "Would you like to submit your code?" Click Yes.

Result:
After clicking Yes nothing happens.

Expected Result:
A pop up window saying "You cannot submit unless you have successfully compiled first." should be displayed

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#43
