### ISSUE TITLE
"Almost" can be removed in the message

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#1081]
Windows 8, FF33
1. login, register for an SRM
2. wait for the registration ends, observe the message

expected: "Almost" should be removed

actual: see screenshot

![qq20141127-2](https://cloud.githubusercontent.com/assets/4590317/5211585/acdbf67c-7620-11e4-8dec-0ac5fb834f11.jpg)

**Comment by skyhit** [comment]
no change need.
