### ISSUE TITLE
[Common] If we fail the compilation; the status in the Leaderboard display as 'Compiled'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1082]
## Description

[Common] If we fail the compilation; the status in the Leaderboard display as 'Compiled'
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the coding phase starts
Click ENTER
Go to the code editor
Enter code and Don't compile it
Click the Leaderboard and check the status of that problem --> Opened
Now go to code editor
Remove the class name
Compile it
When the Error message displays
Check 'Leaderboard'
Check the Status --> Compiled
## Expected result

Must fix the Issue
- Must not display as Compiled
- User may think he compiled that successfully when he saw that
- Must remain Opened or compiled with Errors
## Actual result

[Common] If we fail the compilation; the status in the Leaderboard display as 'Compiled'
## Image

![42](https://cloud.githubusercontent.com/assets/4592712/5211827/13e2fdfe-7610-11e4-974a-3256a34eddf0.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by Goodwine** [comment]
I would disagree, "Compiled" would mean that the contestant "Compiled his/her code", and I don't think that the other contestants should know if the compilation succeeded/failed.  
It would mean that the contestant is no longer on the coding phase, and he/she might have a solution already which would put pressure on the others.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#22
