### ISSUE TITLE
challenge message is always "unsuccessfully" even though it is a successful challenge

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#1083]
win8, FF33
1. login with some accounts (same division ratings), register for an SRM
2. code some solutions (correct and incorrect)
3. when challenge starts, try to challenge
4. observe

expected: message should be correctly reflect the challenge state.

actual: see screenshot, it always shows "A unsuccessfully challenged B" even though there are successful challenges.

![qq20141127-4](https://cloud.githubusercontent.com/assets/4590317/5212501/3abae3c8-7634-11e4-9d95-13d3a964e7dc.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#21
