### ISSUE TITLE
[Common][Orange Theme][a41500000000aVh] Missing theme style

### ISSUE THREAD

**Issue by karthikbecse** [cloudspokes/arena-web#1084]
Steps:
Login & go to https://arena.topcoder.com/#/u/dashboard
click Theme switcher
click Orange Theme 
check "Active Matches" & "Now chatting in: Chat Room 1" color

Actual Result:
theme not display properly

Expected Result:
theme should  display properly

![bi](https://cloud.githubusercontent.com/assets/3225433/5214006/43124a90-763c-11e4-8906-c36fb321e41b.png)
Environment

 Chrome 39.0.2171.71 m

**Comment by skyhit** [comment]
purposely made.
