### ISSUE TITLE
Feedback form opened behind the expanded 'Leaderboard', 'Challengers' and 'Challenges' tables

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1086]
## Description

Feedback form opened behind the expanded 'Leaderboard', 'Challengers' and 'Challenges' tables
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the coding phase starts
Click ENTER
Click 'Challenges & Leaderboard'
Expand 'Leaderboard', 'Challengers' or'Challenges' table
Click Feedback
## Expected result

Must fix the Issue
- Must open in front of the 'Leaderboard', 'Challengers' or'Challenges' table
## Actual result

Feedback form opened behind the expanded 'Leaderboard', 'Challengers' and 'Challenges' tables
## Image

![43](https://cloud.githubusercontent.com/assets/4592712/5218392/54c60a84-7672-11e4-827a-54b61b285e13.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#20
