### ISSUE TITLE
[Light Theme] When we hover over the username it will change the color

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1087]
## Description

[Light Theme] When we hover over the username it will change the color
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Change the Theme to Light Theme
Hover over the username
## Expected result

Must fix the Issue
- Must not change the color
- Compare with the Dark theme and Orange Theme
## Actual result

When we hover over the username it will change the color
## Image

![44](https://cloud.githubusercontent.com/assets/4592712/5219494/d3221524-767e-11e4-8721-63c5ed110cfd.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#19
