### ISSUE TITLE
Python compiler not aware of Class Name, Mathod Name, Return Type and Arg Types values

### ISSUE THREAD

**Issue by karthikbecse** [cloudspokes/arena-web#1088]
Login & goto https://arena.topcoder.com/#/u/coding/16311/12628/2

choose python 
enter code
class Bag:
    def **init**(self):
        self.data = []
    def add(self, x):
        self.data.append(x)
    def addtwice(self, x):
        self.add(x)
        self.add(x)

click compile

Expected Result

Must fix the Issue.

   should display compiler error

Actual Result

compiles without error

Environment
Chrome  39.0.2171.71 m

![pyth](https://cloud.githubusercontent.com/assets/3225433/5222406/0a2da3f8-76bb-11e4-870b-f1e974b6db3f.png)

**Comment by skyhit** [comment]
this is the system limitation.
