### ISSUE TITLE
a41500000000XP6 - Calendar Widget is shown in Topcoder Server Time which is unlike the rest of the application

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1089]
Env: Mac OS 10.10.1 Chrome 39

Steps:
1. Go to https://arena.topcoder.com/ and login with valid user details
2. Observe the calendar widget in the dashboard

Actual:

Calendar Widget is not showing the Upcoming Match details. It displays the matches scheduled until Now 27. But there are matches scheduled for Nov 28 which are not shown in the calendar widget. Please see the screenshot.

[Edit: Actually Topcoder Widget is showing the matches of Nov 28 under the date Nov27. It seems like it is showing in the Topcoder server time which is unlike the rest of the application.

Expected:

Calendar Widget should display the Upcoming Match details.

[Edit: Calendar widget should display the schedule in local time in order to sync with the Match schedule list in the dashboard}

Screenshot:
![upcoming matches are not displayed](https://cloud.githubusercontent.com/assets/5114190/5222987/923394f8-76d2-11e4-8656-6de4b823f1ce.png)

![match not seen in list view too](https://cloud.githubusercontent.com/assets/5114190/5223051/40499dca-76d4-11e4-9ea5-870ed93bf56a.png)

![calendar widget not reflecting local time](https://cloud.githubusercontent.com/assets/5114190/5223088/bb0f5350-76d5-11e4-8a4a-3cb27b931f2e.png)

![displayed incorrectly in calendar widget](https://cloud.githubusercontent.com/assets/5114190/5223108/3d6f2d5c-76d6-11e4-9a83-bd45af7cee7e.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#18
