### ISSUE TITLE
'Test SRM  will start in 5 minutes' displayed in the begining 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#109]
## Description

'Test SRM  will start in 5 minutes' displayed in the beginning 
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Check the Text : 'Test SRM  will start in 5 minutes'  --> at the very beginning, before the reg phase starts
## Expected result

Must fix the Issue. Must not display it, It must display when the registration phase is opened
Before that It must hide or display another message
## Actual result

'Test SRM  will start in 5 minutes' displayed in the beginning 
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/3413520/8edf9570-fe0c-11e3-8a98-8649f1771c78.png)

**Comment by skyhit** [comment]
5 minutes are rough estimation.
