### ISSUE TITLE
a41500000000aVh - Header is not in vertical alignment with the other elements

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1090]
Mac OS10.10.1 Chrome 39
1. Go to https://arena.topcoder.com and login with valid user details
2. Observe the Header "Competition Arena: Dashboard"

Actual:

It is not vertically aligned with other elements. Please see screenshot below.

Expected:

It should be in alignment with other vertical elements as in the "0B ~ Arena-Light.png"

Screenshot:
![header not aligned as in the psd](https://cloud.githubusercontent.com/assets/5114190/5223174/f5d5b176-76d7-11e4-953a-e3afc3c280af.png)

![0b arena-light](https://cloud.githubusercontent.com/assets/5114190/5223184/33459efe-76d8-11e4-9378-9ebae9721be3.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#17
