### ISSUE TITLE
Sort by 'R' creates a Layout Issue in 'Room Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1091]
## Description

Sort by 'R' creates a Layout Issue in 'Room Leaderboard'
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click ENTER from a match
Click 'Challenges & Leaderboard'
Click 'R' from 'Room Leaderboard'

https://arena.topcoder.com/#/u/contests/16302/2/summary/room
## Expected result

Must fix the Issue
- Sort icon must display in line
## Actual result

Sort by 'R' creates a Layout Issue in 'Room Leaderboard'
## Image

![45](https://cloud.githubusercontent.com/assets/4592712/5223401/ec43befe-76dd-11e4-88ba-e3f2b8dd6836.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#16
