### ISSUE TITLE
Must sort exact handle not others

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#1092]
## Description

Must sort exact handle not others
## Steps

Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click ENTER from a match
Click 'Challenges & Leaderboard'
In 'Room Leaderboard'
https://arena.topcoder.com/#/u/contests/16302/2/summary/room
Click Filter
Select : Specific Handle
Enter : sdgunqa
Click Filter
## Expected result

Must fix the Issue
- Must sort exact handle not others
## Actual result

Filter displays handles that have searched text as part of their handles
## Image

![46](https://cloud.githubusercontent.com/assets/4592712/5223411/4b06565e-76de-11e4-8a78-a568039f8711.png)
## Environment

IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit
## Bug Hunt

Web Arena QA for 201411 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#15
