### ISSUE TITLE
In Test panel  add  button missing

### ISSUE THREAD

**Issue by karthikbecse** [cloudspokes/arena-web#1093]
Login & go to https://arena.topcoder.com/#/u/practiceProblemList
select any one or GooseInZooDivTwo
enter code
compile & click test panel
check test panel

Expected Result

add button should visible

Actual Result

add button missing

Environment
Chrome 39.0.2171.71 m

![pra](https://cloud.githubusercontent.com/assets/3225433/5223586/ea01dc8a-76e1-11e4-921a-a050de8f6ed5.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#14
