### ISSUE TITLE
System Status Messages are duplicated a lot of times

### ISSUE THREAD

**Issue by imylyanyk** [cloudspokes/arena-web#1094]
I've received approximately 7 messages that Coding phase started. It's annoying, and they popup every time, and this isn't user-friendly.
![screenshot 2014-11-28 15 08 53](https://cloud.githubusercontent.com/assets/1242084/5228285/ab334af0-7710-11e4-9a33-d8b704bf0242.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#13
