### ISSUE TITLE
Code disappear after clicking expand on statement or code a few times

### ISSUE THREAD

**Issue by imylyanyk** [cloudspokes/arena-web#1095]
Steps to reproduce:
Open problem, change code in the code section, perform a few clicks on "expand"/"collapse" buttons on code and on statement, and eventually you will see that code returned to the state it was on load (here I mean that if you oppened a new problem - code will disappear, and if you oppened already submitted problem - your editions will disappear, and your code will return to submitted one).

You can redo this by pressing Ctrl+Z, but it's not very nice, isn't it?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#12
