### ISSUE TITLE
Only 'Test SRM will start in' is displayed when we start the 'Coding Phase'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#110]
## Description

Only 'Test SRM will start in' is displayed when we start the 'Coding Phase'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Then check the text : 'Test SRM will start in' 
## Expected result

Must fix the Issue. Must not display it
## Actual result

Only 'Test SRM will start in' is displayed when we start the 'Coding Phase'
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/3413582/39137a0c-fe0d-11e3-93cd-bcc54148d92c.png)

**Comment by skyhit** [comment]
can not reproduce.
