### ISSUE TITLE
(win7 Chrome39)Fail to zoom in (zoom out) when the cursor focused on Problem Area and Code Area panel.

### ISSUE THREAD

**Issue by maximxue** [cloudspokes/arena-web#1106]
I wanted to change the font size by pressing CTRL key (Win7) and rolling mouse wheel, but fail to do zoom in or out when my cursor focused on Problem Area and Code Area panel. Instead, it scrolled down and up the scrollbar which can be achieved by only rolling the mouse wheel. Can anyone fix that?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#4
