### ISSUE TITLE
Challenges Advertising Bug - error loading challenges

### ISSUE THREAD

**Issue by dexyk** [cloudspokes/arena-web#1108]
There is error during loading challenges advertising (arena.topcoder.com deployed version):

<pre>
"Error: helper.CHALLENGE_ADVERTISING.TRACK_SHORTNAMES["default".toLowerCase(...)] is undefined
</pre>

and there are challenges which are not loaded because of this error.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#3
