### ISSUE TITLE
Coding area erased

### ISSUE THREAD

**Issue by 0Xellos** [cloudspokes/arena-web#1118]
All the code in the coding area is erased when it's minimised, sometimes (about half the time) also when the problem area is maximised. This doesn't seem to persist after submitting and reopening, although (I'm okay with this as a feature) I can't minimise the coding area at all.

(Windows 7, Chrome, incognito mode)

**Comment by skyhit** [comment]
this is a known issue, we are working on it.

by the way, please report issues to https://github.com/appirio-tech/arena-web/issues

we are make the migration.
