### ISSUE TITLE
'Summary' and 'Chat Room' must move to left to align with the 'Competition Arena' title 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#112]
## Description

'Summary' and 'Chat Room' must move to left to align with the 'Competition Arena' title 
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
Check the 'Summary' and 'Chat Room' widget and 'title'
Check the 'Summary' Section
Click 'View Detail'
Check the 'Summary'widget and 'title'
## Expected result

Must fix the Issue. 'Summary' and 'Chat Room' must move to left to align with the 'Competition Arena' title 
Like 'Competition Arena' Details page (6.2)
## Actual result

'Summary' and 'Chat Room' is not align with the 'Competition Arena' title 
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

6.1
![6 1](https://cloud.githubusercontent.com/assets/4592712/3413752/838ba8d8-fe0e-11e3-9d47-44679010769a.png)

6.2
![6 2](https://cloud.githubusercontent.com/assets/4592712/3413753/865daa66-fe0e-11e3-92c4-c9cfcaf06ebf.png)

**Comment by skyhit** [comment]
no, it is following the design, and center position is expected.
