### ISSUE TITLE
pollard rho算法

### ISSUE THREAD

**Issue by apolloliu** [cloudspokes/arena-web#1121]
int pollard_rho(int n, int c)///c为自己设定的某值
{
    int x, y, d, i = 1, k = 2;
    x = rand() % (n - 1) + 1;
    y = x;
    while (true) {
        ++i;
        x = (modular_multi(x, x, n) + c) % n;
        d = gcd(y - x, n);
        if (1 < d && d < n)
            return d;
        if (x == y)
            return n;
        if (i == k)
            y = x, k <<= 1;
    }
}

**Comment by skyhit** [comment]
what is this?

**Comment by apolloliu** [comment]
It is an algorithm named pollard rho.

**Comment by skyhit** [comment]
this is not related to this repository, right/
