### ISSUE TITLE
'Coding Phase' is not starting properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#113]
## Description

'Coding Phase' is not starting properly
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
Check the coding phase start countdown
## Expected result

Must fix the Issue. Must start the 'Coding Phase' properly
## Actual result

'Coding Phase' is not starting properly
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![7](https://cloud.githubusercontent.com/assets/4592712/3413865/a12b6c74-fe0f-11e3-853e-235520a2e922.png)

**Comment by skyhit** [comment]
can not reproduce by following the steps.
