### ISSUE TITLE
'Challenge Phase is starting for Test SRM - Test SRM Round.' Must --> 'Challenge Phase is started in Test SRM - Test SRM Round.'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#114]
## Description

'Challenge Phase is starting for Test SRM - Test SRM Round.' Must --> 'Challenge Phase is started in Test SRM - Test SRM Round.'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Challenge Phase' Starts
Check the Pop up Message
## Expected result

Must fix the Issue. 
This message displays when the 'Challenge Phase' is already stared so 'Challenge Phase is starting for Test SRM - Test SRM Round.' Must --> 'Challenge Phase is started in Test SRM - Test SRM Round.'
## Actual result

'Challenge Phase is starting for Test SRM - Test SRM Round.'
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/3413970/ecc27938-fe10-11e3-90ad-0048694d8162.png)

**Comment by sdgun** [comment]
Common to all the Phases

**Comment by skyhit** [comment]
same as arena applet, no change now.
