### ISSUE TITLE
'Share' button won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#119]
## Description

'Share' button won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'

Click 'Share' button
## Expected result

Must fix the Issue. 'Share' button must work
## Actual result

'Share' button won't work
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![10](https://cloud.githubusercontent.com/assets/4592712/3414165/aa195f8c-fe12-11e3-9b84-2c256c6f4f39.png)

**Comment by skyhit** [comment]
this is not implemented.
