### ISSUE TITLE
cannot open problem even though coding phase is started

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#120]
1. load an SRM
2. login as ksmith and register
3. when coding phase starts, click Enter
4. click "Open" link for the problem

expected: the problem statement should be displayed

actual: error is shown, see screenshots

![6](https://cloud.githubusercontent.com/assets/4590317/3415182/f01b4378-fe1d-11e3-93f8-f749d11facb2.jpg)
![7](https://cloud.githubusercontent.com/assets/4590317/3415185/f6910ca6-fe1d-11e3-98a1-e5a8dc381f48.jpg)

**Comment by delemach** [comment]
@winterflame more detail is needed on how to reproduce. Because we know opening problems DOES work, so the question is why it did not work in this particular case.

**Comment by winterflame** [comment]
Maybe this is the data issue. 
Since I reused the same SRM again and again by changing the timeline, the system might consider the event has entered system test phase even though when it is rescheduled to the coding phase?

**Comment by skyhit** [comment]
it should be a data problem of reusing old round
