### ISSUE TITLE
"Back to contest" button is partially shown when the contest name is long

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#121]
1. load an SRM with a long name (like "Test SRM Round dfjklsauroiewurioewu bh bug hunt")
2. login as ksmith, then go into the room after coding starts
3. click "View Detail" link, observe

expected: the "Back to contest" button should not be seen
actual:see screenshot

![partial](https://cloud.githubusercontent.com/assets/4590317/3415205/1468eeb0-fe1e-11e3-83d4-cd43117c0efc.jpg)

**Comment by delemach** [comment]
The fix needs to make sure it works responsively as well (ie when browser is scaled down to tablet and phone sizes).
