### ISSUE TITLE
'Please click View Detail link ...' must --> 'Please click View Details link'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#122]
## Description

'Please click View Detail link ...' must --> 'Please click View Details link'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
Now in the 'Challenge Phase'
Check the Description in the Right side widget
## Expected result

Must fix the Issue. 'Please click View Detail link ...' must --> 'Please click View Details link'
## Actual result

'Please click View Detail link ...' 
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![11](https://cloud.githubusercontent.com/assets/4592712/3414298/fdd8dbb0-fe13-11e3-9623-efb15911d1ec.png)

**Comment by sdgun** [comment]
Common to all the Phases

**Comment by skyhit** [comment]
duplicated.
