### ISSUE TITLE
When we go to coding phase, It will display 'Coding Phase will start in: 1 seconds'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#124]
## Description

When we go to coding phase, It will display 'Coding Phase will start in: 1 seconds'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
## Expected result

Must fix the Issue. 
## Actual result

When we go to coding phase, It will display 'Coding Phase will start in: 1 seconds'
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/3414442/bed51260-fe15-11e3-93a7-5d21c962b6e6.png)

**Comment by skyhit** [comment]
can not reproduce.
