### ISSUE TITLE
profile data is not displayed well

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#125]
1. use the script in the forum to set ratings
2. then login as Yoshi, view the Profile Overview & Important Messages section

expected: data should be displayed properly - all contents should be moved to left a bit, and the last login time should be fully seen
actual; see screenshot

![info](https://cloud.githubusercontent.com/assets/4590317/3415235/64eb22c2-fe1e-11e3-8974-cb1e1eaca8a5.jpg)

**Comment by skyhit** [comment]
this is in purpose. the left part will display user photo.
