### ISSUE TITLE
layout issues on the contest schedule section

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#126]
win8, chrome 35, IE 11
1. load an SRM
2. login as ksmith, when registration ends, go into the room
3. view the right part

expected: all content should be displayed well
actual: see screenshot

![schedule](https://cloud.githubusercontent.com/assets/4590317/3415244/8532b3c4-fe1e-11e3-996f-e28f25f09781.jpg)

**Comment by skyhit** [comment]
it is related to google font loading problem.
