### ISSUE TITLE
unrated user's rating should be written as "1200" instead of "0"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#128]
1. login as ksmith
2. register for an SRM, go into the room, click view detail

expected:unrated user's rating should be written as "1200" instead of "0"
actual: see screenshot
![unrated](https://cloud.githubusercontent.com/assets/4590317/3414544/26211102-fe17-11e3-869c-236ebdb051bd.jpg)

**Comment by skyhit** [comment]
non-rated user will not be assigned a 1200 rating.
