### ISSUE TITLE
"Non-Rated" and "Not Rated" should be consistent

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#129]
1. login as ksmith
2. view the coder info
3. view the Rating key definitions

expected: "Non-Rated" and "Not Rated" should be consistent
actual: see screenshots
![notrated](https://cloud.githubusercontent.com/assets/4590317/3414632/2b2995f6-fe18-11e3-89d1-1e21f206a0c4.jpg)
![nonrated](https://cloud.githubusercontent.com/assets/4590317/3414635/30260c24-fe18-11e3-9696-b69952f5b0c2.jpg)

**Comment by skyhit** [comment]
not a problem
