### ISSUE TITLE
"Compiled" should be in white color as per the applet arena

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#130]
1. load an SRM
2. login as ksmith, open and compile the problem
3. click view detail

expected:  text "Compiled" should be in white color as per the applet arena

actual: see screenshots
![comp](https://cloud.githubusercontent.com/assets/4590317/3414732/3c4e7e7c-fe19-11e3-9754-ab32d6b6053a.jpg)

![whi](https://cloud.githubusercontent.com/assets/4590317/3414734/418c45cc-fe19-11e3-9793-f7296011bf54.jpg)

**Comment by skyhit** [comment]
no, this change is confirmed from me.
