### ISSUE TITLE
"Challenged" should be "Challenge Succeeded" for consistency with applet

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#132]
1. login as ksmith and Yoshi
2. ksmith submitted a wrong solution, then Yoshi challenged him
3. click View Detail

expected: "Challenged" should be "Challenge Succeeded", and the color should not be in red.
actual: see screenshot
![text](https://cloud.githubusercontent.com/assets/4590317/3415403/9457b974-fe20-11e3-8880-0cb2cffc4e69.jpg)

**Comment by skyhit** [comment]
no, due to column size limitation, we used short version
