### ISSUE TITLE
no value for the first test case in the challenge phase

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#134]
1. ksmith and Yoshi competed and submitted a problem in the same SRM room
2. ksmith opens Yoshi's problem, click Challenge, observe

expected: the first test case should be removed if it has no default value in it.

actual: see screenshot, the first test case is moved to the second one (Example 1).
![novalue](https://cloud.githubusercontent.com/assets/4590317/3415546/178899c0-fe22-11e3-9f46-503aa06fd14f.jpg)

**Comment by skyhit** [comment]
this is in purpose, it is not example tests, but you can input your own parameters.
