### ISSUE TITLE
duplicate information should be removed

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#135]
1. login as ksmith. load an SRM
2. go into the room, see the right side content

expected: there is no need to display info "Competition Status: XXX" when there is already a section displaying and highlighting the competition status.

actual: see screenshot.
![dupe](https://cloud.githubusercontent.com/assets/4590317/3415590/92e64b9e-fe22-11e3-9d85-eb165805dc9f.jpg)

**Comment by delemach** [comment]
Not sure this is really a problem. Is it possible to click back to 1.coding during intermission to see info there? Or is the top blue heading purely informational?

**Comment by skyhit** [comment]
it is purely informational.
