### ISSUE TITLE
it should tell the user the problem has been challenged rather than "you have already executed this challenge"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#137]
1. login as Yoshi and ksmith
2. they competed in the same SRM
3. Yoshi submitted a wrong solution
4. then in the challenge phase, ksmith used an existing test case to challenge it successfully.
5. ksmith tried to challenge it again using the same test case

expected: the system should report that the problem has already been challenged - it would save the competitors' time, since there is possibility that ksmith would look for another test case to challenge, which makes no sense.

actual: see screenshot, it will waste user's time since the problem has already been challenged.

![al](https://cloud.githubusercontent.com/assets/4590317/3415708/2b7576b8-fe24-11e3-9fcd-8a08e4a2a19f.jpg)

**Comment by skyhit** [comment]
same as arena applet.
