### ISSUE TITLE
unnecessary scroll bar on the coder info modal

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#138]
win8, Chrome 35, IE11
1. login as Yoshi
2. go into a room, tap on the handle to view user's info

expected: the scroll bar should be removed since there is nothing to scroll
actual: see screenshot

![s](https://cloud.githubusercontent.com/assets/4590317/3415864/f283ed9c-fe25-11e3-8c14-e9b60acfa616.jpg)

**Comment by skyhit** [comment]
can not reproduce with chrome.
