### ISSUE TITLE
time of "Ended at" for "System Test Phase" is incorrectly used

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#139]
1. load an SRM and login as ksmith
2. observe the schedule

expected: "Ended at" should be "Started at" for "System Test Phase" since the system test will start after the challenge phase, but it's impossible for the system test ends immediately.

actual: see screenshot
![end](https://cloud.githubusercontent.com/assets/4590317/3415920/bd5155c8-fe26-11e3-82e9-19cd58139b77.jpg)

**Comment by skyhit** [comment]
data problem, there seems only has end date for system test phase.
