### ISSUE TITLE
end date/time for registration phase is displayed on 2 lines

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#140]
win8, Chrome 35
1. load an SRM and login as Yoshi
2. see the Active Contests section

expected: end date/time should be displayed on a single line

actual:see screenshot
![l](https://cloud.githubusercontent.com/assets/4590317/3419375/cc0a93ba-fe60-11e3-9b60-10306e96f432.jpg)

**Comment by skyhit** [comment]
how to reproduce UTC+0800 timezone format?
