### ISSUE TITLE
"Grid" icon looks different in different browsers

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#142]
Win8, IE 11, Chrome 35
1. login as Yoshi in IE11
2. login as ksmith in Chrome
3. observe the "grid" icon in the Contest Plan section

expected: the icon should look the same
actual: see screenshots

in IE11:
![ie](https://cloud.githubusercontent.com/assets/4590317/3419460/66152ec6-fe65-11e3-9e09-2929ae4dfed8.jpg)

in Chrome:
![chrome](https://cloud.githubusercontent.com/assets/4590317/3419461/6fb9d698-fe65-11e3-8a49-58e0a01ca574.jpg)

**Comment by skyhit** [comment]
looks like you are not viewing as 100% zoom in and zoom out.
