### ISSUE TITLE
underlines are shown for the "<" and ">"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#143]
Win8, IE 11, Chrome 35
1. login as Yoshi
2. observe the Contest Plan section

expected: there should be no underlines under ">" and "<"
actual: see screenshot
![i](https://cloud.githubusercontent.com/assets/4590317/3419470/c2724050-fe65-11e3-9e0d-cfcc4b4f7fe1.jpg)

**Comment by skyhit** [comment]
looks like you are not viewing like 100% zoom in and zoom out.
