### ISSUE TITLE
[Common] Handle Name and Rating display in two lines

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#144]
## Description

[Common] Handle Name and Rating display in two lines
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
Then in the Coding phase click 'OPEN'
Enter the code and compile then submit
Click 'back to Contest'
Click 'View Detail'
Check the 'Room Leaderboard'
## Expected result

Must fix the Issue. Must display in one line
## Actual result

Handle Name and Rating display in two lines
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/3419529/304ed616-fe6a-11e3-9d1b-a8f1b161f550.png)

**Comment by skyhit** [comment]
this is because of column size
