### ISSUE TITLE
[Common] Challenge phase should be "Challenge Phase"

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#145]
## Description

[Common] Challenge phase should be "Challenge Phase"
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
Then in the Coding phase click 'OPEN'
Enter the code and compile then submit
Click 'back to Contest'
Click 'View Detail'
Check the 'Summary'
## Expected result

"Challenge Phase" ("P" in phase should be capital to be consistent with other pages)
## Actual result

Challenge phase
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/3419540/20b9688c-fe6b-11e3-9e3f-32610cacf23b.png)

**Comment by skyhit** [comment]
won't fix
