### ISSUE TITLE
[Common] 'Highest Rating' is not displayed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#148]
## Description

[Common] 'Highest Rating' is not displayed
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on

In the Chat Room
Click on a username in the 'Who's Here" section
Check the Pop up
Check the 'Rating (highest):      400 (0)'
## Expected result

Must fix the Issue, Must display the 'Highest Rating'
## Actual result

'Highest Rating' is not displayed
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/3419755/e866d8c6-fe78-11e3-916f-e59cdd2ea7d4.png)

**Comment by skyhit** [comment]
data problem
