### ISSUE TITLE
should add a label for the username in the Profile Overview & Important Messages section

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#150]
1. login as user
2. see Profile Overview & Important Messages section

expected: a label "User name" expected for the username.
actual: see screenshot
![m](https://cloud.githubusercontent.com/assets/4590317/3419765/0f756cce-fe7a-11e3-9fc0-dc0f59829b48.jpg)

**Comment by skyhit** [comment]
this is following the design.
