### ISSUE TITLE
[Common] 'Please wait for text info' pop up is not seen clearly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#151]
## Description

[Common] 'Please wait for text info' pop up is not seen clearly
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
Wait till 'Coding Phase' Starts
Click 'ENTER'
Click 'View Detail' in 'Summary'
In the Problem area click 'OPEN'
When the 'Challenge Phase' is on
Click on the 'Filter'
Check the Pop up appears in the screen
## Expected result

Must fix the Issue, Must display some time because user can't see what is in that pop up
## Actual result

'Please wait for text info' pop up is not seen clearly
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7

**Comment by skyhit** [comment]
missing image.
