### ISSUE TITLE
Event Registration Time is incorrect in the Registration info pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#155]
## Description

Event Registration Time is incorrect in the Registration info pop up
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
Check the Time of the Pop up and compare it with the actual time
## Expected result

Must fix the Issue, Must correct the time
## Actual result

Event Registration Time is incorrect
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/3419810/2c1fef18-fe7d-11e3-9633-9537585e54a0.png)

**Comment by skyhit** [comment]
backend data problem, not related to web-arena
