### ISSUE TITLE
When we switch to light theme for the First time Layout issue Occured

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#156]
## Description

When we switch to light theme for the First time Layout issue Occured
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
Now go to Theme section --> Select Light Theme
Click Apply
Check the Page

THIS HAPPENS IN THE FIRST TIME WHEN WE SWITCH THE THEME
## Expected result

Must fix the Issue
## Actual result

When we switch to light theme for the First time Layout issue Occured
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/3419812/abf22a3a-fe7d-11e3-9178-e9269a77cc61.png)

**Comment by skyhit** [comment]
can not reproduce.

by showing Event Registration dialog, I can not switch.

if not show the dialog, then switch, can not reproduce.
