### ISSUE TITLE
Parameters displayed when we click 'Yes' in the Info pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#157]
## Description

Parameters displayed when we click 'Yes' in the Info pop up
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
Click on the Info Icon (near Welcome <Username> Section)
Click 'Yes'
Check the page layout
## Expected result

Must fix the Issue. Must not happen
## Actual result

Parameters displayed when we click 'Yes' in the Info pop up
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![24](https://cloud.githubusercontent.com/assets/4592712/3419815/237284e2-fe7e-11e3-9b01-1cae21dde50a.png)

**Comment by skyhit** [comment]
that is dummy logic.
