### ISSUE TITLE
No hand cursor for the Right side in 'Contest Plan'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#158]
## Description

No hand cursor for the Right side in 'Contest Plan'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
Now in the 'Contest Plan' section
Click 'Grid View'
Hover over the 'Orange Color' Number
First hover over left side of the number --> Hand Cursor
Now Hover over Right side of it --> No hand Cursor
Now click on it (Right Hand Side)

It will open the details page
## Expected result

Must fix the Issue. Must have Hand cursor for the Right side also
## Actual result

No hand cursor for the Right side in 'Contest Plan'
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/3419821/37273b44-fe7f-11e3-925c-7b012ec0505a.png)

**Comment by skyhit** [comment]
looks ok to me.
