### ISSUE TITLE
sometimes user cannot login using Firefox

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#159]
Win8, Firefox 29.0
1. login as user
2. then logout, try to login using lightspeed

expected: it should be logged in successfully

actual: see screenshot, error message is shown.
![ro](https://cloud.githubusercontent.com/assets/4590317/3420056/2618795a-fe91-11e3-8ea5-9a4660949545.jpg)

**Comment by skyhit** [comment]
are you sure you are entering the right password?
