### ISSUE TITLE
the status message is not updated properly if the local time is not correct

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#160]
1. load an SRM
2. Adjust the local time to be 1 hour behind
3. login as ksmith, wait for the SRM starts
4. observe the Active Contests section

expected: the message should be "XXX Contest name is live!" when the coding phase starts.

actual: see screenshot, it will be "XXX Contest name is live!" and then changes to "XXX Contest name will start in", which is wrong.
![self](https://cloud.githubusercontent.com/assets/4590317/3420072/d5a10068-fe91-11e3-947f-e408f4b3f987.jpg)

**Comment by skyhit** [comment]
data problem
