### ISSUE TITLE
there should be language info displayed when opening a problem during or after challenge phase

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#161]
1. login as ksmith, submit a solution
2. login as lightspeed, view ksmith's solution during challenge phase

expected: it should follow current applet arena - there should be information about which language is used in the solution

actual: see screenshots, no such information.

![la](https://cloud.githubusercontent.com/assets/4590317/3420081/195fed2c-fe93-11e3-920e-8e6a84145eb1.jpg)

But it has such info in the applet arena:
![c](https://cloud.githubusercontent.com/assets/4590317/3420084/4590f38c-fe93-11e3-8527-8d79a60af3ce.jpg)

**Comment by delemach** [comment]
Where should we put this info? Perhaps to the left of the find box (and push the find control over to the right)?
