### ISSUE TITLE
same format expected for "M minutes N seconds"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#164]
1. load an SRM
2. login as user, observe the countdown when coding phase is not started
3. when coding phase starts, go into the room, see the countdown

expected: the countdown should use same format for minutes/seconds.

actual: in the lobby, there is "and" between minutes and seconds, but there is no "and" in the room when coding phase starts. See screenshots.

![time2](https://cloud.githubusercontent.com/assets/4590317/3420708/04cecc9c-febc-11e3-8784-20a79305ae37.jpg)

But there is "and" below:
![and](https://cloud.githubusercontent.com/assets/4590317/3420710/0d32e3dc-febc-11e3-957c-aa926dd8ee8b.jpg)

**Comment by skyhit** [comment]
won't fix
