### ISSUE TITLE
'Challenge' Test Result Pop up Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#165]
## Description

'Challenge' Test Result Pop up Layout Issue
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Intermission Phase' is on
Click OPEN in the Contest
When the 'Challenge Phase' is on
Click 'Test Panel'
Check the 2nd Example from it
Click 'Challenge'

Check the Pop up
## Expected result

Must fix the Issue. Must reduce the gap between the words
## Actual result

'Challenge' Test Result Pop up Layout Issue
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![26](https://cloud.githubusercontent.com/assets/4592712/3420714/ecf221c2-febc-11e3-9594-1671e01b2bff.png)

**Comment by skyhit** [comment]
backend forms the texts. not related to web arena.
