### ISSUE TITLE
[$50] 'Test is completed' Still displays even there is an error message

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#166]
## Description

'Test is completed' Still displays even there is an error message
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Intermission Phase' is on
Click OPEN in the Contest
When the 'Challenge Phase' is on
Click 'Test Panel'
Check the 2nd Example from it
Click 'Challenge'

Now Click Another Example
Click Re-Run

Check the Message : 'Test is completed' 
## Expected result

Must fix the Issue. Must clear the 'Test is completed' message as soon as user clicks on the Re-Run
## Actual result

'Test is completed' Still displays even there is an error message
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![27](https://cloud.githubusercontent.com/assets/4592712/3420721/89a4aef4-febd-11e3-82b2-f81292a6b9a8.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#291
