### ISSUE TITLE
'You are required to select exactly one test case.' Message displays if we won't select any example

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#168]
## Description

'You are required to select exactly one test case.' Message displays if we won't select any example
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Intermission Phase' is on
Click OPEN in the Contest
When the 'Challenge Phase' is on
Click 'Test Panel'
Check the 2nd Example from it
Click 'Challenge'

Deselect all the examples
Click Re-Run

Check the Message : 'You are required to select exactly one test case.' 
## Expected result

Must fix the Issue. Must display "You haven't Select any Test Case"
## Actual result

'You are required to select exactly one test case.' Message displays if we won't select any example
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/3420727/17cead92-febe-11e3-989a-2f7f79ec3845.png)

**Comment by skyhit** [comment]
the message is clear
