### ISSUE TITLE
When we expand the 'Code Area' Challenge container is not fit into the bottom of that section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#169]
## Description

When we expand the 'Code Area' Challenge container is not fit into the bottom of that section
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Challenge Phase' is on
Click 'View Detail'
Click on the Marks of other user in the 'Room Leaderboard'
Expand the 'Challenge'
Now expand the 'Coding Area'
## Expected result

Must fix the Issue. Must fit to the bottom section
## Actual result

When we expand the 'Code Area' Challenge container is not fit into the bottom of that section
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![29](https://cloud.githubusercontent.com/assets/4592712/3420742/5a7bc99e-febf-11e3-9da5-a263eda2507f.png)

**Comment by skyhit** [comment]
test panel is independent.
