### ISSUE TITLE
Can Edit the Coding of the other user

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#170]
## Description

Can Edit the Coding of the other user
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Challenge Phase' is on
Click 'View Detail'
Click on the Marks of other user in the 'Room Leaderboard'
Expand the 'Challenge'
Select 'Example'
Click 'Challenge'
Click OK to the Pop up
Click on the Coding Area
Type anything
## Expected result

Must fix the Issue. Must restrict it
## Actual result

Can Edit the Coding of the other user
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/3420752/efc1c8dc-febf-11e3-81ef-d871f65dfbfd.png)

**Comment by delemach** [comment]
Should also be some visual indicator that it is non editable, such as the stop icon that is used elsewhere when a control is disabled.

**Comment by skyhit** [comment]
for web page, it is still be possible to copy, we should think about alternative approach, like generating images.

what do you think?
