### ISSUE TITLE
'Linked In' Icon Issue in the Share pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#171]
## Description

'Linked In' Icon Issue in the Share pop up
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Challenge Phase' is on
Click 'View Detail'
Click on the Marks of other user in the 'Room Leaderboard'
Click 'Share'
Check the Linked In' icon
## Expected result

Must fix the Issue. Must replace the (+) with the Linked In Icon
## Actual result

'Linked In' Icon Issue in the Share pop up
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![31](https://cloud.githubusercontent.com/assets/4592712/3420759/a2291f02-fec0-11e3-9d8e-cc059cafa67b.png)

**Comment by skyhit** [comment]
replaced with Github instead.
