### ISSUE TITLE
Small line appears at the bottom in 'Problem Area', when we expand the 'Code Area'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#172]
## Description

Small line appears at the bottom in 'Problem Area', when we expand the 'Code Area'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the 'Active Contests' Widget
When the 'Registration Phase' is on
Click REGISTER
When the 'Challenge Phase' is on
Click 'View Detail'
Click on the Marks of other user in the 'Room Leaderboard'
Expand the 'Coding Area'
## Expected result

Must fix the Issue. Must remove the line
## Actual result

Small line appears at the bottom in 'Problem Area', when we expand the 'Code Area'
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![32](https://cloud.githubusercontent.com/assets/4592712/3420780/db0b0334-fec1-11e3-8f67-43b23c3b1048.png)

**Comment by skyhit** [comment]
the problem seems still exist
