### ISSUE TITLE
"System Test Phase" should be changed to "System Testing Phase" as per the applet arena

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#174]
1. load an SRM
2. login as Yoshi, see the contest schedule

expected: "System Test Phase" should be changed to "System Testing Phase" as per the applet arena

actual: see screenshots

applet arena:
![qq20140628-2](https://cloud.githubusercontent.com/assets/4590317/3421235/ef9887d0-fee0-11e3-9b2a-c92f13620eb2.jpg)

html5 arena:
![qq20140629-1](https://cloud.githubusercontent.com/assets/4590317/3421237/396546b4-fee1-11e3-998f-42023d10ff28.jpg)

**Comment by skyhit** [comment]
we are in purpose to use System Test as in one of our fix.
