### ISSUE TITLE
extra spaces should be removed before the colon

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#175]
1. login as Yoshi
2. go into a room when coding starts
3. observe the status text

expected: extra spaces should be removed before the colon

actual: see screenshot, it looks not professional:
![qq20140629-2](https://cloud.githubusercontent.com/assets/4590317/3421254/b5986086-fee1-11e3-8378-15814987fb0e.jpg)

**Comment by skyhit** [comment]
won't fix.
