### ISSUE TITLE
[iPad][iPhone] last login info is truncated with dots

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#176]
iOS 7.1, iPad Retina simulator, iPhone 4-inch simulator
1. login as ksmith
2. scroll down to view Profile Overview & Important Messages

expected: last login info should be displayed fully.
actual: see screenshot

![qq20140629-3](https://cloud.githubusercontent.com/assets/4590317/3421282/eb47474a-fee3-11e3-9726-0cab96cfacb6.jpg)
![qq20140629-11](https://cloud.githubusercontent.com/assets/4590317/3421448/17aeac42-feee-11e3-85d0-e3e4ccdd3729.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#290
