### ISSUE TITLE
[iPad]cannot scroll down to select options at the bottom when chatting

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#177]
iOS 7.1, iPad Retina simulator
1.    login as ksmith
2.  in the chat section, try to scroll down the options list

expected: should be able to scroll down.
actual: see screenshot, when scrolling, the whole screen will be scrolled.
![qq20140629-4](https://cloud.githubusercontent.com/assets/4590317/3421291/6f053be6-fee4-11e3-994a-0b48cbdeef7b.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#289
