### ISSUE TITLE
some columns are displayed on 2 lines

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#178]
iOS 7.1, iPad Retina simulator
1. login as ksmith, register for an SRM
2. when coding starts, go into the room
3. then click View Detail

expected: column name should be displayed on a single line
actual: see screenshot

![qq20140629-5](https://cloud.githubusercontent.com/assets/4590317/3421325/de2d9daa-fee5-11e3-84e5-30a7a767664f.jpg)

**Comment by skyhit** [comment]
it is due to column size.
