### ISSUE TITLE
[iPad]cannot view the code in the room leaderboard section

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#179]
iOS 7.1, iPad Retina simulator
1.    login as ksmith and Yoshi, they competed for an SRM
2.   when waiting for system test, login as ksmith
3.  in the room leaderboard section, try to click the score to view the code

expected: code should be shown
actual: see screenshot, nothing will happen, no code will be shown

![qq20140629-6](https://cloud.githubusercontent.com/assets/4590317/3421333/8313e7ac-fee6-11e3-85d3-6a41c325bfa6.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#288
