### ISSUE TITLE
[iPad] [Common issue] tooltip overlaps with the modal

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#180]
iOS 7.1 + iPad Retina simulator
1. login as ksmith (Landscape mode)
2. tap the Theme switcher twice

expected: the tooltip should not be displayed when the theme switcher modal is shown

actual: see screenshot, same issues for other menu items.

![qq20140629-7](https://cloud.githubusercontent.com/assets/4590317/3421343/8b256280-fee7-11e3-80f7-1e68ec577b12.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#287
