### ISSUE TITLE
[iPad] 2 "Filter"s should be aligned vertically

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#181]
ios7.1, ipad retina simulator
1. login as ksmith
2. go into the room, then click View Detail

expected: 2 "Filter"s should be aligned vertically

actual: see screenshot
![qq20140629-8](https://cloud.githubusercontent.com/assets/4590317/3421379/ba36bd24-fee9-11e3-8f1b-f769d3d0acda.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#286
