### ISSUE TITLE
[iPhone] "Remember me" is displayed on 2 lines

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#182]
ios 7.1, iPhone 4-inch simulator
1. open http://arena.cloud.topcoder.com:3000/
2. see login form

expected: "Remember me" should be displayed on a single line
actual: see screenshot
![qq20140629-9](https://cloud.githubusercontent.com/assets/4590317/3421420/fcefec9c-feeb-11e3-82a8-310b86145ec3.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#285
