### ISSUE TITLE
[iPhone] error message overlaps the login form

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#183]
ios 7.1, iPhone 4-inch simulator
1. open http://arena.cloud.topcoder.com:3000/ in portrait mode
2. use a wrong credential to login, see error message

expected: even though the error message is displayed on 2 lines, it should not overlap with the login frame
actual: see screenshot
![qq20140629-10](https://cloud.githubusercontent.com/assets/4590317/3421440/827a982a-feed-11e3-8836-8e1f3baf2e11.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#284
