### ISSUE TITLE
[iPhone] layout issues of status text 

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#184]
iOS 7.1, iPhone 4-inch simulator
1.    login as ksmith (Portrait mode)
2.  compete in an SRM, then wait for the system test, go into the room, view status text

expected: it should have no layout issues.
actual: see screenshot, also there are content missing (4. Sys. Test)
![qq20140629-12](https://cloud.githubusercontent.com/assets/4590317/3421456/9b76ee18-feee-11e3-8d78-e89006b6fd10.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#283
