### ISSUE TITLE
[iPhone] "Country name" on the coder info modal cannot be displayed on a single line

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#185]
iOS 7.1, iPhone 4-inch simulator
1.    login as ksmith
2. view a coder's info in portrait mode

expected: country name should be displayed on a single line
actual: see screenshot
![qq20140629-13](https://cloud.githubusercontent.com/assets/4590317/3421461/44a23542-feef-11e3-9397-be6fa256aea5.jpg)

**Comment by skyhit** [comment]
screen size problem.
