### ISSUE TITLE
[iPhone] colon expected for the competition status text

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#186]
iOS 7.1, iPhone 4-inch simulator
1. login as ksmith (Landscape)
2. compete in SRM and wait for system test phase
3. observe the status text

expected: there should be a colon after "Competition Status", just like the web version does.
actual: see screenshot
![qq20140629-14](https://cloud.githubusercontent.com/assets/4590317/3421464/a70e74d4-feef-11e3-9b20-f4e453bc5ab7.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#282
