### ISSUE TITLE
[iPhone] [Common] list cannot be scrolled down

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#187]
iOS 7.1, iPad Retina simulator, iPhone 4-inch simulator
1.  login as ksmith
2. scroll down the screen, click "Rating Key"
3. try to scroll down to view all rating keys

expected: all rating keys should be visible
actual: see screenshot, cannot scroll down to view others
![qq20140629-15](https://cloud.githubusercontent.com/assets/4590317/3421478/1472603a-fef0-11e3-960e-ee8c7538246d.jpg)

**Comment by skyhit** [comment]
looks like the custom scrollbar is not supporting iPhone

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#281
