### ISSUE TITLE
[iPhone] the "logging off" modal is not positioned well when same account logs in elsewhere

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#188]
iOS 7.1, iPhone 4-inch simulator, Chrome 35
1.  login as ksmith in Landscape mode
2. then login as ksmith using Chrome
   1. observe the iPhone

expected: the "logging off" modal should be positioned well so that "Close" button can be seen.
actual: see screenshot
![qq20140629-16](https://cloud.githubusercontent.com/assets/4590317/3422308/e686d5de-ff2b-11e3-8fd1-486a0f69776b.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#280
