### ISSUE TITLE
[iPhone 5][Portrait] 'Profile Overview & Important Message' section is too much to the right side

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#190]
## Description

[iPhone 5][Portrait] 'Profile Overview & Important Message' section is too much to the right side
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
## Expected result

Must fix the Issue. Must move to left, or Display center aligned
## Actual result

'Profile Overview & Important Message' section is too much to the right side
## Environment

iOS 7.1, Simulator
## Image

![35](https://cloud.githubusercontent.com/assets/4592712/3422437/8c55ce14-ff3d-11e3-86b2-3e1538ec137a.png)

**Comment by skyhit** [comment]
there is photo section
