### ISSUE TITLE
[iPhone 5][Portrait] Filter is not seen fully

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#191]
## Description

[iPhone 5][Portrait] Filter is not seen fully
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Click 'View Detail' in Summary
Click 'Filter'
## Expected result

Must fix the Issue. Must fully display
## Actual result

Filter is not seen fully
## Environment

iOS 7.1, Simulator
## Image

![36](https://cloud.githubusercontent.com/assets/4592712/3422438/947c7b9c-ff3d-11e3-96da-0b8cf08e0ba8.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#279
