### ISSUE TITLE
[iPhone 5][Portrait] No line separation in 'Summary' and 'Room Leaderboard' sections

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#192]
## Description

[iPhone 5][Portrait] No line separation in 'Summary' and 'Room Leaderboard' sections
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Click 'View Detail' in Summary
Check the line separation in 'Summary' and 'Room leaderboard' sections
## Expected result

Must fix the Issue. Must have one
## Actual result

No line separation in 'Summary' and 'Room Leaderboard' sections
## Environment

iOS 7.1, Simulator
## Image

![37](https://cloud.githubusercontent.com/assets/4592712/3422439/9a97699c-ff3d-11e3-91b4-9a3c29d26ed2.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#278
