### ISSUE TITLE
[iPhone 5][Portrait] Layout Issue when we click the Expand icon in the 'Room Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#193]
## Description

[iPhone 5][Portrait] Layout Issue when we click the Expand icon in the 'Room Leaderboard'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Click 'View Detail' in Summary
In the 'Room Leaderboard' click Expand Icon
Check the Layout
## Expected result

Must fix the Issue.
## Actual result

Layout Issue when we click the Expand icon in the 'Room Leaderboard'
## Environment

iOS 7.1, Simulator
## Image

![38](https://cloud.githubusercontent.com/assets/4592712/3422444/0a06d3e4-ff3e-11e3-9846-4e3dcbf5c9a3.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#277
