### ISSUE TITLE
[iPhone 5][Portrait] In 'Coding Area', there is a blank area on top

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#194]
## Description

[iPhone 5][Portrait] In 'Coding Area', there is a blank area on top
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Click 'View Detail' in Summary
In the 'Room Leaderboard' 
Click on a mark of a user
## Expected result

Must fix the Issue. Must remove the blank area
## Actual result

In 'Coding Area', there is a blank area on top
## Environment

iOS 7.1, Simulator
## Image

![39](https://cloud.githubusercontent.com/assets/4592712/3422445/1c568206-ff3e-11e3-8962-538473ab8752.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#276
