### ISSUE TITLE
[iPhone 5][Portrait] Text overlaps in the Problem Area

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#195]
## Description

[iPhone 5][Portrait] Text overlaps in the Problem Area
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Click 'View Detail' in Summary
In the 'Room Leaderboard' 
Click on a mark of a user
In 'Problem Area' scroll down

Check the 'Limits' section
## Expected result

Must fix the Issue. Must not overlap the text in Problem Area
## Actual result

Text overlaps in the Problem Area
## Environment

iOS 7.1, Simulator
## Image

![40](https://cloud.githubusercontent.com/assets/4592712/3422446/2f31eb90-ff3e-11e3-9a65-01c1a0a9d3f1.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#275
