### ISSUE TITLE
[iPhone 5][Portrait] No Line Separation between the problem and Topcoder credits

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#196]
## Description

[iPhone 5][Portrait] No Line Separation between the problem and Topcoder credits
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Click 'View Detail' in Summary
In the 'Room Leaderboard' 
Click on a mark of a user
In 'Problem Area' scroll down

Check the line between Problem and topcoder credits --> There is no such a line
## Expected result

Must fix the Issue. Must have one, Check with the Desktop Site (41.2)
## Actual result

No Line Separation between the problem and Topcoder credits
## Environment

iOS 7.1, Simulator
## Image

iOs
![41 1](https://cloud.githubusercontent.com/assets/4592712/3422448/4bfbe1d6-ff3e-11e3-91c2-834521c295b1.png)

Desktop
![41 2](https://cloud.githubusercontent.com/assets/4592712/3422449/4e8064ea-ff3e-11e3-871b-acfbcc6b8d55.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#274
