### ISSUE TITLE
[iPhone 5][Portrait]checkbox is missing after logged out 

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#197]
iOS7.1, iPhone simulator
1. login as ksmith
2. then disconnect the internet connection, there will be error message displayed
3. click "Close" to go to login screen
4. observe

expected: checkbox for "Remember me" should be displayed
actual: see screenshot
![qq20140629-19](https://cloud.githubusercontent.com/assets/4590317/3422634/7a4c973c-ff53-11e3-90a2-9e8644bc6d54.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#273
