### ISSUE TITLE
layout issues of status text

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#198]
Mac 10.9.3, Chrome 35.0
1. load an SRM
2. login as ksmith, registered for it and competed
3. when it enters system test phase, observe the status text

expected: should be no layout issues.
actual: see screenshot
![qq20140629-20](https://cloud.githubusercontent.com/assets/4590317/3422645/5d4b4f6a-ff54-11e3-9bff-4a75edf6083b.jpg)

**Comment by skyhit** [comment]
the problem related to networking to load google fonts/
