### ISSUE TITLE
[$50] Hovering Over the 'Search Icon' will change it's position

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#199]
## Description

Hovering Over the 'Search Icon' will change it's position
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
When the 'Coding Phase' is Active
Click OPEN in the Problem area
Then in the 'Coding Area'
Hover over the 'Search icon'
## Expected result

Must fix the Issue.
## Actual result

Hovering Over the 'Search Icon' will change it's position
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![42](https://cloud.githubusercontent.com/assets/4592712/3422651/05c5a01e-ff55-11e3-992f-332f5221d551.png)

**Comment by ananthhh** [comment]
Already fixed. Check #773

**Comment by huangqun** [comment]
fixed
