### ISSUE TITLE
Coding Phase Count Down won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#200]
## Description

Coding Phase Count Down won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
When the 'Coding Phase' is Active
Click OPEN in the Problem area
Check the Coding count down
## Expected result

Must fix the Issue. Must work the count down
## Actual result

Coding Phase Count Down won't work
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![43](https://cloud.githubusercontent.com/assets/4592712/3422655/5a16beaa-ff55-11e3-8fad-fb7478e7a58e.png)

**Comment by skyhit** [comment]
setup problem.
