### ISSUE TITLE
[iPhone] [Common issue] cannot dismiss the dropdown by tapping the outside area

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#201]
ios7.1, iPhone 4-inch simulator
1. load an SRM
2. login as ksmith
3. tap "Contest Schedule" dropdown, then try to dismiss it by tapping outside area of it

expected: the dropdown should be dismissed.
actual: cannot dismiss it
![qq20140629-21](https://cloud.githubusercontent.com/assets/4590317/3422657/7d40418a-ff55-11e3-8de1-e630783a1f27.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#272
