### ISSUE TITLE
'Search' and 'Go To' won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#202]
## Description

'Search' and 'Go To' won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
When the 'Coding Phase' is Active
Click OPEN in the Problem area
Enter a code

Enter text and click Search OR Check 'Go To'
## Expected result

Must fix the Issue. 'Search' and 'Go To' must work
## Actual result

'Search' and 'Go To' won't work
## Environment

Chrome 35.0.1916.114 m, FF 30, IE 10+, Safari 5.1.7 in Window 7
## Image

![44](https://cloud.githubusercontent.com/assets/4592712/3422662/d548593a-ff55-11e3-8a54-c3e9dcacda3e.png)

**Comment by skyhit** [comment]
this is not implemented yet.
