### ISSUE TITLE
[iPhone][Portrait] Editor settings pop up Overlap with the 'Test Panel'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#203]
## Description

[iPhone][Portrait] Editor settings pop up Overlap with the 'Test Panel'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
When the 'Coding Phase' is Active
Click OPEN in the Problem area
Enter a code

Click 'Test Panel'
Now click 'Editor Settings' Icon
## Expected result

Must fix the Issue. Must not overlap
## Actual result

Editor settings pop up Overlap with the 'Test Panel'
## Environment

iOS 7.1, Simulator
## Image

![45](https://cloud.githubusercontent.com/assets/4592712/3422665/5114429a-ff56-11e3-9bae-4000d45508ef.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#271
