### ISSUE TITLE
[iPhone][Portrait] 'This Problem has been successfully Challenged' text is not shown fully

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#205]
## Description

[iPhone][Portrait] 'This Problem has been successfully Challenged' text is not shown fully
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
When the 'Coding Phase' is Active
Click OPEN in the Problem area
Enter a code
Submit

Then in the 'Challenge Phase'
Go back to the contest Page
Click on the Marks on the other user
Select the 'Challenge'
Select 'test case'
Click 'Challenge'
Check the Message
## Expected result

Must fix the Issue. Must display fully
## Actual result

'This Problem has been successfully Challenged' text is not shown fully
## Environment

iOS 7.1, Simulator
## Image

![46](https://cloud.githubusercontent.com/assets/4592712/3422671/1a4b333a-ff57-11e3-8d54-df590561faa3.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#270
