### ISSUE TITLE
[iPhone][Portrait] Layout Issue when we are in the 'Challenge Phase'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#206]
## Description

[iPhone][Portrait] Layout Issue when we are in the 'Challenge Phase'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
When the 'Challenge Phase' is Active
Check the Progress Box
## Expected result

Must fix the Issue. "Challenge Phase' text must fully visible
Competition status must display in one line
## Actual result

Layout Issue when we are in the 'Challenge Phase'
## Environment

iOS 7.1, Simulator
## Image

![47](https://cloud.githubusercontent.com/assets/4592712/3422674/d21b1052-ff57-11e3-94c7-f40ce53d8a68.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#269
