### ISSUE TITLE
[iPhone][Portrait][Common] Summary Drop Down text must left align when we choose from drop down

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#207]
## Description

[iPhone][Portrait][Common] Summary Drop Down text must left align when we choose from drop down
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as sandking/password
In the Portrait Mode
In the 'Active Contest' Page
Click ENTER
Check the 'Summary' section
Check the Room selection drop down --> Change the items from Drop Down
Text is too far away from the left ide margin
## Expected result

Must fix the Issue. Summary Drop Down text must left align when we choose from drop down
## Actual result

Summary Drop Down text is too far away from the left border when we choose from drop down
## Environment

iOS 7.1, Simulator
## Image

![48](https://cloud.githubusercontent.com/assets/4592712/3422679/4a7bc99c-ff58-11e3-9ca8-bc533d2f703d.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#268
