### ISSUE TITLE
"My Status" tab is disabled when it is in registration phase

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#208]
Mac 10.9.3, Chrome 35
1. load an SRM
2. login as ksmith, wait for registration starts
3. click "My Status" tab

expected: it should not be disabled.
actual: it's disabled, but "Contest Summary" is not disabled. "My Status" and "Contest Summary" both look the same. see screenshot:

![qq20140629-23](https://cloud.githubusercontent.com/assets/4590317/3423097/83b23fca-ff80-11e3-993e-1bc454747655.jpg)

**Comment by skyhit** [comment]
it is removed, we can add back if real info is provided.
