### ISSUE TITLE
Loaded Round not Always appearing in Active Contest Widget

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#213]
When a round is loaded by the backend it does not always appear in the active contest widget. Sometimes a refresh is required for it to show up.

Specifically I observed this behavior when two round were unloaded (they correctly disappeared) and then one of them was reloaded (it did NOT reappear). However I don't know if that is the specific case when it does not show up, or there are others. Investigation is required here.

**Comment by flytoj2ee** [comment]
Is there any other detail for this issue?
I test it several times but it works fine during my test.

**Comment by skyhit** [comment]
can not reproduce
