### ISSUE TITLE
After registering for match, Contest Summary is blank

### ISSUE THREAD

**Issue by ajefts** [cloudspokes/arena-web#216]

**Comment by skyhit** [comment]
yes, as you can see in arena applet, this is no such information defined for a contest or round.

**Comment by skyhit** [comment]
@mdesiderio @delemach what do you think we should show in this section?

**Comment by mdesiderio** [comment]
I think we should show the handle of the members, their current ratings, and the total points they have scored in the current match.

Anyway, let's not handle this as a bug, but as an enhancement, and add a challenge to our Backlog milestone and close this.

Thanks!

**Comment by skyhit** [comment]
added, closing this one - https://www.topcoder.com/direct/contest/detail?projectId=30045722
