### ISSUE TITLE
user should not be able to chat with himself

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#22]
1. login as ksmith in one browser and login as lightspeed in another browser
2. ksmith selects "Reply to", then click the users list, you'll see ksmith can talk to himself

expected: the users list should not contain the user himself

actual: see screenshot
![1](https://cloud.githubusercontent.com/assets/4590317/3328924/a3d7ecf8-f7c1-11e3-8ae4-b28133f365da.jpg)

**Comment by skyhit** [comment]
same as arena applet
