### ISSUE TITLE
Add real sponsor info in the footer

### ISSUE THREAD

**Issue by ajefts** [cloudspokes/arena-web#224]

**Comment by skyhit** [comment]
where should this info be retrieved?

**Comment by ajefts** [comment]
For now it's just going to be static content.  Is there a separate html file or something that we could edit and include in that part of the page?

**Comment by skyhit** [comment]
currently, it can be edited at https://github.com/cloudspokes/arena-web/blob/fb31e1d71badfde6aea57cfd88f491ac53f42fdf/app/partials/base.html#L69-L83

**Comment by skyhit** [comment]
fixed.
