### ISSUE TITLE
Can't post in other chat rooms

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#225]
Can type a message at the bottom, but hitting enter doesn't post the message.  Just clears it.

http://www.screencast.com/t/ZMxlkS1BqdBM

Also returning to first chat room (Chat Room 1), I don't see my or others chat messages for a while.  Just a black area.  Less than a minute later the messages are displayed, including my own.

**Comment by NoRKin** [comment]
Is it systematic for you? I've witnessed this bug once but I can't reproduce it.

Also it seems to be the same bug that issue #237.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue.

Does it cause by slow network connection? It works as expected if it cost long time to change room and get chat data.

**Comment by skyhit** [comment]
can not reproduce.
