### ISSUE TITLE
Menu bar disappears from Coding window

### ISSUE THREAD

**Issue by ajefts** [cloudspokes/arena-web#227]
1. Start typing in the coding window.  Note that the Save/Submit/Compile/etc. buttons are there.
2. Type enough lines to make the coding area scroll vertically.  As it starts to scroll, notice that the menu bar disappears.

**Comment by bruzzi** [comment]
I've seen this too.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue now. Is there any other detail to re-create it?

Is it possible that the contest is changed to challenge phase and then hide the menu? If so, it works as expected.

**Comment by skyhit** [comment]
this is related to Coding phase

**Comment by skyhit** [comment]
should be fixed.
