### ISSUE TITLE
user should not be able to input non existing user's handle

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#23]
win8, chrome 35
1. login as ksmith
2. selects "Reply to", then enter some random text in the users text box, post a comment

expected: the user should not be able to "Reply To" a non existing handle
![2](https://cloud.githubusercontent.com/assets/4590317/3328978/3dc8259e-f7c2-11e3-86e4-c8b2de519b61.jpg)

actual: see screenshot

**Comment by skyhit** [comment]
same as arena applet
