### ISSUE TITLE
Long handles are not displayed well

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#230]
Long handles extend behind the scrollbar, and then are simply cut off. See screenshot, which shows handle "theonewhoknocks"

![tmp](https://cloud.githubusercontent.com/assets/4539459/3528721/5808d0cc-0792-11e4-80bd-97982c6e5675.png)

**Comment by skyhit** [comment]
is there max length for handle?  what do you think the best way to handle this.

**Comment by ajefts** [comment]
15 chars is the max that we validate when users create handles...

**Comment by skyhit** [comment]
the rating indicator is not shown properly
