### ISSUE TITLE
Opening multiple windows disconnects user from arena

### ISSUE THREAD

**Issue by ajefts** [cloudspokes/arena-web#231]
When you open up more than 1 tab/browser you get disconnected and are forced to login again.

**Comment by skyhit** [comment]
yes, we only allow one page or login through arena applet.

like you can use one arena applet to login.

**Comment by ajefts** [comment]
Is that a technical constraint?  I think it would be much better for usability if people could open more than 1 window...?

**Comment by skyhit** [comment]
yes, it is technical constraint. because the socket.io connection can not be shared by different windows.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#266
