### ISSUE TITLE
Coding area scrollbar and test panel scrollbar are not friends

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#232]
Seems like they are using the same scrollbar? It is confusing and there were a couple times I could not easily scroll in the coding window or in the test panel as I moved back and forth between them.

**Comment by NoRKin** [comment]
Seems to be the same issue than #242

**Comment by flytoj2ee** [comment]
In current coding editor, the coding editor scroll bar is override by the test panel.

It comes from batch test assembly UI prototype. Is it a expected result?

**Comment by skyhit** [comment]
UI prototype?

**Comment by flytoj2ee** [comment]
![1](https://cloud.githubusercontent.com/assets/4497285/4317365/62385506-3f12-11e4-88c7-8e71cbdcca84.gif)

**Comment by skyhit** [comment]
sorry, I didn't get it.

**Comment by flytoj2ee** [comment]
In coding editor, it has scroll bar.
But if the test panel is shown, that scroll bar is hidden.

**Comment by skyhit** [comment]
except we improve the UI, it  seems not possible to change
