### ISSUE TITLE
Coding area editor not using all available screen

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#233]
The coding editor size is not expanding to use all available screen real estate. It is fixed at the size of the test panel. This could be related to [issue 232](https://github.com/cloudspokes/arena-web/issues/232).

resizing browser window and/or the coding area widget does not help.

This is on Firefox v30.0 on windows 8.1

![tmp](https://cloud.githubusercontent.com/assets/4539459/3529061/d56565c8-0795-11e4-97dd-6be468067b3a.png)

**Comment by NoRKin** [comment]
Did you use the developer tools to change the fixed height of the coding editor div? Or does it happen automatically when you load the page?

**Comment by flytoj2ee** [comment]
I also cannot re-create this issue. It's using "height: auto;" attribute in current panel. 

Is there any other detail to re-create this item?
