### ISSUE TITLE
Chat blanks out if you switch rooms after being logged in for some time

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#237]
After being logged in for some times, if you change rooms the chat window blanks out, you don't see any messages anymore and have to refresh the page.

**Comment by NoRKin** [comment]
Is it systematic for you? I've witnessed this bug once but I can't reproduce it.

Also it seems to be the same bug that issue #225.

**Comment by mdesiderio** [comment]
Yes, it was happening to me every time. What I needed to do was wait a little while and then try to change rooms.

I was using chrome on Ubuntu.

Indeed it looks like these two issues may have the same root cause, we could merge them.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue.

Does it cause by slow network connection? It works as expected if it cost long time to change room and get chat data.

**Comment by mdesiderio** [comment]
I cannot reproduce this anymore as well, I assume it has been indirectly fixed by another update.
