### ISSUE TITLE
whispered text is hard to read

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#24]
win8, IE11, chrome 35
1. login as ksmith, lightspeed in 2 browsers
2. lightspeed wispered ksmith
3. see the text

expected: the text should be easily to read
actual: it is hard to read due to the color, see screenshot
![3](https://cloud.githubusercontent.com/assets/4590317/3329038/d0ae3c90-f7c2-11e3-86db-8395980df0f5.jpg)

**Comment by skyhit** [comment]
it is following same style as arena applet.
