### ISSUE TITLE
Dropped connection boots participant back to lobby page

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#243]
if internet connection is dropped you are sent back to the lobby. 

Ideal scenario would be to remain in the coding page and still be able to work on the problem but not be able to compile, save, or test until connection is restablished

**Comment by flytoj2ee** [comment]
At first version, it'll force to login page if lost connection.

In current code, it'll popup an error message dialog, and then stay in coding editor. But it cannot re-connect, it needs to login again. It can copy the changes in coding editor.

What's the suggestion to change?

**Comment by skyhit** [comment]
if so, this issue is invalid now.
