### ISSUE TITLE
Duplicate replies to admins in chat room.

### ISSUE THREAD

**Issue by ashashwat** [cloudspokes/arena-web#252]
In new web based arena, every time I try replying to any admins [orange color] the message is duplicated.  It does not happen for other users.  

Attached is a snapshot.  

![screenshot 2014-07-10 00 51 28](https://cloud.githubusercontent.com/assets/121233/3529875/8726d884-079e-11e4-983b-9d1537ddc960.png)

**Comment by NoRKin** [comment]
Do you still have this problem? I tried to reproduce it but I can't. It seems to be working normally for me.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue. Is there any related detail? Thanks.
