### ISSUE TITLE
No phase info in summary page

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#254]
There is no phase and countdown on the room/division summary page.

![tmp](https://cloud.githubusercontent.com/assets/4539459/3529902/d170c59e-079e-11e4-9b04-338be7db66a7.png)

**Comment by skyhit** [comment]
if you want to support it, seems the UI should be changed.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#261
