### ISSUE TITLE
Empty challenge info on summary page (maybe not implemented yet?)

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#256]
The challenger/challenges info stayed empty on the summary page.

![tmp](https://cloud.githubusercontent.com/assets/4539459/3529954/55b99c22-079f-11e4-9913-04caed2235fe.png)

**Comment by skyhit** [comment]
yes, it is not implemented, need backend event support.

**Comment by skyhit** [comment]
this is implemented.
