### ISSUE TITLE
Need good way to see coder history

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#258]
In current arena you can get to the coder's history for that contest from the room/division summary by right clicking on the handle and selecting "history."

This is very hard to find if you don't know it's there. However there is extremely valuable information in there, such as which system test caused a failure.

We need to add a clean intuitive view onto this data. 

![tmp](https://cloud.githubusercontent.com/assets/4539459/3529999/d83935ea-079f-11e4-88f7-6b90133164a2.png)

**Comment by skyhit** [comment]
should we have a new column for this action? for web page, right click seems not a good way.
