### ISSUE TITLE
"find text" should be "Find text" for consistency

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#26]
1. login as ksmith
2. click the search icon to see "find text"

expected: should be changed to "Find text" for consistency with "Type chat"
actual: see screenshot
![5](https://cloud.githubusercontent.com/assets/4590317/3329125/d9659b34-f7c3-11e3-8603-0e14966012f5.jpg)

**Comment by skyhit** [comment]
this is not implemented yet/
