### ISSUE TITLE
Room Summary back button hidden.

### ISSUE THREAD

**Issue by ashashwat** [cloudspokes/arena-web#260]
If we go to "Room Summary" pane, the button to go back is barely visible.  Attached is the screenshot.  

![screenshot 2014-07-10 01 04 56](https://cloud.githubusercontent.com/assets/121233/3530067/b25fd6b6-07a0-11e4-947a-c0b23912c270.png)

**Comment by skyhit** [comment]
known issue.

**Comment by skyhit** [comment]
fixed.
