### ISSUE TITLE
Lack of option to change language in coding phase.

### ISSUE THREAD

**Issue by ashashwat** [cloudspokes/arena-web#262]
During test SRM, I wanted to code in Python.  Ideally we have an option which allow us to switch languages on the fly but I was not able to see any.  Therefore, I was forced to code in my default language i.e. C++.  Will the new arena have this option or is it hidden from plain sight ?

**Comment by skyhit** [comment]
the gear button allowed to change.

**Comment by flytoj2ee** [comment]
Yes, click the gear button in coding phase can change the languages.
