### ISSUE TITLE
Clicking a handle in chat window should set controls as "reply" to that person

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#267]
In applet arena if you double click a handle in the chat window it will set that handle as the person to whom you are replying. Web arena should have similar functionality. (Perhaps with single click instead of double.)

**Comment by flytoj2ee** [comment]
In current implementation, if user clicks the users under "who's here" section, it'll set the reply to in chat method and select the user.
If user double clicks the users under "who's here" section, it'll show the coder info popup.

I changed to user double clicks the users under registration section to show coder info to make it consistence. Is it okay?

**Comment by skyhit** [comment]
can we do like 

single click - > show coder info
double click -> make selection?

**Comment by skyhit** [comment]
fixed.
