### ISSUE TITLE
sometimes error is shown when chatting in the admin lobby

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#27]
win8, IE11, chrome 35
1. login as ksmith and lightspeed
2. they both choose to enter admin lobby room and try to chat

expected: both should be able to chat

actual: when ksmith sends message, error is shown, see screenshot

![6](https://cloud.githubusercontent.com/assets/4590317/3329233/c022685e-f7c4-11e3-9326-8667b84c6d1c.jpg)

**Comment by skyhit** [comment]
can not reproduce, I think you are sending Question type message.
