### ISSUE TITLE
Don't wipe out Chat history after changing chat rooms

### ISSUE THREAD

**Issue by gaitonde** [cloudspokes/arena-web#270]
I changed the Chat Room from Chat Room 1 to Chat Room 2. Once I went back to Chat Room 1 all the previous chats were gone in Chat Room 1. It would be nice if those didn't go away.

**Comment by skyhit** [comment]
@flytoj2ee when I switch to Chat Room 2, I can not see the messages typed. but I can see them in arena applet.

**Comment by flytoj2ee** [comment]
What's the "can not see the messages typed" mean?

I test in arena applet but it'll clean the messages.

**Comment by skyhit** [comment]
switching to Chat Room 2, there is no list of messages entered.

by default, there should be an entering room message (system message), but I can not see.

**Comment by skyhit** [comment]
the problem can not reproduce, but please check 

![image](https://cloud.githubusercontent.com/assets/58106/3933078/bbf8db8e-2477-11e4-80fa-0057385cd827.png)

**Comment by flytoj2ee** [comment]
It may be caused by network problem. I cannot re-create it now. I didn't modify the room changes logic in this issue fixed.
