### ISSUE TITLE
Admins should have the ability to "pin" a chat message in arena chat

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#273]
This way the message doesn't get lost in the chat thread as it quickly scrolls by.  For example, the "Enter" button didn't appear in today's arena match.  Would have been good to post a pinned message to all saying "We're working on it" or "Here's the solution:..."

**Comment by flytoj2ee** [comment]
What's the pin mean here? 

Is it same with the issue 268 which means lock the scroll bar?

**Comment by skyhit** [comment]
yes, not relate to admin.

**Comment by flytoj2ee** [comment]
In current implementation, if the scroll dragger is on the bottom, it'll show all chat text as usual.

If user move the scroll dragger a little up, while it's not on the bottom, it'll stop scroll and pin the message.

Is this implementation okay?

**Comment by skyhit** [comment]
looks fine. I will double check in Final fix.

**Comment by flytoj2ee** [comment]
In my test, it can work as following test steps:
a) In chat area, input some text to show scroll bar.
b) Move the scroll bar dragger a little up
c) Continue input chat text, you can see the chat area is not scroll.
d) Move the scroll bar dragger to bottom, it'll show all content.

**Comment by skyhit** [comment]
fxied.
