### ISSUE TITLE
Search in the chat window doesn't work

### ISSUE THREAD

**Issue by gaitonde** [cloudspokes/arena-web#274]
I clicked the search icon at the bottom of the chat window and the chat bar turned into a search bar. Then I typed a search term and hit enter. Nothing happened. I clicked the magnifying glass and it went back to the chat bar.

**Comment by gaitonde** [comment]
Just figured out that collapsing and re-expanding the section fixes the problem.

**Comment by flytoj2ee** [comment]
As discussed in https://github.com/cloudspokes/arena-web/issues/272 , it should not use html to show the chat content.
If so, how to highlight the search text in chat content? Highlight the lines which contain the search result?

**Comment by skyhit** [comment]
you can use html to show the chat content, just for input box, no need to support html tags.

**Comment by flytoj2ee** [comment]
I just found that it already has search function in browser. 

It implements the same logic. Does it need to implement it again in chat text fields?

**Comment by skyhit** [comment]
what do you mean in browser? (triggered by Ctrl + F)?

**Comment by flytoj2ee** [comment]
yes, use Ctrl + F to search the page. It's the common usage to search the pages in browser.

**Comment by flytoj2ee** [comment]
Any update?

**Comment by skyhit** [comment]
this is different functionality, we'd like the Search in Chat, different browser has similar functionality, but different UX.

**Comment by flytoj2ee** [comment]
Okay, I'll try to add search in chat area. But it needs some time, would you mind to extend the final fix phase a little?

**Comment by flytoj2ee** [comment]
![333](https://cloud.githubusercontent.com/assets/4497285/3907810/37b65ea2-22fe-11e4-904c-e6a37a4fa662.gif)
After look into the angularjs detail in about 6 hours, I finally find a solution to high light the search text in chat area. Please refer to above screen snap.

In current UI, it has "hightlight" checkbox. But in my understanding, it always hightlight the search text so this checkbox is unnecessary. 

What's your option?

**Comment by flytoj2ee** [comment]
It still has minor issues about search in html tags. I still working on it and will submit the final fix in coming 12 hours.

**Comment by skyhit** [comment]
compare with arena applet, for Find button, it will navigate from one to next.

with hightlight, it will show all in color.

I am not sure if it is easy to implement. I think highlight all  is fine.

**Comment by flytoj2ee** [comment]
To implement find next function, 
a) It needs to change UI. Because in current UI, it'll return to input chat text mode if clicked find button.
b) It'll cause very complex scroll operations. The reason is that ng-scroll bar is using x/y offset locations to implement the scroll. The x/y offset for rows are different in different window sizes.

Is it okay to just remove the highlight checkbox?

**Comment by skyhit** [comment]
yes, if it is not needed. I will review your implementation.

**Comment by skyhit** [comment]
@flytoj2ee the functionality works, but the Match Case checkbox is showing below. (Tested in Chrome)

**Comment by flytoj2ee** [comment]
What's the "showing below" mean? It works in my test.
![123](https://cloud.githubusercontent.com/assets/4497285/3931459/93a79752-2458-11e4-97bf-9a5e4660c6b3.gif)

**Comment by skyhit** [comment]
wired, it is different from my test, it is showing under the input section.

**Comment by flytoj2ee** [comment]
Can you clear the cache and test it again?

**Comment by skyhit** [comment]
sorry, it is cache problem.
