### ISSUE TITLE
'Who's here' list on Competition Arena doesn't show scroll bar and goes out of pane

### ISSUE THREAD

**Issue by sudoster** [cloudspokes/arena-web#276]
see below screen shot.
![screen shot 2014-07-18 at 12 57 21 am](https://cloud.githubusercontent.com/assets/1217557/3615720/422b7b26-0dcb-11e4-92d8-f25db1de7ba4.png)

**Comment by skyhit** [comment]
possilly a bug in the custom scrollbar, but can not reproduce now
