### ISSUE TITLE
Number of 'Registrants' in Chat window is blank in Competition Arena

### ISSUE THREAD

**Issue by sudoster** [cloudspokes/arena-web#278]
Registrants shows like 'Registrants()' without any number in the parenthesis.

![screen shot 2014-07-18 at 1 00 58 am](https://cloud.githubusercontent.com/assets/1217557/3615769/b7c31948-0dcb-11e4-96e3-c6dea7053ebe.png)

**Comment by flytoj2ee** [comment]
I cannot re-create this issue. Is there any more detail about it?

**Comment by skyhit** [comment]
I can not reproduce too. and for dashboard, there should be no Registrants() section, can you check the related code?

**Comment by flytoj2ee** [comment]
In Registrants section, it shows the assigned users in current room.

**Comment by skyhit** [comment]
yes, this is expected behavior.
