### ISSUE TITLE
no enter/exit messages in some browser (Chrome)

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#28]
win8, IE11, Chrome 35
1. login as lightspeed in Chrome, login as ksmith in IE11
2. they go into the same room and exit the room and then go into the room again

expected: each time there should be enter/exit messages

actual: in Chrome there is no such message, see screenshots.

![ok](https://cloud.githubusercontent.com/assets/4590317/3329336/fe6a0a08-f7c5-11e3-9355-a4922fa02c27.jpg)
![no](https://cloud.githubusercontent.com/assets/4590317/3329342/098e863e-f7c6-11e3-97dc-e5d0fef6fe27.jpg)

**Comment by skyhit** [comment]
can not reproduce, I can always see System> user has entered the room.
