### ISSUE TITLE
Unable to login directly to the Arena

### ISSUE THREAD

**Issue by gaitonde** [cloudspokes/arena-web#280]
I was unable to login directly to the arena. I had to login to topcoder.com and then go to arena.

My username has a hyphen in it (day-al) so perhaps that's the issue.

**Comment by flytoj2ee** [comment]
How to change the user name in sma.auth0.com?

I want to change user to user-1 for test. I modified the user name in database but it cannot pass the auth0 validation.

**Comment by skyhit** [comment]
because we are using a custom ldap for all VMs. even you changed the username in your database, it is not updated in ldap.

leave to final fix to work out a solution

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#258
