### ISSUE TITLE
Bottom panels should be responsive to screen height

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#283]
Would be cool if these two bottom panels could be responsive to screen height (i.e, fit to the window size, especially a typical laptop resolution), instead of requiring scrolling to see functionality below (e.g., posting chats, seeing leader board, etc.)

http://www.screencast.com/t/F4wZH9M5o8

**Comment by tghaas** [comment]
I was thinking the top panels should have the ability to be minimized, or possibly the entire screen could be rearranged.

**Comment by flytoj2ee** [comment]
In current implementation, if the window is narrow in width, it'll rearrange the pages.

Do you mean to rearrange the pages if window is changed in height?

If so, it needs to change much things and workload is too heavy for a but fix.

**Comment by flytoj2ee** [comment]
Any update?

**Comment by skyhit** [comment]
I think the requirement is for showing the Chat Widget completely, with a min height.

**Comment by flytoj2ee** [comment]
Okay, I'll add it.

**Comment by skyhit** [comment]
fixed.
