### ISSUE TITLE
Can't select bottom Chat Type options if browser window isn't big enough

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#284]
Can't scroll down to bottom chat type options if browser window size doesn't leave sufficient space under picklist.

http://www.screencast.com/t/mJjFU8rSbfZ4

**Comment by flytoj2ee** [comment]
In my test, it could show the scroll bar on the page right side if window size is resize to small. It could scroll the page to show all chat type options.

Does the scroll bar show on the right side of page?

**Comment by skyhit** [comment]
yes, the scroll bar is present, but this behaviour is wired.

can we show the drop down upward (above the box).

**Comment by flytoj2ee** [comment]
Do you mean change to show the popup to top side?

**Comment by skyhit** [comment]
I mean make it wisely to show upward or downward

**Comment by flytoj2ee** [comment]
About this issue, one reviewer has following comment.
"You bring another issue,
When collapse the "Who is here", you should adjust the size of Registrant list"

But I didn't modify "Who is here" related logic.

**Comment by skyhit** [comment]
fixed.
