### ISSUE TITLE
Unable to discern which links are enabled/disabled

### ISSUE THREAD

**Issue by gaitonde** [cloudspokes/arena-web#287]
In the "Active Contests" section there are 3 links 
1. Contest Summary
2. Contest Schedule
3. My Status

Current selected "tab" appears blue, others appear gray. While waiting for the contest to start, I was able to click on the first 2, but not the last (My Status). Assuming this is the correct behavior - the colors for "unselected" and "disabled" should be different.

**Comment by skyhit** [comment]
My Status tab is removed.
