### ISSUE TITLE
Auto-advance in chat should temporarily cease if I scroll back up to review prior chat history

### ISSUE THREAD

**Issue by bryceglass** [cloudspokes/arena-web#288]
As new Chat lines come into the window, the conversation auto-advances (scrolls down) to display the new line. This is good! :smile_cat: 

BUT, if I scroll back up in the chat history (perhaps to review what I've missed, or perhaps to find a link that someone posted, etc.) then every time a new Chat entry arrives, the window auto-jumps back down to the bottom of the conversation. Very frustrating. :frowning: 

Perhaps there should be some logic where.. if the portion of chat displayed in the window is showing within the final 'n' lines of the conversation (10? 5?) then go ahead and advance the screen to bottom to display new incoming messages. Otherwise, do nothing. 

Optionally, if chat window has sat idle for more than 5 minutes (I have not been scrolling around in it), go ahead and advance the screen to bottom. 

I think some combination of these two fixes would greatly improve the herky-jerkiness of the chat experience. Also related is issue #261 (lag in scrolling.)

**Comment by skyhit** [comment]
fixed.
