### ISSUE TITLE
Must have gap between the 'Username' and '>'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#29]
## Description

Must have gap between the 'Username' and '>'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password
Enter 'Chat' and click Enter
Check the 'Username' and '>'
## Expected result

Must fix the Issue. Must have gap between the 'Username' and '>'
## Actual result

No gap between the 'Username' and '>'
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/3329359/2b356b90-f7c6-11e3-81a3-4004b0fb6ac8.png)

**Comment by skyhit** [comment]
same style as arena applet.
