### ISSUE TITLE
Opening a problem Auto-scroll to Problem Area

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#297]
Screen auto-scroll here so I don't intuitively know there is more web page above (with the header, time countdown, etc.)

http://www.screencast.com/t/cQaGdlTArzPk

**Comment by flytoj2ee** [comment]
Strange. I test with different window sizes but it didn't auto scroll. It stays on top of page and it looks fine. Is there any detail about how to re-create this issue?

**Comment by skyhit** [comment]
seems the problem is fixed, not sure if it is related to phases.

reviewer will double check this if you can not reproduce.

**Comment by flytoj2ee** [comment]
I re-created this issue and fixed.

**Comment by skyhit** [comment]
great, please provide the steps in DG for reviewer to reproduce.

**Comment by skyhit** [comment]
fixed.
