### ISSUE TITLE
Test panel sometimes thinks I haven't selected an example to test

### ISSUE THREAD

**Issue by tghaas** [cloudspokes/arena-web#298]
Test panel sometimes thinks I haven't selected an example to test, even if I have one or more selected.

http://screencast.com/t/nteUjxgdJh

**Comment by flytoj2ee** [comment]
I think it's not an issue.

The current workflow is correct. It needs to select exact one test case to run.

**Comment by skyhit** [comment]
yes, I agree. we will improve this part in the future to support batch tests.
