### ISSUE TITLE
Problem Area--> Contest is not displaying second time if user has open the contest once.

### ISSUE THREAD

**Issue by DhananjayKumar1** [cloudspokes/arena-web#299]
1. Open any contest.
2. Go back to contest.
3. Open another contest.
4. Open first opened contest.

Screen Cast: http://screencast.com/t/u76bWmUknE

**Comment by skyhit** [comment]
it should be data latency problem, need to investigate.

**Comment by flytoj2ee** [comment]
It works in my test.

Is there more detail?

**Comment by skyhit** [comment]
can not reproduce, may be networking issue.
