### ISSUE TITLE
Getting error 'Sorry, the request is timeout.' while clicking on any Registrants user.

### ISSUE THREAD

**Issue by DhananjayKumar1** [cloudspokes/arena-web#302]
Screen Cast: screencast.com/t/dDo7VJtB

**Comment by flytoj2ee** [comment]
Cannot re-create this issue. It may be fixed by previous assemblies.

**Comment by skyhit** [comment]
yes. the same to me, possible, network problem.

**Comment by flytoj2ee** [comment]
In current code, click the user names, it'll show coder info. Double click the users in "who's here" section, it'll set reply to user in chat input fields.
