### ISSUE TITLE
'Coding Phase will end in 1 second' is displaying for long time. BUG

### ISSUE THREAD

**Issue by DhananjayKumar1** [cloudspokes/arena-web#308]
Screen Cast: http://screencast.com/t/vMosd1Duk6

**Comment by flytoj2ee** [comment]
It's same with issue https://github.com/cloudspokes/arena-web/issues/337 , it needs to refresh round in admin tools to solve it.

**Comment by skyhit** [comment]
but the client still can count to 0 and show the Coding Phase is ended. right?

**Comment by flytoj2ee** [comment]
In current code, the coding phase changes are driven by phase changed response data from server side. If it didn't get the phase changed data, it'll stay in coding phase and show "will end in 1 second".

Refresh the round in admin tool could update and send the phase changed data.

It'll move to next phase after got the phase changed data in client side.

**Comment by skyhit** [comment]
what is the behavior of this case in arena applet?

**Comment by flytoj2ee** [comment]
![1](https://cloud.githubusercontent.com/assets/4497285/3902673/f47202ea-22c1-11e4-8c37-83ee3ef12ba6.gif)

I just test it again, it's same in arena applet version and web version. Please refer to above screen snapshot.

It's missing a change phase event some times in backend code. It needs to refresh round in admin tool to send the phase changed data.

**Comment by skyhit** [comment]
can we show it like Intermission 00:00:00 as arena applet?

**Comment by flytoj2ee** [comment]
![222](https://cloud.githubusercontent.com/assets/4497285/3905139/99e7647e-22e3-11e4-89e4-7c5660cf628d.gif)

After look into code, "Challenge Phase will start in:" is equals to the "Intermission 00:00:00".

In current arena web code, there is no Intermission phase and it replaces with "Challenge Phase will start in".
