### ISSUE TITLE
Phase X "is ending" is not accurate

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#309]
We should say "has ended" as "in ending" implies it will be ending in the near future.

**Comment by skyhit** [comment]
where did you see this?

**Comment by flytoj2ee** [comment]
Any update?

**Comment by skyhit** [comment]
no, leave to final fix.  as I know this words is from backend. in the Phase Change popup

**Comment by flytoj2ee** [comment]
In phase changed popup, it has text "The coding phase is ending for Test SRM - Test SRM Round."

Replace it with "has ended" in popup?

**Comment by skyhit** [comment]
I think we should fix it in the backend.  replace is just a temporary solution.

leave it for the bug fix.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#249
