### ISSUE TITLE
"Find text" does not work

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#31]
win8, IE11, Chrome 35
1. login as lightspeed
2. enter some text "hi"
3, then click the search button, enter "hi" to search

expected: matched text should be highlighted

actual: nothing happened
![7](https://cloud.githubusercontent.com/assets/4590317/3329413/b119493e-f7c6-11e3-93ac-5bcbe8a37640.jpg)

**Comment by skyhit** [comment]
this is not implemented.
