### ISSUE TITLE
If all rooms share same challenge then coder should be able to select different room, can see leaderboard and challenge any solution.

### ISSUE THREAD

**Issue by abdul-qadir** [cloudspokes/arena-web#310]

**Comment by bruzzi** [comment]
Well, the whole point of breaking participants down into Rooms is to make the set of people you can challenge a smaller group.  That said, I would love to see a consolidated Leaderboard across all rooms, even if I can't challenge everyone: https://github.com/cloudspokes/arena-web/issues/311

**Comment by abdul-qadir** [comment]
@bruzzi Agree to have consolidated leaderboard. Not sure but that means in one rare use case, if any room has not good number of  submissions then coders can not challenge anyone/ have not enough one to challenge in that phase.

**Comment by abdul-qadir** [comment]
or we can reshuffle participants in intermission phase to balance the ratio.

**Comment by skyhit** [comment]
this is the current concept for division summary, it is not implemented yet.

we are processing it.
