### ISSUE TITLE
There should be tool tip on the 'Log Out' button.

### ISSUE THREAD

**Issue by DhananjayKumar1** [cloudspokes/arena-web#312]
Pre-condition : Browser cache/history should be cleared 
1. Hit url : http://qa.arena.topcoder.com 
2. Enter topcoder username and password 
3. Click login and once browser asks to save password click Remember 
4. Verify for the Logout button

Actual Result

There is no tool tip on the 'Log Out' button. 
Screencast : http://screencast.com/t/2y8LEzXdir2

**Comment by skyhit** [comment]
duplicated, it is ongoing.
