### ISSUE TITLE
	 'My Status' is displaying wrong data--> User has been registered in June month and displaying data under for feb month under 'My Status'.

### ISSUE THREAD

**Issue by DhananjayKumar1** [cloudspokes/arena-web#313]
Pre-condition : Browser cache/history should be cleared 
1. Hit url : http://qa.arena.topcoder.com 
2. Enter topcoder username and password 
3. Click login and once browser asks to save password click Remember 
4. Open 'Competition Arena: Dashboard'. 
5. Click on the 'My Status'. 
6. Verify the data under 'My Status'.

Actual Result:

User has been registered in June month and displaying data under for feb month under 'My Status'. 

Screencast : http://screencast.com/t/tNYfVwZ0Yrc

**Comment by skyhit** [comment]
this is dummy data, we didn't implement that yet.
