### ISSUE TITLE
Competition arena template code visible

### ISSUE THREAD

**Issue by ajayhada** [cloudspokes/arena-web#315]
I clicked on "Yes" link from one of the default message appear in right top message popup
 and it open topcoder arena template code. see screenshots 

https://dl.dropboxusercontent.com/u/12269376/images/Screen%20Shot%202014-07-24%20at%2010.18.09%20AM.png 

https://dl.dropboxusercontent.com/u/12269376/images/Screen%20Shot%202014-07-24%20at%2010.19.48%20AM.png

**Comment by skyhit** [comment]
the message arena is dummy no.
