### ISSUE TITLE
Search won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#32]
## Description

Search won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password
Enter 'Chat' : Hi this is a test chat description with long details typed, here we go this is contest description.
And Press Enter
Click Search
type: description
Check : Highlight

Press Enter
## Expected result

Must fix the Issue. Search must work
## Actual result

Search won't work
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/3329453/18eddd22-f7c7-11e3-8ed5-81d66db34ec7.png)

**Comment by skyhit** [comment]
this is not implemented.
