### ISSUE TITLE
Language not supporting its variables

### ISSUE THREAD

**Issue by NikitaJain11** [cloudspokes/arena-web#323]
Integer variable is getting failed when we test the result.

If we replace the same with int, it works.

Java should support 'Interger'.

**Comment by skyhit** [comment]
it should be supported by compiler, should not related to our system.

can you double check.

**Comment by abdul-qadir** [comment]
Spelling mistake - It should be Integer instead of 'Interger'

**Comment by skyhit** [comment]
can not reproduce
