### ISSUE TITLE
Preffered language should not change

### ISSUE THREAD

**Issue by NikitaJain11** [cloudspokes/arena-web#324]
The language selected should be maintained throughout the whole session.

Like if Java is selected by someone, it should be same across the entire test unless user changes it explicitly. But here the language is getting changed itself.

**Comment by flytoj2ee** [comment]
For user, it has default language.
For each component in each round, it has language setting too.

In current code, if user change the component language setting, and then do some operations such as compile/submit/test. It'll keep the component language in this case.

Does it need to change current workflow? If yes, how to change?

**Comment by skyhit** [comment]
> > > For user, it has default language. 
> > > you mean like in arena applet, is this default language, take affect?

if yes, can we do like user changes default language, it will update the server side too.

**Comment by skyhit** [comment]
> > > In current code, if user change the component language setting, and then do some operations such as compile/submit/test. It'll keep the component language in this case.

what if user close the component, and open another problem?

**Comment by flytoj2ee** [comment]
It could change the user default language. But what's the workflow in pages? The current language setting is for components.

Close one problem and then open another problem, it's using the default java language.

**Comment by skyhit** [comment]
the purpose is to remember user's selection during the whole session (like in the SRM).

in advance, remember in any time, unless, user change it purposely.

**Comment by flytoj2ee** [comment]
How about the following workflow?

a) User changes the language in editor. It'll change the user default language.
b) While user opening the problem, if it already has code, using the current code language.
If the problem doesn't have code, uses the user's default language.

**Comment by skyhit** [comment]
yes, this looks good.
