### ISSUE TITLE
Code is running fine in Visual studio but Compilation error in SRM challenge

### ISSUE THREAD

**Issue by shodhika** [cloudspokes/arena-web#325]
In the 250 points problem, the code was giving compilation error:
"Class BlockPutting not found"

But the code is getting successfully compiled in Microsoft Visual studio 2008.

Code:
using System;
namespace BlockPuttingApplication
{
    public class BlockPutting
    {
        private string s;
        private int count=0, space=0;
        public int getmax(string s)
        {
            this.s = s;
            int c=0;
            c=s.Length;
            for(int i=0;i<c;i++)
            {
                if(s[i]=='.')
                    c=c+1;
                else
                    c=0;
            }
            return c;
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            string inp;
            int space;
            BlockPutting bp = new BlockPutting();
            Console.WriteLine("Enter a string [only X and .]:");
            inp = Console.ReadLine();

```
        space = bp.getmax(inp);
        Console.WriteLine("The space left in the box is: {0}", space);

        Console.ReadLine();

    }
}
```

}

**Comment by skyhit** [comment]
what is the error message?

**Comment by shodhika** [comment]
Error  message is: "Class BlockPutting not found"

**Comment by skyhit** [comment]
oh, possibly, you don't need to define namespace.

**Comment by shodhika** [comment]
but when i removed namespace part, then the error for namespace was coming. I tried that.

**Comment by skyhit** [comment]
why removing namespace, I got error like

Your code did not compile:

Prohibited Method: System.Console::ReadLine
Prohibited Method: System.Console::ReadLine

which means you can not use ReadLine functionality in your solution, which is for security consideration.

**Comment by shodhika** [comment]
but i selected C# as my lang, and ReadLine is a function in that to read inputs.

**Comment by skyhit** [comment]
yes, I know, this is our system consideration, and we don't need ReadLine for inputs.
