### ISSUE TITLE
Rating a code is not working

### ISSUE THREAD

**Issue by plovek** [cloudspokes/arena-web#326]
Steps --
1. Login to application
2. Go to a contest leaderboard
3. Click on the any status like Challenged or click on the points.
4. Notice above there is an option to rate code.
5. Click +1 or -1

Expected --
I should be able to rate

Actual --
Not able to rate

**Comment by skyhit** [comment]
this is not implemented yet.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#247
