### ISSUE TITLE
color of "Admin" seems not orange

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#33]
1. login as ksmith
2. click "Rating Key" to see each color and rating

expected: "Admin" should be orange

actual: see screenshot, seems not orange, looks a bit red

![c](https://cloud.githubusercontent.com/assets/4590317/3329494/7bc8caf6-f7c7-11e3-9142-0f4724467628.jpg)

**Comment by skyhit** [comment]
this is fixed in Rating Indicator Assembly.
