### ISSUE TITLE
Request time out when we compile the Code

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#331]
## Description

Request time out when we compile the Code
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the coding phase stats
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Compile
## Expected Result

Must compile the code
## Actual Result

Request time out when we compile the Code
## Environment

IE 11 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/3710386/11ad85fc-1488-11e4-845b-1927e2c47e5d.png)

**Comment by skyhit** [comment]
env issue, no window processor.
