### ISSUE TITLE
Request time out when we compile the Code

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#332]
## Description

Request time out when we compile the Code
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the coding phase stats
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Compile
## Expected Result

Must compile the code
## Actual Result

Request time out when we compile the Code
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/3710390/68a9a5f2-1488-11e4-8508-bbaa75daae5d.png)

**Comment by skyhit** [comment]
env issue, no window processor.
