### ISSUE TITLE
The green score is not clearly seen; difficult to see the color

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#333]
## Description

The green score is not clearly seen; difficult to see the color
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the coding phase stats
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Compile
After the coding phase ends
Click 'Back to Contest'
Click 'View All' from Division II
Check the 'sandking' score' [Light and Orange Theme]
## Expected Result

Must use another color
## Actual Result

The green score is not clearly seen; difficult to see the color
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/3710402/a8243278-1489-11e4-964e-e24ba7f2bc86.png)

**Comment by ananthhh** [comment]
What color is expected ?

**Comment by skyhit** [comment]
@mdesiderio what do you think?

**Comment by mdesiderio** [comment]
Let's use the same green as the lightspeed handle on the handle column, which is a bit darker.

**Comment by skyhit** [comment]
fixed.
