### ISSUE TITLE
Extra '0' displayed in the Event registration confirmation Pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#336]
## Description

Extra '0' displayed in the Event registration confirmation Pop up
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the Registration phase stats
Click Register
Check the confirmation pop up time

Test Contest 1 - Test Round 1 starts at 2014-07-26 10:20:00.0 and is open for registration. Agree to the terms below to register.
## Expected Result

Must remove the last '0' (2014-07-26 10:20:00)
## Actual Result

Extra '0' displayed in the Event registration confirmation Pop up

Test Contest 1 - Test Round 1 starts at 2014-07-26 10:20:00.0 and is open for registration. Agree to the terms below to register.
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/3711320/3ab5c534-14d0-11e4-9d51-faab171a4aab.png)

**Comment by skyhit** [comment]
this is date format issue, same problem with arena applet.
