### ISSUE TITLE
Can't code even we are in the coding phase; Error occurs

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#337]
## Description

Can't code even we are in the coding phase; Error occurs
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the Registration phase stats
Click Register
Click Enter 
While in the Coding phase
Click Open

Check the Error message:

You cannot view the problems until the coding phase is active.
## Expected Result

Must fix the Issue; In coding phase the error must not show
## Actual Result

Error : You cannot view the problems until the coding phase is active.
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![5 1](https://cloud.githubusercontent.com/assets/4592712/3711372/6a3d40b8-14d3-11e4-81d3-a5805deb38c4.png)

![5 2](https://cloud.githubusercontent.com/assets/4592712/3711373/706fa8b8-14d3-11e4-9b1e-6badef86dd15.png)

**Comment by dexyk** [comment]
Do you get the same error in Arena applet? Sometimes you have to refresh round in Admin applet before the coding phase. Try Run contest -> Refresh Round.

**Comment by sdgun** [comment]
I have load the Contest twice, same result : Login as Partha, reassembler and Hung

**Comment by dexyk** [comment]
Try Run contest -> Refresh round (in Admin applet) (first load the round).

**Comment by sdgun** [comment]
OK, I am trying now.

**Comment by sdgun** [comment]
Same Result again.

**Comment by dexyk** [comment]
What do you get in Arena applet?

**Comment by sdgun** [comment]
In Arena Applet (ContestAppletProd), can we login as Partha, reassembler and Hung, If I login as my TC username where can I find the Contest to test?

**Comment by dexyk** [comment]
Yes, you can use those usernames, but NOT your TC username.

**Comment by sdgun** [comment]
I have created New Contest and New Round, Then all went well, Then I Reset the Values of the same contest to test them again by other users (Change Round Times); Then This issue happens

Done below steps before rerun:
1.  Go to File → Load Round Access...
2.  Select the round you created (ex. Test Contest 1 Test Round 1)
3.  Wait for the message “Change round successful”.
4.  Go to Run contest → Before contest → Load round and choose `Yes`. Wait for the message “Contest round loaded.”

**Comment by skyhit** [comment]
it is possibly round setup problem.

**Comment by flytoj2ee** [comment]
It needs to run refresh round in admin tools.

**Comment by skyhit** [comment]
after run refresh round, everything is working?

**Comment by flytoj2ee** [comment]
yes, I got this issue several times before. It works after refresh round.

**Comment by skyhit** [comment]
ok. so no need to fix this.
