### ISSUE TITLE
'Waiting to reconnect' message is not shown when we refresh the page

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#338]
## Description

'Waiting to reconnect' message is not shown when we refresh the page
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the Registration phase stats
Click Register
Click Enter 

Refresh the page
## Expected Result

Must fix the Issue; Must show it, Check it from FF
## Actual Result

'Waiting to reconnect' message is not shown when we refresh the page
## Environment

FF 30 in Windows 7
## Image

![6](https://cloud.githubusercontent.com/assets/4592712/3711575/7ff2fc4a-14dd-11e4-891c-005ded78a283.png)

**Comment by skyhit** [comment]
only relate to FF 30?

**Comment by flytoj2ee** [comment]
To fix the issue https://github.com/cloudspokes/arena-web/issues/243 , I removed these connecting messages. 

Should we add it back here?

**Comment by skyhit** [comment]
if so, what is the behaviour now for refresh ?

**Comment by flytoj2ee** [comment]
In current implementation, it'll not show the popup message after refresh page.

It'll directly log off and log in again.

**Comment by skyhit** [comment]
yes, that is fine.
