### ISSUE TITLE
'Type Chat' alignment Issue in Safari

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#34]
## Description

'Type Chat' alignment Issue in Safari
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password
Check the 'Type Chat' text
## Expected result

Must fix the Issue. Must align properly
## Actual result

'Type Chat' alignment Issue in Safari
## Environment

Safari 5.1.7 in Window 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/3329526/b5e257f2-f7c7-11e3-8c6f-b89a6f95c80d.png)

**Comment by skyhit** [comment]
can not reproduce in Safari in Mac OS, possibly env issue.,

**Comment by sdgun** [comment]
I have reported this in windows if you noticed the 'Environment'.

**Comment by skyhit** [comment]
yes, that is why I said env issue. as I know Safari in windows has some specific wired behavior, and it is not popular in windows env.
