### ISSUE TITLE
Compile Icon Issue in Orange Theme

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#340]
## Description

Compile Icon Issue in Orange Theme
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Wait till the Registration phase stats
Click Register
Click Enter 
When the Registration Phase started
Click Open

Check the (+) icon in the Compile --> Must Orange
## Expected Result

Must fix the Issue; Must display in Orange
## Actual Result

Compile Icon Issue in Orange Theme
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/3711823/63f2f8b4-14ed-11e4-86d5-01ffac94a43b.png)

**Comment by flytoj2ee** [comment]
It's using the same icon for share link on top of page.

Should we change the share icon too?

**Comment by flytoj2ee** [comment]
I changed the share icon too. It could be changed again if necessary in final fix phase.

**Comment by skyhit** [comment]
yes for style consistence.

**Comment by flytoj2ee** [comment]
Does it need to change Light Theme? It seems the current color is fine in Light Theme.

**Comment by skyhit** [comment]
not needed for Light Theme.
