### ISSUE TITLE
Invalid Dates and Data Displays in the 'Status' tab

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#341]
## Description

Invalid Dates and Data Displays in the 'Status' tab
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as Hung
Wait till the Registration phase stats
Click 'My Status' Tab

Check the Dates and Time with the Contest Schedule Tab
## Expected Result

Must fix the Issue; Must display the correct data
Must not open the 'My Status' Tab before contest ends
## Actual Result

Invalid Dates and Data Displays in the 'Status' tab
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![10 1](https://cloud.githubusercontent.com/assets/4592712/3712925/fa41800e-153f-11e4-9632-94875c99f309.png)

![10 2](https://cloud.githubusercontent.com/assets/4592712/3712926/fa436ff4-153f-11e4-835e-c7b2ff755840.png)

**Comment by skyhit** [comment]
this is not implemented. 

these are dummy data.
