### ISSUE TITLE
Reopened problems may be blank

### ISSUE THREAD

**Issue by delemach** [cloudspokes/arena-web#343]
During the internal SRM we received a report that - 
1. Open a problem
2. Return to contest
3. Open a different problem
4. Return to contest
5. Open same problem from step 1

Results in the coding window being blank - the problem statement is not correctly loaded. Please investigate.

**Comment by flytoj2ee** [comment]
It's same with https://github.com/cloudspokes/arena-web/issues/299

**Comment by skyhit** [comment]
did you try to setup two problems?

**Comment by skyhit** [comment]
can not reproduce.
