### ISSUE TITLE
'Rooms' tab Arrow Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#346]
## Description

'Rooms' tab Arrow Layout Issue
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click Rooms
## Expected Result

Must point to the 'Rooms' title
## Actual Result

'Rooms' tab Arrow Layout Issue
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/3788050/10c6389c-1a4f-11e4-9558-5ae3999bd550.png)

**Comment by flytoj2ee** [comment]
I already fixed this issue in https://github.com/cloudspokes/arena-web/pull/357

It works fine in current latest code.
