### ISSUE TITLE
error message should be ended with a dot

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#35]
1. login as ksmith
2. select "Reply To" but select no user, try to post some comment
3. see screenshot

expected: it should have a ending period
actual: see sceenshot

![8](https://cloud.githubusercontent.com/assets/4590317/3329567/22084dce-f7c8-11e3-80ce-37e0be32b53b.jpg)

**Comment by skyhit** [comment]
same as arena applet, backend issue.
