### ISSUE TITLE
'Go To' is not working in Coding Area

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#350]
## Description

'Go To' is not working in Coding Area
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click Enter
Click Open in the 'Problem'
Enter some code
Click 'Go To', enter '5' click Enter
## Expected Result

Must point to the Line number in the code area
## Actual Result

'Go To' is not working in Coding Area
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/3788084/c8edc31c-1a50-11e4-806d-0f67e4692731.png)

**Comment by flytoj2ee** [comment]
In current implementation, it'll scroll the screen to set the target line to the middle of screen. 

For example, if there is 100 lines and click go to 80, it'll scroll and set the line 80 to the middle of screen.

What's the expected to change for this issue?

**Comment by flytoj2ee** [comment]
Any update?

**Comment by skyhit** [comment]
is it possible to highlight that line, or move cursor to that line?

**Comment by skyhit** [comment]
fixed.
