### ISSUE TITLE
'Division I' and 'Division II' Arrow Layout Issue in the Summary Tab

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#351]
## Description

'Division I' and 'Division II' Arrow Layout Issue in the Summary Tab
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click Enter
Click 'Division I'
Click 'Division II'
Check the Arrow position
## Expected Result

'Division I' Arrow must point to the Text properly
## Actual Result

'Division I' Arrow Layout Issue in the Summary Tab
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/3788091/28e9d468-1a51-11e4-8064-3e905d22a2e1.png)

**Comment by skyhit** [comment]
fixed
