### ISSUE TITLE
'Division II' Content position is not as same as 'Room' and 'Division I' in the Summary Tab

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#352]
## Description

'Division II' Content position is not as same as 'Room' and 'Division I' in the Summary Tab
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click Enter
Click 'View Detail' in the Rooms Tab
Click 'Division I' or 'Rooms'
Check the 'Challengers' content position

Now Click 'Division II'
Check the 'Challengers' content position

After that when we click 'Division I' or 'Rooms' content matches with the 'Division II'
## Expected Result

'Division II' content must display in the same location as others
## Actual Result

'Division II' Content position is not as same as 'Room' and 'Division I' in the Summary Tab
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![10 1](https://cloud.githubusercontent.com/assets/4592712/3788112/0824d416-1a52-11e4-8955-f64abdefe577.png)

![10 2](https://cloud.githubusercontent.com/assets/4592712/3788113/084ed37e-1a52-11e4-8a2e-2538e2a49f12.png)

**Comment by skyhit** [comment]
fixed.
