### ISSUE TITLE
'Challengers' Table gap increase when we expand one of them in the Summary Tab

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#353]
## Description

'Challengers' Table gap increase when we expand one of them in the Summary Tab
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Challenge Phase starts
Click Enter
Click 'View Detail' in the Rooms Tab
Click 'Expand' button in the First 'Challengers' Table
Now click collapse
## Expected Result

Must maintain the same gap 
## Actual Result

'Challengers' Table gap increase when we expand one of them in the Summary Tab
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![11](https://cloud.githubusercontent.com/assets/4592712/3788117/858b2b62-1a52-11e4-9157-9e9bb2be631b.png)

**Comment by ananthhh** [comment]
Lets have some gap even before expanding ? IMO it looks better with gap.

**Comment by skyhit** [comment]
there should be some gap, but the gap should not be increased or decreased mystically.

**Comment by ananthhh** [comment]
Fine. Can we maintain the gap as shown in the screenshot of the bug ?

**Comment by skyhit** [comment]
the gap is too much, if there are some data.

**Comment by ananthhh** [comment]
This is the gap in which data will be filled. It won't increase or decrease with data. Only scrollbar will come when data exceeds the gap.
You can view this similar to chat area. Gap doesn't increase or decrease with content inside chat area but scroll bar appears when chat content fills that gap.

**Comment by flytoj2ee** [comment]
I already implemented it as above screen snapshot. Can we leave the gap size to final fix?

**Comment by skyhit** [comment]
ok, leave to final fix.

**Comment by skyhit** [comment]
fixed.
