### ISSUE TITLE
No Message when we save the code in Arena

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#354]
## Description

No Message when we save the code in Arena
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Save
## Expected Result

Must have one
## Actual Result

No Message when we save the code in Arena
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

New Arena Web:

Arena Applet:
![1 2](https://cloud.githubusercontent.com/assets/4592712/3788120/98a3420c-1a52-11e4-9497-43e18104af9b.png)

**Comment by skyhit** [comment]
this is not implemented.

**Comment by flytoj2ee** [comment]
The save link is removed in bug fix 4. Can we skip this issue?
