### ISSUE TITLE
No Message when we Clear the code in Arena

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#355]
## Description

No Message when we Clear the code in Arena
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Clear
## Expected Result

Must have one
## Actual Result

No Message when we Clear the code in Arena
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

New Arena Web:

Arena Applet:
![2 2](https://cloud.githubusercontent.com/assets/4592712/3788121/a8880d9c-1a52-11e4-8d35-f1f28f322294.png)

**Comment by flytoj2ee** [comment]
In latest code, it already has a confirmed popup dialog after clicked clear link in code editor.

Is there more detail about this issue?

**Comment by skyhit** [comment]
if so, this issue should be fixed.
