### ISSUE TITLE
Blue border appears when we click on a user in the Chat Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#356]
## Description

Blue border appears when we click on a user in the Chat Room
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click 'Room'
Click 'Room 1' or assigned Room for that user
Click on another user in the Chat Room
## Expected Result

Must not display Blue border - In any Theme
## Actual Result

Blue border appears when we click on a user in the Chat Room
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/3788152/acd8d8b6-1a54-11e4-875e-5e72f1297f25.png)

**Comment by flytoj2ee** [comment]
Again, I already fixed this kind issues in rooms assembly final fix.

Please confirm it.

**Comment by skyhit** [comment]
we will double test, it is common issue?

**Comment by ananthhh** [comment]
I too cannot reproduce this with latest code
