### ISSUE TITLE
'View Detail' must 'View Details' in the Summary Tab

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#358]
## Description

'View Detail' must 'View Details' in the Summary Tab
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click ENTER
Click 'Room', 'Division I' and 'Division II'
Check the link 'View Detail'
## Expected Result

'View Detail' must 'View Details' in the Summary Tab
## Actual Result

'View Detail' 

Check the Right side Phase section description:

Please click View Details link in Room Summary to do further actions. --> It says 'View Details'
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![13](https://cloud.githubusercontent.com/assets/4592712/3788173/16f8bfd0-1a56-11e4-83f3-9c77f991773a.png)

**Comment by skyhit** [comment]
fixed.
