### ISSUE TITLE
Layout Issue in the Chat Drop Down in IE

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#359]
## Description

Layout Issue in the Chat Drop Down in IE
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Click Theme switcher
Change the Theme
Now in the Chat window
Click on the Rooms Drop Down
## Expected Result

Must fix the Drop Down as others
## Actual Result

Layout Issue in the Chat Drop Down in IE 
## Environment

IE 11 in Windows 7
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/3788244/faa0646a-1a59-11e4-8781-966d1755b9a0.png)

**Comment by skyhit** [comment]
fixed.
