### ISSUE TITLE
[All Themes] Color Issue in the (DOT) : In Active Contest Window Info Text 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#360]
## Description

[All Themes] Color Issue in the (DOT) : In Active Contest Window Info Text 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
When the  Coding Phase starts
Check the DOT in the Active Contest Window Info Text 

eg: Test SRM  will start in . 
## Expected Result

Must use same color as the text
## Actual Result

Color Issue in the (DOT) : In Active Contest Window Info Text
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/3788270/3b7bc55a-1a5b-11e4-91ff-e84267401267.png)

**Comment by flytoj2ee** [comment]
Sometimes, admin tool will miss to send PhaseDataResponse.

If it's not get the PhaseDataResponse while the count down is less than 0, it'll show this issue's text.

If it gets the PhaseDataResponse, it should look like as following.
![37](https://cloud.githubusercontent.com/assets/4497285/4260156/53db5c90-3b2c-11e4-87e0-c00678334f3c.gif)

It could refresh round in admin tool to fix it manually.

**Comment by skyhit** [comment]
what is the red dot?

**Comment by flytoj2ee** [comment]
At first, it shows the text "Test SRM will start in 3 seconds.".

If it get the phase changed data, it'll change to "Test SRM is live!".

But if it pass the phase and it doesn't get the phase changed data, it'll show the "Test SRM will start in.".

"3 seconds" comes from count down function. It'll get empty if count down to 0.

**Comment by skyhit** [comment]
ok, close this.
