### ISSUE TITLE
[Dark Theme] Rating '1500-2199' highlighted in BLUE when we hover over it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#361]
## Description

[Dark Theme] Rating '1500-2199' highlighted in BLUE when we hover over it
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Expand the 'Rating Key' in the Chat room
Hover over '1500-2199'
## Expected Result

Must not have hover effect
## Actual Result

Rating '1500-2199' highlighted in BLUE when we hover over it
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/3788283/80542f72-1a5c-11e4-958f-b46a74148ca0.png)

**Comment by skyhit** [comment]
fixed.
