### ISSUE TITLE
icon should not be shown below the column name

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#362]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed
3. go into the Room when the coding starts
4. click "Division II" to see leaderboard
5. click each column name to sort, observe

expected: the "triangle" icon should be shown to the right side of each column name.
actual: see screenshot, when the column is "R", it is shown below to the column name.
![2](https://cloud.githubusercontent.com/assets/4590317/3790118/394bef9e-1ae7-11e4-93f5-f86d60d18ad5.jpg)

**Comment by ananthhh** [comment]
I cannot reproduce this, icon is display properly. Is there any special condition like resize or something like that need to be applied to reproduce this ?

**Comment by skyhit** [comment]
what do you mean "display properly"? it is shown to the right side of "R"?

**Comment by flytoj2ee** [comment]
![123](https://cloud.githubusercontent.com/assets/4497285/3941967/e2ca1176-254c-11e4-92d3-7d31f956f1fa.gif)
I also cannot re-create this issue. I test with long user handle but it shows properly.

**Comment by ananthhh** [comment]
Yes. I mean  it is shown to the right side of "R"

**Comment by skyhit** [comment]
if you can not reproduce, then leave it.

**Comment by skyhit** [comment]
it can be reproduced in Chrome Version 36.0.1985.143.

**Comment by skyhit** [comment]
and IE 11.

**Comment by flytoj2ee** [comment]
I still cannot re-create this issue.

Could you provide your VM and I connect to test? It maybe data related. I re-installed the database but still cannot re-create this issue.

**Comment by skyhit** [comment]
fixed.
