### ISSUE TITLE
[Orange Theme] Layout Issue in the 'Profile Overview & Important Messages' 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#363]
## Description

[Orange Theme] Layout Issue in the 'Profile Overview & Important Messages' 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Now check the 'Profile Overview & Important Messages' section
No gap in between the title section and data section
## Expected Result

Must have some gap in between the title section and data section
Compare with the other themes (Dark and Light)
## Actual Result

[Orange Theme] Layout Issue in the 'Profile Overview & Important Messages'
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![16 1](https://cloud.githubusercontent.com/assets/4592712/3790032/46caf478-1ae0-11e4-8989-8ee455e1176f.png)

![16 2](https://cloud.githubusercontent.com/assets/4592712/3790033/46cbedf6-1ae0-11e4-8f0c-726047b75f53.png)

**Comment by skyhit** [comment]
fixed.
