### ISSUE TITLE
blue border shown when clicking the row of the "Rooms" 

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#364]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed
3. go into the Room when the coding starts
4. click "Rooms" tab
5. click the rooms list row, observe

expected: there should be no blue border shown

actual: see screenshot
![3](https://cloud.githubusercontent.com/assets/4590317/3790115/12a9084a-1ae7-11e4-8b1e-cbb41a8f3dde.jpg)

**Comment by skyhit** [comment]
duplicated.
