### ISSUE TITLE
Sorting Icon Issue in the Division Leaderboard (I and II)

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#365]
## Description

Sorting Icon Issue in the Division Leaderboard (I and II)
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
Click 'View Detail' in the 'Division I or II'
Go to leaderboard section
Click Columns one by one

Check 'Place, R, Handle'  --> Asc
Also Check '500, Score' --> Dec
## Expected Result

Must sort the All columns 'Ascending' Order
## Actual Result

Sorting Icon Issue in the Division Leaderboard (I and II)
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![17](https://cloud.githubusercontent.com/assets/4592712/3790048/3b7b8d52-1ae1-11e4-96d2-fcd99209119c.png)

**Comment by skyhit** [comment]
what do you mean?  the sort can be asc or desc.

**Comment by ananthhh** [comment]
I don't understand. What's the issue here ?

**Comment by flytoj2ee** [comment]
Any update for this issue? It's not so clear in description.

**Comment by skyhit** [comment]
I think it is related to the default sort order for each column.

**Comment by flytoj2ee** [comment]
Oh, I see.

**Comment by skyhit** [comment]
fixed.
