### ISSUE TITLE
clicking "History" during coding phase will show user info modal

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#366]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed
3. go into the Room when the coding starts
4. click "Division II"
5. click "History" link

expected: it should not show user info modal

actual: see screenshot

![4](https://cloud.githubusercontent.com/assets/4590317/3790113/fa69a870-1ae6-11e4-898e-e1b2e3bdf0f7.jpg)

**Comment by skyhit** [comment]
duplicated.
