### ISSUE TITLE
Share button is not working

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#367]
## Description

Share button is not working
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
Click 'Share' button
## Expected Result

Share button must work
## Actual Result

Share button is not working
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/3790051/ecc00214-1ae1-11e4-9b29-1d43c560c3bb.png)

**Comment by skyhit** [comment]
this is not implemented.
