### ISSUE TITLE
no way to easily go to my own room if I am in others' room

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#368]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed
3. go into other room when the coding starts
4. now I want to go back to my room

expected: there should be an easy way to go back to my own room on any page

actual: no way to go my room easily

**Comment by ananthhh** [comment]
Can we use text 'Back to my room' in button ?
This should be visible only if user is in different room ?

**Comment by skyhit** [comment]
yes.

**Comment by skyhit** [comment]
fixed.
