### ISSUE TITLE
'Registrants' hyperlink is not in Orange color

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#369]
## Description

'Registrants' hyperlink is not in Orange color
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
Check the 'Registrants' in the Contest Overview section

Compare with the Light and Dark themes
## Expected Result

'Registrants' hyperlink must in Orange color
## Actual Result

'Registrants' hyperlink is not in Orange color
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![19 1-orange](https://cloud.githubusercontent.com/assets/4592712/3790060/6e60bb10-1ae2-11e4-9964-becfb0e28dae.png)

![19 2](https://cloud.githubusercontent.com/assets/4592712/3790061/6e8cdbb4-1ae2-11e4-99ab-c2c1828efa96.png)

**Comment by ananthhh** [comment]
In orange theme, all links are in this color only. Link hover only is orange color.
Check the 'View Detail' link in same screen shot, its also in same color. 
Do we have to do any change here ?

**Comment by skyhit** [comment]
can we follow the link style at http://www.topcoder.com/community/?

**Comment by ananthhh** [comment]
There is a slight change required in all links if we follow http://www.topcoder.com/community/, in http://www.topcoder.com/community/ link color is light grey(hash666) and in arena-web it is dark grey(hash333) should we change this in all places  or lets keep it same ?
Hover color is orange and there is no change required for that.

**Comment by flytoj2ee** [comment]
I'm a little confuse now. Only update the issue mentions links, or update all links?

**Comment by skyhit** [comment]
leave to final fix, I have to check with PM and Designer.

**Comment by flytoj2ee** [comment]
Okay, so I updated the issues as above issue steps required. And it's final fix issues to update it again.

**Comment by skyhit** [comment]
fixed.
