### ISSUE TITLE
caption of the modal should be changed

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#370]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed
3. go into others room when the coding starts
4. click "Open" for a problem, see the error modal

expected: the caption of the modal should be changed, e.g. change to "Error".

actual: see screenshot
![5](https://cloud.githubusercontent.com/assets/4590317/3790112/e423f02a-1ae6-11e4-9bc0-2e4432dd4f73.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#245
