### ISSUE TITLE
'Match Case' Layout issue in Chat Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#371]
## Description

'Match Case' Layout issue in Chat Room
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ROOMS
Click on a Room
Go to Chat Room
Click on a Search icon

Check 'Match Case' 
## Expected Result

Must fix the issue
## Actual Result

'Match Case' Layout issue in Chat Room
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![20](https://cloud.githubusercontent.com/assets/4592712/3790073/9f2e5972-1ae3-11e4-84df-13f807107da6.png)

**Comment by flytoj2ee** [comment]
I already fixed this issue in bug fix assembly 4. Can you confirm it? Thanks.

**Comment by skyhit** [comment]
yes if you are using latest commit hash.

**Comment by skyhit** [comment]
fixed.
