### ISSUE TITLE
location of the "angle" should be below the "Rooms"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#372]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed
3. click "Rooms" , observe

expected: the location of the "angle" should be below the "Rooms" 

actual: see screenshot
![an](https://cloud.githubusercontent.com/assets/4590317/3790111/c9cf9990-1ae6-11e4-83fd-ab67b528e598.jpg)

**Comment by skyhit** [comment]
duplicated.
