### ISSUE TITLE
duplicate slash in the URL

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#373]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as user
3. view division II summary after coding starts
4. observe the URL

expected: there should be no duplicate slash

actual: see screenshot
![du](https://cloud.githubusercontent.com/assets/4590317/3790107/66e55e64-1ae6-11e4-9e48-b636350fa417.jpg)

**Comment by flytoj2ee** [comment]
I cannot re-create this issue. Is there more detail?

**Comment by skyhit** [comment]
no, if you can not reproduce by following the steps. I think it may be already fixed.
