### ISSUE TITLE
sometimes the division summary cannot be loaded

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#374]
win8, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
2. login as lightspeed and user, both finish the SRM problem.
3. view division II summary after coding starts

expected: the division summary should be loaded always

actual: see screenshot, sometimes it cannot be loaded

![div](https://cloud.githubusercontent.com/assets/4590317/3790109/9a05d4ae-1ae6-11e4-82b7-34a65b54fc9b.jpg)

**Comment by skyhit** [comment]
looks like networking problem.
