### ISSUE TITLE
'Open' hyperlink is not in Orange color

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#375]
## Description

'Open' hyperlink is not in Orange color
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
Check the 'Open' in the 'Competition Status'

Compare with the Light and Dark themes
## Expected Result

'Open' hyperlink must in Orange color
## Actual Result

'Open' hyperlink is not in Orange color
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![21 1](https://cloud.githubusercontent.com/assets/4592712/3790202/d69abd18-1aef-11e4-8dc3-6b1e923ed98b.png)

![21 2](https://cloud.githubusercontent.com/assets/4592712/3790203/d69c862a-1aef-11e4-9bc8-5d882155a6e6.png)

**Comment by ananthhh** [comment]
This is similar to #369
Any change required ?

**Comment by skyhit** [comment]
yes, see that ticket.

**Comment by skyhit** [comment]
fixed.
