### ISSUE TITLE
border will be shown for the room leaderboard table when clicking in the table

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#376]
mac 10.9.3, chrome 35
1.  launch an SRM, register the following users: lightspeed, user, hung, sandking
2.  login as sandking and user, both finish the SRM problem.
3.  view the room leaderboard , click in the table, observe

expected: there should be no border shown when clicking in the table

actual: see screenshot

![qq20140803-3](https://cloud.githubusercontent.com/assets/4590317/3790274/2545e546-1af5-11e4-8cfe-14605b412400.jpg)

**Comment by flytoj2ee** [comment]
Does it same with https://github.com/cloudspokes/arena-web/issues/356 ?

**Comment by skyhit** [comment]
yes.

**Comment by skyhit** [comment]
fixed.
