### ISSUE TITLE
unable to go back to division II leaderboard page after viewing the problem solution

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#377]
mac 10.9.3, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2. login as sandking, go into the room
3. click "Division II" to view the division II leaderboard after challenge phase ends
4. click on a point value to view the solution
5. click "Back to contest"

expected: the user should be redirected to "Division II leaderboard" page after step 5

actual: see screenshots, the user will be taken back to his room

![qq20140803-4](https://cloud.githubusercontent.com/assets/4590317/3790400/cdac65ce-1b00-11e4-9e48-ba0001275736.jpg)
![qq20140803-6](https://cloud.githubusercontent.com/assets/4590317/3790404/f216b61c-1b00-11e4-83d8-37baec91a66a.jpg)

**Comment by skyhit** [comment]
fixed.
