### ISSUE TITLE
intermediate message for loading division leaderboard looks weird

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#378]
mac 10.9.3, chrome 35
1. launch an SRM, register the following users: lightspeed, user, hung, sandking
   1. login as sandking, go into the room
   2. click "Division II"
2. observe
   expected: the intermediate message should be changed dynamically while loading
   actual: see screenshot, it seems always shown as "0/2"
   ![qq20140803-5](https://cloud.githubusercontent.com/assets/4590317/3790405/422d8194-1b01-11e4-8dd9-38d688300ddb.jpg)

**Comment by skyhit** [comment]
looks like networking problem, I can not reproduce.
