### ISSUE TITLE
[iPad] unable to view problem solution on the division leader page

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#379]
mac 10.9.3, iPad simulator 7.1, Safari 
1.  launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  login as sandking, go into the room
3.  click "Division II" to view the division II leaderboard after challenge phase ends
4.  try to  click on a point value to view the solution

expected: the chosen problem should be opened

actual: nothing happened

![qq20140803-7](https://cloud.githubusercontent.com/assets/4590317/3790533/51116050-1b0a-11e4-88ac-7982f0128fbc.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#244
