### ISSUE TITLE
'Find text...' Alignment Issue in Safari

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#38]
## Description

'Find text...' Alignment Issue in Safari
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password
Click Search
Check the 'Find text...' Alignment
## Expected result

Must fix the Issue. Must align properly
## Actual result

'Find text...' Alignment Issue in Safari
## Environment

Safari 5.1.7 in Window 7
## Image

![5](https://cloud.githubusercontent.com/assets/4592712/3329646/c7ec0ab4-f7c8-11e3-9d3e-df8bed856a7f.png)

**Comment by skyhit** [comment]
can not reproduce in Safari in Mac OS
