### ISSUE TITLE
[iPhone] too much vertical space

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#380]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. observe the vertical space

expected: the vertical space should be decreased a little
actual: see screenshot
![qq20140803-8](https://cloud.githubusercontent.com/assets/4590317/3790547/d0516440-1b0b-11e4-9f4e-bad95539be0d.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#243
