### ISSUE TITLE
[iPhone] "Place" is patically seen when sorting by it

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#381]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  login as sandking, go into the room, wait until challenge phase ends
3. then view Division II leaderboard
4. click "Place" column to sort, observe

expected: the "P" should not be cut
actual: see screenshots, both orientations have such issue.

![qq20140803-9](https://cloud.githubusercontent.com/assets/4590317/3790559/53aa36aa-1b0c-11e4-9301-cd9766b16457.jpg)

![qq20140803-10](https://cloud.githubusercontent.com/assets/4590317/3790563/81fca682-1b0c-11e4-8b05-cd83c6cf14d7.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#256
