### ISSUE TITLE
[iPhone] "Back to Contest" is not aligned well when viewing leaderboard in full screen mode

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#382]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. click "Division II" to view leaderboard
4. click "Expand" 
5. observe the location of "Back to Contest" button

expected: it should be aligned well to the right side.
actual: see screenshot

![qq20140803-11](https://cloud.githubusercontent.com/assets/4590317/3790568/fe4b5c92-1b0c-11e4-823e-8bdd6ca2c6d0.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#241
