### ISSUE TITLE
[iPhone] "Filter" and "View" are too close 

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#383]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. click "Division II" to view leaderboard
4. click "Expand" 
5. observe the location of "Filter" and "View"

expected: they should not be so close
actual: see screenshot
![qq20140803-12](https://cloud.githubusercontent.com/assets/4590317/3790570/49c4ed96-1b0d-11e4-9646-bd93a197f4ae.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#242
