### ISSUE TITLE
[iPhone] "Unopened" is shown as "Unopen" in "Full Screen" mode

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#384]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, Hung, sandking, all finish at least one problem except Hung
2.  in Portrait mode, login as sandking, go into the room 
3. click "Division II" to view leaderboard
4. click "Expand" 
5. observe the unopened problem status in the table

expected: it should be "Unopened"
actual: see screenshot, it's "Unopen"
![qq20140803-13](https://cloud.githubusercontent.com/assets/4590317/3790580/9b054264-1b0d-11e4-8ae8-a92252eed0c3.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#240
