### ISSUE TITLE
"R" is not aligned well with the rating indicator icons

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#385]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. click "Division II" to view leaderboard
4. click "Expand" 
5. observe the alignment of "R" and rating indicator icons

expected: they should be aligned well with each other
actual: see screenshot
![qq20140803-14](https://cloud.githubusercontent.com/assets/4590317/3790582/160c2dc4-1b0e-11e4-9ee0-62c1c663f657.jpg)

**Comment by skyhit** [comment]
fixed.
