### ISSUE TITLE
[iPhone] "Score" is not fully seen in landscape mode

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#386]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Landscape mode, login as sandking, go into the room 
3. click "Division II" to view leaderboard
4. observe the score column

expected: it should be fully seen
actual: see screenshot
![qq20140803-15](https://cloud.githubusercontent.com/assets/4590317/3790586/57b3d7ea-1b0e-11e4-9529-fc06405c4c1e.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#239
