### ISSUE TITLE
[iPhone][Portrait] unable to see all columns

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#387]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. observe Summary section

expected: user should be able to scroll horizontally to view all columns.

actual: see screenshot, not all columns can be seen
![qq20140803-16](https://cloud.githubusercontent.com/assets/4590317/3790592/f7772336-1b0e-11e4-970f-f6f5262b4c72.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#238
