### ISSUE TITLE
[iPhone] Layout Issue when we expand the 'Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#388]
## Description

[iPhone] Layout Issue when we expand the 'Leaderboard'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
In the Summary
Click 'View Detail'
Scroll down
Click Expand Button
## Expected Result

Must fix the Issue
## Actual Result

Layout Issue when we expand the 'Leaderboard'
## Environment

iOS Simulator
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/3790593/f9ec6518-1b0e-11e4-9618-e7659b3d7f58.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#237
