### ISSUE TITLE
[iPhone] unnecessary spaces should be removed 

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#389]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. click "Division II" to view leaderboard
4. scroll down to observe

expected:  unnecessary vertical spaces should be removed

actual: see screenshot
![qq20140803-17](https://cloud.githubusercontent.com/assets/4590317/3790603/56965116-1b0f-11e4-87bf-bf9c2869c332.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#236
