### ISSUE TITLE
Chat user list goes beyond the Chat lobby

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#39]
## Description

Chat user list goes beyond the Chat lobby
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password
Expand the 'Who is here (4)
Must have 4 or more users

Now expand the 'Rating Key'
## Expected result

Must fix the Issue. Must display with in the lobby area
## Actual result

Chat user list goes beyond the Chat lobby
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+ in Window 7
## Image

![6](https://cloud.githubusercontent.com/assets/4592712/3329734/9de61aec-f7c9-11e3-80b2-39383e39392f.png)

**Comment by skyhit** [comment]
can not reproduce
