### ISSUE TITLE
[iPhone][Common] Filter window is not seen fully

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#390]
## Description

[iPhone][Common] Filter window is not seen fully
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
In the Summary
Click 'View Detail'
Click 'Filter' option in the Page (any Filter option)
## Expected Result

Must fix the Issue
## Actual Result

[iPhone][Common] Filter window is not seen fully
## Environment

iOS Simulator
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/3790604/5bbf56ba-1b0f-11e4-9276-af37697a04f7.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#235
