### ISSUE TITLE
[iPhone] colon expected for the competition status text

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#391]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Landscape mode, login as sandking, go into the room when the challenge phase ends
3. observe the status text

expected: there should be a colon shown , just like the web version
actual: see screenshots

**Comment by skyhit** [comment]
where are the screenshots?

**Comment by winterflame** [comment]
Attached the screenshot for iPhone:
![qq20140803-18](https://cloud.githubusercontent.com/assets/4590317/3811681/296a9dfc-1ca2-11e4-9ef0-8905cda4940c.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#255
