### ISSUE TITLE
[iPhone][Common] Too much space in between the 'Challengers' and 'Leaderboard' sections

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#392]
## Description

[iPhone][Common] Too much space in between the 'Challengers' and 'Leaderboard' sections
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
In the Summary
Click 'View Detail'
Check the 'Challengers' and 'Leaderboard' Section spaces in Portrait Mode
## Expected Result

Must fix the Issue
## Actual Result

Too much space in between the 'Challengers' and 'Leaderboard' sections
## Environment

iOS Simulator
## Image

![24 1](https://cloud.githubusercontent.com/assets/4592712/3790608/c1c30858-1b0f-11e4-8a73-2806badcc57d.png)

![24 2](https://cloud.githubusercontent.com/assets/4592712/3790609/c1f32aba-1b0f-11e4-8ad0-6f43019724c3.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#234
