### ISSUE TITLE
[iPhone] rating key should be shown fully 

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#393]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. observe the Rating key section

expected: user does not need to scroll down in order to view all, all rating keys should be shown

actual: see screenshot
![qq20140803-19](https://cloud.githubusercontent.com/assets/4590317/3790613/1cf90dd0-1b10-11e4-8314-945b08a7d278.jpg)

**Comment by skyhit** [comment]
not necessary, as it is not important.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#233
