### ISSUE TITLE
[iPhone][Common] Phase progress bar last items are not fully seen

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#394]
## Description

[iPhone][Common] Phase progress bar last items are not fully seen
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Click ENTER
Check the Phase progress bar

NOTE: In DARK Theme
## Expected Result

Must fix the Issue. Must display them
## Actual Result

Phase progress bar last items are not fully seen
## Environment

iOS Simulator
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/3790614/1e204124-1b10-11e4-9a5c-ee85838d66c3.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#232
