### ISSUE TITLE
[iPhone] "OK" button is not seen on the modal

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#395]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Landscape mode, login as sandking, go into the room 
3. in chat section, click a user's handle
4. observe

expected: the "OK" button should be shown
actual: see screenshot
![qq20140803-20](https://cloud.githubusercontent.com/assets/4590317/3790619/6281f844-1b10-11e4-9fde-0e30d2aab146.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#231
