### ISSUE TITLE
"Get" and "Retrieve" should be consistent

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#396]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. click on a user's handle, observe the intermediate modal

expected:  the verbs used should be consistent

actual: see screenshot
![qq20140803-21](https://cloud.githubusercontent.com/assets/4590317/3790639/0a801f76-1b11-11e4-8915-76afdee33432.jpg)

**Comment by skyhit** [comment]
that is fine.
