### ISSUE TITLE
[Common] 'Contest Schedule' Headings color are not different than the text in Orange and Light

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#397]
## Description

[Common] 'Contest Schedule' Headings color are not different than the text in Orange and Light
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Check the 'Contest Schedule' Headings color
In Orange and Light Theme --> Compare with the Dark Theme
## Expected Result

Must fix the Issue. Must use different color
Using different Colors; user can separate the sections very clearly. specially in Mobile versions
## Actual Result

'Contest Schedule' Headings color are not different than the text in Orange and Light
## Environment

iOS Simulator
IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![26 1](https://cloud.githubusercontent.com/assets/4592712/3790654/12536f5e-1b12-11e4-8189-5042c87ab667.png)
![26 2](https://cloud.githubusercontent.com/assets/4592712/3790655/12541ee0-1b12-11e4-9af0-cdc9febe07bf.png)
![26 3](https://cloud.githubusercontent.com/assets/4592712/3790656/12552588-1b12-11e4-874e-c75799a84996.png)

iOS:
![26 4](https://cloud.githubusercontent.com/assets/4592712/3790657/1256749c-1b12-11e4-8c4f-87b74892dd00.png)

**Comment by skyhit** [comment]
that is fine.
