### ISSUE TITLE
[iPhone] options in the dropdown cannot be dismissed if pressing outside

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#398]
mac 10.9.3, iPhone 4-inch simulator, Safari
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  in Portrait mode, login as sandking, go into the room 
3. click the "Room" dropdown
4. then click the outside part of the dropdown

expected: it should dismiss the option values of the dropdown.
actual: see screenshot, it will not dismiss the option values, but only blue background will be dismissed
![Uploading QQ20140803-22.jpg . . .]()

**Comment by skyhit** [comment]
missing screenshot.
