### ISSUE TITLE
icon is shown under the column name

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#399]
mac 10.9.3, chrome 35
1.    launch an SRM, register the following users: lightspeed, user, hung, sandking, all finish at least one problem
2.  login as sandking, go into the room 
3. in "Challenge" section, click the first column to sort
4. observe

expected: the triangle icon should not be shown under the column name
actual: see screenshot
![qq20140803-23](https://cloud.githubusercontent.com/assets/4590317/3790756/df212120-1b17-11e4-8ce6-fbff38f1cfde.jpg)

**Comment by skyhit** [comment]
duplicated.
