### ISSUE TITLE
Can type in the users list, when we select 'Reply To' in the Lobby

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#40]
## Description

Can type in the users list, when we select 'Reply To' in the Lobby
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as yoshi/password
Select : Reply to
Select a user from drop down
Activate cursor on it
Type any text
## Expected result

Must fix the Issue. Must disable typing in the user list textbox when we select 'Reply to'
## Actual result

Can type in the users list, when we select 'Reply To' in the Lobby
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![7](https://cloud.githubusercontent.com/assets/4592712/3329801/5ada19d2-f7ca-11e3-82cb-67aee475696b.png)

**Comment by skyhit** [comment]
same as arena applet.
