### ISSUE TITLE
[Common] Summary Section Arrow for 'Room', 'Division I', 'Division II' is not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#400]
## Description

[Common] Summary Section Arrow for 'Room', 'Division I', 'Division II' is not visible
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile
Now go to Lobby
Click ENTER
Click View Detail
Now switch the theme
## Expected Result

Summary Section Arrow for 'Room', 'Division I', 'Division II' must visible when switching the theme
## Actual Result

Summary Section Arrow for 'Room', 'Division I', 'Division II' is not visible
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7

**Comment by skyhit** [comment]
missing images.
