### ISSUE TITLE
Column is not sorting

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#401]
## Description

Column is not sorting
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile
Now go to Lobby
Click ENTER
Click View Detail
Go to Division I

(Must have one user with the status 'Compiled', Other 'Unopened'

Click '250' or '500' etc to sort the column
## Expected Result

Must sort the column
## Actual Result

Column is not sorting
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/3790766/afe23894-1b18-11e4-9fa6-5634be66caf4.png)

**Comment by skyhit** [comment]
it should sortable, but mainly because of no score.
