### ISSUE TITLE
[iPhone] Test Panel Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#402]
## Description

[iPhone] Test Panel Layout Issue
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile
Now go to Lobby
Click ENTER
Click 'Open' in the Problem Area
In the Coding Window
Click 'Test Panel
## Expected Result

Must fix the Issue
## Actual Result

[iPhone] Test Panel Layout Issue
## Environment

iOS
## Image

![29](https://cloud.githubusercontent.com/assets/4592712/3790861/d0dd0000-1b1e-11e4-8875-616beade1467.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#230
