### ISSUE TITLE
Layout Issue in the 'Problem Area' When we collapse it 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#403]
## Description

Layout Issue in the 'Problem Area' When we collapse it 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile
Now go to Lobby
Click ENTER
Click 'Open' in the Problem Area
In the Coding Window
Click 'collapse' in the 'Problem Area'
## Expected Result

Must hide the content when we collapse it
## Actual Result

Layout Issue in the 'Problem Area' When we collapse it
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/3790863/de50fdf4-1b1e-11e4-81f2-0915412889fd.png)

**Comment by flytoj2ee** [comment]
It already fixed in latest code.

It has one white border in light theme but I don't think it's an issue.

**Comment by skyhit** [comment]
yes.
