### ISSUE TITLE
Layout Issue in the Rate (-1) indicator

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#404]
## Description

Layout Issue in the Rate (-1) indicator
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenge
Enter the Code and compile
Now go to Lobby
Click ENTER
Click 'Open' in the Problem Area
In the Coding Window
Check the Rate (-1) indicator
## Expected Result

Must have some space in between the icon and text
## Actual Result

Layout Issue in the Rate (-1) indicator
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![31](https://cloud.githubusercontent.com/assets/4592712/3790866/f0bee5e6-1b1e-11e4-8507-967596fe5c06.png)

**Comment by skyhit** [comment]
fixed.
