### ISSUE TITLE
After we test a wrong values and then test a valid value won't display the GREEN circle

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#405]
## Description

After we test a wrong values and then test a valid value won't display the GREEN circle
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile

public class TestProblem {
    public int sum(int A, int B) {
        if (A == 100) {
            return -1;
        }
        return A + B;
    }
}

Click 'Test Panel'
select a Example (intA=5, intB=10)
Click Run Test
It will display Green circle when it is OK

select a Example (intA=100, intB=10)
Click Run Test
It won't display Green circle

select a Example (intA=10, intB=10)
Click Run Test
It won't display Green circle when it is OK
## Expected Result

Must display the green circle
## Actual Result

After we test a wrong values and then test a valid value won't display the GREEN circle
## Environment

IE 9-11, Safari 5.1.7, Chrome 35.0.1916.153 m and FF 30 in Windows 7
## Image

![32](https://cloud.githubusercontent.com/assets/4592712/3790927/21ab8fd6-1b21-11e4-86e5-e5727329584e.png)

**Comment by dexyk** [comment]
The red/green circle should appear only when the tests you provided are one of the example tests. The back end won't give you the response about the correctness if you provide custom example.

**Comment by skyhit** [comment]
correct. the custom test need your own assessment.

**Comment by flytoj2ee** [comment]
So it's not an issue?

**Comment by skyhit** [comment]
originally, there is a green cricle for example test cases.

**Comment by flytoj2ee** [comment]
I test it again and it shows green cricle after test with wrong test case and example test case.

![1112](https://cloud.githubusercontent.com/assets/4497285/3942038/e6968416-2550-11e4-8eee-fb10ecf32937.gif)

**Comment by ananthhh** [comment]
There is green or red circle based on success and failure of example test case. No circle for custom test case. 
This is how its working now. Below are all screenshots
![image](https://cloud.githubusercontent.com/assets/3583234/3942548/5b03676e-256b-11e4-8c44-56d5fc28af1d.png)
![image](https://cloud.githubusercontent.com/assets/3583234/3942550/795f9a2a-256b-11e4-9291-2bb19f5d5f41.png)
![image](https://cloud.githubusercontent.com/assets/3583234/3942553/a309d58e-256b-11e4-80ba-53023370e18a.png)

What change required here ?

**Comment by skyhit** [comment]
if so, no change needed.
