### ISSUE TITLE
Layout Issue in the Challenge Phase in the Code Editor

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#406]
## Description

Layout Issue in the Challenge Phase in the Code Editor
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile

When the Challenge Phase is on
Click on the Division and click View Details
Click on the score of another user
Check the Code editor top section
## Expected Result

Must remove/reduce the empty space on the top
## Actual Result

Layout Issue in the Challenge Phase in the Code Editor
## Environment

iOS, Simulator
## Image

![33](https://cloud.githubusercontent.com/assets/4592712/3790968/b06ce214-1b22-11e4-8426-5e55703f5f0c.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#229
