### ISSUE TITLE
Programming Language and Search box touches each other in the Code Editor [Challenge Phase]

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#407]
## Description

Programming Language and Search box touches each other in the Code Editor [Challenge Phase]
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile

When the Challenge Phase is on
Click on the Division and click View Details
Click on the score of another user
Check the Code editor top section
Check the gap between Programming Language and Search box
## Expected Result

Must have some gap in between them
## Actual Result

Programming Language and Search box touches each other in the Code Editor [Challenge Phase]
## Environment

iOS, Simulator
## Image

![34](https://cloud.githubusercontent.com/assets/4592712/3790980/1e89517e-1b23-11e4-815b-34d68b6a6da5.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#228
