### ISSUE TITLE
[iPhone][Portrait] Share button (-), touches the Share content container [Challenge Phase]

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#408]
## Description

[iPhone][Portrait] Share button (-), touches the Share content container [Challenge Phase]
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as sandking
Wait till the Registration phase starts
Click Register
Wait till the Coding Phase Starts
Go to the Assigned Room
Click open in the Challenege
Enter the Code and compile

When the Challenge Phase is on
Click on the Division and click View Details
Click on the score of another user
Click (+) in the Share button

Now check the (-) button and container border
## Expected Result

Must have some gap in between them
## Actual Result

Share button (-), touches the Share content container [Challenge Phase]
## Environment

iOS, Simulator
## Image

![35](https://cloud.githubusercontent.com/assets/4592712/3790993/ac5cb298-1b23-11e4-836e-9397bd06f961.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#227
