### ISSUE TITLE
admin handle changes to white when hovering on

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#41]
1. login as heffan
2. hover on the handle on the left

expected: should not change its color while hovering

actual: see screenshots

![x](https://cloud.githubusercontent.com/assets/4590317/3329820/9bd1ef96-f7ca-11e3-8d3d-cda30d791c3b.jpg)

When hovered:
![hov](https://cloud.githubusercontent.com/assets/4590317/3329822/a491158a-f7ca-11e3-8b2e-c57327da5136.jpg)

**Comment by skyhit** [comment]
fixed
