### ISSUE TITLE
Copy prevention of someone else's code during challenge phase is weak

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#412]
During the challenge phase, when a user is looking at someone else's code, we don't want them to be able to copy this code to the clipboard and then paste on an IDE where they can run multiple test cases automatically without penalty.

There is copy prevention on the challenge screen. You cannot right click and select copy, and the keyboard shortcut for copying (command + C or ctrl + c) doesn't work, however it can be bypassed if you select the code, right click it, and then use the keyboard shortcut (command + c)

This was tested on Mac using Chrome.

Also it is very easy to copy the code from the browser's development tools and use some form of regex to clear html tags and have a clean code as if you had copied and pasted it from the coding window.

**Comment by skyhit** [comment]
actually, it is hard to prevent, even disallow that, you can still see the source code, and find the code there.

ideally, we should convert it into image.

**Comment by mdesiderio** [comment]
Ok, if you think there is no improvements we can do, and the only option is really the image, let's handle that in an assembly challenge. In that case you can close this case for now.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#226
