### ISSUE TITLE
Test result screen doesn't have a clear separation between footer bar and content

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#413]
![screen shot 2014-08-14 at 4 31 57 pm](https://cloud.githubusercontent.com/assets/1629884/3927375/9795ecf0-23fa-11e4-8936-3191c66fe56a.png)

Since the content and the footer bar have exactly the same color, and the content panel scrolls, the text can get cut and it looks ugly.

We should put a border around the content area.

**Comment by skyhit** [comment]
I think we should properly standarize the modal style, like use different color for bottom section of buttons
