### ISSUE TITLE
Must have hand cursor when we hover over the 'Match Case' and 'Highlight'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#42]
## Description

Must have hand cursor when we hover over the 'Match Case' and 'Highlight'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as yoshi/password
Click 'Search'
Hover over the 'Match Case' and 'Highlight'
## Expected result

Must fix the Issue. Must have hand cursor when we hover over the 'Match Case' and 'Highlight'
## Actual result

No hand cursor when we hover over the 'Match Case' and 'Highlight'
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/3329830/bdf78b1c-f7ca-11e3-85eb-f9dddb396e8b.png)

**Comment by skyhit** [comment]
not needed, it is default checkbox behavior
