### ISSUE TITLE
Registration Process Issues

### ISSUE THREAD

**Issue by guycurry** [cloudspokes/arena-web#428]
TopCoder Handler: guy.curry
#1: When I attempt to register, I receive a message stating I need to agree to terms.  Everything looks ok except Registration Terms are "NULL".  I clicked on 'I Agree' to proceed to the next step.
#2: After i agree to the "NULL" terms i receive a message stating "Based on your answers you are not eligible."  Note that there were no questions. between #1 and #2.
#3:  I'm assuming these issues are what lead up to my inability to correctly enter the contest and view any of the problems.  Similar to several other contestants i received a "You are not assigned to this room" when trying to view a problem.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#199
