### ISSUE TITLE
Not able to register

### ISSUE THREAD

**Issue by tarora-appirio** [cloudspokes/arena-web#429]
When I was first trying to register the system prompted that "You are not eligible to register". Although after this prompt it gave me a status  of "Registered". 

I was able to move into the challenge but I was not able to open any problem. When I clicked on "Open"  to open any problem, the system again prompted me with error "You are not assigned  to this room".

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#198
