### ISSUE TITLE
admin should be able to double click the handle to reply

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#43]
1. login as heffan and ksmith respectively
2. ksmith sends a message to admin

expected: admin should be able to double click the "ksmith" in the chat log to respond.

actual: admin has to select the "Reply To" and choose "ksmith" in the list to respond, which is not user friendly.

Note that such feature is available in applet arena.

![p](https://cloud.githubusercontent.com/assets/4590317/3329919/7a65e3c0-f7cb-11e3-90e6-5d8a3f65cedc.jpg)

**Comment by skyhit** [comment]
this is not implemented.
