### ISSUE TITLE
Scroll bar of Chat is not good

### ISSUE THREAD

**Issue by tarora-appirio** [cloudspokes/arena-web#430]
I can not scroll up easily in chat area. The present scroll bar scrolls multiple records very fast on a little scrolling . It becomes difficult to read previous chats and scrolling at the same time up. It should also include some arrow buttons which scrolls the chat records one by one slowly.

**Comment by flytoj2ee** [comment]
In current code, if the scroll bar dragger is not on the bottom, it'll lock the scroll bar in that place.

If moving the dragger to bottom, it'll show new added chat data.

So if the chat area updated very fast, it could move the dragger a little up to lock the scroll bar.

What's the suggestion of changes?

**Comment by skyhit** [comment]
fixed.
