### ISSUE TITLE
Multilogin causes strange behaviour

### ISSUE THREAD

**Issue by 0Xellos** [cloudspokes/arena-web#437]
When I tried to open 2 tabs, it once happened that I was logged out from one, but couldn't open the problems in the other. They were all marked as "open" and when I tried to open them, it said I'm not assigned to that room (which I obviously was). The problem persisted even after moving out of the contest summary and back, until logging out and back in.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#180
