### ISSUE TITLE
Layout issue in the 'points' column when we sort from it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#439]
## Description

Layout issue in the 'points' column when we sort from it
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Compile
Then wait till the challenge phase starts
Click on the Division II
Click 'View Details'

Click points in the 'Challengers' table
## Expected Result

Must fix the Issue, Must display the sorting icon right of the text as others
## Actual Result

Layout issue in the 'points' column when we sort from it
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/4128785/18c44ea4-3312-11e4-85c4-7e1954564dbc.png)
## Bug Hunt

Challenges and Challengers 1.0

**Comment by skyhit** [comment]
@flytoj2ee  please check this.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue.

And in issue steps, it says "Click on the Division II, Click 'View Details'".

But the detail page in Division II is not implemented so far.

**Comment by flytoj2ee** [comment]
Any updated? I still cannot re-create this issue.

**Comment by skyhit** [comment]
can not reproduce. close it.
