### ISSUE TITLE
Search text is not clearing when we close that and come again

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#44]
## Description

Search text is not clearing when we close that and come again
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as yoshi/password
Click 'Search'
Enter text to 'find text...' : sadasda
Click 'Search' icon

Now click 'Search icon again
## Expected result

Must fix the Issue. Must clear the text
## Actual result

Search text is not clearing when we close that and come again
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/3329888/3f0b9996-f7cb-11e3-947c-a639075399e8.png)

**Comment by skyhit** [comment]
this is not implemented.
