### ISSUE TITLE
Survey and Questions Support model is too close to the bottom sectio

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#440]
## Description

Survey and Questions Support model is too close to the bottom section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
## Expected Result

Must fix the Issue, Must center align with in the screen
## Actual Result

Survey and Questions Support model is too close to the bottom section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/4128999/fa4fcd54-3316-11e4-94fa-c43743e4e3d2.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#193
