### ISSUE TITLE
Layout issue when we have long answers

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#441]
## Description

Layout issue when we have long answers
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
## Expected Result

Must fix the Issue,
## Actual Result

Layout issue when we have long answers
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/4129095/236a1efe-3319-11e4-92b9-579fccf9ebff.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
@flytoj2ee please fix this.

**Comment by skyhit** [comment]
fixed.
