### ISSUE TITLE
Some option won't display the answers

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#442]
## Description

Some option won't display the answers
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model

In Admin Tool : We have selected the style as 'Multiple Choice'
## Expected Result

Must fix the Issue, Must display the answers
## Actual Result

Some option won't display the answers
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![4 1](https://cloud.githubusercontent.com/assets/4592712/4129121/c8b2352c-3319-11e4-9cd2-15d7480cb995.png)
![4 2](https://cloud.githubusercontent.com/assets/4592712/4129122/c909385e-3319-11e4-942f-5658a3a41aed.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
@flytoj2ee  please fix this.

**Comment by flytoj2ee** [comment]
Did you refresh the round in admin tool?

I cannot re-create this issue in my test.

**Comment by sdgun** [comment]
Yes. I refresh the round every time when i am launcing a contest as in the DG

**Comment by sdgun** [comment]
Sorry i have closed the issue accidentally. I reopened it again.

**Comment by flytoj2ee** [comment]
It seems it's same with https://github.com/cloudspokes/arena-web/issues/448

Could you please check it again?

**Comment by skyhit** [comment]
yes

**Comment by skyhit** [comment]
a configuration issue close this.
