### ISSUE TITLE
No Text Field display when we have 'Short Answer' as the style

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#443]
## Description

No Text Field display when we have 'Short Answer' as the style
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model

In Admin Tool : We have selected the style as 'Short Answer'
## Expected Result

Must fix the Issue, Must display a text field to enter the text
## Actual Result

No Text Field display when we have 'Short Answer' as the style
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![5 2](https://cloud.githubusercontent.com/assets/4592712/4129153/82621d2a-331a-11e4-8adb-d65455048cdd.png)

![5](https://cloud.githubusercontent.com/assets/4592712/4129130/f901f14a-3319-11e4-804d-727cff2d9956.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
this seem an invalid state for Short Answer, why there is incorrect answers?

**Comment by flytoj2ee** [comment]
Agree. It should only have one correct answer for short answer question type.

**Comment by skyhit** [comment]
is it a backend problem or frontend?

**Comment by flytoj2ee** [comment]
In admin tool, it needs to make sure the questions are properly set. For example, it only has one correct question in text question.

**Comment by skyhit** [comment]
ok, we need further investigation, if it is a problem of configuration, you can leave it.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#192
