### ISSUE TITLE
'You must provide an answer to the question' must 'You must provide an answers to the below questions'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#444]
## Description

'You must provide an answer to the question' must 'You must provide an answers to the below questions'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
Don't answer to anything
Click 'I AGREE'

Check the Validation model title : 'You must provide an answer to the question'
## Expected Result

Must fix the Issue, 'You must provide an answers to the below questions'
## Actual Result

You must provide an answer to the question
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![6](https://cloud.githubusercontent.com/assets/4592712/4129151/74a23c10-331a-11e4-9318-03c62018d691.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
"an answers" is incorrect, let's change to "You must answer the following questions"

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#191
