### ISSUE TITLE
Question boxes are not aligned properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#445]
## Description

Question boxes are not aligned properly
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
Check the boxes (Questions)

They have not equal spaces from the left and right borders
## Expected Result

Must fix the Issue, Must have equal spaces from the left and right borders
## Actual Result

They have not equal spaces from the left and right borders
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![7](https://cloud.githubusercontent.com/assets/4592712/4129182/f758e3f2-331a-11e4-8a4e-e4088cdcfc81.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#190
