### ISSUE TITLE
'Agree' must display as 'I Agree' 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#446]
## Description

'Agree' must display as 'I Agree' 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
Check the 'Important Notice' section
## Expected Result

Must fix the Issue, 'Agree' must display as 'I Agree' 
## Actual Result

'Agree' 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/4129213/5601d92c-331b-11e4-8552-5972f5328576.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#189
