### ISSUE TITLE
Error Model is not aligned properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#447]
## Description

Error Model is not aligned properly
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
Click 'I Agree'
Check the 'Error' Model
## Expected Result

Must fix the Issue, Must align with the 'Event Registration' pop up
## Actual Result

Error Model is not aligned properly
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/4129243/e8040dcc-331b-11e4-97c4-3278a8982c4c.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
I think it is purposed to show like this.

**Comment by flytoj2ee** [comment]
Should we change for this issue?

**Comment by skyhit** [comment]
can it be shown a bit down, instead of right?

**Comment by skyhit** [comment]
fixed.
