### ISSUE TITLE
Even If we fill all the questions, Can't end the Survey

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#448]
## Description

Even If we fill all the questions, Can't end the Survey
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
Click 'I Agree'
Check the 'Error' Model

In Admin Tool : Add Multitle Choice, Single Choice, Short Answer and Long Answers
## Expected Result

Must fix the Issue, Must end the survey when we select all the answers and then click 'I Agree'
## Actual Result

Even If we fill all the questions, Can't end the Survey
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![10](https://cloud.githubusercontent.com/assets/4592712/4129256/3d4c3c14-331c-11e4-8fa9-b26719113776.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
can you retry by clean the cache?  when do you have your VM?

**Comment by sdgun** [comment]
VM: Tue, Sep 2, 2014 at 11:19 AM; I think you mean browser cache?

**Comment by sdgun** [comment]
If we add 'Add Multiple Choice, Single Choice, Short Answer and Long Answers', Some of them won't give options to fill out the answers; so if this is the case we can't end the survey.

**Comment by flytoj2ee** [comment]
![35](https://cloud.githubusercontent.com/assets/4497285/4260071/9069999c-3b27-11e4-8798-68031d69d313.gif)
![36](https://cloud.githubusercontent.com/assets/4497285/4260073/ad244e42-3b27-11e4-967e-72f67ccd5259.gif)

I cannot re-create this issue. I added many questions in admin tool and it could register.

**Comment by skyhit** [comment]
a possible case is the answers are not properly set.
