### ISSUE TITLE
Scroll bar touches the Title Section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#449]
## Description

Scroll bar touches the Title Section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
In the Survey and Questions Support model --> Check the Scroll bar
Click 'I Agree'
Check the 'Error' Model --> Check the Scroll bar

In Admin Tool : Add Multitle Choice, Single Choice, Short Answer and Long Answers
## Expected Result

Must fix the Issue, Must have some gap between them
## Actual Result

Scroll bar touches the Title Section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![11 1](https://cloud.githubusercontent.com/assets/4592712/4129291/c636cbde-331c-11e4-8f75-47aecb7eba47.png)
![11 2](https://cloud.githubusercontent.com/assets/4592712/4129292/c6407076-331c-11e4-8a35-69543a9a6a8b.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
fixed.
