### ISSUE TITLE
Layout Issue in the 'Results' column in Challenges Table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#450]
## Description

Layout Issue in the 'Results' column in Challenges Table
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to VB.NET
Copy the solution
Click Compile
Then wait till the challenge phase starts
Click on the Division II
Click 'View Details'

Click points in the 'Challenges' table
## Expected Result

Must fix the Issue, Must display the Sort icon right side of the text as other themes
## Actual Result

Layout Issue in the 'Results' column in Challenges Table in Orange Theme
## Environment

Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![12 1](https://cloud.githubusercontent.com/assets/4592712/4129406/be77f082-331f-11e4-8c25-9d90fe9d27e4.png)
![12](https://cloud.githubusercontent.com/assets/4592712/4129407/be7b633e-331f-11e4-8ccc-3296be725d08.png)
## Bug Hunt

Challenges and Challengers 1.0

**Comment by skyhit** [comment]
@flytoj2ee please check this.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue.
And in issue steps, it says "Click on the Division II, Click 'View Details'".

But the detail page in Division II is not implemented so far.

**Comment by flytoj2ee** [comment]
Would you mind to re-check it? I still cannot re-create this issue.

**Comment by skyhit** [comment]
yes, I can not reproduce it with latest commit hash. no need to fix.
