### ISSUE TITLE
No section separator for the buttons in Event Registration model 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#451]
## Description

No section separator for the buttons in Event Registration model 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Now scroll down the Question list

In Light Theme we have a separator
But in others (Orange and Dark) it won't
## Expected Result

Must fix the Issue, Must have section separator for the buttons
## Actual Result

No section separator for the buttons in Event Registration model 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![13 2-orange](https://cloud.githubusercontent.com/assets/4592712/4146684/149e22b6-340f-11e4-9773-53a86ee7fe3f.png)
![13 3-light](https://cloud.githubusercontent.com/assets/4592712/4146685/149fea92-340f-11e4-8335-3cc7f32e250e.png)
![13 4-dark](https://cloud.githubusercontent.com/assets/4592712/4146686/14a2a156-340f-11e4-96cb-277a4d554858.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
yes, we are planning formalize the popups.

**Comment by skyhit** [comment]
fixed.
