### ISSUE TITLE
No section separator for the buttons in Error model 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#452]
## Description

No section separator for the buttons in Error model 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Now scroll down the Question list
Don't fill any question
Click 'I Agree'

In Light Theme we have a separator
But in others (Orange and Dark) it won't
## Expected Result

Must fix the Issue, Must have section separator for the button (Cancel)
## Actual Result

No section separator for the buttons in Error model 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![14 1-dark](https://cloud.githubusercontent.com/assets/4592712/4146694/32bf5d0a-340f-11e4-94ca-73513c8784cb.png)
![14 2-orange](https://cloud.githubusercontent.com/assets/4592712/4146695/32dec4d8-340f-11e4-82ea-d8652ddd1757.png)
![14 3-light](https://cloud.githubusercontent.com/assets/4592712/4146696/331bb794-340f-11e4-82db-34fbdfab6b81.png)
## Bug Hunt

Survey and Questions Support For Contest Registration

**Comment by skyhit** [comment]
yes, we are planning to formalize the format of the popups.

**Comment by skyhit** [comment]
fixed.
