### ISSUE TITLE
'Challenges' section Search Icon is not working 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#453]
## Description

'Challenges' section Search Icon is not working 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
Click 'Challenge' and click OK

---

Then in the Summary Section; Click Room
In the 'Challenges' section
Click Search icon
## Expected Result

Must fix the Issue, 
## Actual Result

'Challenges' section Search Icon is not working 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/4150639/91c68316-343f-11e4-8533-78a0aab3ea7a.png)
## Bug Hunt

Challenges and Challengers

**Comment by skyhit** [comment]
yes, it is not implemented.
