### ISSUE TITLE
Layout issue in the Filter when we expand the 'Challengers' table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#454]
## Description

Layout issue in the Filter when we expand the 'Challengers' table
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
Click 'Challenge' and click OK

---

Then in the Summary Section; Click Room
In the 'Challengers'section
Click Expand
Click Search icon
Check the Filter model
## Expected Result

Must fix the Issue, Must align it properly
When we click on the search Icon; 'Challenges' table is filtered, So no need to display it in the expand version; OR must disable the feature
## Actual Result

Layout issue in the Filter when we expand the 'Challengers' table
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![16](https://cloud.githubusercontent.com/assets/4592712/4150646/a2e256d4-343f-11e4-83aa-15cf72eb41a5.png)
## Bug Hunt

Challenges and Challengers

**Comment by flytoj2ee** [comment]
About "When we click on the search Icon; 'Challenges' table is filtered, So no need to display it in the expand version; OR must disable the feature". 

I think it's reasonable to keep this function. It'll show the filtered challenges after narrow the window.

**Comment by skyhit** [comment]
I think showing the popup is not good.

can you we some messages after Filter text, like Filter by 'sandking' etc.

**Comment by flytoj2ee** [comment]
The current workflow is as following:
a) User expand the challenger table.
b) User clicks the search icon to filter challenges.
c) User narrows the window, in challenges, it shows the filtered result. It'll not show the filtered popup.

**Comment by skyhit** [comment]
that is fine.

**Comment by skyhit** [comment]
fixed.
