### ISSUE TITLE
Border lines are not aligned in 'Challenges' table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#455]
## Description

Border lines are not aligned in 'Challenges' table
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
Click 'Challenge' and click OK

---

Then in the Summary Section; Click Room
In the 'Challenges'section
Check the first row blue line
## Expected Result

Must fix the Issue, Must align it properly
## Actual Result

Border lines are not aligned in 'Challenges' table
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![17](https://cloud.githubusercontent.com/assets/4592712/4150654/b8726782-343f-11e4-9be6-a8ef4daa59a6.png)
## Bug Hunt

Challenges and Challengers

**Comment by skyhit** [comment]
fixed.
