### ISSUE TITLE
No hand cursor displayed when we hover over the handle name in 'Challenges' and 'Challengers' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#456]
## Description

No hand cursor displayed when we hover over the handle name in 'Challenges' and 'Challengers' section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
Click 'Challenge' and click OK

---

Then in the Summary Section; Click Room
In the 'Challenges' and 'Challengers' section
Click on a Handle 
## Expected Result

Must fix the Issue, Must display the hand cursor when we hover over the handle name
If we click on it we can see the handle name info pop up
## Actual Result

No hand cursor displayed when we hover over the handle name in 'Challenges' and 'Challengers' section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/4150661/c5289aa0-343f-11e4-88db-9991ae628f29.png)
## Bug Hunt

Challenges and Challengers

**Comment by skyhit** [comment]
@flytoj2ee please check this.
