### ISSUE TITLE
when we click on the same handle name in two locations; it won't display the pop up info in 'Challenges' and 'Challengers' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#457]
## Description

when we click on the same handle name in two locations; it won't display the pop up info in 'Challenges' and 'Challengers' section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
Click 'Challenge' and click OK

---

Then in the Summary Section; Click Room
In the 'Challenges' and 'Challengers' section
Click on a Handle (eg:  lightspeed)
In other location click : lightspeed 
## Expected Result

Must fix the Issue, Must display the info for the second occurance
## Actual Result

when we click on the same handle name in two locations; it won't display the pop up info in 'Challenges' and 'Challengers' section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/4150669/d218fcb4-343f-11e4-87e6-fd6978acb804.png)
## Bug Hunt

Challenges and Challengers

**Comment by flytoj2ee** [comment]
Could you please try it again? I cannot re-create this issue.

**Comment by skyhit** [comment]
can not reproduce too. close it.
