### ISSUE TITLE
If records filter from the clicked handle from the 'Challengers' table; No need to display the filter pop up in Challenges' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#458]
## Description

If records filter from the clicked handle from the 'Challengers' table; No need to display the filter pop up in Challenges' section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
Click 'Challenge' and click OK

---

Then in the Summary Section; Click Room
In the 'Challengers' section
Click on a Search icon (eg:  lightspeed)
Check the 'Challenges' section
## Expected Result

Must fix the Issue, 
If records filter from the clicked handle from the 'Challengers' table; No need to display the filter pop up in Challenges' section
## Actual Result

Display the filter pop up in Challenges' section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![20](https://cloud.githubusercontent.com/assets/4592712/4150895/8904a36e-3441-11e4-898c-655f081680b7.png)
## Bug Hunt

Challenges and Challengers

**Comment by skyhit** [comment]
@flytoj2ee please fix this.

**Comment by skyhit** [comment]
fixed.
