### ISSUE TITLE
Sorting Icon too close to the '#' in 'Challengers' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#459]
## Description

Sorting Icon too close to the '#' in 'Challengers' section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
## Click 'Challenge' and click OK

Then in the Summary Section; Click Room
In the 'Challengers' section
Click on Expand
Now click on the '#'
Check the 'sort icon' and '#'
## Expected Result

Must fix the Issue, 
Must have some gap between 'Sorting Icon' and '#' in 'Challengers' section
## Actual Result

Sorting Icon too close to the '#' in 'Challengers' section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/4153808/63b612ee-345c-11e4-9469-3e4ba18a316e.png)
## Bug Hunt

Challenges and Challengers

**Comment by skyhit** [comment]
fixed.
