### ISSUE TITLE
'R' column name is not in BOLD in 'Challengers' and 'Challenges' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#460]
## Description

'R' column name is not in BOLD in 'Challengers' and 'Challenges' section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
When we coding phase starts, enter the code and compile it
Then submit it

When the Challenge Phase is on
Click the 'Division' and click 'view details'
Click on a Score
Click 'Challenge' 
Click a Test case
## Click 'Challenge' and click OK

Then in the Summary Section; Click Room
In the 'Challengers' section
Check the 'R'

In the 'Challenges' section
Check the 'R'
## Expected Result

Must fix the Issue, 
Must BOLD the column name; Others are in BOLD
## Actual Result

'R' column name is not in BOLD in 'Challengers' and 'Challenges' section
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/4153873/1980990a-345d-11e4-87be-d685ba839028.png)
## Bug Hunt

Challenges and Challengers

**Comment by skyhit** [comment]
fixed.
