### ISSUE TITLE
Scroll bar layout issue when we delete all the test cases

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#463]
## Description

Scroll bar layout issue when we delete all the test cases
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click +Add twice
Then Delete all of them
## Expected Result

Must fix the Issue, 
## Actual Result

Scroll bar layout issue when we delete all the test cases
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/4166143/bf3b1748-3508-11e4-9b86-9dc109e49b9f.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
