### ISSUE TITLE
'Check All' is already selected

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#465]
## Description

'Check All' is already selected
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
## Expected Result

Must fix the Issue, Must deselect the 'Check All' when we open it
## Actual Result

'Check All' is already selected
## Environment

IE 11 in Windows 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/4166203/4a8434a6-3509-11e4-8158-71f39cdf3bf2.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
