### ISSUE TITLE
After removing the First 'Test Cases'; Numbers won't reset

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#466]
## Description

After removing the First 'Test Cases'; Numbers won't reset
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click '+Add' - 2-3 Times
Delete All the Test Cases
Now click '+Add'
Check the Test Case number
## Expected Result

Must fix the Issue, Must reset the number when we add new test cases
## Actual Result

After removing the First 'Test Cases'; Numbers won't reset
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/4166279/f6c39d4c-3509-11e4-8425-3813653833bf.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
I think it is enough, and good to track that you have manually add and delete some.
