### ISSUE TITLE
No scroll bar in the Test Panel in Orange Theme

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#467]
## Description

No scroll bar in the Test Panel in Orange Theme
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click '+Add' - 2-3 Times
Check the scroll bar
## Expected Result

Must fix the Issue, Must have the scroll bar
## Actual Result

No scroll bar in the Test Panel in Orange Theme
## Environment

Chrome 37.0.2062.102 m in Windows 7
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/4166355/a0f6cf8c-350a-11e4-9eba-62e486380c98.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
