### ISSUE TITLE
Always display scroll bar even we have expanded the Test case in the Test Panel

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#468]
## Description

Always display scroll bar even we have expanded the Test case in the Test Panel
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Select all the Test cases
Click 'Run Test'
Click 'Test cases' (Check whether the Test Case in Collapsed)
Check the scroll bar
## Expected Result

Must fix the Issue, Must display the scroll bar when we have enough test cases to scroll
## Actual Result

Always display scroll bar even we have expanded the Test case in the Test Panel
## Environment

IE 11 in Windows 7
## Image

![5](https://cloud.githubusercontent.com/assets/4592712/4174792/12c581d2-35a9-11e4-95ef-8431ba4b9309.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
