### ISSUE TITLE
Can't rename the Test case name in the Test Panel

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#469]
## Description

Can't rename the Test case name in the Test Panel
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click '+Add'
Then click on the Test case name
Enter a New Name
Click anywhere
## Expected Result

Must fix the Issue, Able to rename it
## Actual Result

Can't rename the Test case name in the Test Panel
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![Uploading 6.jpg . . .]()
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
this should be working.

**Comment by skyhit** [comment]
fixed.
