### ISSUE TITLE
it will ignore the last part of a handle entered in the user text box

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#47]
1. login as lightspeed
2. select "Whisper", enter the text "lightspeed hi" in the user text box, enter "hello" as comment, post it

expected: it should take "lightspeed hi" as a user handle.

actual: it takes the first part "lightspeed" as a user, and "hi" as the comment along with the "hello", see screenshots.

entered text:
![df](https://cloud.githubusercontent.com/assets/4590317/3330082/0bed5318-f7cd-11e3-98a3-affd5ed88d58.jpg)

results:
![kj](https://cloud.githubusercontent.com/assets/4590317/3330090/227eeb96-f7cd-11e3-97dd-54f479a5e111.jpg)

**Comment by skyhit** [comment]
same behavior as arena applet, and normally, a handle can not contain whitespace.
