### ISSUE TITLE
Scroll bar issue in the Error pop up when we scroll down

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#470]
## Description

Scroll bar issue in the Error pop up when we scroll down
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click '+Add' 
Add 5-10 Test Cases
Click 'Select All'
Then Click 'Run Test'
Scroll down the pop up Errors
## Expected Result

Must fix the Issue, Scroll bar must fully displayed when we scroll it to the bottom
## Actual Result

Scroll bar issue in the Error pop up when we scroll down
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![7](https://cloud.githubusercontent.com/assets/4592712/4166647/0d7a82be-350d-11e4-86ea-1b859b4e6087.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
