### ISSUE TITLE
Button separator is not displayed in the pop up [Orange/Dark Themes]

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#471]
## Description

Button separator is not displayed in the pop up [Orange/Dark Themes]
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click '+Add' 
Add 5-10 Test Cases
Click 'Select All'
Then Click 'Run Test'
Check the Button seperator in the pop up [Orange/Dark Themes]
## Expected Result

Must fix the Issue, Must display the Button seperator
## Actual Result

Button seperator is not displayed in the pop up [Orange/Dark Themes]
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/4166709/816cd30c-350d-11e4-9cff-b98b23a66ea5.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by flytoj2ee** [comment]
What's the "Button seperator" mean? 

I checked other themes but it also doesn't have "Button seperator" in popup footer.

**Comment by sdgun** [comment]
@flytoj2ee : Check the Light theme and compare it with the Orange/Dark Themes

**Comment by skyhit** [comment]
fixed
