### ISSUE TITLE
If we rename one item it will effect to all the test cases 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#472]
## Description

If we rename one item it will effect to all the test cases 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
## In the Code Editor Change the Language to JAVA

In the Code Editor
Click 'Test panel'
Click '+Add' 
Add 5-10 Test Cases
Click on a Test case name
Rename it
Then add another 3-4 Test cases
Click on the test case name

Check the name
## Expected Result

Must fix the Issue, 
## Actual Result

If we rename one item it will effect to all the test cases
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/4166811/46700ea8-350e-11e4-9d6d-6fc1c2c02b9e.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
