### ISSUE TITLE
Delete all the items won't deselect the 'Select All' check box

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#473]
## Description

Delete all the items won't deselect the 'Select All' check box
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Click '+Add' 
Add 5-10 Test Cases
Click 'Seelct All'
Then Delete Test Cases one by one
Check the 'Select All' check box after deleting all the Test Cases
## Expected Result

Must fix the Issue, Must deselect the check box
## Actual Result

Delete all the items won't deselect the 'Select All' check box
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![10](https://cloud.githubusercontent.com/assets/4592712/4167272/060299d6-3512-11e4-8a4f-03bd16f9f161.jpg)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
is the example tests also be deleted?

**Comment by skyhit** [comment]
fixed.
