### ISSUE TITLE
Can't see the last Test Report

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#474]
## Description

Can't see the last Test Report
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Click '+Add' 
Add 5-10 Test Cases
Click 'Seelct All'
Then click 'Run Test'

Check the 'Test Report' (All the test cases are expanded by default)
Now collapse all
Now Expand them all again
try to scroll down
Can't see the last Test Report
## Expected Result

Must fix the Issue, Must able to see the last Test Report
## Actual Result

Can't see the last Test Report
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![11](https://cloud.githubusercontent.com/assets/4592712/4174182/f0e7b758-357e-11e4-959d-adaef7b5f31b.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
