### ISSUE TITLE
No text for Non Executed Test Cases

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#475]
## Description

No text for Non Executed Test Cases
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Select all
Then Click 'Run Test'
Check the Non executed Test Case
## Expected Result

Must fix the Issue, Must have a Text
## Actual Result

No text for Non Executed Test Cases
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/4174746/d45847a2-35a5-11e4-8ecb-059115a15e78.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
