### ISSUE TITLE
Blank area displayed when we collapse the executed Test Cases in Test Report 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#476]
## Description

Blank area displayed when we collapse the executed Test Cases in Test Report 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Select all
Then Click 'Run Test'
in the Report, Collapse the test cases one by one
Check the blank space at the bottom
## Expected Result

Must fix the Issue, Must not display a blank space at the bottom
## Actual Result

Blank area displayed when we collapse the executed Test Cases in Test Report
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![13](https://cloud.githubusercontent.com/assets/4592712/4174747/06ea0606-35a6-11e4-805f-927e76cd4a2f.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
what do you suggest to show for this case?

**Comment by sdgun** [comment]
When you run all the test cases, they are expanded by default; If we collapse them one by one we can scroll down beyond the current visible area, If we can see all the test cases we don't need to scroll down.

Currently even we collapse all the test cases we can scroll down.

**Comment by skyhit** [comment]
fixed.
