### ISSUE TITLE
unnecessary text displayed in the default Test cases

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#477]
## Description

unnecessary text displayed in the default Test cases
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Expand a Default Test case
## Expected Result

Must fix the Issue, Must not display them and also must fix the Layout Issue
## Actual Result

unnecessary text displayed in the default Test cases
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/4174762/2c017220-35a7-11e4-930e-9cc4c494aa5c.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
it is not unnecessary, this is parameter.
