### ISSUE TITLE
'Correct' Text is not clearly seen in Orange Theme

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#478]
## Description

'Correct' Text is not clearly seen in Orange Theme
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Click 'Select All'
Click 'Run Test'
Check the Report 'Correct' Text
## Expected Result

Must fix the Issue, Must use darker Green color
## Actual Result

'Correct' Text is not clearly seen in Orange Theme
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![16](https://cloud.githubusercontent.com/assets/4592712/4174787/668120ac-35a8-11e4-819f-6e21de16dda7.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
