### ISSUE TITLE
Test Case Results are not displayed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#479]
## Description

Test Case Results are not displayed
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Click 'Select All'
Click 'Run Test'
You can see the Test Result
Scroll Down the List --> This is important
Close the report from the OK button
Now expand the Test Panel
Click Run button from the Test Cases
## Expected Result

Must fix the Issue, Must display the test results
## Actual Result

Test Case Results are not displayed
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![17](https://cloud.githubusercontent.com/assets/4592712/4174803/ce3fdc46-35a9-11e4-9754-5a0864e5b47b.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed
