### ISSUE TITLE
When we click on the username, pop up will appear and then the page position chages (move to right)

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#48]
## Description

When we click on the username, pop up will appear and then the page position chages (move to right)
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as yoshi/password
Click on a 'Username'
## Expected result

Must fix the Issue. Must maintain the page position
## Actual result

When we click on the username, pop up will appear and then the page position chages (move to right)
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/3330117/5bbcc7c0-f7cd-11e3-82a8-0107eb9e2a1f.png)

**Comment by skyhit** [comment]
bootstrap problem
