### ISSUE TITLE
'return 0' is not displayed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#480]
## Description

'return 0' is not displayed
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Click 'Select All'
Click 'Run Test'
Check the Report

Setup data : 1, 100,50,20, 25
## Expected Result

Must fix the Issue, 
## Actual Result

'return 0' is not displayed
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/4174812/a5487da6-35aa-11e4-8d53-a1e289a3ec97.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed
