### ISSUE TITLE
Wrong value displayed when we enter '2147483647' as int a

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#481]
## Description

Wrong value displayed when we enter '2147483647' as int a
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Click '+Add'
Enter a-2147483647; b-"a"; c-{1}; d-1; f-{"a"}
Click Run
Check the Test Result
## Expected Result

Must fix the Issue, 
## Actual Result

Wrong value displayed when we enter '2147483647' as int a
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/4174923/e88b7378-35b1-11e4-8547-5755bb2b2ae6.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
this is related to overflow for int type.
