### ISSUE TITLE
('X of x' tests passed successfully) message is not shown in the title

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#482]
## Description

('X of x' tests passed successfully) message is not shown in the title
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Select some Test cases
Click "Run Test'

Check the Title
## Expected Result

Must fix the Issue, Must display the ('X of x' tests passed successfully) message
It is in the Deployment Guide screen shots
## Actual Result

('X of x' tests passed successfully) message is not shown in the title
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![20](https://cloud.githubusercontent.com/assets/4592712/4174947/c5e6dd88-35b3-11e4-8b1c-9d63ab929f12.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
this is purposely removed.
