### ISSUE TITLE
'Custom Test Case2' must 'Custom Test Case 2' 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#483]
## Description

'Custom Test Case2' must 'Custom Test Case 2' 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it [Language : C++]

In the Code Editor
Click 'Test panel'
Check the : Example Test Case 2

Click '+Add'
Check the : Custom Test Case2
## Expected Result

Must fix the Issue, 'Custom Test Case2' must 'Custom Test Case 2'
- Must have space in between the number and the text
  eg: Example Test Case 2
## Actual Result

 'Custom Test Case2'
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/4175005/7b1b1490-35b8-11e4-8272-40cf4024c11e.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
