### ISSUE TITLE
'Select All' check box in activated when we click on the white space right of the controller 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#484]
## Description

'Select All' check box in activated when we click on the white space right of the controller 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it [Language : C++]

In the Code Editor
Click 'Test panel'
Click on the white space right of the controller 
## Expected Result

Must fix the Issue, Must check it if we click on the text or check box
## Actual Result

'Select All' check box in activated when we click on the white space right of the controller 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/4175012/d83268d6-35b8-11e4-9f48-ffca3cdf6dbd.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
