### ISSUE TITLE
When we expand the 'Coding Area' Challenge panel won't fit to the bottom 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#486]
## Description

When we expand the 'Coding Area' Challenge panel won't fit to the bottom 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
Insert the code and compile it [Language : C++]
## In the Challenge phase

Click 'view details from Division
Click on the score
Click 'Challenge'

Click Expand icon
## Expected Result

Must fix the Issue, Must fit to the bottom
## Actual Result

When we expand the 'Coding Area' Challenge panel won't fit to the bottom 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![24](https://cloud.githubusercontent.com/assets/4592712/4175297/f8e448a8-35ca-11e4-9a4c-727314af0bf8.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
