### ISSUE TITLE
Nothing happens when we click 'Test Case' and then click 'Challenge'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#487]
## Description

Nothing happens when we click 'Test Case' and then click 'Challenge'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
Insert the code and compile it [Language : C++]
In the Challenge phase
Click 'view details from Division
## Click on the score

Expand the 'Challenge' Panel
Click 'Test Case'
Then fill out it
Click 'Challenge'
## Expected Result

Must fix the Issue, 
## Actual Result

Nothing happens when we click 'Test Case' and then click 'Challenge'
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/4175306/7d5567fc-35cb-11e4-925f-fef7445a8076.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
