### ISSUE TITLE
When user successfully 'Challenged' : Challenge window must disable or closed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#488]
## Description

When user successfully 'Challenged' : Challenge window must disable or closed
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
Insert the code and compile it [Language : C++]
In the Challenge phase
Click 'view details from Division
## Click on the score

Expand the 'Challenge' Panel
Click 'Test Case'
Then fill out it
Click 'Challenge'
Click YES
After 'Challenge success' pop up
Click RUN again

Although it will validate - user has to go through several steps before it
## Expected Result

Must fix the Issue, When user successfully 'Challenged' : Challenge window must disable or closed
## Actual Result

When user successfully 'Challenged' : Challenge window won't disable the RUN option 
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![26](https://cloud.githubusercontent.com/assets/4592712/4175314/35298656-35cc-11e4-8130-e2f6ad488688.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
