### ISSUE TITLE
No Scroll bar activated to the 'Challenge' Panel after user successfully 'Challenged'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#489]
## Description

No Scroll bar activated to the 'Challenge' Panel after user successfully 'Challenged'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
Insert the code and compile it [Language : C++]
In the Challenge phase
Click 'view details from Division
## Click on the score

Expand the 'Challenge' Panel
Click Run on a Test Case
Now Close the 'Challenge' Panel
Open it again
Expand 2-3 Items
try to scroll them
## Expected Result

Must fix the Issue, Need to have a scroll bar to scroll the list
## Actual Result

No Scroll bar activated to the 'Challenge' Panel after user successfully 'Challenged'
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![27](https://cloud.githubusercontent.com/assets/4592712/4175339/08737e58-35ce-11e4-92a8-c6fb215da384.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
