### ISSUE TITLE
When we change the chat room, not able to chat

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#49]
## Description

When we change the chat room, not able to chat
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as yoshi/password
Click Chat Room drop down and Select 'Admin Lobby Room'
Chat with others

Now switch to 'Chat Room 1'
some text into 'type chat...' and press enter
## Expected result

Must fix the Issue. Must able to chat
If we enter some text into 'type chat...' and press enter
It must display on the screen
## Actual result

When we change the chat room, not able to chat
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![13](https://cloud.githubusercontent.com/assets/4592712/3330227/893ca304-f7ce-11e3-8601-1c5b21301ca5.png)

**Comment by skyhit** [comment]
can not reproduce.
