### ISSUE TITLE
Wrong parameter info displayed in the 'Challenge details' pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#490]
## Description

Wrong parameter info displayed in the 'Challenge details' pop up
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
Insert the code and compile it [Language : C++]
In the Challenge phase
Click 'view details from Division
## Click on the score

Expand the 'Challenge' Panel
Click Run on a Test Case
Check the parameters
## Expected Result

Must fix the Issue, Must display the correct parameters 
## Actual Result

Wrong parameter info displayed in the 'Challenge details' pop up
## Environment

IE 11 in Windows 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/4175406/ad590530-35d0-11e4-9e25-3b39d4c774c3.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by flytoj2ee** [comment]
In above attachment, looking into the code in coding editor, it's using Python.

The popup parameters are correct if it's using Python. 

Could you please check it again?

**Comment by skyhit** [comment]
in the reproduce step, it says "In the Code Editor Change the Language to JAVA"

**Comment by flytoj2ee** [comment]
I think the current result is reasonable.

After change the language, it needs to compile and submit the code again. It'll not save the code if doesn't submit.
