### ISSUE TITLE
Scroll bar disappears; after we scroll up/Down from dragging and dropping using scroll bar

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#491]
## Description

Scroll bar disappears; after we scroll up/Down
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Register for the challenge
Wait till the coding phase starts
Click Open
In the Code Editor Change the Language to JAVA
## Insert the code and compile it

In the Code Editor
Click 'Test panel'
Collapse all the items
Scroll the item list to bottom from dragging and dropping scroll bar to the bottom
Scroll bar --> disappears

This happens in the Challenge phase

In the Code Editor
Click 'challenge'
Collapse all the items
Scroll the item list to bottom from dragging and dropping scroll bar to the bottom
Scroll bar --> disappears
## Expected Result

Must fix the Issue, Must have the scroll bar
- When we expand an items scroll bar won't enable so we can't scroll down a see the content of them
## Actual Result

Scroll bar disappears; after we scroll up/Down
## Environment

IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7
## Image

![15 1](https://cloud.githubusercontent.com/assets/4592712/4175437/5885f91c-35d2-11e4-91a2-7eed13510855.png)
![15](https://cloud.githubusercontent.com/assets/4592712/4175438/588f543a-35d2-11e4-9b6b-52e5d0ffd549.png)
## Bug Hunt

Test Panel For Batch Testing

**Comment by skyhit** [comment]
fixed.
