### ISSUE TITLE
Chat content disappears on changing room

### ISSUE THREAD

**Issue by ananthhh** [cloudspokes/arena-web#495]
Steps to reproduce:
1. Login to web arena with twight/password
2. In chat window, enter around 40 chat messages like below so that you will get scrollbar
![image](https://cloud.githubusercontent.com/assets/3583234/4263238/4cbb5aee-3bd8-11e4-9b3e-afd6838aff35.png)
3. Now change the chat room to Chat room 2

Expected Behaviour:
You should see chat message 'System> twight has entered the room.'

Current Behaviour:
Chat area is empty. No message will appear even after entering some messages.
![image](https://cloud.githubusercontent.com/assets/3583234/4263242/a2b4023e-3bd8-11e4-9330-ba325f8773d0.png)

**Comment by skyhit** [comment]
yes, there should be. can you double check the problem?

**Comment by ananthhh** [comment]
I have checked it. Its due to ngScrollbar.
If i go back to the room 1 and scroll to top and then move to room 2 again,
I can see the content

**Comment by skyhit** [comment]
please fix it.

**Comment by ananthhh** [comment]
I have fixed it. Should i include this fix with the contest Module Assembly - Web Arena - Local Chat Persistence ?

**Comment by skyhit** [comment]
fixed.
