### ISSUE TITLE
'Contest Creation Wizard' pop up is not focused on center of the screen

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#496]
## Description

'Contest Creation Wizard' pop up is not focused on center of the screen
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
## Expected Result

Must fix the Issue, Must open center of the screen
## Actual Result

'Contest Creation Wizard' pop up is not focused on center of the screen
- Must center align with in the display area of the PC/Laptop
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/4264293/f73c8140-3c1f-11e4-92ef-e2abf89f7c7b.png)
## Video

https://www.dropbox.com/s/ibg7sq8adtidgx7/1.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by flytoj2ee** [comment]
One reviewer said to move the dialog top to show full dialog.

Another reviewer said to move the dialog to page center.

What's your suggestion?

**Comment by snowone** [comment]
any update?

**Comment by skyhit** [comment]
put in center.

**Comment by skyhit** [comment]
fixed.
