### ISSUE TITLE
Layout of the 'Contest Creation Wizard' pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#497]
## Description

Layout of the 'Contest Creation Wizard' pop up
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
## Expected Result

Must fix the Issue;
## Actual Result

Layout of the 'Contest Creation Wizard' pop up
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/4264297/2f97b424-3c20-11e4-9238-2d560b2ebad4.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
