### ISSUE TITLE
modal is not fully seen

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#498]
mac 10.9.4, Chrome 35
1. login as heffan
2. click Contest creation wizard
3. observe

expected: the modal should be fully seen
actual: see screenshot
![qq20140914-1](https://cloud.githubusercontent.com/assets/4590317/4266210/86c5bfc8-3c77-11e4-9c13-0f5f08a66a82.jpg)

**Comment by skyhit** [comment]
duplicate with #496
