### ISSUE TITLE
After selecting 'Admin user' color is white

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#50]
## Description

After selecting 'Admin user' color is white
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as twight/password
Must login 4 users with a Admin user
Select : Reply to'
Then select 'heffan' as user
In the Drop down : heffan ---> Orange
After selected --> white
## Expected result

Must fix the Issue. Color must 'Orange'
## Actual result

After selecting 'Admin user' color is white
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/3330398/4bc80886-f7d0-11e3-9fc5-600cbf1e7175.png)

**Comment by delemach** [comment]
Actually I see slightly different behavior - The second dropdown simply is not enabled even though I see an admin in the room
![tmp](https://cloud.githubusercontent.com/assets/4539459/3509379/ee7b098e-0699-11e4-819b-ddc5543317c0.png)

**Comment by skyhit** [comment]
for admin, there is no option to select handle.
