### ISSUE TITLE
When we want to select multiple Languages; it is not easy in 'Allowed Languages' drop down

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#500]
## Description

When we want to select multiple Languages; it is not easy in 'Allowed Languages' drop down
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Click 'Allowed Languages' drop down
Select one Language
try to select another

because it have checkboxes we can select more than one language
If the drop down is closing when we select one language
It is difficult to select 3-4 Languages
## Expected Result

Must fix the Issue; Must not close the Drop down when we select one language from the 'Allowed Languages' drop down
If we need to select another languages, we have to open the drop down again
## Actual Result

Drop Down closes when we select obne language
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/4264311/bec26004-3c20-11e4-8b86-1cfa37cff188.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
