### ISSUE TITLE
step 3 should be “Advanced Setting”

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#501]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. click Contest creation wizard
3. observe the text

expected: step 3 text "Advance Setting" should be “Advanced Setting”

actual: see screenshot

![qq20140915-7](https://cloud.githubusercontent.com/assets/4590317/4266219/d6fff058-3c77-11e4-86a4-6cc484a35f4a.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#195
