### ISSUE TITLE
Small space below the AM/PM drop down

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#502]
## Description

Small space below the AM/PM drop down
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Click AM/PM drop down
## Expected Result

Must fix the Issue; Must remove the space
## Actual Result

Small space below the AM/PM drop down
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/4264832/c5cf9a0a-3c35-11e4-9568-9353e61ae729.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
