### ISSUE TITLE
Start time should be limited to 2 chars

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#503]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter some chars/digits for the start time

expected: Start time should be limited to 2 chars for the “hh:mm”, and should not accept non-digits chars.

actual: see screenshot
![qq20140915-8](https://cloud.githubusercontent.com/assets/4590317/4266230/058c2cd4-3c78-11e4-98e4-4bba92e6989d.jpg)

**Comment by skyhit** [comment]
fixed
