### ISSUE TITLE
Selected time missing when we click Forward and come back

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#504]
## Description

Selected time missing when we click Forward and come back
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the Step 01
Select a Date from the Calender (eg: 15th)
Click > in the calender area (go to next Month)
Now click <
Check teh selected date
## Expected Result

Must fix the Issue; Must select the selected date
## Actual Result

Selected time missing when we click Forward and come back
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![4 1](https://cloud.githubusercontent.com/assets/4592712/4264837/ece897f4-3c35-11e4-9a28-7d9105f44236.png)
## Video

https://www.dropbox.com/s/qxmkit82s11y2yf/5.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
