### ISSUE TITLE
currently hovered row should be highlighted on the step 3

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#505]
mac 10.9.4, Chrome 35
1. login as heffan
2. click Contest creation wizard
3. enter some proper data for the step 1, proceed to step 2
4. enter some proper data for step 2, proceed to step 3
5. hover on “Customize Phase Schedule” and “Customized Room Assignment” respectively, observe

expected: currently hovered row should be highlighted on the step 3

actual: see screenshot, non hovered row looks brighter than hovered row, which is confusing.

![qq20140914-4](https://cloud.githubusercontent.com/assets/4590317/4266234/35ea4e56-3c78-11e4-804d-521f6cd05dcc.jpg)

**Comment by skyhit** [comment]
it is following the design.
