### ISSUE TITLE
layout issue on the summary screen

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#506]
mac 10.9.4, Chrome 35
1. login as heffan
2. click Contest creation wizard
3. enter proper data on each screen, then observe the screen on the summary screen

expected: should have no layout issues

actual: see screenshot

![qq20140915-9](https://cloud.githubusercontent.com/assets/4590317/4266242/85e3f40c-3c78-11e4-8325-22a9a8a5993a.jpg)

**Comment by skyhit** [comment]
@flytoj2ee this seems not fixed.

**Comment by flytoj2ee** [comment]
I changed the UI as reviewers' suggestion. Is there any other places need to change?
![summary_page](https://cloud.githubusercontent.com/assets/4497285/4642384/31a2224a-5444-11e4-9c7c-d0c602b38987.gif)

**Comment by skyhit** [comment]
no, that looks good.

**Comment by mdesiderio** [comment]
Moved to the other repo
