### ISSUE TITLE
Numbers missing when we click Down arrow after the value '0'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#507]
## Description

[Common] Numbers missing when we click Down arrow after the value '0'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Go to Step 03

In 'Customize Phase Schedule'
Click Down arrow and come to '0'
Then click Down arrow again in the Registration. coding, intermission etc ..
## Expected Result

Must fix the Issue; Must not show the empty values in the Registration. coding, intermission etc ..
## Actual Result

Numbers missing when we click Down arrow after the value '0'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![5](https://cloud.githubusercontent.com/assets/4592712/4264840/02fc9ea0-3c36-11e4-8cfe-6ec8b28096d4.png)
## Video

https://www.dropbox.com/s/9sxxwapf7z7gon7/507.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
