### ISSUE TITLE
colon should be removed after “Status”/"Type"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#508]
mac 10.9.4, Chrome 35
1. login as heffan
2. click Contest creation wizard
3. enter proper data on each screen step by step, then observe the screen on the summary screen

expected: colon should be removed after “Status” and "Type"

actual: see screenshot

![qq20140915-10](https://cloud.githubusercontent.com/assets/4590317/4266246/bf471292-3c78-11e4-8959-886bc124565d.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#186
