### ISSUE TITLE
No hand cursor when we hover over the items in 'Assignment method' Drop down

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#509]
## Description

No hand cursor when we hover over the items in 'Assignment method' Drop down
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Go to Step 03

In 'Customized Room Assignment'
Click 'Assignment method'
Hover over the items
## Expected Result

Must fix the Issue; Must have hand cursor
## Actual Result

No hand cursor when we hover over the items in 'Assignment method' Drop down
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/4264341/6ba23cda-3c22-11e4-966d-ae1051a19e74.png)
## Video

https://www.dropbox.com/s/jo7hx7akweyqw9l/509.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#185
