### ISSUE TITLE
When chat with 'Admin' contacts (heffan) : NO space in between the ">" and the chat text

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#51]
## Description

When chat with 'Admin' contacts (heffan) : NO space in between the ">" and the chat text
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as heffan/password
Select : 'admin'
Then select 'twight' as user
Enter some text
Press ENTER
## Expected result

Must fix the Issue. Must have soem space
When we chat with normal user you can see the space
## Actual result

When chat with 'Admin' contacts (heffan) : NO space in between the ">" and the chat text
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/3330860/d803b0ca-f7d5-11e3-88ed-6c0d8416682f.png)

**Comment by skyhit** [comment]
there is actually space. but due to italic, it is not obvious

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#184
