### ISSUE TITLE
Layout in the Summary Page

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#510]
## Description

Layout in the Summary Page
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Fill all the required data in the Step 1,2 and 3
Go to 'Summary page'
## Expected Result

Must fix the Issue; Must have some space in between them
## Actual Result

Layout in the Summary Page
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/4264346/b4fc7e22-3c22-11e4-8f3c-1e8792e5083a.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
duplicate
