### ISSUE TITLE
Can't go directly to the section using Top header

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#511]
## Description

Can't go directly to the section using Top header
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Fill all the required data in the Step 1,2 and 3
Go to 'Summary page'
Click Step 3
Now try to click Step 1 or 2
## Expected Result

Must fix the Issue; Must able to do that
- When we are in the Summary page, it won't have a Previous button so user can go back by clicking the main menu tab section
- But after we click once we can't click on another tab to select it directly

So must enable direct selection from tab for all the tabs or include Previous button in the Summary Tab
## Actual Result

Can't go directly to the section using Top header
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![10](https://cloud.githubusercontent.com/assets/4592712/4264844/397b4044-3c36-11e4-9303-f35a55ec48c2.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
yes, this the current implementation.
