### ISSUE TITLE
hand cursor should not be shown when hovering on the uploaded logo

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#512]
mac 10.9.4, Chrome 35
1. login as heffan
2. click Contest creation wizard
3. enter proper data on first screen
4. go to step 2, select a picture to upload, then hover on the uploaded logo

expected: no need to show the hand cursor since it is not clickable

actual: see screenshot

![qq20140914-6](https://cloud.githubusercontent.com/assets/4590317/4266248/daa92c64-3c78-11e4-941a-84b40bbf2138.jpg)

**Comment by skyhit** [comment]
fixed.
