### ISSUE TITLE
Info message must change : Success to create contest.

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#513]
## Description

Info message must change : Success to create contest.
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
Fill all the required data in the Step 1,2 and 3
Go to 'Summary page'
Click Create Contest
## Expected Result

Must fix the Issue; Contest created successfully
## Actual Result

Success to create contest.
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![11](https://cloud.githubusercontent.com/assets/4592712/4264352/453c2366-3c23-11e4-8240-e93bdb91cd60.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
