### ISSUE TITLE
Date selection touches the Top border

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#514]
## Description

Date selection touches the Top border
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the First Step
Click on the Date (eg :Sept 8th)

Check the Circle and Top border
## Expected Result

Must fix the Issue; Must have some gap
## Actual Result

Date selection touches the Top border
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/4264857/8b53f276-3c36-11e4-9997-77e33ce0bd32.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
