### ISSUE TITLE
 0 should not change to empty at last

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#515]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter proper data on first and second screen
4. on the step 3 screen, click “Customize Phase Schedule”
5. click the “down” arrow for the hour of “Coding Length” several times, observe

expected: 0 should not change to empty at last

actual: see screenshot, same issues for other places where have this widget (Registration Limit on step 1, "Registration Start" on this page, etc.)

![qq20140915-11](https://cloud.githubusercontent.com/assets/4590317/4266267/99996b3e-3c79-11e4-8a5b-d2a0b811f631.jpg)

![qq20140915-12](https://cloud.githubusercontent.com/assets/4590317/4266271/c3790e6e-3c79-11e4-8ea3-985956ab372e.jpg)

![qq20140915-13](https://cloud.githubusercontent.com/assets/4590317/4266273/c8b75606-3c79-11e4-8347-2ec44817924a.jpg)

**Comment by skyhit** [comment]
duplicated.
