### ISSUE TITLE
 text “Remove Intermission and Challenge” should be changed

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#516]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter proper data on first and second screen
4. on the step 3 screen, click “Customize Phase Schedule”
5. observe

expected: text “Remove Intermission and Challenge” should be changed to “Remove Intermission and Challenge Phase”

actual: see screenshot

![qq20140914-7](https://cloud.githubusercontent.com/assets/4590317/4266280/e93a7e44-3c79-11e4-97f5-fbae018e114e.jpg)

**Comment by skyhit** [comment]
I think it is clear.
