### ISSUE TITLE
Layout Issue in the Step 01 in Orange Theme

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#519]
## Description

Layout Issue in the Step 01 in Orange Theme
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Check the First Step
## Expected Result

Must fix the Issue; 
- Must fix the 'Contest Name' field it touches the Calender section
- Fix the drop down issue in 'Allowed Languages'
- Calender section gay display with in the section
- Main menu Selection Issue (Must not match with the unselected top menus - Gray once)
## Actual Result

Layout Issue in the Step 01 in Orange Theme
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/4264861/a499dae8-3c36-11e4-8ad2-7a76eb218654.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
