### ISSUE TITLE
'Admin' contacts (heffan) username is not clear (Bold) too must Italic in Safari

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#52]
## Description

'Admin' contacts (heffan) username is not clear (Bold) too must Italic in Safari
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as heffan/password
Select : 'Reply to'
Then select 'twight' as user
Enter some text
Press ENTER

Check the username 'heffan' in Chat window and user window
Compare with other browsers
## Expected result

Must fix the Issue. Must BOLD and clear
Too much italic
## Actual result

'Admin' contacts (heffan) username is not clear (Bold) too must Italic in Safari
## Environment

Safari 5.1.7 in Window 7
## Image

Safari:
![16 1](https://cloud.githubusercontent.com/assets/4592712/3330894/7463bc62-f7d6-11e3-93bd-b63326e6e35b.png)

Others: (Chrome, FF, IE)
![16 2](https://cloud.githubusercontent.com/assets/4592712/3330895/80796484-f7d6-11e3-84e0-728a5040661e.png)

**Comment by skyhit** [comment]
I checked css, it is nothing special, just italic style.

so it is browser specific issue.
