### ISSUE TITLE
tagline should be limited to some amount of chars

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#520]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter proper data on each step, note that on the step 2, provide a long string for the sponsor tagline
4. then forward to observe the summary page

expected: tagline should be limited to some amount of chars

actual: see screenshot
![qq20140914-8](https://cloud.githubusercontent.com/assets/4590317/4266287/49dd8822-3c7a-11e4-9401-b38b0c2e2016.jpg)

**Comment by flytoj2ee** [comment]
The step 2 "Sponsorship" panel is not implemented yet.

Does it need to fix?

**Comment by skyhit** [comment]
fix as much as possible for client side, the backend is out of scope.

**Comment by skyhit** [comment]
fixed.
