### ISSUE TITLE
[Common] 'Assignment method' drop down won't close when we click previous and then click Next

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#521]
## Description

'Assignment method' drop down won't close when we click previous and then click Next
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Check the First Step --> Fill all the required data
Click Next
Expand the 'Assignment method' drop down
Click Previous
Now Click Next

Still you can see the expanded Drop down

NOTE: When we switch between the 'Customize Phase Schedule' and 'Customized Room Assignment' same thing happens
## Expected Result

Must fix the Issue; Must close the drop down when we navigate away from the Tab and come again
## Actual Result

'Assignment method' drop down won't close when we click previous and then click Next
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![16](https://cloud.githubusercontent.com/assets/4592712/4264873/2ef444e4-3c37-11e4-8806-ac35b8916a44.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
