### ISSUE TITLE
'Add Notes' textbox text is too close to the left border

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#524]
## Description

'Add Notes' textbox text is too close to the left border
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Sumamry Page
Enter some text to the 'Add Notes'
## Expected Result

Must fix the Issue; Must have some gap from front
## Actual Result

'Add Notes' textbox text is too close to the left border
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![17](https://cloud.githubusercontent.com/assets/4592712/4264876/56482664-3c37-11e4-9a62-59821f18f2e3.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
