### ISSUE TITLE
Must expand the 'Add Sponsorship Info' by default

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#525]
## Description

Must expand the 'Add Sponsorship Info' by default
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Sumamry Page
Enter some text to the 'Add Notes'
## Expected Result

Must fix the Issue; There is only one option here so Must expand the 'Add Sponsorship Info' by default
## Actual Result

'Add Sponsorship Info' is collapsed by default
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/4264879/735c9dde-3c37-11e4-9e4f-b12b6dff7ca2.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
this is optional
