### ISSUE TITLE
should not allow create a contest on the past date

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#526]
mac 10.9.4, Chrome 35
1. login as heffan
2. click Contest creation wizard
3. select a past date like “03/03/2013” for the date, enter other data properly on each screen
4. proceed to last page, click to create

expected:it should not allow creating a contest on the past date

actual: it can be created

![qq20140915-18](https://cloud.githubusercontent.com/assets/4590317/4266315/492cdcd8-3c7b-11e4-9fbe-ad5b8b420318.jpg)

**Comment by skyhit** [comment]
fixed.
