### ISSUE TITLE
Must expand one of these steps by default 'Customize Phase Schedule' or 'Customized Room Assignment'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#527]
## Description

Must expand one of these steps by default 'Customize Phase Schedule' or 'Customized Room Assignment'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Step 03
Must expand one of these steps by default
'Customize Phase Schedule' or 'Customized Room Assignment'
## Expected Result

Must fix the Issue; Must expand one of these steps by default
## Actual Result

both 'Customize Phase Schedule' and 'Customized Room Assignment' in collapsed state
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/4264882/79cdc080-3c37-11e4-82c0-593d8b68b447.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
there are default settings for SRM, no need to adjust normally.
