### ISSUE TITLE
 layout issue on step 2 (Orange theme)

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#528]
mac 10.9.4, Chrome 35
1. login as heffan, change to Orange theme
2. click Contest creation wizard
3. enter proper data on step 1, then go to step 2, observe

expected:it should have no layout issue

actual: see screenshot, the line should be connected with the gray bar

![qq20140914-10](https://cloud.githubusercontent.com/assets/4590317/4266320/5f1a9760-3c7b-11e4-8161-7ccef0a21e13.jpg)

**Comment by skyhit** [comment]
similar issue reported.
