### ISSUE TITLE
NO validation for the Image upload

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#529]
## Description

NO validation for the Image upload
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Step 02
Upload a text file
Then Click next
## Expected Result

Must fix the Issue; Must validate the image uplaod
## Actual Result

NO validation for the Image upload
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![20](https://cloud.githubusercontent.com/assets/4592712/4264883/91fea502-3c37-11e4-9d85-f9d6832aadc8.png)
## Bug Hunt

Contest Creation Wizard

**Comment by flytoj2ee** [comment]
The step 2 "Sponsorship" panel is not implemented yet.

Does it need to fix?

**Comment by skyhit** [comment]
the backend logic is out of scope, but for client side, please fix as much as possible.

**Comment by skyhit** [comment]
@flytoj2ee this seems not fixed.

**Comment by flytoj2ee** [comment]
It works in my test. Any more detail about this issue?
![pic_validation](https://cloud.githubusercontent.com/assets/4497285/4642366/f1efac08-5443-11e4-9bf6-afced94177a8.gif)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#179
