### ISSUE TITLE
Layout Issue in the 'Room Selection drop down in Safari

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#53]
## Description

Layout Issue in the 'Room Selection drop down in Safari
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password
Click 'Rooms' drop down
## Expected result

Must fix the Issue. Drop down container must not go beyond the controller
## Actual result

Layout Issue in the 'Room Selection drop down in Safari
## Environment

Safari 5.1.7 in Window 7
## Image

![17](https://cloud.githubusercontent.com/assets/4592712/3331075/a241fc8c-f7d8-11e3-8cd9-797c34e93cd5.png)

**Comment by skyhit** [comment]
no need to be same size as dropdown.
