### ISSUE TITLE
Error message Validation marker Issue in 'Allowed Languages' [Orange Theme]

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#531]
## Description

Error message Validation marker Issue in 'Allowed Languages' [Orange Theme]
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Step 01
Click Next (Don't fill anything)
## Expected Result

Must fix the Issue; Must highlight the whole Drop down
- Compare with the Dark and Light themes
## Actual Result

Error message Validation marker Issue in 'Allowed Languages' [Orange Theme]
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/4264885/a2d45908-3c37-11e4-8962-c16235710fb8.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
