### ISSUE TITLE
 layout issue if the image name is too long on the step 2

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#532]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. enter proper data on 1st step, proceed to step 2
3. select an image with a long name to upload, observe

expected: should have no layout issue, an easy way is to just not show the file name.

actual: see screenshot
![qq20140915-19](https://cloud.githubusercontent.com/assets/4590317/4266327/a8f31ede-3c7b-11e4-9c8c-14c27cc154f8.jpg)

**Comment by flytoj2ee** [comment]
The step 2 "Sponsorship" panel is not implemented yet.

Does it need to fix?

**Comment by skyhit** [comment]
yes, we still need to fix the long name problem, so we can implement it sponsorship later

**Comment by skyhit** [comment]
fixed.
