### ISSUE TITLE
NO max limit for 'Coders per room'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#533]
## Description

NO max limit for 'Coders per room'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Step 03
Enter '9999999999999999999999999999999992224244444444444444444442' to Coders per room
## Expected Result

Must fix the Issue; Must have a max limit
## Actual Result

NO max limit for 'Coders per room'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/4264890/c14f11c0-3c37-11e4-98d4-6e61f6cb1a84.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed
