### ISSUE TITLE
checkbox is hard to find on step 3 (Orange theme)

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#534]
mac 10.9.4, Chrome 35
1. login as heffan, change to Orange theme
2. enter proper data on 1st step and 2nd step
3. click the “Customize Phase Schedule” on step 3 page, observe

expected: checkbox should be easily to see

actual: see screenshot

![qq20140914-13](https://cloud.githubusercontent.com/assets/4590317/4266330/c8d7bb06-3c7b-11e4-8f1a-eb834ccd75bb.jpg)

**Comment by skyhit** [comment]
per my testing, it looks clear.
