### ISSUE TITLE
“Restration Start” should be “Restration Starts”

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#535]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. enter proper data on 1st step and 2nd step
3. click the “Customize Phase Schedule” on step 3 page, observe

expected: “Registration Start” should be “Registration Starts” since there is other text after it. The whole sentence reads as “Registration starts hh:mm prior to contest.”.

actual: see screenshot

![qq20140915-20](https://cloud.githubusercontent.com/assets/4590317/4266342/1d16a27c-3c7c-11e4-80c5-66130a018fa4.jpg)

**Comment by skyhit** [comment]
I don't see any confusion.
