### ISSUE TITLE
Long Tag line will create a Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#536]
## Description

Long Tag line will create a Layout Issue
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to the Step 02
Enter '9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM9-14-2014 8-43-11 PM'
To the Tag line
Go to Summary
Check the tag section
## Expected Result

Must fix the Issue; 
## Actual Result

Long Tag line will create a Layout Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/4264892/c7831802-3c37-11e4-8377-9761e04baf16.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
duplicated.
