### ISSUE TITLE
[$5] “1 minutes” should be “1 minute” for intermission phase

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#537]
mac 10.9.4, Chrome 35
1. login as heffan, change to Orange theme
2. enter proper data on 1st step and 2nd step
3. customize every phase to 1 minute, then proceed to next page

expected: “1 minutes” should be “1 minute” for intermission phase on the summary page

actual: see screenshot
![qq20140914-14](https://cloud.githubusercontent.com/assets/4590317/4266347/51f3c9d4-3c7c-11e4-8fe4-bbf019852a69.jpg)

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed

**Comment by huangqun** [comment]
fixed.
