### ISSUE TITLE
[$5] Allowed Language must --> Allowed Languages

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#538]
## Description

Allowed Language must --> Allowed Language(s)
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Fill all teh resuired data
Go to Summary
Check the Allowed Language
## Expected Result

Must fix the Issue; 
- Allowed Language must --> Allowed Language(s)
- Because use can select only one Language and also 3-4 languages
## Actual Result

Allowed Language
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![24](https://cloud.githubusercontent.com/assets/4592712/4264895/d63e5b90-3c37-11e4-9867-7f1bc340be81.png)
## Bug Hunt

Contest Creation Wizard

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
