### ISSUE TITLE
summary page should also show whether the contest is rated or not information

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#539]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. enter proper data on 1-3 steps
3. observe the summary page

expected: summary page should also show whether the contest is rated or not information, which is filled on the step 2.

actual: see screenshots, not such info.
![qq20140915-22](https://cloud.githubusercontent.com/assets/4590317/4266358/82ccc9f2-3c7c-11e4-98d6-e465b249db32.jpg)

There is info about rated or not:

![qq20140915-21](https://cloud.githubusercontent.com/assets/4590317/4266360/90608c48-3c7c-11e4-8735-15d020940892.jpg)

**Comment by flytoj2ee** [comment]
The step 2 "Sponsorship“ panel is not implemented yet. 

Does it need to fix?

**Comment by skyhit** [comment]
sponsorship part is out of scope.

**Comment by skyhit** [comment]
@flytoj2ee this seems not fixed.

**Comment by flytoj2ee** [comment]
You said "sponsorship part is out of scope." so I didn't change the UI for sponsorship part.

It needs to modify the sponsorship UI if necessary.

**Comment by skyhit** [comment]
this is about rated or not info.

**Comment by flytoj2ee** [comment]
So in summary page, how to place the "rated or not" section?

**Comment by skyhit** [comment]
after the status section

**Comment by flytoj2ee** [comment]
I fixed this issue. Please refer to pull request https://github.com/cloudspokes/arena-web/pull/842
