### ISSUE TITLE
Must use (-) when the word displays in two lines

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#54]
## Description

Must use (-) when the word displays in two lines
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password

Meanwhile - Register for a contest
While the coding phase starts
Check the message:

Room assignments are completed for Test SRM - Test SRM Round. You may move to your room anytime by selecting the contest from the Active Contest menu.

Must use (-) for "anytime"
## Expected result

Must fix the Issue. Must use (-) when the word displays in two lines
## Actual result

Not using (-) when the word displays in two lines
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/3331115/0cb07918-f7d9-11e3-9f76-c6ab2fb572be.png)

**Comment by delemach** [comment]
Instead of hyphenating, break on spaces. If the word is very long only then use hyphens.
