### ISSUE TITLE
Type section; Normal value displaying Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#540]
## Description

Type section; Normal value displaying Issue
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 01
Click "normal' as Type
Go to Summary
Check the type section
## Expected Result

Must fix the Issue; 
- Must display as 'Normal' in Summary instead 'Invitational' because in Step 01; Types are listed as Normal and Public
- Must display types; Normal as 'Invitational' in the Step 01 because in summary when we select normal it displays as 'Invitational'
## Actual Result

Type section; Normal value displaying Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![24a 1](https://cloud.githubusercontent.com/assets/4592712/4264907/252991a2-3c38-11e4-8c26-8a6a5896d20e.png)
![24a 2](https://cloud.githubusercontent.com/assets/4592712/4264908/253399b8-3c38-11e4-9081-ad67bc12eb15.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
Should be invitational.

**Comment by skyhit** [comment]
fixed.
