### ISSUE TITLE
Bottom border hides when we click 'Remove Intermission and Challenge' in Orange Thene

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#541]
## Description

Bottom border hides when we click 'Remove Intermission and Challenge' in Orange Thene
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 03
Click 'Remove Intermission and Challenge'
Check the line
## Expected Result

Must fix the Issue; Must display the line as Light Theme
## Actual Result

Bottom border hides when we click 'Remove Intermission and Challenge' in Orange Thene
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![25 1](https://cloud.githubusercontent.com/assets/4592712/4264910/29ef3f20-3c38-11e4-95c6-d37817b4daba.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
this is following the design.
