### ISSUE TITLE
[$5] "Summary Screen" should be changed to "Summary"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#542]
mac 10.9.4, Chrome 35
1. login as heffan, change to Orange theme
2. fill all data properly, go to last page

expected: "Summary Screen" should be changed to "Summary", no need to emphasize "Screen".

actual: see screenshot
![qq20140915-23](https://cloud.githubusercontent.com/assets/4590317/4266373/bf653494-3c7c-11e4-856f-e5d43b2c4619.jpg)

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
