### ISSUE TITLE
[Common] Accepting spaces as valid inputs

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#543]
## Description

[Common] Accepting spaces as valid inputs
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 03
Expand the 'Customize Phase Schedule'
In Registration Start, Coding Length, Intermission Length and Challenge Length
Enter space
Click Next
## Expected Result

Must fix the Issue; Must restrict it
## Actual Result

[Common] Accepting spaces as valid inputs
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![26](https://cloud.githubusercontent.com/assets/4592712/4264917/b1a01b2e-3c38-11e4-93c3-0d88a73aa682.png)
## Video

https://www.dropbox.com/s/zxtnvzw0xfeg43t/543.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
