### ISSUE TITLE
[Common] Error message won;t clear when we navigate back

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#544]
## Description

[Common] Error message won;t clear when we navigate back
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 03
Expand the 'Coders per room'
Enter '999999999999' to Coders per room
Click Next
When the error message comes
Click Previous
## Expected Result

Must fix the Issue; Must clear the error message
## Actual Result

[Common] Error message won;t clear when we navigate back
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![27](https://cloud.githubusercontent.com/assets/4592712/4264919/bb78d398-3c38-11e4-89ff-81a15edbff21.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
