### ISSUE TITLE
[Common] Error message hides when we come back again

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#545]
## Description

[Common] Error message hides when we come back again
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 03
Expand the 'Coders per room'
Enter '999999999999' to Coders per room
Click Next
When the error message comes
Click Previous (Step 02)
Click Previous (Step 01)

Click Next twice
Check the Error message
## Expected Result

Must fix the Issue; Must display the Error message 'Please correct the errors and try again.'
## Actual Result

Error message hides when we come back again
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/4264922/c1774c16-3c38-11e4-9c0b-1b55e0931bb3.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed
