### ISSUE TITLE
[Common] 'Coder per room' must 'Coders per room' in Summary page

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#546]
## Description

[Common] 'Coder per room' must 'Coders per room' in Summary page
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 03
Expand the 'Coders per room'
Enter '100' to Coders per room
Click Next
In the Summary page check the 'Coder per room'

'Coder per room' must 'Coders per room' in Summary page
## Expected Result

Must fix the Issue; 'Coder per room' must 'Coders per room' in Summary page
## Actual Result

 'Coder per room'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![29](https://cloud.githubusercontent.com/assets/4592712/4264530/e3690cb4-3c2a-11e4-8b29-3b35adec7b0f.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed
