### ISSUE TITLE
 “Launch Contest!” should be “Launch Contest”

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#547]
mac 10.9.4, Chrome 35
1. login as heffan, change to light theme
2. enter proper data on steps 1-3
3. observe the summary page

expected: button text “Launch Contest!” should be “Launch Contest” 

actual: see screenshot
![qq20140915-24](https://cloud.githubusercontent.com/assets/4590317/4266377/db773ed4-3c7c-11e4-85a1-b5ae94e78c80.jpg)

**Comment by skyhit** [comment]
following design
