### ISSUE TITLE
[$5] [Common] 2 hour must be --> 2 hours

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#548]
## Description

[Common] 2 hour must be --> 2 hours
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 03
Expand the 'Customize Phase Schedule'

Enter 2 : 00 for Coding Length, Intermission Length and Challenge Length

Click Next
Check the numbers in SUmmary page
## Expected Result

Must fix the Issue; 2 hour must be --> 2 hours
## Actual Result

2 hour
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/4264926/e19c8b78-3c38-11e4-9593-0fe2975ccf0c.png)
## Bug Hunt

Contest Creation Wizard

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
