### ISSUE TITLE
[$5] "Offical rated contest" should be "Offically rated contest" on step 2

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#549]
mac 10.9.4, Chrome 35
1. login as heffan, change to Orange theme
2. enter proper data on step 1, proceed to step 2, observe

expected: "Official rated contest" should be "Officially rated contest" on step 2
actual: see screenshot.

![qq20140915-21](https://cloud.githubusercontent.com/assets/4590317/4266379/ef0fc3a8-3c7c-11e4-9f06-a64701bcbade.jpg)

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
![image](https://cloud.githubusercontent.com/assets/6045894/4770505/90eef66c-5b86-11e4-9394-e976c0ce7764.png)
not fixed

**Comment by huangqun** [comment]
fixed
