### ISSUE TITLE
When we expand 'Registrants(x)' the 'Who's Here(x) moves to the bottom of the section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#55]
## Description

When we expand 'Registrants(x)' the 'Who's Here(x) moves to the bottom of the section
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)

Then collapse 'Rating Key', 'Registrants(x)' and 'Who's here (x)
Now expand 'Registrants(x)'

There is only 3 users in the 'Registrants(x)'
## Expected result

Must fix the Issue. Must display below the last record of the 'Registrants' section
## Actual result

When we expand 'Registrants(x)' the 'Who's Here(x) moves to the bottom of the section
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/3331225/3ad24d98-f7da-11e3-94ec-6799ff84c6b9.png)

**Comment by skyhit** [comment]
this is desired.
