### ISSUE TITLE
[$5] [Common] 'Please wait for saving contest data' must be --> 'Please wait while saving contest data'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#550]
## Description

[Common] 'Please wait for saving contest data' must be --> 'Please wait while saving contest data'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Fill all the data
Go to Sumamry
Click Launch Contest

Check the next pop up
## Expected Result

Must fix the Issue; 'Please wait for saving contest data' must be --> 'Please wait while saving contest data'
## Actual Result

'Please wait for saving contest data'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![31](https://cloud.githubusercontent.com/assets/4592712/4264927/eaad0544-3c38-11e4-98f1-5e2c9c0f4674.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
image is missing. but the issue clear.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
