### ISSUE TITLE
“Select Contest Start Date” field is confusing

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#551]
win 8 , IE 11
1. login as heffan, change to Orange theme
2. observe “Select Contest Start Date”

expected:  no cursor should be shown when clicking in it.

actual: see screenshot, user clicks the text field, the cursor is blinking but the user cannot enter anything.
![2](https://cloud.githubusercontent.com/assets/4590317/4266399/60469dd0-3c7d-11e4-859f-8bddc9b00e55.jpg)

**Comment by skyhit** [comment]
looks like browser behavior, I can not reproduce in Chrome.

**Comment by skyhit** [comment]
fixed.
