### ISSUE TITLE
[Common] 'Registration Limit' remove the number when we click Down arrow from value '1'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#552]
## Description

[Common] 'Registration Limit' remove the number when we click Down arrow from value '1'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Go to Step 01
Click Registration Limit
Enter '1'
Click Down Arrow
## Expected Result

Must fix the Issue; 
## Actual Result

'Registration Limit' remove the number when we click Down arrow from value '1'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![31a](https://cloud.githubusercontent.com/assets/4592712/4264933/2174d340-3c39-11e4-9aeb-9804045ac2f0.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
duplicated.
