### ISSUE TITLE
Arrows can decrease the hours beyond Zero

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#553]
1. Go to Contest Wizard section
2. Go to Step 3
3. Expand Customize Phase Schedule
4. In the Registration Start dropdown field, use the arrows to reduce the number of hours and observe

Actual:

user is able to reduce the hours beyond 0. 

Expected:

user should not be able to reduce beyond 0. This is common to all such fields.

**Comment by nithyaasworld** [comment]
Environment: Windows 7, FF32

**Comment by nithyaasworld** [comment]
![arena12](https://cloud.githubusercontent.com/assets/5114190/4265042/f8a3c620-3c3c-11e4-896f-f6a35063bd4a.png)

**Comment by skyhit** [comment]
duplicated.
