### ISSUE TITLE
Hand symbol should not be shown on lower arrow when the field is not active

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#554]
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Go to Step 3
Expand Customize Phase Schedule
In the Registration Start dropdown field, in the minute dropdown field, Observe the lower arrow when the value is in 0
Actual:

Lower arrow is active and clickable and show a handsymbol on hover though the value is already in 0.

Expected:

Hand symbol should not be shown when the filed is not active

**Comment by nithyaasworld** [comment]
Environment: Windows 7, FF32

![arena14](https://cloud.githubusercontent.com/assets/5114190/4265072/1e79236c-3c3e-11e4-90c0-db672e2e8b4e.png)

**Comment by skyhit** [comment]
fixed.
