### ISSUE TITLE
Layout issue in the 'Assign by region' section in Orange Theme

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#555]
## Description

Layout issue in the 'Assign by region' section in Orange Theme
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Fill all the data
Go to Sumamry

Check the 'Assign by region' section 
## Expected Result

Must fix the Issue; Must display the Orange Line within the container
## Actual Result

Layout issue in the 'Assign by region' section in Orange Theme
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![32](https://cloud.githubusercontent.com/assets/4592712/4264615/bcd90e70-3c2d-11e4-9151-38e0075c1574.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
