### ISSUE TITLE
Minute fields accept values more than 60

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#556]
Environment: Windows7 FF32

Steps:
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Go to Step 3
Expand Customize Phase Schedule
In the Registration Start dropdown field, in the minute dropdown field, Enter value as 99 and observe

Actual:
99 is accepted as minute value

Expected:
99 should not be accepted as minute value.

**Comment by flytoj2ee** [comment]
I think it's not an issue. It needs to click next button to trigger the validation logic.

**Comment by skyhit** [comment]
this didn't look good, can we limit the range for that field?

**Comment by flytoj2ee** [comment]
Is it okay to change to use dropdown list in minutes field?

For example, it contains 0-59 items. User could select one of them.

**Comment by skyhit** [comment]
the list is too long then. please try to implement it with current way.

**Comment by flytoj2ee** [comment]
What to do if user inputs 99 in minutes field? Auto-change to 60? Or show validation error?

**Comment by snowone** [comment]
update?

**Comment by skyhit** [comment]
show validation error.

**Comment by skyhit** [comment]
fixed.
