### ISSUE TITLE
'Summary Screen' must --> Summary

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#557]
## Description

'Summary Screen' must --> Summary
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Fill all the data
Go to Sumamry

Check the Tab title : 'Summary Screen'
## Expected Result

Must fix the Issue; 'Summary Screen' must --> Summary
## Actual Result

'Summary Screen'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![33](https://cloud.githubusercontent.com/assets/4592712/4264643/6bb22f8a-3c2e-11e4-9073-e9d9cc252fad.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
duplicated.
