### ISSUE TITLE
There is No format (or measure) mentioned for Schedule 

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#558]
![arena10](https://cloud.githubusercontent.com/assets/5114190/4268900/a9892bba-3cb5-11e4-8278-1b35062ff840.png)
Environment: Windows7, FF32

Steps:
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Go to Step 3
Expand Customize Phase Schedule
Observe the fileds

Actual:

It is not sure if those fields represents {hours and minutes} or {Days and hours} or {weeks and Days}.

Expected:

There should be a header for those fields stating the format to be entered. that is, HH:MM

**Comment by flytoj2ee** [comment]
What's the changes suggestion?

Add "(HH:MM)" in section title?

**Comment by skyhit** [comment]
yes.

**Comment by skyhit** [comment]
fixed.
