### ISSUE TITLE
In Summary Page; No Placeholder label for 'Contest name'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#559]
## Description

In Summary Page; No Placeholder label for 'Contest name'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the ORANGE THEME
Fill all the data
Go to Sumamry

Check the Contest Title in SUmmary
## Expected Result

Must fix the Issue; Need to have a label or must have different color for formatting
## Actual Result

In Summary Page; No Placeholder label for 'Contest name'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![34](https://cloud.githubusercontent.com/assets/4592712/4264663/ef3a6b24-3c2e-11e4-8ce6-3295053f1f5f.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
following the design.
