### ISSUE TITLE
No Back button in the Summary Screen

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#560]
Environemnt: Windows 7, FF32

Steps:
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Enter valid details for all the steps and reach to the final Summary Screen
Observe

Actual:
There is no Previous button to go back to the previous screen

Expected:
there should be a Previous button present like it does in every other page.

**Comment by skyhit** [comment]
no, it is following the design. click the nav section can go back.
