### ISSUE TITLE
Registration Start time looks misleading in the Summary Screen

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#561]
![arena2](https://cloud.githubusercontent.com/assets/5114190/4269043/676d7c52-3cb7-11e4-9948-dfc932fe1bca.png)
Environment: Windows7, FF32

Steps:
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Enter valid values for all the steps and reach out to the last screen "summary"
Observe the information displayed under "Phase Schedule"

Actual:
It says "Registration Start" 23 hours 59 minutes.

Expected:
"Registration is starting 23 hours 59 minutes PRIOR TO THE CONTEST LAUNCH". This information should be present fully. Now it looks like Registration starts in 23 hours 59 minutes.

**Comment by flytoj2ee** [comment]
It's too long in current UI to show all above text.

Is there any changes suggestion in UI?

**Comment by skyhit** [comment]
it can not easily fit for current ui, let's leave it.

**Comment by skyhit** [comment]
close this, the suggestion is not fit.
