### ISSUE TITLE
Layout Issue in the date section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#562]
## Description

Layout Issue in the date section
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01
Check the Date section (marked in the screen shot)
## Expected Result

Must fix the Issue; Must fill the gap between the border in Dark Theme
## Actual Result

Layout Issue in the date section
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![35 1](https://cloud.githubusercontent.com/assets/4592712/4264686/7828911c-3c30-11e4-9423-47fda4538917.png)
![35](https://cloud.githubusercontent.com/assets/4592712/4264685/782422f8-3c30-11e4-8f2f-fd49a3551b4f.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
