### ISSUE TITLE
Coders Per room can be decreased beyond Zero using down arrows

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#563]
Environment: Windows7, FF32

Steps:
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Go to step 3
Under the section "Customized Room Assignment", try to decrease the "Coders Per room" using the down arrow and
observe

Actual:

Able to decrease the field beyond 0. 

Expected.

User should not be able to decrease this field beyond 0.

![arena3](https://cloud.githubusercontent.com/assets/5114190/4269103/0e149e64-3cb8-11e4-9231-0bd0d65d0045.png)

**Comment by skyhit** [comment]
duplicate, similar issue already reported.
