### ISSUE TITLE
Won't disable the Arrows when user reaches the Min max values in the 'Registration Limit'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#564]
## Description

Won't disable the Arrows when user reaches the Min max values in the 'Registration Limit'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01
Enter '99999' to the Registration Limit
Click Next
Click Previous

Click Up arrow (eg: 100000)
Click next
Error pop up
## Expected Result

Must fix the Issue; Must disable the Arrows when user reaches the Min max values in the 'Registration Limit'
Like mins in the Step 03
## Actual Result

Won't disable the Arrows when user reaches the Min max values in the 'Registration Limit'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![36](https://cloud.githubusercontent.com/assets/4592712/4264722/7fe8f9cc-3c31-11e4-8377-36bcbc2b63d6.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed
