### ISSUE TITLE
No Hovering Symbol when hovered over checkboxes

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#565]
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
In the Step 1, Expand the dropdown "Allowed Languages"
Hover the mouse over the checkbox and observe

Actual:

There is no handsymbol displayed

Expected:

It should display hand symbol when hovering over the checkboxez

Environment: Windows 7, Chrome 37

**Comment by skyhit** [comment]
same as other part.
