### ISSUE TITLE
It should be either "Customize" or "Customized" in both the places for consistency

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#566]
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
Go to Step 3
Observe the sections "Customize Phase Schedule" and "Customized Room assignment"

Actual:

The first section starts with "Customize". The second section starts with "Customized"

Expected:

Both of them should start with either "Customize" or "Customized" for consistency.

Environment:

Windows 7, Chrome 37

**Comment by nithyaasworld** [comment]
![arena13](https://cloud.githubusercontent.com/assets/5114190/4265057/886b3e6e-3c3d-11e4-9c3e-246a5f736277.png)

**Comment by skyhit** [comment]
duplicated.
