### ISSUE TITLE
Can enter chars to the Start Time

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#567]
## Description

Can enter chars to the Start Time
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01
Enter 'dsfdf : asdasd' to Start Time
Click Next
## Empty input as the Start Time

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01
Click Next -- > It will validate the Start Time
Now Enter Time and click next -- > It will remove the validation Red indicator
Now Enter all the required data
Then Delete the Time in the textboxes
Click Next --> It won't ask Time again
## Expected Result

Must fix the Issue; 
- Empty input must validate (37.3)
- Character input must validate (37.1)
- Must validate if we enter only one input to the two boxes (Currently if we enter data to the first one and leave the second one blank won't validate it) (37.2)
## Actual Result

Can enter chars/Blank Data to the Start Time
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

37.1
![37](https://cloud.githubusercontent.com/assets/4592712/4264793/73aca116-3c33-11e4-93ae-fd8aef9fab61.png)

37.2
![37 2](https://cloud.githubusercontent.com/assets/4592712/4267244/bc5631b6-3c97-11e4-87e3-fffee7b95a85.png)

37.3
![37 3](https://cloud.githubusercontent.com/assets/4592712/4267245/bea9d490-3c97-11e4-8be4-cb650bb4b288.png)
## Video

https://www.dropbox.com/s/0dwzywpdugy8j0g/567.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
