### ISSUE TITLE
There is no disable Mode for the top Tabs in Orange and Light Themes

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#568]
## Description

There is no disable Mode for the top Tabs in Orange and Light Themes
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01
Check the Step 02, 03 and Summary
## Expected Result

Must fix the Issue; Need to display as Disabled when we are in the Step 01
Check the Dark theme and compare it with the other themes (Orange and Light)
## Actual Result

There is no disable Mode for the top Tabs in Orange and Light Themes
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![38 1](https://cloud.githubusercontent.com/assets/4592712/4264809/5f29a170-3c34-11e4-83a4-019834542eb7.png)
![38 2](https://cloud.githubusercontent.com/assets/4592712/4264810/5f960194-3c34-11e4-9364-cdfed275d374.png)
## Bug Hunt

Contest Creation Wizard

**Comment by flytoj2ee** [comment]
In current code, it already has disable color.
![17](https://cloud.githubusercontent.com/assets/4497285/4492906/3124a45e-4a45-11e4-9674-815582fee678.gif)

**Comment by flytoj2ee** [comment]
The orange theme is same with other fields.
![18](https://cloud.githubusercontent.com/assets/4497285/4492929/569fe860-4a45-11e4-9410-7d704bc69fd0.gif)

**Comment by skyhit** [comment]
so this problem is fixed in previous assembly, please double check, if it is invalid, just leave it. reviewer will double check too.
