### ISSUE TITLE
Some of the dates are in Orange Colour

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#569]
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
In the Step 1, go to the month February 2014
Observe

Actual:

It has alternative dates in Orange colour

Expected:

Not sure what does orange colour on alternative dates indicate. This should be in white colour.

Environment: Windows 7, FF32

**Comment by nithyaasworld** [comment]
![arena10](https://cloud.githubusercontent.com/assets/5114190/4264825/25a84248-3c35-11e4-9b6d-d35bd08015de.png)

**Comment by skyhit** [comment]
fixed.
