### ISSUE TITLE
When user submit a solution, it is displayed in BOLD text

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#57]
## Description

When user submit a solution, it is displayed in BOLD text
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)

Then Open the problem and submit a answer and compile
Check the other users chat room

System> Yoshi has submitted the 250-point problem for 106.77 points 
## Expected result

Must fix the Issue. Must display in normal text formatting
## Actual result

When user submit a solution, it is displayed in BOLD text
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/3331291/3629973c-f7db-11e3-831b-508a873d26bd.png)

**Comment by skyhit** [comment]
same as arena applet.
