### ISSUE TITLE
Cannot choose the start time as 00:01AM

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#570]
Environment: Windows7, FF32

Steps:
Go to arena.cloud.topcoder.com:3000 and login as heffan
Go to Contest Wizard section
In the Step1: Choose start time as 00:01AM
Enter valid values in all other fields and click Next
observe

Actual:
It throws error and the start time fields are highlighted in red.

Expected:
It should not be highlighted in red when valid start time is chosen.

**Comment by nithyaasworld** [comment]
![arena11](https://cloud.githubusercontent.com/assets/5114190/4264878/5f02c138-3c37-11e4-8057-2f2cc3369f6b.png)

**Comment by skyhit** [comment]
fixed.
