### ISSUE TITLE
Border is missing for "Allowed Languages" in Orange Theme

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#571]
Go to arena.cloud.topcoder.com:3000 and login as heffan
Change the theme to Orange
Go to Contest Wizard section
Observe the Allowed Languages

Actual:

The border is missing. Only the left border of the whole box is displayed.

Expected:

Border for the dropdown should be present fully like it does in other themes.

Environment: Windows 7, FF32

**Comment by skyhit** [comment]
fixed.
