### ISSUE TITLE
[$5] [Common] 'Please correct the errors and try again.' Must display as Please correct the error(s) and try again.

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#573]
## Description

[Common] 'Please correct the errors and try again.' Must display as Please correct the error(s) and try again.
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01
Don't enter contest name and fill all the required data
Click Next

Check the error message
## Expected Result

Must fix the Issue; 
- 'Please correct the errors and try again.' Must display as Please correct the error(s) and try again.
- If there is only one error we can't say errors
## Actual Result

'Please correct the errors and try again.'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![39](https://cloud.githubusercontent.com/assets/4592712/4264977/7e9e1602-3c3a-11e4-9b43-c3d0ca84ba41.png)
## Bug Hunt

Contest Creation Wizard

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
