### ISSUE TITLE
Sponsor Tagline accepts endless characters thus it causes layout issue in the summary screen

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#575]
Go to arena.cloud.topcoder.com:3000 and login as heffan
Change the theme to Orange
Go to Contest Wizard section
In the Step2, Enter long characters in Sponsor tagline and Observe

Actual:
1. There is no limit for input characters for the field "Sponsor tagline"
2. Entering long sentence in this field causes, layout issue in the summary screen.

Expected:

Sponsor Tagline input characters should be limited.

Environment:

Windows 7, FF32

**Comment by skyhit** [comment]
duplicated.
