### ISSUE TITLE
“Assignment method” is not aligned well on the summary screen

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#576]
Mac 10.9.4, Safari 7.0.6
1. login as heffan
2. fill with proper data on each step, then go to summary screen to observe

expected: “Assignment method” should be aligned left and moved closer to the bottom line.

actual: see screenshot

![qq20140915-1](https://cloud.githubusercontent.com/assets/4590317/4266097/bd4a0928-3c72-11e4-8e8c-a85917cddbea.jpg)

**Comment by skyhit** [comment]
fixed.
