### ISSUE TITLE
user experience is not good when the user chooses allowed languages

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#577]
Mac 10.9.4, Safari 7.0
1. login as heffan, click the "Contest creation wizard"
2. click the “Allowed Languages” dropdown list, then try to choose “Java” and “C++” only

expected: the option values modal should not be closed when checking/unchecking any checkboxes, it is better to have a “Done” button on the modal.

actual: see screenshot, the option values modal will be closed whenever user checks/unchecks an option, user has to click the dropdown again to open the modal, which is very inconvenient.

![qq20140915-2](https://cloud.githubusercontent.com/assets/4590317/4266125/8f9167a0-3c73-11e4-8ef2-85d8c603235a.jpg)

**Comment by skyhit** [comment]
duplicated.
