### ISSUE TITLE
default value for “Registration Limit” should be changed

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#578]
Mac 10.9.4, Safari 7.0
1. login as heffan
2. click “Contest creation wizard”
3. observe the default value of “Registration Limit”

expected: it should be changed a reasonable value, AFAIK currently it allows about 2200 (or more) registrants at most.

actual: see screenshot, it’s only 1024, Admin will need to change it every time.

![qq20140915-3](https://cloud.githubusercontent.com/assets/4590317/4266153/162a5e10-3c75-11e4-84ad-6428fce113f3.jpg)

**Comment by skyhit** [comment]
it is 1024 by default in Admin tool.
