### ISSUE TITLE
dropdown values modal does not dismiss when clicking “Next” button

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#579]
Mac 10.9.4, Safari 7.0
1. login as heffan, change to Light theme
2. click “Contest creation wizard”
3. click the “AM/PM” dropdown (do NOT make a choice), then click “Next” button

expected: the dropdown values modal should be closed after clicking the “Next” button

actual: see screenshot, there will be validation errors shown, but it won’t close.

![qq20140915-4](https://cloud.githubusercontent.com/assets/4590317/4266179/21574180-3c76-11e4-874d-15b90edb2f7e.jpg)

**Comment by skyhit** [comment]
fixed.
