### ISSUE TITLE
dropdown values overlaps with the “Next” button

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#580]
Mac 10.9.4, Safari 7.0
1. login as heffan
2. click “Contest creation wizard”
3. click the “AM/PM” dropdown, observe

expected: they should not be overlapped

actual: see screenshot
![qq20140915-5](https://cloud.githubusercontent.com/assets/4590317/4266182/4fe6f540-3c76-11e4-9eb8-a708487b4f13.jpg)

**Comment by skyhit** [comment]
this is fine.
