### ISSUE TITLE
[$5] “start” should be “starts”

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#581]
Mac 10.9.4, Safari 7.0
1. login as heffan
2. click “Contest creation wizard”
3. fill with proper data on step 1 and 2, go to step 3
4. click “Customize Phase Schedule”, read the text on the right side.

expected: last word “start” should be changed to “starts”

actual: see screenshot
![qq20140915-6](https://cloud.githubusercontent.com/assets/4590317/4266205/3935697a-3c77-11e4-8023-2b6e874b2342.jpg)

**Comment by billthu** [comment]
I'm working at it.

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
