### ISSUE TITLE
[Common] Start Date is not set properly in Admin Tools

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#582]
## Description

[Common] Start Date is not set properly in Admin Tools
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01 --> Fill all the data as below
date and time as : 15th Sept 2014, 8:00 SLST (screenshot : 40)

Step 02 --> Fill all the data
Step 03 --> Fill all the data as below

Reg Start : 10mins
Coding Length : 1:00
Intermission Length 00:05
Challenge Length : 1:00
Go to Summary check the details are correct (screenshot : 40.1)
Click Launch contest

Go to Admin tool and check the values --> Start date and time (screenshot : 40.2)
## Expected Result

Must fix the Issue; 
- Must set properly
- I have set Start date and time as : 15th Sept 2014, 8:00 SLST
- Reg Start : 10mins, (prior to contest) means : 7:50 SLST
- Coding Length, Intermission Length and Challenge Length --> They are correct
## Actual Result

Start Date is not set properly in Admin Tools
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![40 1](https://cloud.githubusercontent.com/assets/4592712/4266333/ec6089cc-3c7b-11e4-9539-162af54fdbbd.png)
![40 2](https://cloud.githubusercontent.com/assets/4592712/4266334/ec85f554-3c7b-11e4-972c-7679a11daf4a.png)
![40 3](https://cloud.githubusercontent.com/assets/4592712/4266335/ec95531e-3c7b-11e4-9d7c-281cb774ba44.png)
![40](https://cloud.githubusercontent.com/assets/4592712/4266336/ecb27ade-3c7b-11e4-81b9-d445fa80574b.png)
## Bug Hunt

Contest Creation Wizard

**Comment by flytoj2ee** [comment]
I cannot re-create this issue in my test.
![58](https://cloud.githubusercontent.com/assets/4497285/4514959/9455ce88-4b9c-11e4-875b-028d91bced4f.gif)

![59](https://cloud.githubusercontent.com/assets/4497285/4514961/aadac960-4b9c-11e4-8b6a-f9b545a4a44b.gif)

**Comment by flytoj2ee** [comment]
And according to UI, the start date contains the registration phase length. So I think the current code is fine. 

What's your suggestions?

**Comment by skyhit** [comment]
you mean the start date is the registration start date?

**Comment by flytoj2ee** [comment]
Yes, in current logic, the following 3 dates are same.
a) contest start date
b) round start date
c) registration start date

**Comment by snowone** [comment]
update?

**Comment by skyhit** [comment]
fine.
