### ISSUE TITLE
'Registration will open specified amount of ....' must --> 'Registration will open in specified amount of ...'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#583]
## Description

'Registration will open specified amount of ....' must --> 'Registration will open in specified amount of ...'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01 --> Fill all the data as below
Go to Step 03 --> 
Check the paragraph in the 'Registration Start'

Registration will open specified amount of time prior to contest . Also Registration will always close five minutes before the contest start.
'Registration will open specified amount of ....' must --> 'Registration will open in specified amount of ...'
## Expected Result

Must fix the Issue; 
- 'Registration will open in specified amount of ...'
## Actual Result

'Registration will open specified amount of ....'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![41](https://cloud.githubusercontent.com/assets/4592712/4266413/92e1b234-3c7d-11e4-941f-4bd4075003e8.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
it seems fine, it is talking about the registration length.
