### ISSUE TITLE
Field is still marked with Validation marker

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#584]
## Description

Field is still marked with Validation marker
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01 --> Fill all the data
Go to Step 02 --> Fill all the data
Go to Step 03 --> 
Enter text (eg : abcd) to the 'Registration Start' textfield and click Next
It will trigger the validation
Now Adjust the text to '10' (instead the text you have entered)
Click Previous twice
Click Next Twice
## Expected Result

Must fix the Issue; 
- Must remove the validation marker if we correct the issue and come back
## Actual Result

Field is still marked with Validation marker
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![42](https://cloud.githubusercontent.com/assets/4592712/4266515/abc3d85c-3c7f-11e4-9217-9866112ad494.png)
## Video

https://www.dropbox.com/s/22v8mfq627xu32u/584.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
