### ISSUE TITLE
We can't see the contest in the 'Active Contests' dashboard after we create it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#585]
## Description

We can't see the contest in the 'Active Contests' dashboard after we create it
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the DARK THEME
Go to Step 01 --> Fill all the data as below
Go to Step 02 --> Fill all the data as below
Go to Step 03 --> Fill all the data as below
In the 'Summary' section
Click Launch Contest!

Check the 'Competition Arena: Dashboard'
http://arena.cloud.topcoder.com:3000/#/u/dashboard
## Expected Result

Must fix the Issue; 
- Must display it in the 'Active Contests' dashboard
## Actual Result

We can't see the contest in the 'Active Contests' dashboard after we create it
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![43](https://cloud.githubusercontent.com/assets/4592712/4266686/331f84c8-3c84-11e4-9c87-faf70fa4d7dd.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
there are separate process and configuration before activating it.
