### ISSUE TITLE
red border for validation error does not disappear completely

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#586]
Win 8, Chrome 37.0
1. login as heffan
2. click “Contest creation wizard”
3. click Next
4. then fill the Contest Name with some text, click Next again, observe

expected: red border for the Contest Name field should be disappeared completely.

actual: see screenshot
![3](https://cloud.githubusercontent.com/assets/4590317/4267028/b4320f2c-3c8e-11e4-8672-25eced5e7538.jpg)

**Comment by skyhit** [comment]
can not reproduce.
