### ISSUE TITLE
[$5] 'Contest Wizard' must --> 'Contest Creation Wizard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#587]
## Description

'Contest Wizard' must --> 'Contest Creation Wizard'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
In the DARK THEME
Click 'Contest Creation Wizard'
Check the Title
## Expected Result

Must fix the Issue; 
- 'Contest Wizard' must --> 'Contest Creation Wizard'
## Actual Result

'Contest Wizard'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![44](https://cloud.githubusercontent.com/assets/4592712/4267672/8b5dd588-3ca0-11e4-8b8f-fd45a071d6a1.png)
## Bug Hunt

Contest Creation Wizard

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
