### ISSUE TITLE
there should be text shown like “Not set” if Sponsor is not set on summary screen

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#588]
Mac 10.9.4, FF 32
1. login as heffan
2. click “Contest creation wizard”
3. fill with proper data on steps 1-3, do not fill sponsor details on step 2
4. observe summary page

expected: there should be text shown like “Not set” if Sponsor is not set on summary screen.

actual: see screenshot

![qq20140915-26](https://cloud.githubusercontent.com/assets/4590317/4269527/7fd9074c-3cbd-11e4-922a-2f078cde1b5e.jpg)

**Comment by huangqun** [comment]
not necessary IMO.
