### ISSUE TITLE
There is a column '250'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#59]
## Description

There is a column '250'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer

In the 'Summary'
Check the 'Room Leaderboard' section
Check the Column header '250'
## Expected result

Must fix the Issue. Must rename it to 'Score'
## Actual result

There is a column '250'
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/3331471/f861d368-f7dc-11e3-9981-2d05c90d63e0.png)

**Comment by skyhit** [comment]
250 means the 250 point problem.
