### ISSUE TITLE
[$50] Expand/Collapse icon is very hard to see in Light Theme 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#590]
## Description

Expand/Collapse icon is very hard to see in Light Theme 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
In the LIGHT THEME
Click 'Contest Creation Wizard'
Go to Step 02 --> Check the Expand/Collapse icon in 'Add Sponsorship Info'
Go to Step 03 --> Check the Expand/Collapse icon in 'Customize Phase Schedule' and 'Customized Room Assignment'
## Expected Result

Must fix the Issue; 
- Must use Darker color
## Actual Result

Expand/Collapse icon is very hard to see in Light Theme 
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![46 1](https://cloud.githubusercontent.com/assets/4592712/4269733/e17372ce-3cbf-11e4-8489-b3f185031ea0.png)
![46 2](https://cloud.githubusercontent.com/assets/4592712/4269734/e1748290-3cbf-11e4-9193-cbbc13be6f8b.png)
## Bug Hunt

Contest Creation Wizard

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
