### ISSUE TITLE
error message should be adjusted when there is no internet connection

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#592]
Mac 10.9.4, FF 32
1. login as heffan
2. click “Contest creation wizard”
3. fill with proper data on steps 1-3
4. go to summary screen
5. disconnect internet connection, click “Launch Contest!” button, observe

expected: the error message should be adjusted, like:
Failed to create contest: _Detailed reason goes here_.

actual: see screenshot, there is grammar issue "Fail to create contest" and the status code 0 is hard to understand.

![qq20140915-27](https://cloud.githubusercontent.com/assets/4590317/4273093/e11c92ce-3ce7-11e4-81f6-43e60f75acb3.jpg)

**Comment by skyhit** [comment]
fixed.
