### ISSUE TITLE
current date should be hightlighted in the calendar

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#593]
Mac 10.9.4, FF 32
1. login as heffan
2. click “Contest creation wizard”
3. observe

expected: current date should be selected in the calendar, and the “contest start date” field is filled with the current date.

actual: see screenshot, no default value chosen
![qq20140915-28](https://cloud.githubusercontent.com/assets/4590317/4273357/d83864ce-3ce9-11e4-972a-9ef1c81d8cab.jpg)

**Comment by skyhit** [comment]
@flytoj2ee  not fixed.

**Comment by flytoj2ee** [comment]
I cannot re-create this issue. The current date is highlight in my test.
![highlight](https://cloud.githubusercontent.com/assets/4497285/4642326/9726c82e-5443-11e4-83ba-7f1aff163815.gif)

**Comment by skyhit** [comment]
this is selection, try to select another day.

**Comment by flytoj2ee** [comment]
I think the current implementation meets the issue description "current date should be selected in the calendar, and the “contest start date” field is filled with the current date.".

Do you mean to add different style to today?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#177
