### ISSUE TITLE
hour/minute can be changed to use dropdown list for Start Time

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#594]
Mac 10.9.4, FF 32
1. login as heffan
2. click “Contest creation wizard”
3. observe the Start Time fields

expected: hour and minute should also be dropdown lists for the user to choose, this will make the user experience better.

actual: see screenshot, user has to input hour and minute manually.

![qq20140915-29](https://cloud.githubusercontent.com/assets/4590317/4273523/931f8f5a-3ceb-11e4-8d8f-f4d2cbed1dae.jpg)

**Comment by clevertension** [comment]
I think it is fast to input "35" as minute than select from dropdown list

**Comment by skyhit** [comment]
yes, I agree.

**Comment by flytoj2ee** [comment]
Is the '12:00 AM' valid date?

I think it's valid according to http://en.wikipedia.org/wiki/12-hour_clock

**Comment by skyhit** [comment]
12:00 AM means midnight.

**Comment by skyhit** [comment]
no change needed.
