### ISSUE TITLE
Can't increment the numbers using arrows if we delete the numbers 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#595]
## Description

Can't increment the numbers using arrows if we delete the numbers 
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
In the LIGHT THEME
Click 'Contest Creation Wizard'
In the Step 01
Double click on the 'Registration Limit'
When the number is selected click DELETE
Now click Next
Now Click Up/Down arrow to increase the numbers
## Expected Result

Must fix the Issue; 
- Must increase the numbers when we click on the up/Down arrows
## Actual Result

Can't increment the numbers using arrows if we delete the numbers
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![47](https://cloud.githubusercontent.com/assets/4592712/4298584/02ddee00-3e26-11e4-84e0-e1e8e118b22e.png)
## Video

https://www.dropbox.com/s/mu18hs9x7yqpoh7/595.mp4?dl=0
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
since you delete it, it didn't know the current set.
