### ISSUE TITLE
'Select Contest Start Date' must --> 'Contest Start Date'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#596]
## Description

'Select Contest Start Date' must --> 'Contest Start Date'
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
In the LIGHT THEME
Click 'Contest Creation Wizard'
In the Step 01
Check the 'Select Contest Start Date' label
## Expected Result

Must fix the Issue; 
- 'Select Contest Start Date' must --> 'Contest Start Date'
- Because user can't select the dates from the pointed textbox, they are selecting via calender function
- The textbox is used to display the selected date, So label must display as 'Contest Start Date'
## Actual Result

'Select Contest Start Date'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![48](https://cloud.githubusercontent.com/assets/4592712/4273706/38a9054a-3ced-11e4-855c-1728edef3726.png)
## Bug Hunt

Contest Creation Wizard

**Comment by huangqun** [comment]
I don't think changing the text message is really necessary.
