### ISSUE TITLE
Even we disabled the 'Intermission and Challenge'; user can edit the numbers in those items

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#597]
## Description

Even we disabled the 'Intermission and Challenge'; user can edit the numbers in those items
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
In the DARK THEME
Click 'Contest Creation Wizard'
In the Step 03
Click 'Remove Intermission and Challenge'
Now double click on a textbox og 'Intermission' or 'Challenge'
Change the value
## Expected Result

Must fix the Issue; 
- Must restrict the editing function when user clicks 'Remove Intermission and Challenge'
## Actual Result

Even we disabled the 'Intermission and Challenge'; user can edit the numbers in those items
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.1 in Windows 7
## Image

![49](https://cloud.githubusercontent.com/assets/4592712/4275519/5376ce9c-3cfd-11e4-889a-a9897be3ea31.png)
## Bug Hunt

Contest Creation Wizard

**Comment by skyhit** [comment]
fixed.
