### ISSUE TITLE
Layout Issue when we sort the table from 'Defender (rating)' in Summary section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#60]
## Description

Layout Issue when we sort the table from 'Defender (rating)' in Summary section
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as reassembler/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer

In the 'Summary'
Click 'Defender (rating)'
## Expected result

Must fix the Issue. Must display sorting icon inline
## Actual result

Layout Issue when we sort the table from 'Defender (rating)' in Summary section
##  Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![24](https://cloud.githubusercontent.com/assets/4592712/3331533/a9c936d2-f7dd-11e3-8d99-6dd99e406056.png)

**Comment by skyhit** [comment]
not in scope to test.

**Comment by skyhit** [comment]
this is from prototype, as you can see no data at all.
