### ISSUE TITLE
Not able to register for SRM

### ISSUE THREAD

**Issue by lower-case** [cloudspokes/arena-web#600]
I am not able to register for SRM .At the time of registration an error comes and the registration ends but i am still unregistered. Please set this issue .It is very crucial .I loose the chance to compete in SRM due to this.

**Comment by skyhit** [comment]
is it because the registration is ended?

**Comment by lower-case** [comment]
@skyhit no it's not because that ,it is due to some error which come while registering .I tried to register when the registration was open

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#175
