### ISSUE TITLE
Display error on Conquest Challenge

### ISSUE THREAD

**Issue by rootelement** [cloudspokes/arena-web#605]
![capture](https://cloud.githubusercontent.com/assets/5400156/4322648/43d649b4-3f4a-11e4-85d6-f53d5eda4af7.JPG)

**Comment by ananthhh** [comment]
No steps to reproduce is given.
Am getting it without any problem. 
Where i can get conquest problem ?
I have tried with bigger test more than 2 lines as well.
![image](https://cloud.githubusercontent.com/assets/3583234/4594182/4b826f9a-508d-11e4-8c51-3b49e3373543.png)

**Comment by skyhit** [comment]
since we can not reproduce properly, let's leave it for this challenge.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#171
