### ISSUE TITLE
Error message is not displaying within the login container

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#609]
## Description

Error message is not displaying within the login container
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Don't fill anything, click Login
Fill only username, click login
Enter invalid username and password, click Login

Check the 
-'Password cannot be empty' 
- 'Username cannot be empty'
- 'Invalid username or password. Please try again.' messages
## Expected Result

Must fix the Issue, Error message must display within the login container
## Actual Result

Error message is not displaying within the login container
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/4349041/3ebf5a7a-41a6-11e4-8042-6c45201cda66.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
this position is fine.
