### ISSUE TITLE
Layout Issue in the Column 'Challenger (Rating)' in Summary section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#61]
## Description

Layout Issue in the Column 'Challenger (Rating)' in Summary section
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer

In the 'Summary'
Click 'Challenger (Rating)' in the second table
## Expected result

Must fix the Issue. Must display in one line (Check the above table)
## Actual result

Layout Issue in the Column 'Challenger (Rating)' in Summary section
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/3331561/0e9a06e0-f7de-11e3-93cf-2886973c9fd1.png)

**Comment by skyhit** [comment]
this is from prototype, as you can see no data at all.
