### ISSUE TITLE
'TopCoder' must 'topcoder in --> 'Login with your TopCoder account'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#610]
## Description

'TopCoder' must 'topcoder in --> 'Login with your TopCoder account'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Don't fill anything
Check the text in the login section 'Login with your TopCoder account'
## Expected Result

'TopCoder' must 'topcoder in --> 'Login with your TopCoder account'
## Actual Result

'TopCoder'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/4349044/523baa5e-41a6-11e4-961a-f231a76f84ae.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
seems to have been already fixed

**Comment by skyhit** [comment]
yes.
