### ISSUE TITLE
No period (.) in the error messages

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#611]
## Description

No period (.) in the error messages
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Don't fill anything, click Login
- 'Username cannot be empty'
  Fill only username, click login
  -'Password cannot be empty' 
## Expected Result

Must fix the issue, Need to have period at the end of the error message
## Actual Result

No period (.) in the error messages
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![3 1](https://cloud.githubusercontent.com/assets/4592712/4349046/5b4e10b4-41a6-11e4-85b9-ef5bf318b98f.png)
![3 2](https://cloud.githubusercontent.com/assets/4592712/4349047/5b546a4a-41a6-11e4-919a-28ddb669c601.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#166
