### ISSUE TITLE
'topcoder' term is differently used in the 'agreement' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#612]
## Description

'topcoder' term is differently used in the 'agreement' section
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Scroll the page below

Check the "By logging into the arena, you indicate your agreement to these terms as well as those specified in the TopCoder Terms of Service on our website."
Check --> "TopCoder Terms of Service on our website"
## Expected Result

Must fix the Issue, 'TopCoder' must --> 'topcoder'
## Actual Result

'TopCoder'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![4](https://cloud.githubusercontent.com/assets/4592712/4349050/6f7df266-41a6-11e4-9679-b49d99791294.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed
