### ISSUE TITLE
[$75] Login via Social Networks won't redirect the page to web arena

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#613]
## Description

Login via Social Networks won't redirect the page to web arena
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
In the Login
Login via Social Media (FB, Google +, Github, Twitter)
## Expected Result

Must fix the Issue, Must redirect the page to Web arena after login via social media
## Actual Result

Login via Social Networks won't redirect the page to web arena
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![5](https://cloud.githubusercontent.com/assets/4592712/4349051/77a025e0-41a6-11e4-8d99-10cb27881706.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#165
