### ISSUE TITLE
Login page is not displayed correct using IE

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#614]
Access application link http://tcqa1.topcoder.com/.

actual: login page is not displayed using IE.

expected: login page must be displayed.

see attachments!

**Comment by onetliviunicolae** [comment]
![ie](https://cloud.githubusercontent.com/assets/5114907/4347701/b3074196-4164-11e4-98d8-004d315bc2f7.png)
![browser-version](https://cloud.githubusercontent.com/assets/5114907/4347702/b827f8fa-4164-11e4-9252-81e24b2f109c.png)

**Comment by skyhit** [comment]
looks like networking issue to load styling files, like css, javascript etc.
