### ISSUE TITLE
Support link from bottom of page not works

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#615]
Access application link http://qa.arena.topcoder.com/#/a/home.

Use vertical scroll bar to the bottom of page.

Press on "support@topcoder.com".

actual: nothing happens.

expected: open email tool(Mozilla Thunderbird, Microsoft Outlook,... ) automatically from local computer and complete send field with "support@topcoder.com".

see attachment!

**Comment by onetliviunicolae** [comment]
![support](https://cloud.githubusercontent.com/assets/5114907/4347721/4057a936-4166-11e4-8309-d969e47e45f8.png)

**Comment by shubhendusaurabh** [comment]
its a local problem. user must configure his email client for this. on my computer thunderbird opens with the given email address with any problem

**Comment by skyhit** [comment]
yes, you are right.
