### ISSUE TITLE
Arena dashboard: contest schedule are not correct displayed.

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#616]
Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Competition Arena Dashboard, Active Contests section use page numbers 1,2,3.

actual: when select page number 3 layout of section is not fixed and is not displayed correct.

expected: display correct layout of page.

see attachment!

arena-dashboard.png
![arena-dashboard](https://cloud.githubusercontent.com/assets/5114907/4347765/daffc340-4168-11e4-9f6a-e5b93a94e83b.png)

**Comment by skyhit** [comment]
can not reproduce, possibly google font loading issue.

**Comment by onetliviunicolae** [comment]
this issue can be reproduced every time, no matter if browser cache is clear or not.
please test again this issue!

**Comment by onetliviunicolae** [comment]
please test again this issue because can be simulate every time!

**Comment by skyhit** [comment]
can you inspect the networking using developer tool, and see if it is unable to load google fonts from google?

**Comment by onetliviunicolae** [comment]
Yes, I will try right now!

**Comment by onetliviunicolae** [comment]
Now Active Contest section contain only one active contest(14.09 Puneet SRM3 is live!).
This looks fine, but in example from issue description multiple pages with contests was available.

**Comment by onetliviunicolae** [comment]
I used Firebug added in Mozilla Firefox and google fonts are added!

**Comment by skyhit** [comment]
in another of your screenshots, I can see that is displayed properly.

please try clean your browser cache.

**Comment by onetliviunicolae** [comment]
the same behavior even browser cache is clear!

**Comment by skyhit** [comment]
I can see you have no problem here see #802

**Comment by onetliviunicolae** [comment]
is not true, in #802 contest selected is 14.09 Release QA SRM 25 and in print screen from attachment is else contest (14.09 Release QA SRM 10).
please re test again!

**Comment by skyhit** [comment]
the behavior should be same.

**Comment by onetliviunicolae** [comment]
how the behavior should be the same if there is a bug?

**Comment by skyhit** [comment]
I mean the setup for both SRMs are same. so it is possible, your browser didn't load the google font properly, or have any other problem, since I can not reproduce it, I checked with several machines.
