### ISSUE TITLE
logo properly display 

### ISSUE THREAD

**Issue by karthikbecse** [cloudspokes/arena-web#617]
while changing resolution of the browser topcoder logo not properly display 

click the link http://qa.arena.topcoder.com/#/a/home
minimize  browser  (resolution below 600px )

Actual result
topcoder logo image not display properly

expected result 
topcoder logo should display well

Browser version

Firefox 32.0.2

Windows 7 

![logo](https://cloud.githubusercontent.com/assets/3225433/4347773/32a771e2-4169-11e4-90f3-2cd2ea52d7b6.png)

**Comment by ananthhh** [comment]
Getting problem when window become too small
![image](https://cloud.githubusercontent.com/assets/3583234/4594039/02b0e9aa-508c-11e4-8e8e-a6fd7b42b9f4.png)

If it is too small, lets display only symbol like below ?
![image](https://cloud.githubusercontent.com/assets/3583234/4594063/34c413c2-508c-11e4-9a15-a00eeb7b77e5.png)

**Comment by skyhit** [comment]
yes.

**Comment by skyhit** [comment]
fixed.
