### ISSUE TITLE
System word is not match in chat room after uppercase

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#618]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Press on search icon in Chat Room section.

Check Match Case checkbox.

Complete field with "system".

actual: System words are not match.

expected: ignore upercase letters.

see attachments!

1.png
2.png
3.png

**Comment by onetliviunicolae** [comment]
![1](https://cloud.githubusercontent.com/assets/5114907/4347795/0fb9d0ec-416b-11e4-9156-182a73233d86.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4347796/17b6392a-416b-11e4-9525-72b3a2118607.png)
![3](https://cloud.githubusercontent.com/assets/5114907/4347797/1c533b4a-416b-11e4-962b-456ed7cac026.png)

**Comment by skyhit** [comment]
you checked Match case.
