### ISSUE TITLE
Dashboard: contest summary is not available

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#619]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Dashboard, Active Contests section select Contest Summary.

actual: no information in contest summary section for any available contests.

expected: display contest summary details.

see attachment!

contest-summary.png
![contest-summary](https://cloud.githubusercontent.com/assets/5114907/4347815/a7e42ef8-416b-11e4-9244-462bc4e42d9d.png)

**Comment by skyhit** [comment]
there is nothing displaying now.
