### ISSUE TITLE
'Check All' won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#62]
## Description

'Check All' won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer

In the 'Room Leaderboard'
Click on the Score
Click 'Challenge' in the Coding Area
Click 'Check All'
## Expected result

Must fix the Issue. 'Check All' must work
## Actual result

'Check All' won't work
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![26](https://cloud.githubusercontent.com/assets/4592712/3331795/8249dbb8-f7e0-11e3-8a7f-e149c318e841.png)

**Comment by skyhit** [comment]
disabled in purpose
