### ISSUE TITLE
Chat Room: Drop down list is not correct displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#620]
```
Environment
```

---

Windows 7
## Mozilla Firefox 32.0.2

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand general drop down list in Chat Room section.

actual: items of drop down list are not correct displayed.

expected: display items of drop down list.

see attachment!

drop-down-list.png

**Comment by onetliviunicolae** [comment]
![drop-down-list](https://cloud.githubusercontent.com/assets/5114907/4347829/3dda49ba-416c-11e4-977e-b44ac387fe77.png)

**Comment by skyhit** [comment]
based on the screenshots, it is working.

**Comment by onetliviunicolae** [comment]
please test again, this issue is related to drop down list which is not displayed correct.
please re test this issue!

**Comment by skyhit** [comment]
what do you mean "not working"? a scrollbar is showing to scroll.

**Comment by onetliviunicolae** [comment]
not this is a problem, please see issue description the problem is here this " items of drop down list are not correct displayed.", as you can see in attachment the last item from drop down list(Question) is not all visible!

**Comment by skyhit** [comment]
you mean it is partially shown?  but we can use scrollbar to show it completely.

I don't think we need to fix that.

**Comment by onetliviunicolae** [comment]
ok, thank you for response!
