### ISSUE TITLE
Add a space between tc time and hours

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#621]
Environment

---

Windows 7
Mozilla Firefox 32.0.2

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

actual: TC TIME 00:00:00 AM GMT+0000 are very nearly.

exepcted: add a space between TC TIME and text to be more intuitive.

see attachment!

tc-time.png

**Comment by onetliviunicolae** [comment]
![tc-time](https://cloud.githubusercontent.com/assets/5114907/4347842/5c180bf0-416d-11e4-807a-1fcb1d4be393.png)

**Comment by skyhit** [comment]
not need.

**Comment by onetliviunicolae** [comment]
why?
do you like how is displayed now?
an user must not understand!

**Comment by skyhit** [comment]
it is design decision, we are just following the storyboard.

**Comment by onetliviunicolae** [comment]
maybe in storyboard is buggy!

**Comment by skyhit** [comment]
I can not say maybe.

but if you are good at design, please join the design competitions and help us to provide better designs.
