### ISSUE TITLE
“Division 1” should not be shown in the division summary if it’s only a “Div 2” contest

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#622]
Mac 10.9.4
1. login
2. register the contest
3. go into a room, wait for a contest starts
4. when the contest coding phase starts, click to view division summary

expected: “Division 1” should not be shown in the division summary if it’s only a “Div 2” contest

actual: see screenshot

**Comment by skyhit** [comment]
it is not div 2 only challenge.  problems are assigned for both division
