### ISSUE TITLE
Validation summary missing

### ISSUE THREAD

**Issue by karthikbecse** [cloudspokes/arena-web#623]
click here 
 http://qa.arena.topcoder.com/#/a/home
click login (without user name and password)

see error message
"Username cannot be empty"
Expected result:
"Username and password cannot be empty"

validation  messages  should include collect all the error messages and display 

Actual Result 
only one error message display

Environment
Windows 7 32 bit 
Mozilla Firefox 32.0.2
Google Chrome Version 37.0.2062.120 m

![login](https://cloud.githubusercontent.com/assets/3225433/4347890/ba8a3e4e-4170-11e4-9434-22be3ea202a5.png)

**Comment by skyhit** [comment]
if we meet the first problem, validation is stopped.
