### ISSUE TITLE
Filtration after not rated not works

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#624]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m

---

Description

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Rating Key section.

Select Non-Rated option.

actual: no results.

expected: display only users without rating(ex: onetliviu.nicu, testnithya).

see attachments!

1.png

2.png
![2](https://cloud.githubusercontent.com/assets/5114907/4347911/8ad44cd8-4172-11e4-8db9-9c24fa1719df.png)

![1](https://cloud.githubusercontent.com/assets/5114907/4347910/826b305c-4172-11e4-9dd7-5d58293c7156.png)

**Comment by skyhit** [comment]
no such functionality, the Rating key part are information only
