### ISSUE TITLE
When select replay to is not necessary to display in drop down list logged user

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#625]
Environment

---

Windows 7
Mozilla Firefox 32.0.2Chrome 35.0.1916.114 dev-m

---

Description

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Chat Room section set first filter drop down list as Replay To.

Expand the second drop down list.

actual: logged user is available and can be selected(ex: onetliviu.nicu).

expected: do not display logged user in drop down list because is not necessary.

see attachment!

1.png
![1](https://cloud.githubusercontent.com/assets/5114907/4347917/2d3d7e36-4173-11e4-98c3-6f6f1097d07d.png)

**Comment by skyhit** [comment]
duplicated with #626
