### ISSUE TITLE
[$50] General behavior for room filters is not correct

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#626]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Chat Room section select any filter option(Question, Replay to and Whisper).

actual: logged issue is available and can be selected.

expected: do not display logged issue in drop down list.

see attachment!

1.png
2.png
3.png
![1](https://cloud.githubusercontent.com/assets/5114907/4347929/c9c71d48-4173-11e4-8b99-84efb6f2e33c.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4347930/ceb9c40e-4173-11e4-8c4e-004c8e24ecab.png)
![3](https://cloud.githubusercontent.com/assets/5114907/4347931/d316c524-4173-11e4-99b4-2d1600361537.png)

**Comment by onetliviunicolae** [comment]
related to this issue!
this can be considered as three issues because is a general case with three different behaviors.
1.question
2.replay to
3.whisper

If I would be logged three different issues for every case you accepted each case so please set payment according!

For this issue you must set 15$!

**Comment by skyhit** [comment]
I can not agree, it is common case.  I am count it as valid issue, but it can be invalid, if you check arena applet.

**Comment by onetliviunicolae** [comment]
is valid yes.
this contain 3 different cases.
I colud log 3 different issue for every case.
that means 15$.
I put a general case in one issue but this must be paid with 15$.

**Comment by skyhit** [comment]
I can not agree, if you think it is fit for three cases, please log as three issues in the future. otherwise, I can not consider it as 3 issues. the payment is not proceed and determined by me.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
