### ISSUE TITLE
Active Contests: do not display as hand over when mouse over selected tab

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#627]
Environment

---

Windows 7
## Mozilla Firefox 32.0.2

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering Contest Schedule selected mouse over this.

actual: hand mouse is displayed.

expected: do not display as hand when mouse over selected tab.

see attachment!

1.png
![1](https://cloud.githubusercontent.com/assets/5114907/4347945/8f6000a6-4174-11e4-8d3b-356fa9d3d250.png)

**Comment by skyhit** [comment]
using hand mouse is fine.

**Comment by onetliviunicolae** [comment]
is not necessary to display as hand once tab is selected.
any user may think as tab is not displayed.
please review this issue!
