### ISSUE TITLE
Share icons are not working

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#628]
## Description

Share icons are not working
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Coding phase
Click ENTER
Click the 'Share +' icon
## Expected Result

Must fix the Issue, Must open the pop up
## Actual Result

Share icons are not working
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![6](https://cloud.githubusercontent.com/assets/4592712/4347947/b3a126ca-4174-11e4-97b4-ee0d065b3aaf.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
it is not implemented
