### ISSUE TITLE
Layout issue in the 'Points' Column in Challengers

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#629]
## Description

Layout issue in the 'Points' Column in Challengers
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
Click 'View Details' in the Room
In the 'Challengers' Table
Click 'Points'
## Expected Result

Must fix the Issue, Must display the sorting icon right of the text
## Actual Result

Layout issue in the 'Points' Column in Challengers
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![7](https://cloud.githubusercontent.com/assets/4592712/4349054/87b20142-41a6-11e4-8a83-4de1cbbdf711.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#164
