### ISSUE TITLE
'Search' and 'Go To' won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#63]
## Description

'Search' and 'Go To' won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer

In the 'Room Leaderboard'
Click on the Score
Enter some text in the Search and press enter
Type some value in the 'Go To' and press Enter
## Expected result

Must fix the Issue. 'Search' and 'Go To' Must work
## Actual result

'Search' and 'Go To' won't work
##  Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![27](https://cloud.githubusercontent.com/assets/4592712/3332124/61e9ee1e-f7e3-11e3-8bb4-1d34430f064e.png)

**Comment by skyhit** [comment]
not implemented yet.
