### ISSUE TITLE
[$50] Layout issue in the 'R' Column in Challengers

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#630]
## Description

Layout issue in the 'R' Column in Challengers
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
Click 'View Details' in the Room
In the 'Challengers' Table
Click 'R'
## Expected Result

Must fix the Issue, Must display the sorting icon right of the text
## Actual Result

Layout issue in the 'R' Column in Challengers
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![8](https://cloud.githubusercontent.com/assets/4592712/4349055/91c3efce-41a6-11e4-978c-6c7f099b0aec.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
