### ISSUE TITLE
Can;t get info of the user

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#631]
## Description

Can;t get info of the user
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
Click 'View Details' in the Room
In the 'Challengers' Table or 'Challenges' Table
Click on a username
## Expected Result

Must fix the Issue, Must display the user info
## Actual Result

Can;t get info of the user
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/4349057/9be4ffca-41a6-11e4-89f7-b2bdc6e5f239.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
possibly server side problem to process the request.
