### ISSUE TITLE
[$50] Leaderboard: keep vertical scroll bar fixed when select an item

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#632]
Environment

---

Windows 7
Mozilla Firefox 32.0.2

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Leaderboard section.

Expand Rounds drop down list and select the last item from list.

Close drop down list item.

Expand again drop down list.

actual: vertical scroll bar position is set to the first item from list.

expected: keep the same position of drop down list(the last item) when expand list second time.

see attachment!

1.png

2.png
![1](https://cloud.githubusercontent.com/assets/5114907/4347960/fa620ce0-4175-11e4-8bb0-20a51d7e50c7.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4347961/fe7712b2-4175-11e4-9888-623c837390dd.png)

**Comment by gus-costa** [comment]
working

**Comment by huangqun** [comment]
fixed
