### ISSUE TITLE
'Coder history window is not center align with in the window

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#633]
## Description

'Coder history window is not center align with in the window
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
Click 'Coder History' icon in the Room Leaderboard section
Check the position
## Expected Result

Must fix the Issue, Must center align with in the window
## Actual Result

'Coder history window is not center align with in the window
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![10](https://cloud.githubusercontent.com/assets/4592712/4349059/a5421b7a-41a6-11e4-8a3a-cefc2517fdb5.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by flytoj2ee** [comment]
In above section, it says "Coder history window is not center align with in the window".

What's the "Coder history window is not center align" mean?

The content in coder history window? Or the coder history window itself?

**Comment by skyhit** [comment]
it is about coder history window.

**Comment by skyhit** [comment]
fixed.
