### ISSUE TITLE
[$50] Last record bottom line is not displayed in the table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#634]
## Description

Last record bottom line is not displayed in the table
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
Click 'Coder History' icon in the Room Leaderboard section
Check the Table
## Expected Result

Must fix the Issue, Must display the last row bottom line
## Actual Result

Last record bottom line is not displayed in the table
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![11](https://cloud.githubusercontent.com/assets/4592712/4349061/af202a42-41a6-11e4-812f-4e675a9a6804.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
![image](https://cloud.githubusercontent.com/assets/6045894/4770599/6f7d4c08-5b87-11e4-80f5-6d6818b7c377.png)

not fixed

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
