### ISSUE TITLE
Layout issue in the table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#635]
## Description

Layout issue in the table
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
In the Room Leaderboard section
Check the Table (Check the Long username row)
There are double lines (Marked in the screen shot)
## Expected Result

Must fix the Issue, Must not display two lines in a row
## Actual Result

Layout issue in the table
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/4349062/bb382e2e-41a6-11e4-838b-fc52a38232e0.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
this is valid for special case.
