### ISSUE TITLE
Active Users: active user is available even has left the room

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#636]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Active Users section.

actual: an user which has left the room is displayed as active.

exepcted: display only active users in Active Users section.

see attachment!

![active-users](https://cloud.githubusercontent.com/assets/5114907/4347969/8a5a689c-4176-11e4-934a-a61ca31b0393.png)
active-users.png

**Comment by skyhit** [comment]
this is correct. active users list are whole site even you are in different rooms.

**Comment by onetliviunicolae** [comment]
users are not in different rooms there, user is in the same room.
please review again this issue!

**Comment by skyhit** [comment]
the active user list has to to manually refreshed. we don't expect it automatically refreshed.

**Comment by onetliviunicolae** [comment]
ok, I understand!
