### ISSUE TITLE
[$50] Go To line is not working

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#637]
## Description

Go To line is not working
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
In the Room Leaderboard section
Click on a score
Enter line number in the GO TO
Click ENTER
## Expected Result

Must fix the Issue, Go To line must work
## Actual Result

Go To line is not working
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
@huangqun i remember seeing similar issue with hotfix label. this has already been fixed in dev branch

**Comment by huangqun** [comment]
Yes, it was fixed.
