### ISSUE TITLE
[$50] Layout Issue in the Rating section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#638]
## Description

Layout Issue in the Rating section
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
In the Room Leaderboard section
Click on a score
Check the rating section
## Expected Result

Must fix the Issue, 
## Actual Result

Layout Issue in the Rating section
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![13](https://cloud.githubusercontent.com/assets/4592712/4349068/0216a5f0-41a7-11e4-8198-28a20ab6e5dc.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
@huangqun fixed already

**Comment by huangqun** [comment]
fixed
