### ISSUE TITLE
Layout Issue in the 'Problem Area'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#639]
## Description

Layout Issue in the 'Problem Area'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
In the Room Leaderboard section
Click on a score
Scroll down the Problem Area
Copyright section is mixed with the problem
## Expected Result

Must fix the Issue, Copyright section must not mixed with the problem
## Actual Result

Layout Issue in the 'Problem Area'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/4349071/1d4201b2-41a7-11e4-8ab3-0d630278ff5e.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
