### ISSUE TITLE
'Config' button won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#64]
## Description

'Config' button won't work
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer

In the 'Room Leaderboard'
Click on the Score
Click on the 'Config' button 
## Expected result

Must fix the Issue. 'Config' button Must work
## Actual result

'Config' button won't work
##  Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/3332159/dfc0b6ec-f7e3-11e3-84b0-2db24581e459.png)

**Comment by skyhit** [comment]
for your case, it is expected, view code only mode.
