### ISSUE TITLE
Empty 'Problem Area' displayed when we expand it and then collapse it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#640]
## Description

Empty 'Problem Area' displayed when we expand it and then collapse it
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the Challenge phase
In the Room Leaderboard section
Click on a score
Expand the Problem Area
Scroll down
Collapse the Problem Area
## Expected Result

Must fix the Issue, 
## Actual Result

Empty 'Problem Area' displayed when we expand it and then collapse it
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![16](https://cloud.githubusercontent.com/assets/4592712/4349072/286b9a62-41a7-11e4-9565-5f89a6e66ce7.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed
