### ISSUE TITLE
Username must display in one line

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#641]
## Description

Username must display in one line
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
Click 'View Details' from Room Tab in Summary Table
Check the 'Challenges' Table
eg: sdgunqabughunt1
## Expected Result

Must fix the Issue, eg: sdgunqabughunt1 (this is the max length of the username) 15chars
So must adjust the table according to this.
## Actual Result

Username must display in one line
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/4349075/385c4778-41a7-11e4-8dcf-280db7996f03.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
What will be the max characters allowed for username ?

**Comment by skyhit** [comment]
based on schema setting, it can be 50 at max.

**Comment by ananthhh** [comment]
50 characters won't fit in that area. Lets put scrollbar to x-axis for whole table when there is long names ?

**Comment by skyhit** [comment]
yes, if needed

**Comment by amethystlei** [comment]
Now the header and the content of the table are independent. If put scrollbar to x-axis for the whole table then the header won't align with the content. And if we merge the header and the content, the header won't fix on top when scroll in y-axis. Is this acceptable?

**Comment by ananthhh** [comment]
I too facing the same problem. I believe there won't be much users with long username like this. If they have long username lets wrap it like this which looks much better than putting scrollbar in x-axis.
Also it will be annoying for users to scroll along x-axis.
Please advice
EDIT: To add to my point, there will be long list of challenges and users have to scroll long way down to find x-axis scroll bar which is much more annoying

**Comment by skyhit** [comment]
if so, I think adding x-axis scrollbar is not a good solution.

please use wrap approach.

**Comment by skyhit** [comment]
fixed.
