### ISSUE TITLE
'Coder History' pop up will flicker when we open it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#642]
## Description

'Coder History' pop up will flicker when we open it
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
Click 'View Details' from Room Tab in Summary Table
Check the 'Room Leaderboard' Table
Click 'Coder History' icon

NOTE: Competition Status must : Preparing for System Test Phase !!! Important
## Expected Result

Must fix the Issue, Must not flicker
## Actual Result

'Coder History' pop up will flicker when we open it
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

Can't provide a s clear screen shot for this
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
not a problem.
