### ISSUE TITLE
Competition Arena: no message when filter for unexisting specific handle

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#643]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests select page 6.

Press Enter.

For Room press View Details.

Select Challengers -> Filter.

From Show drop down list select Specific Handle.

Complete Handle with "test" as example.

Press Filter.

actual: no message related to filter after unexisting user.

expected: return a message for invalid filtration(ex: no user with this name).

see attachment!

1.png

2.png
![1](https://cloud.githubusercontent.com/assets/5114907/4348013/76f856bc-4179-11e4-8653-f8a858a9af88.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4348014/7bb18fd4-4179-11e4-9b20-7f3e1015fe20.png)

**Comment by skyhit** [comment]
not needed.

**Comment by onetliviunicolae** [comment]
why you not consider this as an issue?
any user can think is not correct to not display a message once no result is displayed!

**Comment by onetliviunicolae** [comment]
please add a comment!
