### ISSUE TITLE
Summary: points tab is not aligned

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#644]
Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests select page 6.

Press Enter.

For Room press View Details.

actual: Points tab name is not aligned.

expected: tabs must be aligned.

see attachment!

points.png
![points](https://cloud.githubusercontent.com/assets/5114907/4348017/cf192e3e-4179-11e4-9faa-0c8df69ed66d.png)

**Comment by onetliviunicolae** [comment]
Notes

Points tab change position when is selected!

**Comment by skyhit** [comment]
duplicated.
