### ISSUE TITLE
Filter is not clear when is close window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#645]
Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests select page 6.

Press Enter.

For Room press View Details.

Press Filter tab.

Select Specific Handle and set a name(ex: test).

Press Filter button.

Press again on Filter tab.

actual: filtration is displayed as specific handle and test name.

expected: display filter as Show = All Handles.

see attachment!

filter.png
![filter](https://cloud.githubusercontent.com/assets/5114907/4348029/8dc3c4b6-417a-11e4-908e-6f3b0e5cf86d.png)

**Comment by skyhit** [comment]
not needed.
