### ISSUE TITLE
[$50] 'Arrows' are not aligned with the scroll bars

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#647]
## Description

'Arrows' are not aligned with the scroll bars
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the 'Chat Room'
Check the scroll bars in the 'Who's here (x) and Main chat window
## Expected Result

Must fix the Issue, Must align with scroll bars
## Actual Result

'Arrows' are not aligned with the scroll bars
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![20](https://cloud.githubusercontent.com/assets/4592712/4349085/77a87a96-41a7-11e4-9846-294d48494e8b.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by clevertension** [comment]
i am working on it

**Comment by huangqun** [comment]
fixed
