### ISSUE TITLE
NO 'Arrows' in the Rating Key section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#648]
## Description

NO 'Arrows' in the Rating Key section
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the 'Chat Room'
Check the scroll bars in the 'Rating Key' section
## Expected Result

Must fix the Issue, Must insert that section also
## Actual Result

NO 'Arrows' in the Rating Keys section
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/4349086/7d670394-41a7-11e4-841b-7a1c736b6f97.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
not needed, arrow are used for special case.
