### ISSUE TITLE
[$50] Small ORANGE DOT Appears near the bottom section of the scroll bar

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#649]
## Description

Small ORANGE DOT Appears near the bottom section of the scroll bar
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the 'Chat Room'
Check the bottom section of the scroll bars
## Expected Result

Must fix the Issue, Must remove it
## Actual Result

Small ORANGE DOT Appears near the bottom section of the scroll bar
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/4349089/8b7d1d24-41a7-11e4-9169-4baa7d3a9a4e.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
