### ISSUE TITLE
'Please wait for test info' Message is not displayed to the user

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#65]
## Description

'Please wait for test info' Message is not displayed to the user
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Submit a answer
In the 'Coding Area'
Click on the 'Test Panel'
check the pop up
## Expected result

Must fix the Issue. Must display 5-10sec
## Actual result

'Please wait for test info' Message is not displayed to the user
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![29](https://cloud.githubusercontent.com/assets/4592712/3332664/03db75e8-f7ea-11e3-980d-be1f37d09410.png)

**Comment by skyhit** [comment]
this dialog is displayed if it is slow to retrieve the test info
