### ISSUE TITLE
[$50] Layout Issue in the 'Results' Column in Challenges Table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#650]
## Description

Layout Issue in the 'Results' Column in Challenges Table
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the 'Rooms' click View Details
Now click the 'Results' column in Challenges Table

NOTE: You must have some records to recreate it
## Expected Result

Must fix the Issue, Must display the text and sort icon inline
## Actual Result

Layout Issue in the 'Results' Column in Challenges Table
## Environment

Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/4349091/95810178-41a7-11e4-86e5-c4152a847d33.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
