### ISSUE TITLE
[$50] Coder History: do not display vertical scroll bar when open pop up window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#651]
Environment

---

Windows 7
Mozilla Firefox 32.0.2

---

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests select page 6.

Press Enter.

For Room press View Details.

From Room Leaderboard press on coder history sign for any available user.

actual: a pop up window is displayed with user details and on page vertical scroll bar is available.

expected: do not display vertical scroll bar when open Coder History pop up window.

see attachment!

1.png
2.png
![1](https://cloud.githubusercontent.com/assets/5114907/4348056/63f3479a-417c-11e4-9bc2-051a1acda9dd.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4348058/68a464a4-417c-11e4-801e-c59f67a6d2ea.png)

**Comment by skyhit** [comment]
it is based on page height. seems it is required.

**Comment by onetliviunicolae** [comment]
when Coder History popup window is open vertical scroll bar is not necessary to be displayed.
please review this issue!

**Comment by skyhit** [comment]
ok, reopen to look into the issue.

**Comment by shubhendusaurabh** [comment]
@huangqun looks like already fixed
![screenshot from 2014-10-29 01 44 48](https://cloud.githubusercontent.com/assets/1818387/4816411/67a34bbc-5edf-11e4-9f7d-04f80f02f10c.png)

**Comment by shubhendusaurabh** [comment]
above screenshot is for chrome. same behaviour on firefox

**Comment by huangqun** [comment]
fixed
