### ISSUE TITLE
[$50] Layout Issue in the first row in Challenges Table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#652]
## Description

Layout Issue in the first row in Challenges Table
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the 'Rooms' click View Details
Now click the 'Results' column in Challenges Table

NOTE: You must have some records to recreate it
## Expected Result

Must fix the Issue, Must match the length of the first row lines with the others
## Actual Result

Layout Issue in the first row in Challenges Table
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![24](https://cloud.githubusercontent.com/assets/4592712/4349093/9e3b06b0-41a7-11e4-9433-ddd2f53432ab.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
@shubhendusaurabh I'm still seeing this issue in the latest bugbounty-2 branch.

**Comment by shubhendusaurabh** [comment]
@huangqun this is what i see on latest bugbounty-2 branch on chrome
![screenshot from 2014-10-25 18 47 46](https://cloud.githubusercontent.com/assets/1818387/4779840/89234f0a-5c49-11e4-8f11-4c81a07b9a96.png)
same on firefox

**Comment by huangqun** [comment]
You were right, fixed.
