### ISSUE TITLE
[$50] Coder History: display popup window in the middle of page

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#653]
Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests select page 6.

Press Enter.

For Room press View Details.

From Room Leaderboard press on coder history sign for any available user.

actual: popup window is display to the bottom of page.

expected: display popup window in the middle of page.

see attachment!

1.png

**Comment by onetliviunicolae** [comment]
![1](https://cloud.githubusercontent.com/assets/5114907/4348075/06b9b018-417d-11e4-88ba-6095c3d834ba.png)

**Comment by huangqun** [comment]
fixed
