### ISSUE TITLE
Summary: search functionality not works

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#654]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m

---

Access application link http://qa.arena.topcoder.com.

Use own credentials to login.

Select page 6 as example in Active Contests section.

Press Enter.

Press View Details(in Room tab).

For Challengers use search icon glass.

actual: nothing happens when are pressed.

expected: add functionality for search or do not display this option for users.

see attachment!

search.ppt
![search](https://cloud.githubusercontent.com/assets/5114907/4348087/bbfd723e-417d-11e4-9c70-3ca3bc9fe368.png)

**Comment by skyhit** [comment]
it is working, it seems not working because of the data, there is only one Challenger.

**Comment by onetliviunicolae** [comment]
if only one challenger why appear icon there?
please review again this issue!
