### ISSUE TITLE
Competiton Arena: do not change postion of tab name

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#655]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests select page 6.

Press Enter.

Press View Details option(available in Room tab).

In second challenges try to sort ASC / DESC "Result" column.

actual: tab name Result change position and arrow is displayed under tab name.

expected: do not change position of tab name when try to sort.

see attachment!

result-tab.png
![result-tab](https://cloud.githubusercontent.com/assets/5114907/4348095/6964d11a-417e-11e4-9943-f9933a08fbe8.png)

**Comment by skyhit** [comment]
duplicated.
