### ISSUE TITLE
Drop down won't automatically closing when we click on a item

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#656]
## Description

Drop down won't automatically closing when we click on a item
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Expand the 'Leaderboard'
Click the drop down and select item
## Expected Result

Must fix the Issue, Must match the length of the first row lines with the others
## Actual Result

Drop down won't automatically closing when we click on a item
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/4349095/b220d3e4-41a7-11e4-86f4-3f37a32f59b9.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#163
