### ISSUE TITLE
Scroll bar won't work via Arrows in 'Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#657]
## Description

Scroll bar won't work via Arrows in 'Leaderboard'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Expand the 'Leaderboard'
Click the drop down and click Arrows in the Drop Down
## Expected Result

Must fix the Issue, Must up/Down items through arrows
## Actual Result

Scroll bar won't work via Arrows in 'Leaderboard'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![26](https://cloud.githubusercontent.com/assets/4592712/4349097/bc55d936-41a7-11e4-8edc-c56bb3e0a007.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#162
