### ISSUE TITLE
[Common] Need to have a default Sorting Column in Tables [ Active Users, Leaderboard ]

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#658]
## Description

[Common] Need to have a default Sorting Column in Tables [ Active Users, Leaderboard]
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Expand the 'Leaderboard' OR 'Active Users'
Check the Tables

Now click ENTER
Click 'View Details' from ROOMS
Check the 'Challengers', 'Challenges' and 'Room Leaderboard'
They have default Sorting Column
## Expected Result

Must fix the Issue, Need to have a default Sorting Column in Tables
## Actual Result

NO default Sorting Column in Tables
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Images

![27 1](https://cloud.githubusercontent.com/assets/4592712/4349099/cd4fe8e4-41a7-11e4-8c48-ab1d0317861f.png)
![27 2](https://cloud.githubusercontent.com/assets/4592712/4349100/cd59fa78-41a7-11e4-8224-f825a5480da7.png)
![27 3](https://cloud.githubusercontent.com/assets/4592712/4349101/cd5d45ca-41a7-11e4-83f7-44c63b017551.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#161
