### ISSUE TITLE
[Common][Orange Theme] Parameters are not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#659]
## Description

[Common][Orange Theme] Parameters are not visible
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER
Click 'View Details' from ROOM
Click on a score in Room Leaderboard
Chek the parameters on top
## Expected Result

Must fix the Issue, Must display parameters in BLACK
## Actual Result

Parameters are not visible
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/4349103/d6728e9a-41a7-11e4-948e-b7bd8bfd4455.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#160
