### ISSUE TITLE
Incorrect warning message

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#66]
## Description

Incorrect warning message
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Open the Problem
Input a code and then 'Compile' and 'Submit'

Click 'Back to Contest'
Now click 'Back to Contest'
Click 'Open' in the Challenge Area
Click 'Submit'

You have made a change to your code since the last time you compiled. Do you want to continue with the submit?
## Expected result

Must fix the Issue. Must change the message, because user won't change any code
## Actual result

Incorrect warning message
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/3332750/d3f5391c-f7ea-11e3-8895-cb622abb2201.png)

**Comment by skyhit** [comment]
is this in challenge phase?

**Comment by skyhit** [comment]
is this in challenge phase?

**Comment by sdgun** [comment]
Yes

**Comment by flytoj2ee** [comment]
In coding phase, trying to submit the code again will get this warning message.

What's the suggestion about message?

**Comment by skyhit** [comment]
even without change?

**Comment by flytoj2ee** [comment]
Yes, it cannot know the coding status in client side.

In server side, it'll consider it as second time submit even if it doesn't change.

**Comment by skyhit** [comment]
what is used to determine compiled or not compiled? last compile time?

**Comment by flytoj2ee** [comment]
I added a checking flag in client side to fix this issue.
