### ISSUE TITLE
[Common] Date Issue in the Notification panels

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#660]
## Description

[Common] Date Issue in the Notification panels
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Wait till the System Test Phase starts
When we notifications are displayed 
Check the date : 01/01/70
## Expected Result

Must fix the Issue, Must display the correct date
## Actual Result

01/01/70
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![29](https://cloud.githubusercontent.com/assets/4592712/4349120/7078899a-41a8-11e4-8b3c-e0001d6e9a77.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#159
