### ISSUE TITLE
[$50] [Common] If we don't close Notification they are not closing automatically

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#661]
## Description

[Common] If we don't close Notification they are not closing automatically
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Wait till 10 or more notifications --> Don't close any
You can see last notifications can't see
## Expected Result

Must fix the Issue, Must close the old ones automatically
- If we won't close them manually last notifications are hidden
## Actual Result

If we don't close Notification they are not closing automatically
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/4349121/7663eec6-41a8-11e4-8491-70a9eecbca81.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
