### ISSUE TITLE
[Common] 'Contest Complete' must --> 'Contest is Completed' 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#662]
## Description

[Common] 'Contest Complete' must --> 'Contest is Completed' 
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Wait till contest completed
http://qa.arena.topcoder.com/#/u/contests/16155
Check the Status
## Expected Result

Must fix the Issue, 'Contest Complete' must --> 'Contest is Completed' or 'Contest Completed'
## Actual Result

'Contest Complete'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![31](https://cloud.githubusercontent.com/assets/4592712/4349167/216df284-41aa-11e4-8204-c697bfc01e06.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#158
