### ISSUE TITLE
Dashboard: do not display vertical arrows

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#663]
Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Dashboard page try to collapse Profile Overview & Important Message.

actual: nothing happens.

expected: do not display vertical arrow if section can not be collaped.

see attachment!

arrow.png
![arrow](https://cloud.githubusercontent.com/assets/5114907/4348266/06de2658-4184-11e4-837a-c17da2186bdd.png)

---

Competition

**Comment by skyhit** [comment]
the opened section is for that panel.

**Comment by onetliviunicolae** [comment]
- I understand but if correct behavior is that Profile Overview & Important Messages section to be open why arrow is displayed(is useless to be displayed)!
  please review again this issue!

**Comment by skyhit** [comment]
this is following the design, and designer/PM are all agreed, so no change.

different people will have different opinion.

**Comment by onetliviunicolae** [comment]
ok
