### ISSUE TITLE
'Contest Complete Phase starts ..' in Notification section is wrong

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#664]
## Description

'Contest Complete Phase starts ..' in Notification section is wrong
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Wait till contest completed
Check the Status in the Notification
## Expected Result

Must fix the Issue, Contest Complete is not a phase so it must displays as '14.09 Release QA SRM 7: Contest Completed at 01/01/70 5:30 AM SLST'
## Actual Result

'Contest Complete Phase starts ..' in Notification section is wrong
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![32](https://cloud.githubusercontent.com/assets/4592712/4348264/f55a1c2a-4183-11e4-9bfa-44d7f5c157c2.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#157
