### ISSUE TITLE
Must hover the 'messages' tool tip infront of the 'Message' pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#665]
## Description

Must hover the 'messages' tool tip infront of the 'Message' pop up
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Click 'Message' Icon
Now Hover over the Message Icon
## Expected Result

Must fix the Issue, Must hover the 'messages' tool tip infront of the 'Message' pop up
## Actual Result

'messages' tool tip won't display infront of the 'Message' pop up
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![33](https://cloud.githubusercontent.com/assets/4592712/4348287/d999d830-4184-11e4-9fb5-0260b1256a7b.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Earlier we have removed 'Theme Switcher' tooltip which actually overlapped 'Theme Switcher' popup. Should we add that too now ? or it won't be consistent.

**Comment by skyhit** [comment]
just don't show the tooltip when the popup is present. it is not removal.

**Comment by ananthhh** [comment]
I mean don't show tooltip when popup is present. So shall i follow same logic here ?
In Bug its mentioned to put tooltip infront of popup. Thats why am confused.

**Comment by skyhit** [comment]
> > So shall i follow same logic here ? 

yes.

**Comment by skyhit** [comment]
fixed
