### ISSUE TITLE
Active Contests: prev and next link options are not available

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#666]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Dashboard page, Active Contests section select page numbers 1,2,3...

actual: next / prev navigation links are not available and an user must select page numbers.

expected: add next / prev navigation links.

see attachment!
## next_prev_links.png

Competition

**Comment by onetliviunicolae** [comment]
![next_prev_links](https://cloud.githubusercontent.com/assets/5114907/4348297/205d13cc-4185-11e4-99f5-36c89d83d097.png)

**Comment by skyhit** [comment]
not required to have.
