### ISSUE TITLE
'Broadcast information' Must --> 'Broadcast Information'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#667]
## Description

'Broadcast information' Must --> 'Broadcast Information'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Click 'Message' Icon
Click on a Notification
Check the Pop up
'Broadcast information' Must --> 'Broadcast Information'

Compare with the 'Broadcast Message'
## Expected Result

Must fix the Issue, 'Broadcast information' Must --> 'Broadcast Information'
## Actual Result

'Broadcast information'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![34](https://cloud.githubusercontent.com/assets/4592712/4348295/1c611b42-4185-11e4-947c-13382908781e.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#156
