### ISSUE TITLE
'Type chat' Must --> 'Type your message' in the Chat room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#668]
## Description

'Type chat' Must --> 'Type your message' in the Chat room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

In the Chat Room
Check the Default text in the Chat input box

'Type chat' Must --> 'Type your message' in the Chat room
OR
Left it blank as in the Arena Applet
## Expected Result

Must fix the Issue, 'Type chat' Must --> 'Type your message' in the Chat room
## Actual Result

'Type chat'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![36](https://cloud.githubusercontent.com/assets/4592712/4348314/dcb6ec32-4185-11e4-87fd-b7b752488e40.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
no confusion
