### ISSUE TITLE
[$50] [Orange Theme] Bottom container separator is not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#669]
## Description

[Orange Theme] Bottom container separator is not visible
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
In the Dashboard
Select the contest
Click ENTER

Expand the 'Profile Overview & Important Messages', 'Problem Based Training Area', 'Leaderboard' or 'Active Users (6)'
Check the bottom border 
## Expected Result

Must fix the Issue, Must display the bottom section border as other themes
## Actual Result

[Orange Theme] Bottom container seperator is not visible
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![37 1](https://cloud.githubusercontent.com/assets/4592712/4348325/523a9f80-4186-11e4-87f5-db6e59399295.png)
![37 2](https://cloud.githubusercontent.com/assets/4592712/4348326/5242340c-4186-11e4-8811-1d350e934cba.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
working on it
