### ISSUE TITLE
Info Message must change : Submission was successful for 75.00 points

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#67]
## Description

Info Message must change : Submission was successful for 75.00 points
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Yoshi/password

Meanwhile - Register for a contest
While the coding phase starts
Click ENTER (BLUE BUTTON)
When the coding Phase Started
Open the Problem
Input a code and then 'Compile' and 'Submit'

Click 'Back to Contest'
Now click 'Back to Contest'
Click 'Open' in the Challenge Area
Click 'Submit'
Click 'Yes'
Click 'Yes'
This will show a message that you will loose 10% of your score
Click 'Yes'

Now check the message
## Expected result

Must fix the Issue. Must : Submission was successful and scored 75.00 points.
## Actual result

Info Message must change : Submission was successful for 75.00 points
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![31](https://cloud.githubusercontent.com/assets/4592712/3332918/75e07ba0-f7ec-11e3-9d79-80021e62277f.png)

**Comment by skyhit** [comment]
same as arena applet.
