### ISSUE TITLE
'null' displayed in the Registration Terms:

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#670]
## Description

'null' displayed in the Registration Terms:
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Check the Pop up
## Expected Result

Must fix the Issue, Must display the Registration Terms:
## Actual Result

'null' displayed in the Registration Terms:
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![38](https://cloud.githubusercontent.com/assets/4592712/4348332/9e6646c0-4186-11e4-82a3-123ad4a3dc4d.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#155
