### ISSUE TITLE
'Registration Terms:' section border is touching the button seperator in FF

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#671]
## Description

'Registration Terms:' section border is touching the button seperator in FF
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Check the Pop up
Scroll Down
## Expected Result

Must fix the Issue, Must have some gap from the bottom as other browsers
## Actual Result

'Registration Terms:' section border is touching the button seperator in FF
## Environment

FF 32.0.2 in Windows 7
## Image

![39 1](https://cloud.githubusercontent.com/assets/4592712/4348351/6704f284-4187-11e4-85cd-a3aa2cf5cdb9.png)
![39 2](https://cloud.githubusercontent.com/assets/4592712/4348350/6701af66-4187-11e4-830e-55fd38298c28.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed
