### ISSUE TITLE
'If you believe this to be an error please try' must --> 'If you believe this is an error please try'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#672]
## Description

'If you believe this to be an error please try' must --> 'If you believe this is an error please try'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Pop up, Insert wrong answer
Click I Agree
Check the pop up validation

.... If you believe this to be an error please try again or contact your administrator.
## Expected Result

Must fix the Issue, 'If you believe this to be an error please try' must --> 'If you believe this is an error please try'
## Actual Result

'If you believe this to be an error please try'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![40](https://cloud.githubusercontent.com/assets/4592712/4348356/a76c63f2-4187-11e4-8986-581c6b971c80.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
This message is coming from backend. This requires back-end change.
back-end changes also in scope of this contest ?

**Comment by skyhit** [comment]
not needed, this is a simple change I can made. let's leave this out of scope for this challenge.

**Comment by skyhit** [comment]
fixed.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#154
