### ISSUE TITLE
'TopCoder' must --> 'topcoder'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#673]
## Description

'TopCoder' must --> 'topcoder'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Pop up
Check the 'Important Notice' description

'TopCoder' must --> 'topcoder'
## Expected Result

Must fix the Issue, 'TopCoder' must --> 'topcoder' an error please try'
## Actual Result

'TopCoder'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![41](https://cloud.githubusercontent.com/assets/4592712/4348371/25e565b2-4188-11e4-9612-51002822ba50.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#153
