### ISSUE TITLE
When there is a pop up overlay user can click on the REFRESH button in the 'Active Users (x)' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#674]
## Description

When there is a pop up overlay user can click on the REFRESH button in the 'Active Users (x)' section
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER

IMPORTANT : must expand the 'Active Users (5)' section before clicking the REGISTER
## Expected Result

Must fix the Issue, REFRESH button must display below the overlay
## Actual Result

When there is a pop up overlay user can click on the REFRESH button in the 'Active Users (x)' section
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![42](https://cloud.githubusercontent.com/assets/4592712/4348375/aea7fd42-4188-11e4-8d45-a558648783dc.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed
