### ISSUE TITLE
Keep first letter uppercase for information text

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#675]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering a message received related to registration phase press on message title.

actual: Round Broadcast popup window contain two section "Broadcast information" and "Broadcast Message".

expected: keep first letter from "information" as uppercase so modify in "Broadcast Information".
![information](https://cloud.githubusercontent.com/assets/5114907/4348390/82e9dd0a-4189-11e4-969a-69365f39a18a.png)

---

Competition

**Comment by skyhit** [comment]
duplicate.
