### ISSUE TITLE
[$5] Message (x) must --> 'Message(s) (x)

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#676]
## Description

Message (x) must --> 'Message(s) (x)
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Click on the Mesages icon
In the Pop up --> Message (x) must --> 'Message(s) (x)
## Expected Result

Must fix the Issue, Message (x) must --> 'Message(s) (x)
## Actual Result

Message (x) 
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![43](https://cloud.githubusercontent.com/assets/4592712/4348395/c35aad10-4189-11e4-8c88-e3c06ddb6ea3.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
