### ISSUE TITLE
Competition Arena: division text is readable

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#677]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests press Enter(supposed page 1 selected).

actual: Division I, II is not readable(i letter is to to much near v).

expected: Division I, II must be readable.

see attachment!

division.png
![division](https://cloud.githubusercontent.com/assets/5114907/4348412/43b9c8ce-418a-11e4-9692-54d1d9a21d28.png)

---

Competition

**Comment by skyhit** [comment]
should be font size problem. can not reproduce.

**Comment by onetliviunicolae** [comment]
Can you please test again this issue.
As you can see in print screen attached to this issue is very clear as Division text is not readable.
Anyway I can simulate this issue any time.
