### ISSUE TITLE
'Starts at' must --> 'Started at'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#678]
## Description

'Starts at' must --> 'Started at'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Click 'Contest Schedule'
Check the 'Registration Phase' Start time
## Expected Result

Must fix the Issue, 'Starts at' must --> 'Started at'
- Because 'Registration Phase' is already started
## Actual Result

'Starts at'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![44](https://cloud.githubusercontent.com/assets/4592712/4348414/5aab6cea-418a-11e4-9174-fc1b6c877bb1.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
it is based on coding phase.
