### ISSUE TITLE
Username is not displayed as link

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#679]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Try to press on username from the top right of page.

actual: username is not displayed as link.

expected: username must be displayed as link and when is accessed a redirect to profile page must be made.

see attachment!

username.png
![username](https://cloud.githubusercontent.com/assets/5114907/4348422/bb0753a6-418a-11e4-8273-b255a5f5400e.png)

---

Competition

**Comment by ananthhh** [comment]
No profile page is implemented yet. Should we display userinfo popup ?
But there is already profile information section in dashboard

**Comment by huangqun** [comment]
@skyhit, do you have any input on this one? Thanks!

**Comment by skyhit** [comment]
I think for current situation, just leave it no change.

**Comment by huangqun** [comment]
OK, we'll remove this one from the bug bounty then.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#152
