### ISSUE TITLE
Notification display order Issue in Chrome

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#680]
## Description

Notification display order Issue in Chrome
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till 5mins before contest starts
Check the notification

New Notification must list at the top --> In IE it is correct
But in Chrome, new ones are at the bottom
## Expected Result

Must fix the Issue, 
- Newest must display at top
## Actual Result

Notification display order Issue in Chrome
## Environment

Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![45 1-chrome](https://cloud.githubusercontent.com/assets/4592712/4348431/058d3a94-418b-11e4-8eff-6e6e977a1ebf.png)
![45 2-ie](https://cloud.githubusercontent.com/assets/4592712/4348432/05935564-418b-11e4-8010-10d06baac847.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
