### ISSUE TITLE
[$50] Country are not readable in registrants popup window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#681]
## Environment

Windows 7

Chrome 35.0.1916.114 dev-m

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering phase open.

Press on registrants for contest.

actual: all registrants are displayed in pop up window but countries are not readable.

expected: display country names as highlighted.

see attachment!

country.png
![country](https://cloud.githubusercontent.com/assets/5114907/4348439/68812ca0-418b-11e4-83f6-a66d0afdbef6.png)

---

Competition

**Comment by skyhit** [comment]
looks clear

**Comment by onetliviunicolae** [comment]
looks in the same way as how looks table columns.
do you think is ok to be displayed in this way?

**Comment by skyhit** [comment]
ok, I accept your suggestion, this header should better use a different color.

**Comment by onetliviunicolae** [comment]
ok, so this issue must be reopen!

**Comment by shubhendusaurabh** [comment]
@skyhit what color is to be used here? any suggestions?

**Comment by shubhendusaurabh** [comment]
@huangqun any update on my above question?

**Comment by huangqun** [comment]
Could you just use a different color for the column (except for header) and make sure it's easily changeable?

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
