### ISSUE TITLE
Coding phase starts 2nd Notification won't display properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#682]
## Description

Coding phase starts 2nd Notification won't display properly
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Check the notification
## Expected Result

Must fix the Issue, 
- Must display it properly
## Actual Result

Coding phase starts 2nd Notification won't display properly
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![46](https://cloud.githubusercontent.com/assets/4592712/4348440/714f2148-418b-11e4-94c3-c3464c9fb32d.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
<b>Coding Phase is starting for Test SRM - Test SRM Round.↵Would you like to go to your room now? </b>
Above is the message that's not displayed.
This also has yes or no links. If user clicks yes he will be taken to appropriate room. This should also be implemented ?

**Comment by skyhit** [comment]
that is out of scope for this issue.

**Comment by ananthhh** [comment]
Then lets simply not show this notification ?
It will be weird to show question to user without providing options

**Comment by skyhit** [comment]
no, if you can implement the functionality, I think it will be great.

**Comment by ananthhh** [comment]
I can implement this.
Shall i replace current notify plugin with http://notifyjs.com/
I have explained reasons in forum http://apps.topcoder.com/forums/?module=Thread&threadID=833905&start=0&mc=1#1933762
Or should i stick to existing one ?

**Comment by skyhit** [comment]
let's stick to existing one.

**Comment by skyhit** [comment]
fixed.
