### ISSUE TITLE
Rating is not displayed in the User info Box

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#683]
## Description

Rating is not displayed in the User info Box
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Click on the user in the Chat area
## Expected Result

Must fix the Issue, 
- Must display the rate (Because user have finished previous SRM and have Color rating)
- Must display the 'Rated events' also
## Actual Result

Rating is not displayed in the User info Box
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![47](https://cloud.githubusercontent.com/assets/4592712/4348452/07203d9c-418c-11e4-8db3-1edff53043c4.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
it is backend data processing problem.
