### ISSUE TITLE
Problem Area: invalid text displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#684]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contest consider Code Phase open.

Press Enter.

In Coding section press on "Opened" for a problem title available.

In Problem Area use scroll bar to see details.

actual: invalid text is displayed.

expected: do not display this invalid text.

see attachment!

a1.png

problem-area.png
![a1](https://cloud.githubusercontent.com/assets/5114907/4348463/8ae90834-418c-11e4-9ea0-b72c9d0fef43.png)
![problem-area](https://cloud.githubusercontent.com/assets/5114907/4348465/922d9c4a-418c-11e4-87fb-9514f361a01f.png)

---

Competition

**Comment by skyhit** [comment]
it is not. this is the example tests section
