### ISSUE TITLE
When user clicks on the 'topcoder ARENA beta', App logs out

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#685]
## Description

When user clicks on the 'topcoder ARENA beta', App logs out
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Click 'topcoder ARENA beta'
## Expected Result

Must fix the Issue, 
- Must not logout
## Actual Result

When user clicks on the 'topcoder ARENA beta', App logs out
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![48](https://cloud.githubusercontent.com/assets/4592712/4348467/999cb2fe-418c-11e4-88ad-1474c357f675.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
We should link to the dashboard - same as the home icon.

**Comment by skyhit** [comment]
fixed.
