### ISSUE TITLE
Display problem area more with greater width

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#686]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Press Opened for any available problem.

actual: problem area section is displayed with width too small.

expected: display problem area with more greater width.

see attachment!
![problem-area_001](https://cloud.githubusercontent.com/assets/5114907/4348475/2df24da6-418d-11e4-8989-0319a74f081f.png)
## problem-area_001.png

Competition

**Comment by skyhit** [comment]
actually, coding area is more important. currently split is fine.
