### ISSUE TITLE
Invalid Arg Types text displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#688]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Press Opened for any available problem.

actual: on the top of page Arg Types : (String[], int) is displayed.

expected: displayed correct types of arguments.

see attachment!

arg-types.png
![arg-types](https://cloud.githubusercontent.com/assets/5114907/4348492/9f436de6-418d-11e4-86ab-07e32ee8d7b2.png)

---

Competition

**Comment by skyhit** [comment]
(String[], int) is clear to me.
