### ISSUE TITLE
Wrong message displayed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#689]
## Description

Wrong message displayed
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code (eg : asjdkladjlaksjd)
DON'T ENTER REAL CODING
Click Submit

Check the Pop up
## Expected Result

Must fix the Issue, 
- Must not display this message because user never compile this problem
## Actual Result

Wrong message displayed
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![50](https://cloud.githubusercontent.com/assets/4592712/4348501/230df380-418e-11e4-8ff9-5749fa06e8e2.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
can not reproduce, and the screenshot show you entered something.
