### ISSUE TITLE
one word is shown on 2 lines in the system message

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#69]
1. load an SRM named "Test SRM Round bh 20140619"
2. then login as lightspeed, register for the SRM and wait for it starts
3. observe the system message

expected: word should be shown on a single line
actual: "may" is split on 2 lines
![m](https://cloud.githubusercontent.com/assets/4590317/3335236/7ef5ec34-f80f-11e3-93d4-22187a1c1065.jpg)

**Comment by skyhit** [comment]
duplicated.
