### ISSUE TITLE
[$50] Coding Area: Invalid arrow in drop down list

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#690]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Press Opened for any available problem.

Paste some code in Coding Area section(can be any HTML code).

Complete Go To field with some numbers(1,14,34, ...).

actual: arrow near Go To field is unuseful.

expected: do not display this arrow.

see attachment!

![arrow-invalid](https://cloud.githubusercontent.com/assets/5114907/4348511/5b25c0c2-418e-11e4-823f-c66c04a7c799.png)

---

Competition

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
I don't think the answer is to simply hide / remove the arrow, since otherwise we can't jump to a specific line anymore.

@onetliviunicolae, do you have more details on what you think is the correct behavior?
@skyhit if you have any input please share too, thanks!

**Comment by shubhendusaurabh** [comment]
@huangqun you are taken to the specific line no as you type as there is keypress event associated the line no input, so arrow button is never used

**Comment by huangqun** [comment]
Hmm, maybe this is not in master branch yet? I just tested and I still have to press enter to go to a line, and in that case I think it still makes sense to have the arrow.

@skyhit Is the code that auto jumps on keypress in a different branch and therefore we can remove the arrow?

**Comment by skyhit** [comment]
the arrow can be removed for current situation.

**Comment by huangqun** [comment]
ok, merged the pull request and closed this
