### ISSUE TITLE
Must display valid message when we enter text and click Compile

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#691]
## Description

Must display valid message when we enter text and click Compile
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code (eg : asjdkladjlaksjd)
DON'T ENTER REAL CODING
Click Compile

Check the Pop up
## Expected Result

Must fix the Issue, 
- Must enter valid programming code
## Actual Result

Sorry, the request is timeout.
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![51](https://cloud.githubusercontent.com/assets/4592712/4348521/99148e54-418e-11e4-9437-66f052a9aab0.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
the error message is properly, possiblly server busy
