### ISSUE TITLE
Must fix the message - compile throwing out a request because server is busy

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#693]
## Description

Must fix the message 
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Compile
[WHEN THE SERVER IS BUSY]
Check the Pop up - compile throwing out a request because server is busy
## Expected Result

Must fix the Issue, 

Compile throwing out a request because server is busy.
- Must Capitalize the First Letter
- Must end with a period (.)
## Actual Result

compile throwing out a request because server is busy
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![52](https://cloud.githubusercontent.com/assets/4592712/4348529/1b1c4fa4-418f-11e4-8d95-94a4f8e2a13d.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by huangqun** [comment]
@skyhit This seems to be an issue with server (i.e. the message comes back from the server), so can we close this?

**Comment by skyhit** [comment]
yes.
