### ISSUE TITLE
Message is not framed in popup window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#694]
## Environment

Windows 7

Chrome 35.0.1916.114 dev-m

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Press Opened for any available problem.

Set any html code in coding area.

Press Compile button.

actual: path from message is not framed in popup window.
## expected: all text from popup window must be framed.

Competition
## Web Arena QA for 201409 Release 

Notes: this html code can be used!
<!DOCTYPE html>
<html>
<body>

<em>Emphasized text</em><br>
<strong>Strong text</strong><br>
<dfn>Definition term</dfn><br>
<code>A piece of computer code</code><br>
<samp>Sample output from a computer program</samp><br>
<kbd>Keyboard input</kbd><br>
<var>Variable</var>

</body>
</html>
![message](https://cloud.githubusercontent.com/assets/5114907/4348530/3b09dda4-418f-11e4-81e6-8e4b8a89c608.png)

**Comment by skyhit** [comment]
should add scrollbar for this case.

**Comment by ananthhh** [comment]
There is no custom scrollbar for x-axis ?
Is that ok to show normal scrollbar ?

**Comment by skyhit** [comment]
you mean custom scrollbar only support y-axis?

**Comment by ananthhh** [comment]
Yes

**Comment by skyhit** [comment]
if so, normal scrollbar is fine. but please make sure that.

**Comment by skyhit** [comment]
fixed
