### ISSUE TITLE
Validation message order must chage

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#695]
## Description

Validation message order must chage
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
1. You have made a change to your code since the last time you compiled. Do you want to continue with the submit? [YES]
2. Would you like to submit your code? [YES]
3. You cannot submit unless you have successfully compiled first.
## Expected Result

Must fix the Issue, 

First display 'You cannot submit unless you have successfully compiled first.'
It will save coder's time
## Actual Result

Validation message order must chage
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![53](https://cloud.githubusercontent.com/assets/4592712/4348539/c8463474-418f-11e4-90f2-e51d479fae29.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
one is client side, one is serverside. no change needed.
