### ISSUE TITLE
When submit is not necesarry two confirmation messages

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#696]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Press Opened for any available problem.

Complete Coding Area section with an HTML code.

Press Submit.

actual: two confirmation popup messages are displayed with text "You have made a change to your code since the last time you compiled. Do you want to continue with the submit?" and "Would you like to submit your code?"

expected: is not necessary two confirmation messages for this action.

see attachments!

1-message.png
2-message.png

![1-message](https://cloud.githubusercontent.com/assets/5114907/4348540/e04cdea6-418f-11e4-9827-9270e4c7081c.png)
![2-message](https://cloud.githubusercontent.com/assets/5114907/4348541/e4017ae8-418f-11e4-8824-49ed826870f8.png)

---

Competition

**Comment by skyhit** [comment]
it is expected flow for long time.
