### ISSUE TITLE
Share options are not available

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#697]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Press Opened for any available problem.

Press Share option from the top of page.

Select any available social network.

actual: even press on logo social network redirect to social login page is not made.

expected: allow to share using social networks.

see attachment!

share.png
![share](https://cloud.githubusercontent.com/assets/5114907/4348555/d271e2c6-4190-11e4-9033-d0e6a148a434.png)

---

Competition

**Comment by skyhit** [comment]
duplicated.
