### ISSUE TITLE
[$75] Layout issue in the Test Panel in IE

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#698]
## Description

Layout issue in the Test Panel in IE
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Then Click the 'Test Panel'
## Expected Result

Must fix the Issue, 
- Must hide the Scroll bar in IE
## Actual Result

Layout issue in the Test Panel in IE
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![54](https://cloud.githubusercontent.com/assets/4592712/4348560/6425d51a-4191-11e4-8f2c-3a75b2a8f2f1.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#151
