### ISSUE TITLE
OK button is half hidden in FF

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#699]
## Description

OK button is half hidden in FF
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Then Click the 'Test Panel'
Click SELECT ALL
Click RUN TEST
## Expected Result

Must fix the Issue, 
- Must display fully as other browsers
## Actual Result

OK button is half hidden in FF
## Environment

FF 32.0.2 in Windows 7
## Image

FF
![55](https://cloud.githubusercontent.com/assets/4592712/4348562/b3297a54-4191-11e4-9e59-580e78deaffa.png)
Chrome
![55-chrome](https://cloud.githubusercontent.com/assets/4592712/4348564/c6063964-4191-11e4-8558-7a68e03418a8.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
scroll will show it.
