### ISSUE TITLE
[$50] Selected rooms must not be available in drop down list

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#700]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

In "Now chatting in: Room 2" section expand Room drop down list.

actual: selected room is available in drop down list.

expected: do not displayed selected room as item in drop down list.

see attachment!

![chat-room](https://cloud.githubusercontent.com/assets/5114907/4348573/0ae2914a-4192-11e4-9c4e-22d70d04a923.png)
chat-room.png

---

Competition

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
![image](https://cloud.githubusercontent.com/assets/6045894/4613375/ff5b4b38-52d4-11e4-8066-062b40d5f744.png)
This look really bad when there's only one room available. @skyhit, do you think we really need to fix this?

**Comment by skyhit** [comment]
for current situation, the dropdown always one item, other rooms will not be available. we may just don't show the dropdown.

**Comment by huangqun** [comment]
fixed
