### ISSUE TITLE
Long test Case Values are no displayed properly in 'Test Report'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#701]
## Description

Long test Case Values are no displayed properly in 'Test Report'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Then Click the 'Test Panel'
Click 'Test Case 4'
Click RUN TEST
Check the Report
## Expected Result

Must fix the Issue, 
- Must display fully
## Actual Result

Long test Case Values are no displayed properly in 'Test Report'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![56](https://cloud.githubusercontent.com/assets/4592712/4348577/1f54362e-4192-11e4-9a59-9b7204358f3c.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Should we show scrollbar in x-axis for this or should we wrap the text ?

**Comment by skyhit** [comment]
wrap the text.

**Comment by ananthhh** [comment]
For this contest i will wrap the text.
But i have a suggestion here. Instead of showing whole test case to the user, we can provide a link or button, on clicking it should display a popup which will have the test case params. 
So even if test case is too large Test Report doesn't look ugly.

**Comment by skyhit** [comment]
fixed.
