### ISSUE TITLE
Message: display the last message first

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#702]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Select some rooms (in and out) to receive a message.

Press on email icon from the top of page.

actual: last received message is displayed as the last from list.

expected: display last received message as the first.

see attachment!

messages.png
![messages](https://cloud.githubusercontent.com/assets/5114907/4348589/8b2426f2-4192-11e4-90b7-d2b34ecfc63e.png)

---

Competition

**Comment by skyhit** [comment]
based on the time, it is ordered by time, and the last one is at top.
