### ISSUE TITLE
Title of message is not displayed as bold if is unread

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#703]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Enter in some rooms to receive notification messages.

actual: received messages are not displayed with title bold.

expected: display unread messages with bold title.
message-title-not-bold.png
![message-title-not-bold](https://cloud.githubusercontent.com/assets/5114907/4348593/23d53a58-4193-11e4-8155-70ec655c3c0f.png)

---

Competition

**Comment by skyhit** [comment]
no needed.

**Comment by onetliviunicolae** [comment]
if you receive more messages and read some of them how you know which are read messages and which are unread?

**Comment by skyhit** [comment]
we are considering as a SRM scope, I think it is fine.
