### ISSUE TITLE
Won't reset the 'Custom Test Case #' if we remove them and add again

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#704]
## Description

Won't reset the 'Custom Test Case #' if we remove them and add again
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit

Then Click the 'Test Panel'
Add some Custom Test Cases
Delete all of them
Add again 3-4 Test cases
Check the numbers
## Expected Result

Must fix the Issue, 
- Must reset the value
## Actual Result

Won't reset the 'Custom Test Case #' if we remove them and add again
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![57](https://cloud.githubusercontent.com/assets/4592712/4348603/be4265f2-4193-11e4-81d5-9b4cb0977ab1.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
reset is hard, if you remove something. so we will do always incremental.
