### ISSUE TITLE
Room Leaderboard: view radio buttons can not be set

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#705]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter(to select room).

From Summary tab press on View Details.

In Room Leaderboard try to set View Status radio button.

actual: radio buttons can not be set in CHROME web browser.

expected: all radio buttons options must be set.

see attachment!

radio-buttons.png
![radio-buttons](https://cloud.githubusercontent.com/assets/5114907/4348610/400e55e6-4194-11e4-85c3-4bdec9029569.png)

---

Competition

**Comment by skyhit** [comment]
yes, it is disabled in purpose for that phase, because status info is not ready yet. you need to wait for challenge and system tests phase.

**Comment by onetliviunicolae** [comment]
Ok, if is disable why it can be selected.
Any user can think as see view = status as example.
Solution is to hide these controls if are not available to be used.
Please set correct resolution to this issue!

**Comment by skyhit** [comment]
it is not clickable.

**Comment by onetliviunicolae** [comment]
ok
