### ISSUE TITLE
Hide notification popup window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#706]
## Environment

Windows 7
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest LIVE in Active Contest section.

Press Enter.

Consider a notification for new email received.

Select any else section of application.

actual: notification popup window is not close.

expected: hide automatically notification popup window after some time(ex: 5 minutes).
![hide-notificaton](https://cloud.githubusercontent.com/assets/5114907/4348619/ccf3e46c-4194-11e4-8fb1-9db708ca3f0b.png)

---

Competition

**Comment by skyhit** [comment]
duplicate.

**Comment by onetliviunicolae** [comment]
Can you please put a comment as: duplicate of 'number issue'?

**Comment by skyhit** [comment]
see ##661

**Comment by onetliviunicolae** [comment]
ok
