### ISSUE TITLE
No gap between the user handle and rating icon

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#707]
## Description

No gap between the user handle and rating icon
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Click 'back to Contest'
Click 'View Details' from ROOMS
Click 'Coder History' icon
Check the Handle column data
## Expected Result

Must fix the Issue, 
- Must have some gap between the user handle and rating icon
## Actual Result

No gap between the user handle and rating icon
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![58](https://cloud.githubusercontent.com/assets/4592712/4348623/17cf8ea0-4195-11e4-9127-61c06de80efd.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
we'd better use separate column.

**Comment by skyhit** [comment]
fixed.
