### ISSUE TITLE
Room Leaderboard (Division I) filter is not working

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#708]
## Description

Room Leaderboard (Division I) filter is not working
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Click 'back to Contest'
Click 'View Details' from ROOMS

Now in the 'Room Leaderboard'
Click Filter
Seelct 'Specific Handle' from SHOW
Enter 'sdgunqa'
Click FILTER

Check the result
## Expected Result

Must fix the Issue, 
- Must filter the user handles
## Actual Result

Room Leaderboard filter is not working
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![59](https://cloud.githubusercontent.com/assets/4592712/4348636/8f4db7b8-4195-11e4-9327-07966913b207.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
