### ISSUE TITLE
[$75] Name with color of rating even rating is Not Rated

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#709]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Press View Details in Room tab.

Expand Rating Key section and Registrants.

Press on name sdgunqa.

actual: names sdgunqa and sdgunqabughunt1 are with purple color(rating between 1200- 1499) even rating is Not Rated.

expected: display rating in popup window to be according to color.

see attachments!

1.png

![1](https://cloud.githubusercontent.com/assets/5114907/4348642/e7c29828-4195-11e4-8a29-eff9e1941db3.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4348646/fd0a241c-4195-11e4-9e0f-e43d0de6a4e8.png)

---

Competition

**Comment by shubhendusaurabh** [comment]
looks like it has been fixed

**Comment by shubhendusaurabh** [comment]
![screenshot from 2014-10-12 00 45 28](https://cloud.githubusercontent.com/assets/1818387/4603836/2cb63486-517b-11e4-80de-47e4f5484569.png)
![screenshot from 2014-10-12 00 45 39](https://cloud.githubusercontent.com/assets/1818387/4603837/37024b00-517b-11e4-8cb7-9138d94a8ec6.png)
![screenshot from 2014-10-12 00 45 48](https://cloud.githubusercontent.com/assets/1818387/4603839/3915ae96-517b-11e4-989d-c5b318ce96bd.png)

**Comment by huangqun** [comment]
fixed.
