### ISSUE TITLE
"Challenged" should be "Challenge Succeeded" for consistency with applet

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#71]
1. load an SRM
2. ksmith and lightspeed register for the SRM, then submit a wrong solution
3. challenge the solution, see the room leaderboard

expected: "Challenged" should be "Challenge Succeeded" for consistency with applet

actual: see screenshots
![cha](https://cloud.githubusercontent.com/assets/4590317/3335272/4194e29a-f810-11e3-98f3-905abc60ce12.jpg)

applet:
![app](https://cloud.githubusercontent.com/assets/4590317/3335275/734c2258-f810-11e3-8e04-96ff41f3095d.jpg)

**Comment by skyhit** [comment]
this is in purpose, as for different screen width, long string may not fit.
