### ISSUE TITLE
Parameters listed in two lines

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#710]
## Description

Parameters listed in two lines
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Click 'back to Contest'
Click 'View Details' from ROOMS

Now in the 'Room Leaderboard'
Click on a Score (1000 point contest) of another user
Click Challenge in the Code editor
Click RUN (Sample Test Case 1)
Check the Pop up
## Expected Result

Must fix the Issue, 
- Must display in one line
## Actual Result

Parameters listed in two lines
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![60](https://cloud.githubusercontent.com/assets/4592712/4348677/1b3ef6b4-4197-11e4-93f1-f0ac3c39db9e.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
