### ISSUE TITLE
[$75] 'Challengers' and 'Challenges' filters won't filter the user : sdgunqa 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#711]
## Description

'Challengers' and 'Challenges' filters won't filter the user : sdgunqa 
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Click 'back to Contest'
Click 'View Details' from ROOMS

Click Filter from 'Challengers' and 'Challenges'
Select 'Specific Handle' from Show
Enter Handle : sdgunqa
Click Filter

http://qa.arena.topcoder.com/#/u/contests/16156/1/summary/room
## Expected Result

Must fix the Issue, 
- Must filter the tabel from user : sdgunqa 
## Actual Result

'Challengers' and 'Challenges' filters won't filter the user : sdgunqa 
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![61 1](https://cloud.githubusercontent.com/assets/4592712/4348711/46706b64-4198-11e4-899e-edb03c60bbcf.png)
![61 2](https://cloud.githubusercontent.com/assets/4592712/4348710/466b93dc-4198-11e4-8d23-3f4a4ea73fe1.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
@huangqun filters works with default usernames. is there any particular types of names that won't filter?

**Comment by huangqun** [comment]
I can't seem to reproduce this either, @skyhit  was this fixed already?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#150
