### ISSUE TITLE
Two the same messages are sent for the same action

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#712]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering stage when is change Challenge to Sys. Test

actual: two messages with the same content are received.

expected: only one message must be sent.

see attachment!

![two-messages](https://cloud.githubusercontent.com/assets/5114907/4348727/d64fc040-4198-11e4-8e77-9d48c90de1ae.png)

---

Competition

**Comment by skyhit** [comment]
I didn't see any duplication in the messages list in your screenshot.

**Comment by onetliviunicolae** [comment]
I received then two messages with the same title!

**Comment by skyhit** [comment]
based on your description, I can not reproduce it.
