### ISSUE TITLE
'System Test Phase is in process: 100.00%' must --> 'System Test Phase is in progress: 100.00%'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#713]
## Description

'System Test Phase is in process: 100.00%' must --> 'System Test Phase is in progress: 100.00%'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Click 'back to Contest'

http://qa.arena.topcoder.com/#/u/contests/16156

Wait till the system testing phase starts
Check the message : 'System Test Phase is in process: 100.00%'
## Expected Result

Must fix the Issue, 
- 'System Test Phase is in process: 100.00%' must --> 'System Test Phase is in progress: 100.00%'
## Actual Result

'System Test Phase is in process: 100.00%'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![62](https://cloud.githubusercontent.com/assets/4592712/4348742/3f262582-4199-11e4-93fd-bc6507c894e8.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed
