### ISSUE TITLE
[$75] Rounds Drop down is not sorted Asc by Round Name in 'Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#715]
## Description

Rounds Drop down is not sorted Asc by Round Name in 'Leaderboard'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit

Back to Dashboard
Click the Round Drop Down
Check the item arrangment
## Expected Result

Must fix the Issue, 
- Must sort by Rounds like in the Arena Applet
## Actual Result

Rounds Drop down is not sorted Asc by Round Name in 'Leaderboard'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![64](https://cloud.githubusercontent.com/assets/4592712/4348818/eb6441fa-419c-11e4-9bdb-f1378759d375.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Working on it

**Comment by huangqun** [comment]
fixed
