### ISSUE TITLE
Username is not correct displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#716]
## Environment

Windows 7
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering "Now chatting in: Chat Room 1".

actual: username is not correct displayed seems to be shaded.

expected: display correct username.

see attachment!

![shaded](https://cloud.githubusercontent.com/assets/5114907/4348825/345a2f50-419d-11e4-955c-35dbb3214128.png)
shaded.png

---

Competition

**Comment by skyhit** [comment]
you mean the backgound color?  it is for current logged user.

**Comment by onetliviunicolae** [comment]
Yes, background blue color.
This is not correct.I was able to simulate.
Can you please set correct resolution for this issue!

**Comment by skyhit** [comment]
what do you mean for simulate?

**Comment by onetliviunicolae** [comment]
to simulate this issue means I was able to see blue background on username.
it's for current user.
can you try using my credentials onetliviu.nicu@gmail.com / Password123.
so if you can see this background which is not correct please reopen this issue can consider as valid.

**Comment by skyhit** [comment]
the blue background is right. it is purposely implemented that way to distinguish current user with others.
