### ISSUE TITLE
[$75] User is displayed with different colors

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#717]
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Press "Enter" in Active Contests(14.09 Release QA SRM 8  page 3).

Select Division II tab.

actual: in Division II Leaderboard username onetliviu.nicu is displayed as white.

expecred: display color of user purple.

see attachment!

different-color.png
![different-color](https://cloud.githubusercontent.com/assets/5114907/4348848/38866c8c-419e-11e4-8f5e-2cf4557e48f8.png)

---

Competition

**Comment by paraggupta1993** [comment]
Hello, I am trying to debug this issue but I am having problems running arena-web on my localhost. I cannot login using my top-coder credentials.  Neither  http://qa.arena.topcoder.com is accepting my topcoder credentials.

**Comment by huangqun** [comment]
You can't use your own credentials to login, you should use twight/password or lightspeed/password or heffan/password

**Comment by paraggupta1993** [comment]
@huangqun  Thanks for quick reply.
Can you point out where the full directions for setting-up `arena-web` on `localhost` is present. Example: what all changes are needed in `config/dev-local.sh` or what should replace `tc.cloud.topcoder.com` in `config/dev-local.sh` as `tc.cloud.topcoder.com` doesn't resolves ?

**Comment by huangqun** [comment]
If you have a Arena VM, you need to edit your hosts file to map the VM ip to tc.cloud.topcoder.com, and map 127.0.0.1 to arena.cloud.topcoder.com, then access the web arena using arena.cloud.topcoder.com:3000

**Comment by paraggupta1993** [comment]
Currently, I dont have an Arena VM access. How can I get it ? Is getting a
VM access the only way to get arena up and running ?

On Wed, Oct 15, 2014 at 12:14 AM, huangqun notifications@github.com wrote:

> If you have a Arena VM, you need to edit your hosts file to map the VM ip
> to tc.cloud.topcoder.com, and map 127.0.0.1 to arena.cloud.topcoder.com,
> then access the web arena using arena.cloud.topcoder.com:3000
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cloudspokes/arena-web/issues/717#issuecomment-59095433
> .

## 

Parag Gupta,
B.Tech CSE,
IIIT-Hyderabad.

**Comment by huangqun** [comment]
read challenge page to see how to request vm access: http://community.topcoder.com/tc?module=ProjectDetail&pj=30046385

You should post the request in challenge forum.

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed
![screenshot from 2014-10-16 20 26 16](https://cloud.githubusercontent.com/assets/1818387/4664553/b1285a2e-5544-11e4-980c-a5ab6cfeff28.png)
