### ISSUE TITLE
Room Leaderboard: sort column 250 asc desc can not be made

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#718]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests section press enter for completed 14.09 Release QA SRM.

From Summary - Room press View Details option.

In Room Leaderboard press on 250 column.

Press again on column.

actual: sort desc can not be made.

expected: sort asc desc every time when column name is pressed.

see attachments!
1.png
## 2.png

![1](https://cloud.githubusercontent.com/assets/5114907/4349274/cc826b5a-41af-11e4-8a6d-e0f45390744c.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4349276/d103cc14-41af-11e4-97f6-22ca209704ed.png)

**Comment by skyhit** [comment]
obviously data problem.   what do you think the result should be for this case?

**Comment by onetliviunicolae** [comment]
this sort option must work in the same way as sort works for column 500 or 1000.
please set correct resolution for this issue!

**Comment by onetliviunicolae** [comment]
Also why sort column ASC / DESC after 500 or 1000 column works fine?

**Comment by skyhit** [comment]
I see you report that 1000 is not working.
