### ISSUE TITLE
Room Leaderboard: sort column 1000 asc desc can not be made

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#719]
## Environment

Windows 7
## Mozilla Firefox 32.0.2

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests section press enter for completed 14.09 Release QA SRM.

From Summary - Room press View Details option.

In Room Leaderboard press on 1000 column.

Press again on column.

actual: sort desc can not be made.

expected: sort asc desc every time when 1000 column name is pressed.

see attachment!

1.png

**Comment by onetliviunicolae** [comment]
![1](https://cloud.githubusercontent.com/assets/5114907/4349285/4844a3ca-41b0-11e4-9953-0ceb77b116e3.png)

**Comment by skyhit** [comment]
see comment at #718
