### ISSUE TITLE
"illegalaccess" should be "illegal access"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#72]
1. load an SRM
2. ksmith and lightspeed register for the SRM, then submit a wrong solution below:
   class TestProblem{}
3. challenge the solution, see the message

expected: "illegalaccess" should be "illegal access"
actual: see screenshot
![illegal](https://cloud.githubusercontent.com/assets/4590317/3335284/cc9b0f04-f810-11e3-81e3-a110c1ab9bf3.jpg)

**Comment by skyhit** [comment]
same as arena applet, may improve later. but not related to arena web.
