### ISSUE TITLE
[$5] Add more space between ":" and test

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#720]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
## Safari 5.1.7

Description

Access application link http://qa.arena.topcoder.com..
Use own credentials to login.
In Active Contest select page 1 and press enter button for 14.09 Release QA SRM 8 which is completed.

actual: Contest Status             :Contest Complete

expected:Contest Status  :        Contest Complete

see attachment!
![1](https://cloud.githubusercontent.com/assets/5114907/4349297/18b0eafa-41b1-11e4-9f39-476a378f5261.png)

---

**Comment by shubhendusaurabh** [comment]
@huangqun space is already present between : and text
![screenshot from 2014-10-12 00 19 42](https://cloud.githubusercontent.com/assets/1818387/4603781/6c25a49c-5178-11e4-9886-46b0c500a58e.png)
