### ISSUE TITLE
In Coder History section do not display tests

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#721]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Press Enter for contest 14.09 Release QA SRM 8.

Select Division I and press View Details.

From Division I Leaderboard for sdgunqabughunt1 press on usernames.

actual: tests are displayed in popup window.

expected: do not display tests in popup window.

see attachment!

1_001.png

coder-history-info.png
![1_001](https://cloud.githubusercontent.com/assets/5114907/4349340/d88e0b5e-41b2-11e4-9d24-050b80908663.png)
![coder-history-info](https://cloud.githubusercontent.com/assets/5114907/4349341/dd04e662-41b2-11e4-8669-9db637aff98a.png)

**Comment by skyhit** [comment]
same functionality as arena applet.
