### ISSUE TITLE
[$50] Some system Test Info won't properly formatted

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#722]
## Description

Some system Test Info won't properly formatted
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit

Back to Dashboard
Click 'View Details' from ROOM
Click Coder History of 'sdgbh' from Leaderboard
Click on System Tester result [9-21-2014 18:37:29]

Check the Layout
## Expected Result

Must fix the Issue, 
- Must have equal gap from Top and bottom
## Actual Result

Some system Test Info won't properly formatted
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![65](https://cloud.githubusercontent.com/assets/4592712/4349370/18a49aa4-41b4-11e4-812b-6091066d2f9f.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
