### ISSUE TITLE
[$50] Back to My Room button is available even in this case must not be

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#723]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
## Safari 5.1.7

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select page 5 in Active Contests section.

Press Enter button for 14.09 Release QA SRM 6.

actual: Back to My Room button is available and is not functional.

expected: do not display this button.

see attachment!

**Comment by onetliviunicolae** [comment]
![back-to-my-room](https://cloud.githubusercontent.com/assets/5114907/4349406/847e4c38-41b5-11e4-86c0-770ccf43a219.png)

**Comment by shubhendusaurabh** [comment]
looks like back to my room has already been removed
![screenshot from 2014-10-12 01 21 14](https://cloud.githubusercontent.com/assets/1818387/4603957/2389bba8-5180-11e4-9e46-3ce5b6c3ac15.png)

**Comment by huangqun** [comment]
fixed
