### ISSUE TITLE
[$50] Popup window without 'x' close button

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#724]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
## Safari 5.1.7

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select page 5 in Active Contests.

Press Enter button.

From Registrants section press on available registrant "mdesiderio-qa".

actual: a popup window with title Coder Info is displayed and 'x' close button is not available.

expected: display 'x' close popup window.

see attachment!

![code-info](https://cloud.githubusercontent.com/assets/5114907/4349432/64d21120-41b6-11e4-9d42-ce3087c8c882.png)
code-info.png

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
already fixed in master branch before this pull request, we'll consider this as the $25 verify fix task though.
