### ISSUE TITLE
Chat field is not visible with theme orange

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#725]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
## Safari 5.1.7

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Set theme = Orange Theme and press apply.

Use vertical scroll bar to the bottom of page.

actual: chat field is not visible.

expected: increase font and fields to be more visible.

see attachment!

not-visible.png
![not-visible](https://cloud.githubusercontent.com/assets/5114907/4349472/11c64cd4-41b7-11e4-9c2d-ab54ed73a948.png)

---

**Comment by skyhit** [comment]
wired, the font used in your browser is wired.

**Comment by skyhit** [comment]
here is what I got.
![capture](https://cloud.githubusercontent.com/assets/58106/4421573/5fcbb55a-4585-11e4-8849-67e1df53b0c1.PNG)

**Comment by onetliviunicolae** [comment]
why you put this issue as invalid?
you can see on print screen how looks.
on my computer looks how is in print screen.
no matter if on your computer is different.
this issue must not be closed!

**Comment by skyhit** [comment]
I don't know exactly your env, but since I can not reproduce, I think it is not a common issue.

**Comment by skyhit** [comment]
if I can not reproduce it, how can I mark it valid. otherwise, you have to provide clear steps to reproduce.

**Comment by onetliviunicolae** [comment]
steps are provided, also print screen how is required in contest description is provided.
what else information do you want?
do you want information about my screen resolution?

**Comment by skyhit** [comment]
yes, steps are provided, but I can not reproduce. so I don't know if it is a env specific issue.

and with your screenshot, I can see all fonts are vague (not clear), so I am not sure what is the problem.
