### ISSUE TITLE
Multiple invalid messages are sent from broadcast

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#726]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

actual: In Competition Arena Dashboard section different messages are sent.

expected: multiple messages must not be sent.

see attachment!

multiple-messages.png

message.png
![multiple-messages](https://cloud.githubusercontent.com/assets/5114907/4349588/3fb53434-41bc-11e4-844e-251f5c3ddf7e.png)
![messages](https://cloud.githubusercontent.com/assets/5114907/4349589/443b6c1c-41bc-11e4-96fa-3abf1871a8e1.png)

**Comment by skyhit** [comment]
duplicated.

**Comment by onetliviunicolae** [comment]
please put issue first the same issue and add in comment duplicate of name_issue!
thank you!

**Comment by skyhit** [comment]
sorry to mark it duplicate, the messages are from backend, it seems Admin is playing with some fucntionality for system tests.

it is not a problem.

**Comment by onetliviunicolae** [comment]
why in this case you consider as invalid?

**Comment by skyhit** [comment]
because this is out of scope for web arena, the messages are sending from backend.

**Comment by onetliviunicolae** [comment]
ok, but why you said first is duplicated(that means you accept first reported issue and current issue you mark as duplicate).
anyway on test environment is not my problem as admin is playing with some fucntionality for system tests, because I would not know that and I considered this a bug.
how can I make difference when admin play with some functionality for system and real test environment?

**Comment by skyhit** [comment]
I understand the situation, but as I said, it is not a problem, I suggest you can participants some SRMs with the current official arena applet and the web arena, so you can get more familiar with the concept used in SRMs.

**Comment by onetliviunicolae** [comment]
ok, I understand!
