### ISSUE TITLE
Invalid start and end data are displayed in popup window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#727]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Use email icon to view all messages.

Press on available message.

actual: in Round Broadcast popup window text " System Test Phase starts at 01/01/70 2:00 AM GMT+0300 and ends at 01/01/70 2:00 AM GMT+0300" is displayed with incorrect data.

expected: display correct data.

![incorrect-data](https://cloud.githubusercontent.com/assets/5114907/4349609/c245e61e-41bc-11e4-936a-0561be415926.png)
incorrect-data.png

see attachment!

**Comment by skyhit** [comment]
duplicated.

**Comment by onetliviunicolae** [comment]
please put a comment with duplicate of name_issue!

**Comment by skyhit** [comment]
I can see similar issue, but can not find the exactly, so I will open this one

**Comment by ananthhh** [comment]
If the contest is not started yet, then current phase will be 'starts in' phase. There is no start time for start in phase. There is only end time.
For phases after and equal to system test phase, there is no start and end time.

Only phase between starts in and system test phase has start and end time.

So we need to change the whole message. For starts in phase, we can simply put starts in {endTime} and we don't put end time.
For all phase after system test phase, we simply put {phaseName} started and no date mentioned.
Is this approach fine ?

Is this ok

**Comment by ananthhh** [comment]
any update here ?

**Comment by skyhit** [comment]
yes, it seems a backend change?

**Comment by ananthhh** [comment]
Actually there cannot be any start time for phase before registration
phase. Any phase before registration phase will have end time equal to
registration phase start time.
Same for system testing phase. It will start only when admin runs command
from admin client and it ends when all system tests are completed. So there
is no predefined  start or end time for system test phase.
So let's just put start time for phase before registration phase and let's
put no time for system test phase.
Please confirm

**Comment by ananthhh** [comment]
Since there is no answer and submission time is near, am going ahead and removing start date for starts in phase and removing start and end date for system test phase.
Please allow this to final fix if there are any update to my above mentioned approach.

Also lets not show notification for any phase after system test phase. Those will have no meaning to user which will fix #810

**Comment by huangqun** [comment]
@skyhit  Could you chime in here?

**Comment by skyhit** [comment]
fixed.
