### ISSUE TITLE
NO (.) DOT in the message 'The arena will be restarted soon, please save your work'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#728]
## Description

NO (.) DOT in the message 'The arena will be restarted soon, please save your work'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit

Disconnect the internet
Check the Message
Click Notification Icon and click on the message
Check the pop up
## Expected Result

Must fix the Issue, 
- 'The arena will be restarted soon, please save your work.'
## Actual Result

'The arena will be restarted soon, please save your work'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![66](https://cloud.githubusercontent.com/assets/4592712/4349644/003e974e-41be-11e4-9cbd-23279d9dd14c.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
it is manually entered messages from admin.
