### ISSUE TITLE
Name is written short even is not necessary

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#729]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Go to Summary section.

actual: Lang. is written short even is not necessary.

expected: do not display text short because space are available.

see attachment!

![summary](https://cloud.githubusercontent.com/assets/5114907/4349665/74c791a6-41be-11e4-89c7-7c25aafbda92.png)

**Comment by skyhit** [comment]
it is purposed, for maximized screen, it seem snot needed. but for small, it is really needed.

**Comment by onetliviunicolae** [comment]
Why you put this issue closed?
As you can see in print screen this is maximized screem.
Lang. is displayed as short.
If maximized screen really not need to be written short.
please change resolution of this issue because is valid!

**Comment by skyhit** [comment]
using Lang. is purposely, we don't think it is a valid issue to fix. so I close it.
