### ISSUE TITLE
it should show parameter names while challenging

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#73]
1. load an SRM, use TestProblem for the problem
2. ksmith and lightspeed register for the SRM, then submit a wrong solution
3. try to challenge the solution by selecting a test case, see the popup

expected: "int"/"int" should be "int A" and "int B" 
actual: see screenshot
![int](https://cloud.githubusercontent.com/assets/4590317/3335303/3c53ebea-f811-11e3-993e-913b382fcd31.jpg)

**Comment by skyhit** [comment]
same as arena applet, the index is enough for this purpose.
