### ISSUE TITLE
Available rooms are not display in drop down list

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#730]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select page 6 in Active Contests section.

Press Enter button.

Select Rooms tab.

Expand rooms drop down list.

actual:

**Comment by onetliviunicolae** [comment]
actual: only Room1 is available in drop down list.

expected: two rooms must be available Room1 and Room 2.

see attachments!

![a](https://cloud.githubusercontent.com/assets/5114907/4349691/7349472e-41bf-11e4-92d6-7c1c5b238b4b.png)
![rooms-not-available](https://cloud.githubusercontent.com/assets/5114907/4349692/78e62e0e-41bf-11e4-839b-4d4f83abeda8.png)

**Comment by skyhit** [comment]
yes, we are not supporting room changing in this dropdown.
