### ISSUE TITLE
[$50] Arena doesn't open on IE10, Windows Server 2012

### ISSUE THREAD

**Issue by abhineet-bansal** [cloudspokes/arena-web#731]
The arena opens on Chrome browser on the same machine. But not on IE10. It just shows a blank screen.

Screenshot attached
![ie10](https://cloud.githubusercontent.com/assets/8856556/4353518/1e707680-4234-11e4-8785-19451450c28b.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#149
