### ISSUE TITLE
Do not use the same word twice in text 

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#732]
Environment

Windows 7
Mozilla Firefox 32.0.2

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering an active contest live(14.09 Release QA SRM 13 is live!) press Enter.

actual: in Coding section text "Select a problem from the problem list:" is available.

expected: to be more professional this text must be "Select a problem from the list:".

see attachment!

![text](https://cloud.githubusercontent.com/assets/5114907/4353761/53d2def0-4237-11e4-8ee3-9f171057b8ca.png)

**Comment by skyhit** [comment]
it is fine.

**Comment by onetliviunicolae** [comment]
:), is fine to have the same word twice in the same phrase?
Select a problem from the problem list how sound this?
Is better "Select a problem from the list"!

**Comment by skyhit** [comment]
I don't see any confusion.

**Comment by onetliviunicolae** [comment]
- is not professionl to use the same word twice in the same phrase.
- how sound "Select a problem from the problem list"?
- how sound "Select a problem from the list"?
  Better the second text no?

**Comment by skyhit** [comment]
I don't have any preference which is better. both sentences are clear to me.

**Comment by onetliviunicolae** [comment]
Which of them do you like more? :)
From my point of view to be more professional text is better "Select a problem from the list".
