### ISSUE TITLE
cannot create the same user id as on topcoder production

### ISSUE THREAD

**Issue by rohitwali** [cloudspokes/arena-web#733]
Test Environment
Windows 7
Mozilla 31.0

Steps to reproduce
go to the QA URL http://tcqa1.topcoder.com/
try to register using your existing production user id (not supposed to be on QA)

Actual output
unable to register. says "Username already exists or is invalid."

Expected output
should be able to use existing user id

**Comment by skyhit** [comment]
it says "already exists".
