### ISSUE TITLE
 login on qa.arena.topcoder.com does not work

### ISSUE THREAD

**Issue by rohitwali** [cloudspokes/arena-web#735]
Test environment
windows 7
chrome 37.0.2062.120 m

reproduction steps
create an account on tcqa1.topcoder.com
sucessfully activate the account
clear browser cache
try to login through qa.arena.topcoder.com

actual output
the user is unable to login. Webpage says "Invalid username or password.Try again"

expected output
the user sould be able to login

Alternate
instead, if you first login to tcqa1.topcoder.com and then try to login to qa.topcoder.com, everything works fine.

**Comment by skyhit** [comment]
what is your handle used?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#148
