### ISSUE TITLE
contest summary is empty

### ISSUE THREAD

**Issue by rohitwali** [cloudspokes/arena-web#736]
Test Environment:
WIndows 7
Mozilla 31.0

Reproduction Steps:
login to qa.arena.topcoder.com
in the active contests, switch to cotest summary tab.

actual:
its empty

expected:
 should show the summary

PFB the screen shot
![2](https://cloud.githubusercontent.com/assets/7777325/4356633/4e0e2fc8-425b-11e4-937e-5c8822108eef.png)

**Comment by skyhit** [comment]
yes, for current situation, not a error case.
