### ISSUE TITLE
rounds combobox not collapsing in leaderboard

### ISSUE THREAD

**Issue by rohitwali** [cloudspokes/arena-web#737]
Test Environment
Windows 7
Mozilla 31.0

Steps to reproduce
go to the QA URL http://tcqa1.topcoder.com/
expand the leaderboard on the lower right corner of the page
select the any other round in the comobox.

Actual output
the combobox doesnot auto collapse on single click selection of double click selection unless user click outside of the combobox

Expected output
the combo box should collaspe on selection

PFB the image
![3](https://cloud.githubusercontent.com/assets/7777325/4356705/1c44f19c-425c-11e4-985f-4e7dcfce26be.png)

**Comment by skyhit** [comment]
duplicate
