### ISSUE TITLE
share button not working

### ISSUE THREAD

**Issue by rohitwali** [cloudspokes/arena-web#738]
Test Environment
Windows 7
Mozilla 31.0

Steps to reproduce
go to the QA URL http://tcqa1.topcoder.com/
go to any of the contest page.
now go to any of the rooms
try to share using the top right button

Actual output
unable to share

Expected output
should be able to share

PFB the image
![4](https://cloud.githubusercontent.com/assets/7777325/4356809/2866abf4-425d-11e4-8aa3-3836866ed639.png)

**Comment by rohitwali** [comment]
![4](https://cloud.githubusercontent.com/assets/7777325/4356847/73522d0a-425d-11e4-808f-b160d5995a8d.png)

**Comment by skyhit** [comment]
duplicate
