### ISSUE TITLE
[$50] Drop Down goes beyond the controller area

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#739]
## Description

Drop Down goes beyond the controller area
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Chat Area
Click on the Room Drop down
## Expected Result

Must fix the Issue, 
- Must display within the Area
- Or increase the length of the drop down
## Actual Result

Drop Down goes beyond the controller area
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![67](https://cloud.githubusercontent.com/assets/4592712/4358351/8b296360-4269-11e4-9a2e-e47ee6abe34f.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
