### ISSUE TITLE
[$50] No use of the 'Please wait while we retrieve coder information' message pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#740]
## Description

No use of the 'Please wait while we retrieve coder information' message pop up
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Chat Area
Click on a user handle name
Check the First pop up that appears before the Coder Info pop up
## Expected Result

Must fix the Issue, 
- Must display more time
- Or must remove it
## Actual Result

No use of the 'Please wait while we retrieve coder information' message pop up
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![68](https://cloud.githubusercontent.com/assets/4592712/4358921/09bfc85a-426e-11e4-8345-43655ca86897.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
what we have to do here?
remove it or delay it?

**Comment by skyhit** [comment]
is it possible, make it just grey out the background for other actions, and wait for the code info popup?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#147
