### ISSUE TITLE
[$50] Long username will hides the last part of it by the scroll bar

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#741]
## Description

Long username will hides the last part of it by the scroll bar
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Chat Area
Select : Reply to
Then click on the drop down to select a user
## Expected Result

Must fix the Issue, 
- Must display Fully
## Actual Result

Long username will hides the last part of it by the scroll bar
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![69](https://cloud.githubusercontent.com/assets/4592712/4359233/5160137a-4270-11e4-830c-da5f71b72374.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
