### ISSUE TITLE
Clear (x) Layout issue in Chat 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#742]
## Description

Clear (x) Layout issue in Chat 
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Chat Area
Click 'Search'
Enter text to the textbox
Check the clear (x) mark
## Expected Result

Must fix the Issue, 
- Must display with in the textbox area
## Actual Result

Clear (x) Layout issue in Chat 
## Environment

IE 11 in Windows 8
## Image

![70](https://cloud.githubusercontent.com/assets/4592712/4359374/5322afa0-4271-11e4-82aa-88822e04d4da.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
browser behavior.
