### ISSUE TITLE
Contest Plan: events are not available 

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#743]
---

Environment

---

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
## Safari 5.1.7

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Dashboard, Contest Plan section click on option to see all available events in month.

actual: No Event message is displayed even in selected month are many available contests.

expected: add contest plan functionality.

see attachment!

no-event.png
![no-event](https://cloud.githubusercontent.com/assets/5114907/4360188/34d5a3e2-4279-11e4-8864-17b2209c2a9e.png)

---

**Comment by skyhit** [comment]
it is not implemented.
