### ISSUE TITLE
Contest Plan: delete event text from beta version of application

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#744]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Contest Plan section use left arrow until February 2014.

Use option to see all events from this month.

actual: Lorem Ipsum dolor sit amet text for test is available.

expected: delete text for test from contest plan.

Notes

This is a beta version so any tests which are made on application must be deleted!
![contest-text](https://cloud.githubusercontent.com/assets/5114907/4360249/da3153cc-4279-11e4-864b-e0c50fbe091a.png)

**Comment by skyhit** [comment]
dummy implementation.
