### ISSUE TITLE
Title: 'Submission Results' must --> 'Submission Result'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#745]
## Description

Title: 'Submission Results' must --> 'Submission Result'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
When the Coding phase is Activated
Click ENTER
Click on a Problem
then Go to Code Editor
Enter a code
Click Compile and then click Submit (YES)

Check the Pop up title
## Expected Result

Must fix the Issue, 
- Title: 'Submission Results' must --> 'Submission Result'
## Actual Result

Title: 'Submission Results'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![71](https://cloud.githubusercontent.com/assets/4592712/4360269/2d0671f4-427a-11e4-9d26-937fd62b3f01.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
duplicate.
