### ISSUE TITLE
[$75] Dashboard: keep consistent in contest plan calendar data

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#747]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Contest Plan use option to see all event details from a month.

Use left arrow to select August 2014(No Event is displayed).

Use option to see all data from the month.
## actual:

september month is displayed with all available data.
## expected:

august data must be displayed.

see attachments!
![1](https://cloud.githubusercontent.com/assets/5114907/4360440/f3a0e85c-427b-11e4-988c-d873db94331f.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4360443/f844d38c-427b-11e4-81d8-e2c0d4a52fde.png)
![3](https://cloud.githubusercontent.com/assets/5114907/4360444/fc930aee-427b-11e4-9c8a-ed0f1e82ea78.png)

**Comment by skyhit** [comment]
it is not implemented. using dummy data now.

**Comment by onetliviunicolae** [comment]
Yes, but why not consider this issue.
This is a way how worked when I tested, why you not consider as valid issue?

**Comment by skyhit** [comment]
I can not easily say all issues are valid, resolving it will base on my knowledge.

**Comment by skyhit** [comment]
and the data is from backend, so for QA, if we didn't configure that, No Events is also a properly case.

**Comment by onetliviunicolae** [comment]
you not understand this issue!
the problem is not text "No event" which is displayed for August.
issue is related to switching option for a month.
if you select a month and then use switch option(to see event details) selected month which must be displayed must be the month which was previous set!

**Comment by skyhit** [comment]
sorry, for misunderstanding, you are right.

**Comment by onetliviunicolae** [comment]
ok, thank you!

**Comment by shubhendusaurabh** [comment]
working on it
