### ISSUE TITLE
Active Users: when coder info popup is open refresh option must be disable

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#748]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand "Active Users" section.

Press on any available user to open Coder Info popup window.

Press refresh icon(without close Coder Info popup window).
## actual:

active users refresh section is made.
## expected:

if Coder Info popup window is open refresh option must not be available.

see attachment!

![refresh-window](https://cloud.githubusercontent.com/assets/5114907/4360560/ef9fed9c-427c-11e4-8e8b-647882040b47.png)
refresh-window.png

**Comment by skyhit** [comment]
duplicate.

**Comment by onetliviunicolae** [comment]
Please put a comment with issue number!
duplicate of issue_name!

**Comment by skyhit** [comment]
#674

**Comment by onetliviunicolae** [comment]
ok
