### ISSUE TITLE
Profile Overview: redirect to profile page when username is selected

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#749]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Profile Overview & Important Messages.

Try to click on username.
## actual:

nothnig happens.
## expected:

redirect to profile username page.

see attachment!

![username-as-link](https://cloud.githubusercontent.com/assets/5114907/4360601/5cc2bd96-427d-11e4-86af-6ea4ca189c44.png)

**Comment by skyhit** [comment]
no plan to implement this.
