### ISSUE TITLE
style issue on the radio button

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#75]
win8, IE11
1. load an SRM
2. ksmith registers for the SRM
3. go to see the room summary, see the radio buttons "Points" and "Status"

expected: there should be no line on the radio button
actual: see screenshot
![line](https://cloud.githubusercontent.com/assets/4590317/3335376/0fddf432-f813-11e3-8f9b-5181e1f0fa2a.jpg)

**Comment by skyhit** [comment]
can not reproduce, may be zoom issue.
