### ISSUE TITLE
Leaderboard: display only rounds which contain handls

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#750]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select for example 14.09 Release QA SRM 19 - Round 1.
## actual:

no available information.

**Comment by onetliviunicolae** [comment]
expected:

to be more useful display in rounds drop down list only rounds where exist results otherwise an user must search to find different rounds without sense.

see attachment!

leaderboard.png
![leaderboard](https://cloud.githubusercontent.com/assets/5114907/4360667/0f6a91da-427e-11e4-8bee-26ca0a5ad271.png)

**Comment by skyhit** [comment]
the data is depending on the phase, same behavior as arena applet.

**Comment by onetliviunicolae** [comment]
ok
