### ISSUE TITLE
Leaderboard: round drop down list is close when up / down arrows are selected

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#752]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Leaderboard section.

Expand Rounds drop down list.

Select up / down arrows to navigate between items from drop down list.
## actual:

Rounds drop down list is close.
## expected:

Allow navigation between drop down list items and do not close list.

see attachment!

list-arrows.png
![list-arrows](https://cloud.githubusercontent.com/assets/5114907/4360752/9d86cc54-427e-11e4-8309-eba0bc7a76e8.png)

**Comment by skyhit** [comment]
fixed.
