### ISSUE TITLE
Leaderboard: display correct arrow from field when drop down list is expended

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#753]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Leaderboard section.

Expand Rounds from down list.
## actual:

down arrow is not change when drop down list is expended.
## expected:

by default arrow from field must be to the right and when list is expanded arrow must change position downwards.

see attachments!

1.png
2.png
![1](https://cloud.githubusercontent.com/assets/5114907/4360840/75d73f9e-427f-11e4-8ea6-94812bbce2a8.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4360843/7a5bbcf2-427f-11e4-9c5f-4835ff257258.png)

**Comment by skyhit** [comment]
looks fine, what need to be changed?

**Comment by onetliviunicolae** [comment]
arrow!
In 1.png arrow must be displayed to the right(peak to the left).
in 2.png arrow looks fine!

**Comment by skyhit** [comment]
sorry, I didn't get it

**Comment by onetliviunicolae** [comment]
as you can see in print screen attached to this issue arrow is not correct displayed.
when list from rounds drop down is collapsed arrow must be to the left and when list is expanded arrow must be to the down.

**Comment by skyhit** [comment]
it is not necessory, if you check the watch and unwatch dropdown in this page. the arrow is always remaining same for collapsed expanded state.

**Comment by onetliviunicolae** [comment]
ok
