### ISSUE TITLE
Error text and icon wont' align with in the container

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#754]
## Description

Error text and icon wont' align with in the container
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
When the Coding phase is Activated
Click ENTER
Enter the code and compile it
Then Submit it
after; Click 'Test Panels'

---

Click '+Add'
Enter; String[] field : {"vvvggggggggggggggggggg"} and int dist: 100
Click Run
Check the Report last column
## Expected Result

Must fix the Issue, 
- Error text and icon must align with in the container
## Actual Result

Error text and icon wont' align with in the container
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![73](https://cloud.githubusercontent.com/assets/4592712/4360847/80dd40e6-427f-11e4-97a7-14651f641040.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
What to do if length of input argument goes bigger like here ?
Should we show scroll bar in x-axis or we have to wrap the input argument ?

**Comment by skyhit** [comment]
wrap should look much better, right?

**Comment by skyhit** [comment]
fixed
