### ISSUE TITLE
[$75] Leaderboard: allow navigation between items using keyboard arrow keys

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#755]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select Leaderboard section.

Use mouse to expand rounds drop down list.

Press down keyboard key to navigate on the next item.
## actual:

when press down keyboard key last item from the list is selected.
## expected:

select only next item from the list when down arrow key is pressed.

Notes: keep the behavior as when press one time down arrow key only next item from the list is selected and when press one time up arrow key only last item is selected!

see attachments!

![1_001](https://cloud.githubusercontent.com/assets/5114907/4361001/ad20a7dc-4280-11e4-99e6-c1a0c2ce2709.png)
![2_001](https://cloud.githubusercontent.com/assets/5114907/4361003/b1cad69a-4280-11e4-9b8e-5356c048747a.png)
![200px-arrow_keys](https://cloud.githubusercontent.com/assets/5114907/4361038/f1f286e6-4280-11e4-8588-54aed25d080d.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#146
