### ISSUE TITLE
Messages notifications are not redirect when are selected

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#756]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Consider an notification message popup displayed.

Press on notification title.
## actual:

Nothing happens when notification is selected
## expected:

Expand messages control and close popup window notification automatically.

see attachment!
![a](https://cloud.githubusercontent.com/assets/5114907/4361114/9a07c774-4281-11e4-8d8a-8fb260befc77.png)
![b](https://cloud.githubusercontent.com/assets/5114907/4361117/9eb06240-4281-11e4-8c10-a8cbd4df4cc1.png)

**Comment by skyhit** [comment]
yes, it is expected, nothing happen. all messages are displayed.

**Comment by onetliviunicolae** [comment]
why is correct?
when press on notification pop-up expand messages, this is a correct behavior.
now when you press on notification pop-up nothing happens which is not correct!
please set correct resolution of this issue!

**Comment by skyhit** [comment]
I don't think current implementation is any problem. we didn't need it. 

and we are not going to display all messages with notification popup, any important.

**Comment by onetliviunicolae** [comment]
ok
