### ISSUE TITLE
[Light and Dark Theme] 'R' color in Challengers and Challenges tables are different

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#757]
## Description

[Light and Dark Theme] 'R' color in Challengers and Challenges tables are different
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
When the Coding phase is Activated
Click ENTER
Enter the code and compile it
Then Submit it
Then when the Challenge Phase is ON
Click 'View Details' from ROOMS Tab
Check the 'R' color in Challengers and Challenges tables
## Expected Result

Must fix the Issue, 
- Must use same color (green or Blue in Light Theme)
## Actual Result

'R' color in Challengers and Challenges tables are different
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![74](https://cloud.githubusercontent.com/assets/4592712/4361178/13ddce0e-4282-11e4-9d3b-14248e813417.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
This problem is there in dark theme as well. Shall i change that as well ?
![image](https://cloud.githubusercontent.com/assets/3583234/4588258/1f1428a8-503e-11e4-8cbe-c653415252a2.png)

**Comment by skyhit** [comment]
yes, make it consistent as others.

**Comment by skyhit** [comment]
fixed
