### ISSUE TITLE
Number of messages is displayed incorrect

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#758]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Consider some messages available.
## actual:

number of messages is displayed different than real number.
## expected:

display correct number of messages Message (4)

see attachment!

![messages-number](https://cloud.githubusercontent.com/assets/5114907/4361183/20e86910-4282-11e4-9809-d68eeeccc098.png)

**Comment by amethystlei** [comment]
The steps are not clear to reproduce the issue. Please confirm if it is still valid.

**Comment by skyhit** [comment]
the number of messages should be correct, but it didn't fill up all section, see the blank section below the second message.

**Comment by skyhit** [comment]
fixed.
