### ISSUE TITLE
Today button is displayed for a short time

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#759]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select a contest completed(ex: 14.09 Release QA SRM 13 is completed).

Press Enter button.

Press View Details for room.

Press Back to contest button from the right  of page.

Press Lobby icon from the top of page.
## actual:

for the short time(1second) a button today is displayed in Contest Plan section.
## expected:

do not display this button when redirect to dashboard section.

see attachment!

![home](https://cloud.githubusercontent.com/assets/5114907/4361413/09720906-4284-11e4-94ca-2f9b0378c573.png)
![today](https://cloud.githubusercontent.com/assets/5114907/4361414/0fc9e378-4284-11e4-87f7-4576516dd8d3.png)

**Comment by skyhit** [comment]
can not reproduce.

**Comment by onetliviunicolae** [comment]
to simulate this issue I tried 1h.
you simple put as closed(can not reproduced),
please try again to simulate and see!
how do you think I put print screen from attachment with button displayed?

**Comment by skyhit** [comment]
since I can not easily simulate, I can not easily ask some to fix.

so I close it.  you should provide clear and easy to reproduce steps.  I can not keep on playing some, which occurs magically.

**Comment by onetliviunicolae** [comment]
ok

**Comment by onetliviunicolae** [comment]
- this issue is really not easy to be reproduced but this appears.
- you can see in print screen attached a button "Today" which appear sometimes.
- you can ask programmers if this button real appear there to be satisfied!
  But you must not "close" this issue because trying once this not appear!
  To log this issue I spend 1hour you must believe and you simply put close!

**Comment by skyhit** [comment]
I understand your effort. but as I said, you should provide clear and easy to reproduce steps, not like saying 'keep playing with it and you will see the problem within 1hours'. no member will go to help fix this issues.

and actually we are using a third party calendar widget, fix it is really out of scope .

**Comment by onetliviunicolae** [comment]
ok
