### ISSUE TITLE
[Light Theme] BLUE color is not filled in the left side of the Menu "4. Sys. Test'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#760]
## Description

[Light Theme] BLUE color is not filled in the left side of the Menu "4. Sys. Test'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
When the Coding phase is Activated
Click ENTER
Enter the code and compile it
Wait till 'System Test Phase' starts
http://qa.arena.topcoder.com/#/u/contests/16170

Check the Top Menu, BLUE color is not filled in the right side of the Menu "4. Sys. Test'
## Expected Result

Must fix the Issue, 
- Must fill the Highlighted BLUE color to the right area (Check the screen shot)
## Actual Result

BLUE color is not filled in the right side of the Menu "4. Sys. Test'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![75](https://cloud.githubusercontent.com/assets/4592712/4361489/98b1a194-4284-11e4-895b-7f6a9bfce8f0.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
