### ISSUE TITLE
Message scroll bar is not visible when theme is dark

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#761]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Consider theme dark set.

Considering available messages expand control to view all.

Try to use vertical scroll bar.
## actual:

vertical scroll bar is not visible.
## expected:

vertical scroll bar must be more visible when theme is dark.
![message-scroll-bar](https://cloud.githubusercontent.com/assets/5114907/4361532/f357ca60-4284-11e4-8dde-a04c352bace2.png)

**Comment by skyhit** [comment]
based on your screenshot, the scrollbar is present.

**Comment by onetliviunicolae** [comment]
is present but in issue description is written "vertical scroll bar is not visible".
why you put this issue close?

**Comment by skyhit** [comment]
you mean the scrollbar should not be present?

**Comment by onetliviunicolae** [comment]
scroll bar must be present but more visible as is written in expected!

**Comment by skyhit** [comment]
it is personal opinion, it looks ok for me, and it is following the design.

**Comment by onetliviunicolae** [comment]
ok
