### ISSUE TITLE
[Light Theme] Very hard to see the Search icon in the Chat area

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#762]
## Description

[Light Theme] Very hard to see the Search icon in the Chat area
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Change to Light Theme
Then in the Chat Area
Check the Search icon
## Expected Result

Must fix the Issue, 
- Must change the color of the Search icon (Easier)
- Or must use darker color to the background
## Actual Result

Very hard to see the Search icon in the Chat area
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![76](https://cloud.githubusercontent.com/assets/4592712/4361574/5c6269c0-4285-11e4-93f0-c83d545deba5.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
similar as #80

**Comment by skyhit** [comment]
fixed.
