### ISSUE TITLE
Filter options are not displayed when theme is orange

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#763]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Theme switcher select orange.

Press Apply.

Go to competition arena(Competition Arena: 14.09 Release QA SRM 15 - Room 1).

Press View Details.
## actual:

Filter options are not display as options.
## expected:

increase font or change color of filter because are not visible.

see attachments!

![filter](https://cloud.githubusercontent.com/assets/5114907/4361646/fcc5eae0-4285-11e4-99af-ca45b0ada05f.png)
![filter1](https://cloud.githubusercontent.com/assets/5114907/4361650/011e2274-4286-11e4-8b7c-e70549411cd0.png)

**Comment by skyhit** [comment]
can not reproduce.

**Comment by onetliviunicolae** [comment]
ok
