### ISSUE TITLE
[$75] Coder info displayed even we click on the Handle row

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#764]
## Description

Coder info displayed even we click on the Handle row
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
When the coding phase starts click ENTER
Wait till the challenge phase starts
Make some challenges

In the Summary page click 'View Details' hyperlink
Click pointed areas in the screen shot in 'Challengers' and 'Challenges' tables
## Expected Result

Must fix the Issue, 
- Must display coder info pop up  if we click directly on the handle name
## Actual Result

Coder info displayed even we click on the Handle row
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 8
## Image

![77](https://cloud.githubusercontent.com/assets/4592712/4361700/611ae98c-4286-11e4-8521-670cf3c74329.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Working on it

**Comment by huangqun** [comment]
fixed
