### ISSUE TITLE
Text from bottom of page is not visible with theme orange

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#765]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Theme Switcher set orange and press APPLY.

Use vertical scroll bar to the bottom of page.
## actual:

OUR SPONSOR text is not visible.
## expected:

text must be visible with any theme.

see attachment!

our-sponsor.png
![our-sponsor](https://cloud.githubusercontent.com/assets/5114907/4361887/5bf43722-4288-11e4-89c5-83f2f9d29d62.png)

**Comment by skyhit** [comment]
can not reproduce.
