### ISSUE TITLE
[$75] Available messages can not be sorted

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#766]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Press on email icon from the top of page.
## actual:

available messages can not be sorted after General, Problem or Round option.
## expected:

add sort by general, problem and round option.
![messages](https://cloud.githubusercontent.com/assets/5114907/4362217/63685616-428b-11e4-982a-51291f9f51a4.png)

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by shubhendusaurabh** [comment]
@huangqun how to do the sorting here? i mean if i click on General then hide other messages or we have to sort them according to date?

**Comment by huangqun** [comment]
@skyhit I think this was accepted in one of the bug hunts, was there any decision how sorting should work for these?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#145
