### ISSUE TITLE
Contest Plan: do not display as hand when mouse over

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#768]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Contest Plan section use left arrow and select February 2014.

Press on any highlighted data.

Mouse over on the event.
## actual:

mouse cursor is displayed as hand.
## expected:

do not display as hand mouse cursor when mouse over.

see attachment!

a.png
b.png
![a](https://cloud.githubusercontent.com/assets/5114907/4362392/a8bc82ea-428c-11e4-94d4-33f441373108.png)
![b](https://cloud.githubusercontent.com/assets/5114907/4362399/b0a911ee-428c-11e4-94a7-815ab446ec6f.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#144
