### ISSUE TITLE
Allow to be selected only data from selected month

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#769]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Contest Plan section use left arrow to select February 2014 month.

Press on 1 or 3 data after 28 February(which seems to be disable).
## actual:

1 and 3 data can be pressed even are disable.
## expected:

1 and 3 data must be disable.

see attachment!
![2014-09-22_2246](https://cloud.githubusercontent.com/assets/5114907/4363024/c88fa91c-4291-11e4-8409-45cf5b2a3481.png)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#143
