### ISSUE TITLE
[$50] Text is keep highlighted even search functionality is changed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#770]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In "Now chatting in: Admin Lobby Room" section select chat.

Press search icon glass from chat field.

Complete field with onetliviu.nicu as example.

Press again on search icon glass to return on chat functionality.
## actual:

onetliviu.nicu text is keep highlighted even functionality of field is changed.
## expected:

do not display text highlighted when functionality is changed.

see attachments!

m.png
m1.png
![m](https://cloud.githubusercontent.com/assets/5114907/4363357/bf64bc6c-4294-11e4-873a-1708c6c743c4.png)
![m1](https://cloud.githubusercontent.com/assets/5114907/4363361/c89d7454-4294-11e4-9ce4-85e83c926a84.png)

**Comment by skyhit** [comment]
you have to manually clear it.

**Comment by onetliviunicolae** [comment]
but when I change pressing on search icon glass to return on chat functionality that means I don't want to search, so highlighted text must not be displayed.
please set resolution correct!

**Comment by skyhit** [comment]
ok, I can consider this is valid, actually, it is same behavior as in arena applet/.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
