### ISSUE TITLE
'Eligibility Requirements' Answer textbox is not aligned with the Question box from left side

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#771]
## Description

'Eligibility Requirements' Answer textbox is not aligned with the Question box from left side
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Check the 'Eligibility Requirements' Answer textbox 

Compare with the Arena Applet
## Expected Result

Must fix the Issue, 
- 'Eligibility Requirements' Answer textbox must align with the Question box from left side
## Actual Result

'Eligibility Requirements' Answer textbox is not aligned with the Question box from left side
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![75 1](https://cloud.githubusercontent.com/assets/4592712/4375318/2a7d1f0c-433b-11e4-9c33-cf8db3fab2d1.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Should size of the text box match with question box or just aligning to left is ok ?
Just aligning to left looks like below now
![image](https://cloud.githubusercontent.com/assets/3583234/4587982/232f05fe-5037-11e4-9a7d-1d5c11aff46a.png)

EDIT: Even if we give large text box user can input only 40 characters of text which doesn't come to half of text box size. Check below screenshot. So what is expected text box size here
![image](https://cloud.githubusercontent.com/assets/3583234/4588009/aae35fa4-5037-11e4-843a-64a9d5b5576d.png)

EDIT 2: This alignement is only for text box or single choice, multiple choice and text area also should align left to match to question box. Now everything looks like below
![image](https://cloud.githubusercontent.com/assets/3583234/4588060/1c9a017e-5039-11e4-89b4-d0d1f02366ea.png)
![image](https://cloud.githubusercontent.com/assets/3583234/4588062/293307f0-5039-11e4-8323-b2b5d4ea0b2c.png)

**Comment by skyhit** [comment]
that looks good.

**Comment by ananthhh** [comment]
Am not sure which one you are mentioning.

**Comment by skyhit** [comment]
I mean "EDIT 2"

**Comment by ananthhh** [comment]
That is without any changes.
So we don't need to do any changes here ?

**Comment by skyhit** [comment]
yes, let's close this, some indentation is good for clearness.
