### ISSUE TITLE
Must have more meaningful name for - 'Almost Contest Phase starts at 09/23/14 6:00 PM SLST...' 

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#772]
## Description

Must have more meaningful name for - 'Almost Contest Phase starts at 09/23/14 6:00 PM SLST...' 
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER

Wait till contest starts
Check the message : Almost Contest Phase starts
## Expected Result

Must fix the Issue, 
- Don't know what is this phase : 'Almost Contest Phase'
## Actual Result

Must have more meaningful name for - 'Almost Contest Phase starts at 09/23/14 6:00 PM SLST...' 
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![67](https://cloud.githubusercontent.com/assets/4592712/4371909/e629fc84-431d-11e4-918a-40e228f1fa42.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#142
