### ISSUE TITLE
[$50] When user hover over the search icon location of the icon changes

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#773]
## Description

When user hover over the search icon location of the icon changes
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till contest starts
Click ENTER
Click on a Problem and go to code editor
Hover over the search icon in the code editor
## Expected Result

Must fix the Issue, 
- Must not change the location when we hover over it
## Actual Result

When user hover over the search icon location of the icon changes
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![69](https://cloud.githubusercontent.com/assets/4592712/4372670/2cda801a-4326-11e4-8cc4-f046112ce1a9.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
