### ISSUE TITLE
Error displayed even we compile the code already

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#774]
## Description

Error displayed even we compile the code already
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till contest starts
Click ENTER
Click on a Problem and go to code editor

In the Code Editor
Enter the Code
Click COMPILE
Then go back
Now click on that same problem again (We have compiled it)
Click SUBMIT
## Expected Result

Must fix the Issue, 
- Must not display the error because we have compiled it already
## Actual Result

Error displayed even we compile the code already
## Image

![70](https://cloud.githubusercontent.com/assets/4592712/4375067/23cd4616-4339-11e4-808b-e6bb6e2e78a2.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
This is backend message. Since user gone back and opened problem again, server expects user to compile his solution even though he compiled it already.

**Comment by huangqun** [comment]
@skyhit should we ignore this one for now?

**Comment by skyhit** [comment]
yes. let close this.
