### ISSUE TITLE
Click 'Yes' from the Room Assignment Pop up won't go to Correct Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#777]
## Description

Click 'Yes' from the Room Assignment Pop up won't go to Correct Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till contest starts and room assignment completed
Click on the notofication icon
Check the message;
Coding Phase is starting for 14.09 Release QA SRM 19 - Round 1.
Would you like to go to your room now?

Click YES
## Expected Result

Must fix the Issue, 
- Must go to the correct room
## Actual Result

Click 'Yes' from the Room Assignment Pop up won't go to Correct Room
## Image

![73](https://cloud.githubusercontent.com/assets/4592712/4373551/7cd8aab8-432d-11e4-98c0-e14015f88ef4.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
