### ISSUE TITLE
x clear field option is available only with IE web browser 

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#780]
Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280

Description

Access application link http://qa.arena.topcoder.com..

Considering an active contest completed press Enter button.

Set focus on Chat field and type some text.

actual:

only using IE web browser x clear field option is available(is a default web browser option).

expected:

x clear field option must be available using any web browser.

see attachments!

![chrome-x-clear-field](https://cloud.githubusercontent.com/assets/5114907/4373818/88e2f4ec-432f-11e4-99b4-0d8a5546f7c8.png)
![x-clear-field](https://cloud.githubusercontent.com/assets/5114907/4373820/8dc30b0a-432f-11e4-915d-7b2d618b29dc.png)

**Comment by skyhit** [comment]
browser behavior, out of scope.
