### ISSUE TITLE
[$50] Can click 'Clear' button even without a Code

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#782]
## Description

Can click 'Clear' button even without a Code
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Don't enter any code
Click Clear
## Expected Result

Must fix the Issue, 
- Must disable the clear button when there is no code
## Actual Result

Can click 'Clear' button even without a Code
## Image

![76](https://cloud.githubusercontent.com/assets/4592712/4376497/27bedf16-4346-11e4-84d6-21f106f32306.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
working on it

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
