### ISSUE TITLE
Blank coding area displayed when we expand or collapse

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#783]
## Description

Blank coding area displayed when we expand or collapse
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Expand the Coding Area --> Code Hides

OR

In the Coding Phase
Expand the Coding area
Enter any code
Collapse the Coding Area --> Code Hides
## Expected Result

Must fix the Issue, 
- Must display the code
## Actual Result

Blank coding area displayed when we expand or collapse
## Image

![77](https://cloud.githubusercontent.com/assets/4592712/4376545/89a28ca0-4346-11e4-8052-658d065a83b1.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Is this still happening?
I couldn't replicate with steps mentioned in bug. I did all kind of collapse and expand but no luck.

**Comment by skyhit** [comment]
if so, the problem should be fixed magically, but reviewers will have to recheck

**Comment by skyhit** [comment]
fixed.
