### ISSUE TITLE
Layout issue when we expand the 'Problem Area' when the 'Test Report' is displayed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#784]
## Description

Layout issue when we expand the 'Problem Area' when the 'Test Report' is displayed
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Click Compile and sumbmit
Now Click 'Test Panel'
Execute all the tests
Now click Expand button in the 'Problem Area '
Scroll down the page
Check the layout
## Expected Result

Must fix the Issue, 
- Must close the 'Test Report'
## Actual Result

Layout issue when we expand the 'Problem Area' when the 'Test Report' is displayed
## Image

![78](https://cloud.githubusercontent.com/assets/4592712/4376626/28540d1a-4347-11e4-9c2e-e2eb30e9c09a.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
