### ISSUE TITLE
You are not assigned to this room message

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#785]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering as example 14.09 Release QA SRM 20 is live!

Press Enter button.

From coding section press OPEN option for an available problem.
## actual:

popup message with text "You are not assigned to this room".
## expected:

do not display this message if user is assigned.

see attachments!

![active-contest](https://cloud.githubusercontent.com/assets/5114907/4376797/e2b1c08e-4348-11e4-8672-0b7c02db849a.png)
![not-assigned](https://cloud.githubusercontent.com/assets/5114907/4376800/e78daa5a-4348-11e4-9cea-a32e3532101c.png)

**Comment by skyhit** [comment]
user is not competitor of that room.
