### ISSUE TITLE
Change text unopened to close

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#786]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Active Contests section select 14.09 Release QA SRM 20 is live!.

Press Enter button.

From Summary select Division II.

Press View Details.
## actual:

In Division II Leaderboard "Unopened" text is available in different lines.
## expected:

Change "Unopened" text with "Close" to be more specific.

Notes:

Open - Close and not Unopened

see attachment!
![close](https://cloud.githubusercontent.com/assets/5114907/4376931/1350739c-434a-11e4-95d5-27653c84c977.png)

**Comment by skyhit** [comment]
it is Unopened, check arena applet.
