### ISSUE TITLE
[$50] Display a message when filter and no results are displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#787]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Active Contests section select 14.09 Release QA SRM 20 is live!.

Press Enter button.

From Summary select Division II.

Use expand section option.

Press Filter link option.

Set Show = Specific Handle.

In Handle field enter any text(ex: testtest).

Press enter key(Filter button).
## actual:

redirect to table rows.
## expected:

display a message in content of page "No handle found!", in this way user is informed about no results after search action.

see attachments!

![1](https://cloud.githubusercontent.com/assets/5114907/4377035/ebd11154-434a-11e4-9230-ed4bdf7bb84f.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4377038/f7d2c736-434a-11e4-8b59-c0f71589dc3f.png)
![3](https://cloud.githubusercontent.com/assets/5114907/4377041/fb8537f6-434a-11e4-8648-55bb86444fe1.png)

**Comment by ananthhh** [comment]
Should we display popup or text saying 'No Records found!!!' in Division II leaderboard table itself ?

**Comment by huangqun** [comment]
I think text in the table would be better.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
