### ISSUE TITLE
Clear handle field when control is collapsed

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#788]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Active Contests section select 14.09 Release QA SRM 20 is live!.

Press Enter button.

From Summary select Division II.

Use expand section option.

Press Filter and select Handle.

Complete handle field with any text.

Use right arrow to close search control.

Use again arrow to open search control.
## actual:

text entered in handle field is displayed.
## expected:

handle field must be clear when control is close.

see attachments!

![a](https://cloud.githubusercontent.com/assets/5114907/4377096/8f7262b8-434b-11e4-8241-9cbfe4490621.png)
![1](https://cloud.githubusercontent.com/assets/5114907/4377118/b3036a9c-434b-11e4-93fc-0e3a4e65b67f.png)

**Comment by skyhit** [comment]
this is remembered, unless you clear it manually, it is purposely made.
