### ISSUE TITLE
[$50] Coding Area: display vertical scroll bar to be according to layout used

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#789]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select 14.09 Release QA SRM 20 - Room 2 which is in challenge phase.

Select and press View Details.

Press on any result(green numebers) available.

Use vertical browser scroll bar.
## actual:

in coding area section is displayed vertical scroll bar.
## expected:

display vertical scroll bar to be according to layout application.

see attachment!

![a_001](https://cloud.githubusercontent.com/assets/5114907/4377215/8f7e5a86-434c-11e4-8239-15072a033174.png)
![scroll-bar](https://cloud.githubusercontent.com/assets/5114907/4377217/943e7754-434c-11e4-9b4a-414fe7459da9.png)

**Comment by ghost** [comment]
could you provide more details about how the scrollbar should be displayed ?

**Comment by huangqun** [comment]
I think @onetliviunicolae meant moving it to the right a bit so the rightmost edge aligns withe the right most border?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#168
