### ISSUE TITLE
Coding Area: no message for invalid search result

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#790]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select 14.09 Release QA SRM 20 - Room 2 which is in challenge phase.

Select and press View Details.

**Comment by onetliviunicolae** [comment]
Press on any result(green numebers) available.

In Coding Area section complete Java search field with any test(ex: testtest).

Press enter button.

actual: no message to inform user about no results.

expected: display a message to inform user.
![no-message](https://cloud.githubusercontent.com/assets/5114907/4377295/66eb981c-434d-11e4-9fdb-bdb3b4a795ce.png)

**Comment by ananthhh** [comment]
What message is expected ?
It should come as popup or lets display in the header in red font ?

**Comment by ananthhh** [comment]
any update ?

**Comment by skyhit** [comment]
let's use popup now, stating, no match found.

**Comment by skyhit** [comment]
fixed.
