### ISSUE TITLE
Summary: letter display as green

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#791]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering 14.09 Release QA SRM 20 is live! press Enter button.

From Summary section use View Details.
## actual:

in Summary section letter "R" is displayed with green color and seems to be a link option.
## expected:

do not display this letter with green color.
![displayed](https://cloud.githubusercontent.com/assets/5114907/4377358/03887cd0-434e-11e4-9b84-2ea49fc30a23.png)

**Comment by skyhit** [comment]
duplicate.
