### ISSUE TITLE
Active Contests: display ascending order after start data(Registration Phase) contests.

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#792]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Active Contests section use page numbers to navigate between contests.
## actual:

contest are not displayed ascending after start data.
## expected:

to be more intuitive display contest in ascending order.

![8](https://cloud.githubusercontent.com/assets/5114907/4377416/9c2d145a-434e-11e4-81c8-eec0a20a6c72.png)
![9](https://cloud.githubusercontent.com/assets/5114907/4377418/a080aa94-434e-11e4-93c6-1c18b8cccdcc.png)
![10](https://cloud.githubusercontent.com/assets/5114907/4377424/a40c8994-434e-11e4-8152-4da6e539596b.png)

pages.

**Comment by ananthhh** [comment]
Contests should be sorted based on Registration start time?

**Comment by skyhit** [comment]
yes.

**Comment by skyhit** [comment]
fixed.
