### ISSUE TITLE
Firebug error when open message control

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#793]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Firebug 2.0.4

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Open Firebug tool to see all errors.

Press on message icon from the right top of page.
## actual:

Firebug message "Error: $scope.qtipPastNoti.qtip(...) is null ...".
## expected:

do not display error messages in Firebug tool.

see attachment!

message.png

![message](https://cloud.githubusercontent.com/assets/5114907/4378696/7180270e-435a-11e4-8a72-91711af6df5b.png)

**Comment by skyhit** [comment]
fixed.
