### ISSUE TITLE
[$75] Problem Area: back to contest functionality not redirect to contest

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#794]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Active Contests section select page with a completed contest(14.09 Release QA SRM 19 is completed.).

Press Enter button.

In Summary select Division I tab.

Press View Details.

From Division I Leaderboard press on any result(green number).

Press Back to Contest button from the top right of content page.
## actual:

redirect to Competition Arena: Round 1 section.
## expected:

redirect to Competition Arena: 14.09 Release QA SRM 19 - Room 1 must be made.

see attachments!

![v](https://cloud.githubusercontent.com/assets/5114907/4378935/7081f3ee-435c-11e4-898e-ab794d5b7931.png)
![v1](https://cloud.githubusercontent.com/assets/5114907/4378938/76a4942a-435c-11e4-8e57-ce246b7b614c.png)

**Comment by shubhendusaurabh** [comment]
@huangqun do we need to fix this issue?
        /**
         \* Go back to the contest page when the user is using the coding editor.
         \* Go back to the contest summary page when user is viewing others' code.
         */
above lines are commented for the goBack function for the back to match button

**Comment by huangqun** [comment]
no need to fix for now I think.
