### ISSUE TITLE
Invalid text in registration popup window

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#795]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registration phase open for a contest(ex: 14.09 Release QA SRM 21) press Register button.
## actual:

invalid text is displayed in Event Registration confirmation popup window.
## expected:

do not display this text.

see attachment!

![1](https://cloud.githubusercontent.com/assets/5114907/4379039/1c2e5232-435d-11e4-91f4-7decafeee4d9.png)

**Comment by skyhit** [comment]
there are more contents, in the scrollbar.

**Comment by onetliviunicolae** [comment]
ok
