### ISSUE TITLE
Contest Plan: events are not available even exist

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#796]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

In Contest Plan section set option to see all available events.

Use right arrow until February 2014.
## actual:

only one event is available (Lorem Ipsum dolor sit amet Feb 16, 2014).
## expected:

in February month in multiple days are available events so display all these events.

see attachment!

![1_001](https://cloud.githubusercontent.com/assets/5114907/4379220/b7630d3c-435e-11e4-8782-bf3cfdf78874.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4379223/bbdc49b4-435e-11e4-94fc-1f7a278cd85a.png)

**Comment by skyhit** [comment]
dummy data. not implemented.

**Comment by onetliviunicolae** [comment]
- this is not dummy data.
- for February exist more events and the problem is when you switch these not appear.

**Comment by skyhit** [comment]
see the data is dummy, and it is loaded form this json file - https://github.com/cloudspokes/arena-web/blob/master/app/data/contest-plan.json

**Comment by onetliviunicolae** [comment]
ok, so why not appear these data in first image?
can be the issue there?

**Comment by skyhit** [comment]
there is only one event at 2014-02-16

**Comment by onetliviunicolae** [comment]
yes, you are right, but as you can see in the second image, for February exist more events(in 16, 18, ...) and when you switch to see event details(image 1) only one event is available.
is there an issue of display?
I think yes and this is the reason because I logged issue.
Please verify again!
