### ISSUE TITLE
Contest Overview: invalid text related to registrants

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#797]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering Registration phase open.

Press on number of registrants.
## actual:

invalid text "Div1: [0]   Div2: [1]   New: [1]" is displayed.
## expected:

do not display this text in popup window.

see attachment!
![div](https://cloud.githubusercontent.com/assets/5114907/4379511/43b62614-4361-11e4-9a6a-f2397cc544f1.png)

**Comment by skyhit** [comment]
it is purposely added, the same as arena applet.
