### ISSUE TITLE
Do not display confirmation message if blank code

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#798]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registered into competition.

Considering Code Area blank.

Press "Clear" button.
## actual:

a confirmation popup window is displayed with Yes / No options.
## expected:

display a message "you can not clear a blank section of code".

see attachment!

blank.png
![blank](https://cloud.githubusercontent.com/assets/5114907/4379677/d11acd60-4362-11e4-94b9-09fe74298560.png)

**Comment by skyhit** [comment]
duplicate.

**Comment by onetliviunicolae** [comment]
Can you please put number of duplicate issue?

**Comment by skyhit** [comment]
similar as #782
