### ISSUE TITLE
Leaderboard: registered user not available in section

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#799]
Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registered into competition.

Expand Leaderboard section from the right of page.

Select Rounds = 14.09 Release QA SRM 25 - Round 1.

actual:

even I was registered to this room I am not displayed in section.

expected:

display a all users registered.

see attachment!

![registered](https://cloud.githubusercontent.com/assets/5114907/4388110/d8663f6c-43e6-11e4-86a7-8850f4a71c80.png)

**Comment by skyhit** [comment]
they are different concept.

**Comment by onetliviunicolae** [comment]
in Leaderboard I thought as user registred must be displayed.
user registered must be displayed using AJAX.
Why is invalid?

**Comment by skyhit** [comment]
it seems you are not familar with SRM, leaderboard is no going list all users, but the top ones in each room.
