### ISSUE TITLE
'Search' icon is not clearly seen in the Light Theme

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#80]
## Description

'Search' icon is not clearly seen in the Light Theme
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as twight/password

Switch the theme --> Light Theme
In the Chat room
Check the 'Search icon'
## Expected result

Must fix the Issue. Must use different color or dark Color
## Actual result

'Search' icon is not clearly seen in the Light Theme
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![36](https://cloud.githubusercontent.com/assets/4592712/3335639/075f539a-f819-11e3-90ea-860ae99535cf.png)

**Comment by skyhit** [comment]
![image](https://cloud.githubusercontent.com/assets/58106/4303739/f00dd7d8-3e69-11e4-8fac-427160c85e94.png)

Instead change the search icon color, which already used in some various pages. 
better update the chat bar background to make the search icon pop up.

**Comment by skyhit** [comment]
fixed.
