### ISSUE TITLE
Problem Area: even social networks are available they can not be selected

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#800]
Environment

Windows 7
Chrome 35.0.1916.114 dev-m

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registered into competition.

Select competition and press Enter button.

Press Opened option for an available problem.

Press "Share +" option from the top right of page.

Press on any available social network.

actual:

nothing happens after social network was pressed.

expected:

redirect to login page.

see attachment!

![social-network](https://cloud.githubusercontent.com/assets/5114907/4388212/5235e85a-43e8-11e4-8d47-97a76cec4094.png)

**Comment by skyhit** [comment]
not implemented.

**Comment by onetliviunicolae** [comment]
if is not implement not means this is not an issue.
i don't know is not implemented.
why is close?

**Comment by skyhit** [comment]
and it is already reported at #318

**Comment by onetliviunicolae** [comment]
ok
