### ISSUE TITLE
When we resize the Problem statement area by mouse it won't display the full content

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#801]
## Description

When we resize the Problem statement area by mouse it won't display the full content
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Now Drag and resize the 'Problem Area'
## Expected Result

Must fix the Issue, 
- Must display the full content
- OR Must disable the resize of the container
## Actual Result

When we resize the Problem statement area by mouse it won't display the full content
## Image

![79](https://cloud.githubusercontent.com/assets/4592712/4388218/61bb850a-43e8-11e4-89bd-fc442ef789bf.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
