### ISSUE TITLE
Active Contest: no indication if you are registered or not

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#802]
Environment

Windows 7
Chrome 35.0.1916.114 dev-m

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registered into competition which is not live(14.09 Release QA SRM 25 is live!).

In Active Contests section use page numbers navigation to select page.

actual: no indicator related to registered to this competition.

expected: display a text "registered" to know if logged user is registered or not to competition.

see attachment!

![no-indication](https://cloud.githubusercontent.com/assets/5114907/4388262/f57cdef6-43e8-11e4-9c37-869f7aad627b.png)

**Comment by skyhit** [comment]
the info is displayed when registration phase is open.

**Comment by onetliviunicolae** [comment]
When registration phase is open indicator about registered user is NOT displayed.
You can verify this!
- here I refer to an indicator in active contest section, which inform user as is registered to competition!

**Comment by skyhit** [comment]
in registration phase, it will show Register button if you don't register yet, and Registered text if you already registered.

**Comment by onetliviunicolae** [comment]
ok, I understand!
