### ISSUE TITLE
Two spaces in between the 'Class Name' and ':' in argument section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#803]
## Description

Two spaces in between the 'Class Name' and ':' in argument section
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Check the Argument section
## Expected Result

Must fix the Issue, 
- Need to have single space in between the 'Class Name' and ':'
- Or Must remove all the space in between the word and ':'
## Actual Result

Two spaces in between the 'Class Name' and ':' in argument section
## Image

![80](https://cloud.githubusercontent.com/assets/4592712/4388314/91eee414-43e9-11e4-8a49-fc7cb52383e5.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Shall i put no space in between word and ':' to classname, method name, return type and arg types?

**Comment by skyhit** [comment]
a single space before and after ':' seems fine, what do you think?

**Comment by ananthhh** [comment]
Both single space and no space can be used.
I will go ahead with single space.

Thanks

**Comment by skyhit** [comment]
fixed.
