### ISSUE TITLE
Same space is not maintained above the title : Constraints as others

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#804]
## Description

Same space is not maintained above the title : Constraints as others
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Expand the 'Problem Area'
Scroll down
Check the top space in the title : Constraints
## Expected Result

Must fix the Issue, 
- Must maintain the same space from the top in title : Constraints
## Actual Result

Two spaces in between the 'Class Name' and ':' in argument section
## Image

![81](https://cloud.githubusercontent.com/assets/4592712/4388373/4022c6fe-43ea-11e4-8164-568490afb038.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
Can single note can be so large, so that it can come in multiple lines like in screenshot provided in bug ?

**Comment by skyhit** [comment]
yes, it is possible.

**Comment by skyhit** [comment]
fixed.
