### ISSUE TITLE
[$50] Chat Room: scroll bar position is under up arrow

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#805]
Environment

Windows 7
Chrome 35.0.1916.114 dev-m

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

From Active Contest select section with registered competition(14.09 Release QA SRM 25).

Press Enter to redirect into Competition Arena.

In chat section use vertical scroll bar and set position to the top of page.

actual: scroll bar in the uppermost position is under arrow.

exepcted: scroll bar in the uppermost position must be right next arrow.

see attachments!

![up-arrow](https://cloud.githubusercontent.com/assets/5114907/4388399/7f1e79c0-43ea-11e4-97bb-1390c208bc88.png)
![up-arrow](https://cloud.githubusercontent.com/assets/5114907/4388401/84202f0e-43ea-11e4-9041-32877e8f0359.png)

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by ananthhh** [comment]
No need of any fix here. Its already fixed in #822

**Comment by shubhendusaurabh** [comment]
yes it has already been fixed. i was working on outdated repo
![screenshot from 2014-10-12 11 17 53](https://cloud.githubusercontent.com/assets/1818387/4605215/9aabe320-51d3-11e4-972e-cc7ebb5c83d5.png)

**Comment by huangqun** [comment]
fixed, ananthhh gets the $25 for being the 1st one to report it
