### ISSUE TITLE
Language : Drop down is not closing when we select an item

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#806]
## Description

Language : Drop down is not closing when we select an item
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Expand the 'Coding Area'
Click Editor
Click on the Language Drop down
Select a Language
## Expected Result

Must fix the Issue, 
- Language : Drop down must close when we select an item
## Actual Result

Language : Drop down is not closing when we select an item
## Image

![82](https://cloud.githubusercontent.com/assets/4592712/4388455/52bd058a-43eb-11e4-92cb-35a1e441f2eb.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
fixed.
