### ISSUE TITLE
[$50] Coding Area: drop down list is not necessary

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#808]
Environment

Windows 7
Chrome 35.0.1916.114 dev-m

Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registered to a competition(14.09 Release QA SRM 25 is live!).

Press Enter button.

Press Opened for any available problem from list.

Press "editor" option from the top left of coding area section.

Expand first drop down list(Standard).

actual: only "Standard" item option is available.

expected: do not display drop down list control if only one item option is available.

Notes: you can display "Standard " as text and not as drop down list item.

see attachment!
![standard](https://cloud.githubusercontent.com/assets/5114907/4388539/3a4dc164-43ec-11e4-8599-89709d68579c.png)

**Comment by dgaisan** [comment]
Can't login into  http://qa.arena.topcoder.com using Topcoder credentials. What's the trick?

**Comment by huangqun** [comment]
You'll need to setup your own environment to test this. Edit /etc/hosts to point tc.cloud.topcoder.com to your arena vm ip and run web arena locally.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
![image](https://cloud.githubusercontent.com/assets/6045894/4680578/1b42dcdc-560c-11e4-8691-b57e37823e78.png)
I think the fix from the pull request (https://github.com/cloudspokes/arena-web/pull/844) might be confusing, since the text Standard looks the same as the other titles like "Language".

@skyhit  I think you mentioned in some other issues that we'd show a text box instead? But it won't make sense to make that editable either.

**Comment by skyhit** [comment]
yes, this looks wired. we just need to disable drop down, but show like a drop down IMO.

**Comment by shubhendusaurabh** [comment]
@skyhit @huangqun if it looks like dropdown then users will try to click it. that would be confusing as well. i suggest we remove it altogether  or keep it if more themes will be added in future

**Comment by shubhendusaurabh** [comment]
@huangqun any update on my previous comment

**Comment by huangqun** [comment]
@shubhendusaurabh I think we should follow what @skyhit suggested, make it a disabled drop down so that even if user tries to click there's no harm.

**Comment by huangqun** [comment]
fixed
