### ISSUE TITLE
it requires multiple clicking on the success submission modal

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#81]
1. load an SRM
2. ksmith register for the SRM, then submit a solution
3. resubmit it and you'll see the success modal.
4. try to close it

expected: single click on the "Close" or "X" should close it
actual: see screenshot, it needs 2-3 clicking on it
![mn](https://cloud.githubusercontent.com/assets/4590317/3335645/1b5815bc-f819-11e3-931b-e6d8787cea69.jpg)

**Comment by skyhit** [comment]
fixed.
