### ISSUE TITLE
'Contest Complete Phase starts '; There is no such a phase

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#810]
## Description

'Contest Complete Phase starts '; There is no such a phase
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter a code and compile it, then submit
Wait till contest ends
Check the Notifications

14.09 Release QA SRM 25: Contest Complete Phase starts at 01/01/70 5:30 AM SLST
## Expected Result

Must fix the Issue, 
- 'Contest Complete Phase starts '; There is no such a phase
- Must change the name
## Actual Result

'Contest Complete Phase starts '; There is no such a phase
## Image

![84](https://cloud.githubusercontent.com/assets/4592712/4390106/7772777a-43fa-11e4-943a-43ecd11be818.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by skyhit** [comment]
see #727 this is already worked.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#135
