### ISSUE TITLE
[$50] 'Last Login' Date and time calculation is incorrect

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#811]
## Description

'Last Login' Date and time calculation is incorrect
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Then expand the 'Profile Overview & Important Messages'
Check the 'Last Login' section
## Expected Result

Must fix the Issue, 
- Must display the previous Login Date/Time (instead it is showing current login date/time)
- Check with Arena Applet
## Actual Result

'Last Login' Date and time calculation is incorrect
## Image

![85](https://cloud.githubusercontent.com/assets/4592712/4391176/fa8eb274-4402-11e4-91eb-9b790fc7cdce.png)
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by raj88iitr** [comment]
I'm working on it.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#167
