### ISSUE TITLE
Leaderboard: display items from round ascending

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#812]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Expand Leaderboard section.

Expand Rounds drop down list.
## actual:

available rounds are not sorted.
## expected:

available round must be displayed as sorted ASCENDING after SRM.

ex: 14.09 Release QA SRM 19, 14.09 Release QA SRM 20, ...

see attachment!

![1](https://cloud.githubusercontent.com/assets/5114907/4393523/9265d522-4418-11e4-903b-ac573164390b.png)

**Comment by skyhit** [comment]
duplicate.

**Comment by onetliviunicolae** [comment]
Please add a comment with number of duplicated issue!

**Comment by skyhit** [comment]
see #715
