### ISSUE TITLE
Division II: when sort after results do not change position

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#813]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering 14.09 Release QA SRM 26 is live! press Enter.

Select Division II tab.

Press View Details.

From Challenges second section press on Result tab.
## actual:

arrow is displayed under column name(Result) and section change position.
## expected:

keep the same position when sort asc / desc Result column.

see attachment!

1.png
2.png
![1](https://cloud.githubusercontent.com/assets/5114907/4393628/92bb758a-4419-11e4-8a4e-65cc62d6b842.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4393630/96f03c1c-4419-11e4-99a4-e70ab8746964.png)

**Comment by skyhit** [comment]
duplicate.

**Comment by onetliviunicolae** [comment]
add a comment with duplicated issue!

**Comment by skyhit** [comment]
see #650

**Comment by onetliviunicolae** [comment]
ok
