### ISSUE TITLE
[$50] Display on the same line name of competition

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#814]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering Dev only match is live!.

Press Enter.
## actual:

competition name is displayed on two lines.
## expected:

display competition name on the same line.

Notes: apply this for all competition names!

see attachment!

![1](https://cloud.githubusercontent.com/assets/5114907/4394263/b58a5300-441f-11e4-901e-f192c95d330c.png)

**Comment by skyhit** [comment]
this is fine, if it is not fit, I remember a bug fix for that.

**Comment by onetliviunicolae** [comment]
which bug fix is?

**Comment by onetliviunicolae** [comment]
why is not considered as valid issue, if you remenber a bug fix for this?

**Comment by skyhit** [comment]
it is possible the name will not fit in one line, for this case, wrap into two lines are best way.

**Comment by onetliviunicolae** [comment]
- is not correct to wrap on the next line.
- exist more space there why to wrap on the next line?

**Comment by skyhit** [comment]
why is not correct? the right section is more other purpose, like Back to My Room button etc.

wrapping it is fine for some special cases.

**Comment by onetliviunicolae** [comment]
- exist more space there why to wrap on the next line.

**Comment by skyhit** [comment]
ok, let open it for double check.

**Comment by ghost** [comment]
I'm working on it

**Comment by huangqun** [comment]
fixed
