### ISSUE TITLE
Invalid validation when register to application

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#816]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering 14.09 Release QA SRM 27 in registration phase.

Press Register button.

Enter monaco in field, select one option radio button and check only ONE checkbox(option1) for Multiple choice example.

Press I Agree button.
## actual:

registation with success on this challenge.
## expected:

display a validation message related to multiple choices and allow user to register only if check 2 checkbox options.

see attachments!

![1](https://cloud.githubusercontent.com/assets/5114907/4394925/26a6952a-4426-11e4-961a-2017094dcc98.png)
![2](https://cloud.githubusercontent.com/assets/5114907/4394926/2c260102-4426-11e4-869c-489a2838c21d.png)
![3](https://cloud.githubusercontent.com/assets/5114907/4394929/2fc9e5ee-4426-11e4-9330-acc4f329d656.png)

**Comment by skyhit** [comment]
for multiple choice type, it is not need to select more than 1 opinion.

**Comment by onetliviunicolae** [comment]
ok

**Comment by onetliviunicolae** [comment]
-what means multiple choice?
that means an user must select multiple options(this is the reason because there are checkboxes).
- is different as previous validation when an user must select only one option from radio buttons.
- this is the reason becasue I logged this issue.User must select multiple options(more than 1) for the second section.
- please review this issue!
