### ISSUE TITLE
Competition Arena: invalid time for registration phase

### ISSUE THREAD

**Issue by onetliviunicolae** [cloudspokes/arena-web#817]
---
## Environment

Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---
## Description

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Considering registration phase open press enter to competition arena.
## actual:

in Contest Schedule section Registration Phase ended at: Sep 24, 11:30 PM GTB even real time displayed on the top of page is 11:32.
## expected:

display correct time.

see attachment!
![invalid](https://cloud.githubusercontent.com/assets/5114907/4395347/58514170-442a-11e4-8fc7-f24b24a923e7.png)

**Comment by skyhit** [comment]
looks correct, only after registration phase, you can be enter into the rooms.

**Comment by onetliviunicolae** [comment]
times are different you can see!
this is an issue!

**Comment by skyhit** [comment]
sorry, I didn't get you point.

the registration is ended at 11:30, and there will be 5 min gap before coding phase, for users to prepare and system to prepare.

in the image, it is at 11:32:36, and it says the coding phase will be started within 2minutes 24 second, so it will be start at 11:35, as it contest schedule said.

**Comment by onetliviunicolae** [comment]
I understand!
thank you for response!
