### ISSUE TITLE
When we enter chat messages, can't display the full word in one line

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#83]
## Description

When we enter chat messages, can't display the full word in one line
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as twight/password

Switch the theme --> Light Theme
In the Chat room
Select 'Reply to'
Enter the message : You must also be the first person to report the issue and submit it while submission phase is open.  any issues before and after the submission phase will NOT be counted.
Press Enter

Check the MEssage
## Expected result

Must fix the Issue. Must display the word in single line; If the text ends with 2-3 chars left, must start from next line
Or must use the (-)
## Actual result

When we enter chat messages, can't display the full word in one line
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![37](https://cloud.githubusercontent.com/assets/4592712/3335676/dea3db78-f819-11e3-9a64-5c79589d2dad.png)

**Comment by skyhit** [comment]
duplicate issue.
