### ISSUE TITLE
it should check if the user is challenging himself first

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#84]
1. load an SRM
2. ksmith and lightspeed register for the SRM, then submit a solution
3. when challenge phase starts, ksmith tries to challenge himself with some invalid parameters

expected: the application should report an error that the user cannot challenge himself first.

actual: see screenshot, it complains that the params are invalid, it looks like the user can still challenge himself.
![ch](https://cloud.githubusercontent.com/assets/4590317/3335692/438b09a8-f81a-11e3-8f00-fdec7a399f65.jpg)

**Comment by skyhit** [comment]
same process as arena applet.
