### ISSUE TITLE
latest checked item should uncheck previous checked items

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#85]
1. load an SRM
2. ksmith and lightspeed register for the SRM, then submit a solution
3. when challenge starts, check the test example 0
4. check the test example 1

expected: when we check the test example 1, the previous checked example 0 should be unchecked automatically. This would save competitor's time.
actual: see screenshot
![Uploading check.jpg . . .]()

**Comment by skyhit** [comment]
1. missing screenshots.
2. this is the rough version, we are planning to improve that in later phase.
