### ISSUE TITLE
'Challenges & Leaderboard' Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#858]
## Description

'Challenges & Leaderboard' Layout Issue
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Click on a Completed Match
Click ENTER
Check the 'Challenges & Leaderboard' text
## Expected Result

Must fix the Issue, 
- Must have some gap from top
## Actual Result

'Challenges & Leaderboard' Layout Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![1](https://cloud.githubusercontent.com/assets/4592712/4709086/df180dca-589c-11e4-8656-34242567412a.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#126
