### ISSUE TITLE
Match Plan List view layout issue in the scroll bar

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#859]
## Description

Match Plan List view layout issue in the scroll bar
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the Match
Go to February
Click List View
Scroll down the list
Check the Scroll bar
## Expected Result

Must fix the Issue, 
- Scroll bar must not go beyond the visible area
## Actual Result

Match Plan List view layout issue in the scroll bar
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![3](https://cloud.githubusercontent.com/assets/4592712/4709088/e420d342-589c-11e4-93f0-42401061d121.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#125
