### ISSUE TITLE
"Test Case" should be written as "Example 0"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#86]
1. load an SRM
2. ksmith and lightspeed register for the SRM, then submit a solution
3. when challenge starts, click "Challenge" to see tests cases

expected: "Test Case" should be written as "Example 0"

actual: see screenshot
![tc](https://cloud.githubusercontent.com/assets/4590317/3337732/2080c5b6-f850-11e3-9bbf-192d05aa829e.jpg)

**Comment by skyhit** [comment]
this is not example, but custom example that user can input.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#120
