### ISSUE TITLE
When we switch to List and grid layout issue happens

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#860]
## Description

When we switch to List and grid layout issue happens
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the Match
Go to February
Click List View

Check care fully, list loads and display beyond the section area
## Expected Result

Must fix the Issue, 
## Actual Result

When we switch to List and grid layout issue happens
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
@sdgun can you provide a screenshot?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#124
