### ISSUE TITLE
'TC TIME' and Actual time is too close to each other

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#861]
## Description

'TC TIME' and Actual time is too close to each other
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Check the 'TC TIME' and Actual time
## Expected Result

Must fix the Issue, 
- Must have some small gap
## Actual Result

'TC TIME' and Actual time is too close to each other
## Environment

IE 11 in Windows 7
## Image

![6](https://cloud.githubusercontent.com/assets/4592712/4709201/b1a48d22-589d-11e4-9545-22ab90488843.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
following the design.
