### ISSUE TITLE
Duplicate dates displayed in the Match Plan

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#863]
## Description

Duplicate dates displayed in the Match Plan
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the Match Plan
Go to February
Click on a Date (in Orange) eg: Feb 22

Check the date;
- Feb 22, 2014 
- Saturday 2/22
## Expected Result

Must fix the Issue, 
- Only once is enough
## Actual Result

Duplicate dates displayed in the Match Plan
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![9](https://cloud.githubusercontent.com/assets/4592712/4709290/46776294-589e-11e4-93ee-793a59be6591.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#123
