### ISSUE TITLE
[a4150000000Ea4n] Facebook link is not working in the 'Profile Overview & Important Messages' section

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#864]
## Description

Facebook link is not working in the 'Profile Overview & Important Messages' section
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Expand the 'Profile Overview & Important Messages' section
Click on the Facebook icon
## Expected Result

Must fix the Issue, 
- Must work the facebook link
## Actual Result

Facebook link is not working in the 'Profile Overview & Important Messages' section
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![10](https://cloud.githubusercontent.com/assets/4592712/4709287/3ccec25a-589e-11e4-91e7-0d6e9bbb455c.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#92
