### ISSUE TITLE
[Common] Active Users (x) count is not updating

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#865]
## Description

[Common] Active Users (x) count is not updating 
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Check the Active Users (x) section
## Expected Result

Must fix the Issue, 
- Must update the Active Users (x) count
- We have to enable the Active Users (x) section to get the count
## Actual Result

Active Users (x) count is not updating 
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![21](https://cloud.githubusercontent.com/assets/4592712/4709361/ad33103c-589e-11e4-9fa1-1c0f9f98ea9a.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
following the implementation
