### ISSUE TITLE
[Common] Layout Issue when we scroll the page while the Filter is activated

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#866]
## Description

[Common] Layout Issue when we scroll the page while the Filter is activated
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Open a completed Contest (Click ENTER)
Click 'Challenges & Leaderboard '
Click Filter in 'Challengers', 'Challenges' or 'Room  Leaderboard'
In Expand Mode also
Scroll the page up
## Expected Result

Must fix the Issue, 
## Actual Result

Layout Issue when we scroll the page while the Filter is activated
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![22](https://cloud.githubusercontent.com/assets/4592712/4709365/b2d2a0f2-589e-11e4-849e-910f2b4abd46.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#122
