### ISSUE TITLE
[Common] Phase counter Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#867]
## Description

[Common] Phase counter Layout Issue
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Register for the Competition
When the Coding Phase starts
Click ENTER

Check the Counter in the Header
## Expected Result

Must fix the Issue, 
- Must display it in one line
  eg : Coding: 12 days,  21:06:51
## Actual Result

Phase counter Layout Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![25](https://cloud.githubusercontent.com/assets/4592712/4709404/ef8429b2-589e-11e4-820d-8d6086931f73.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#132
