### ISSUE TITLE
[Common] Header counter and below counter have two values, Below counter is -1sec behind

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#868]
## Description

[Common] Header counter and below counter have two values, Below counter is -1sec behind
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Register for the Competition
When the Coding Phase starts
Click ENTER

Check the Counter in the Header --> 21:03:49 
Check the Green Box Counter --> 21 hours 3 minutes 48 seconds
## Expected Result

Must fix the Issue, 
- Must display same counter values
## Actual Result

Header counter and below counter have two values, Below counter is -1sec behind
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![25 1](https://cloud.githubusercontent.com/assets/4592712/4709405/f4e1c2e8-589e-11e4-8870-a77a2596629b.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#121
