### ISSUE TITLE
[Common] 'Today' button displays when we go back to the 'Active Matches' page

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#869]
## Description

[Common] 'Today' button displays when we go back to the 'Active Matches' page
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the 'Active Matches ' Section
Select a Match
Click ENTER

Click on the 'Lobby' button
Check near the calender
'Today' button displays for 1-2sec and hides
## Expected Result

Must fix the Issue, 
- Must display the 'Today' button
- Or if it is not available; Must hide it 
## Actual Result

'Today' button displays when we go back to the 'Active Matches' page
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![26](https://cloud.githubusercontent.com/assets/4592712/4709426/1d13b9c4-589f-11e4-92a7-a3a4986c2d74.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
