### ISSUE TITLE
Double entry displayed when we 'whispers' someone

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#87]
## Description

Double entry displayed when we 'whispers' someone
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as Hung/password

Switch the theme --> Light Theme
In the Chat room
Select 'Hung'
Enter the message : You must also be the first person to report the issue and submit it while submission phase is open.  any issues before and after the submission phase will NOT be counted.
Activate the cursor in Username textbox
Press Enter
Nothing happens

Then activate the cursor in the message section, press enter

If it is ok, Order must change
1. Hung whispers to you: You must also be the first person to report the issue and submit it while submission phase is open. any issues before and after the submission phase will NOT be counted. 
2. You whisper to Hung: You must also be the first person to report the issue and submit it while submission phase is open. any issues before and after the submission phase will NOT be counted. 

Must change the Order also, First Hung whisper, So message 'You whisper to Hung ...' appears first
Then the 'Hung whispers to you...'
## Expected result

Must fix the Issue. Must not display twice
## Actual result

Double entry displayed when we 'whispers' someone
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![38](https://cloud.githubusercontent.com/assets/4592712/3335731/15b36bbe-f81b-11e3-91cc-9c83d5dc6433.png)

**Comment by skyhit** [comment]
mainly, you are wishper youself, check arena applet, same sequences.
