### ISSUE TITLE
[Orange Theme] 'Leaderboard' Drop Down Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#870]
## Description

[Orange Theme] 'Leaderboard' Drop Down Issue
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Register for the Competition
When the Coding Phase starts
Click 'Leaderboard'
Expand the Drop Down
Check the bottom border
## Expected Result

Must fix the Issue, 
- Bottom margin must fully displayed
## Actual Result

'Leaderboard' Drop Down Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![27](https://cloud.githubusercontent.com/assets/4592712/4709459/7c070a80-589f-11e4-8b23-a0b0229a457a.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by sdgun** [comment]
This can be seen in Light Theme also, and also The scroll bar overlaps with the scroll bar arrows

![27 1](https://cloud.githubusercontent.com/assets/4592712/4711468/6c424562-58bb-11e4-9db5-6610b890c17c.png)

**Comment by skyhit** [comment]
duplicate.
