### ISSUE TITLE
'R' Sorting icon is too close to the Next column text

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#871]
## Description

'R' Sorting icon is too close to the Next column text
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the Leaderboard
Click 'R'
## Expected Result

Must fix the Issue, 
- Must have some gap
## Actual Result

'R' Sorting icon is too close to the Next column text
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![5](https://cloud.githubusercontent.com/assets/4592712/4709197/aa066aae-589d-11e4-9ef0-a8683f738c6c.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
following the design, no change for current situation
