### ISSUE TITLE
[Orange Theme] 'Active Users' bottom section is not fully displayed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#872]
## Description

[Orange Theme] 'Active Users' bottom section is not fully displayed
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Register for the Competition
When the Coding Phase starts
Scroll Down
Check the 'Active Users'section bottom border
And also Text in not align well as others
## Expected Result

Must fix the Issue, 
- Bottom section must fully displayed
## Actual Result

'Active Users' bottom section is not fully displayed
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![28](https://cloud.githubusercontent.com/assets/4592712/4709458/7666c96c-589f-11e4-8007-f8dfa8926dcd.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#119
