### ISSUE TITLE
[Light Theme] Menu Tool Tip Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#873]
## Description

[Light Theme] Menu Tool Tip Issue
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Click ENTER in the completed Contest
Hover over the Menu 
Check the Tool Tip arrow
## Expected Result

Must fix the Issue, 
- Must use blue background color for the arrow head
## Actual Result

Menu Tool Tip Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![32](https://cloud.githubusercontent.com/assets/4592712/4709453/704ab1c4-589f-11e4-9c8c-ed25e58a1718.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#118
