### ISSUE TITLE
[a41500000000V22] Update logos to remove brackets from [topcoder]

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#874]
## Description

[a41500000000V22] Update logos to remove brackets from [topcoder]
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
check the Logo
## Expected Result

Must fix the Issue, 
- Update logos to remove brackets from [topcoder]
## Actual Result

Still the [] are there in the Logo
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![33](https://cloud.githubusercontent.com/assets/4592712/4708436/455e449c-5897-11e4-84ab-29179b4973ef.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
brackets  is needed, we are reverting this back.
