### ISSUE TITLE
'Competition Status' --> must 'Match Status'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#875]
## Description

'Competition Status' --> must 'Match Status'
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the contest starts : Register
When the coding starts
Click ENTER
Check the label : Competition Status
## Expected Result

Must fix the Issue, 
- 'Competition Status' --> must 'Match Status'
## Actual Result

Competition Status
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![34](https://cloud.githubusercontent.com/assets/4592712/4708453/738b85b4-5897-11e4-85bb-a8472c468a24.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#117
