### ISSUE TITLE
[a41500000000XRZ] [Light Theme][Common] "R" text in the tables are not formatted as BOLD

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#876]
## Description

[a41500000000XRZ] [Light Theme][Common] "R" text in the tables are not formatted as BOLD
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Go to Completed Match
Click ENTER
1. Check the 'R' in 'Match Summary' (Room, Division I and Division II)

Click 'Challenges & Leaderboard'
1. Check the 'R' in 'Leaderboard'

Similar to: https://github.com/cloudspokes/arena-web/issues/757
## Expected Result

Must fix the Issue, 
- Must formatted as BOLD
## Actual Result

"R" text in the tables are not formatted as BOLD
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![39 1](https://cloud.githubusercontent.com/assets/4592712/4708522/4ec89a4a-5898-11e4-9e41-58aa44af5036.png)
![39 2](https://cloud.githubusercontent.com/assets/4592712/4708523/4ef3ba9a-5898-11e4-8a75-d97ddebb181d.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#116
