### ISSUE TITLE
[a41500000000XRZ] Logo is not properly removed

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#877]
## Description

[a41500000000XRZ] Logo is not properly removed
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Go to Completed Match
Click ENTER
Resize the browser

Similar to: https://github.com/cloudspokes/arena-web/issues/617
## Expected Result

Must fix the Issue, 
- Must remove the Logo from that size
## Actual Result

Logo is not properly removed
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![42](https://cloud.githubusercontent.com/assets/4592712/4708595/b5067494-5898-11e4-8a81-2e7e61ef8903.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#115
