### ISSUE TITLE
(X) clear icon is not align with in the textbox in IE

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#878]
## Description

(X) clear icon is not align with in the textbox in IE
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the Chat Area
Click 'Search'
Enter any text

Check the (x) clear button
## Expected Result

Must fix the Issue, 
- Must Align it properly OR
- If this is generated by IE, If (X) clear button is not nessacery must hide it in IE
## Actual Result

(X) clear icon is not align with in the textbox in IE
## Environment

IE 11 in Windows 7
## Image

![43](https://cloud.githubusercontent.com/assets/4592712/4708841/e519b752-589a-11e4-9663-40591505a007.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#89
