### ISSUE TITLE
'x events' Must --> 'x Matches'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#879]
## Description

'x events' Must --> 'x Matches'
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Go to 'Profile Overview & Important Messages'
Check the text : 'x events'
## Expected Result

Must fix the Issue, 
- 'x events' Must --> 'x Matches'
## Actual Result

'x events'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![44](https://cloud.githubusercontent.com/assets/4592712/4708997/21915e1e-589c-11e4-9427-bae6e4e73327.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#90
