### ISSUE TITLE
When we switch between 'Reply to' and 'Whisper', The username drop down won't reset

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#88]
## Description

When we switch between 'Reply to' and 'Whisper', The username drop down won't reset
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as twight/password

Switch the theme --> Light Theme
In the Chat room
Select 'Reply To'
Enter the message : You must also be the first person to report the issue and submit it while submission phase is open.  any issues before and after the submission phase will NOT be counted.
Press ENTER
Select 'whisper'
## Expected result

Must fix the Issue. Must clear the Username
## Actual result

When we switch between 'Reply to' and 'Whisper', The username drop down won't reset
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![39](https://cloud.githubusercontent.com/assets/4592712/3335862/fef791a4-f81d-11e3-9d28-e9421de5268a.png)

**Comment by skyhit** [comment]
not need to clear.
