### ISSUE TITLE
[Common] Layout Issue in the List view

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#880]
## Description

[Common] Layout Issue in the List view
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Go to 'Match Plan'
Click List View
Click '<' and go to February

Try to scroll the list
## Expected Result

Must fix the Issue, 
## Actual Result

Layout Issue in the List view
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![45](https://cloud.githubusercontent.com/assets/4592712/4709082/d08f4ac0-589c-11e4-8674-ea0370e73647.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
@skyhit @huangqun I know we are working on this for the next release, but for now we should just clear the sample text.

**Comment by skyhit** [comment]
@mdesiderio we just need to clear the data here - https://github.com/cloudspokes/arena-web/blob/master/app/data/contest-plan.json

**Comment by mdesiderio** [comment]
@skyhit I have fixed this in the QA environment, please close the issue when the challenge is complete.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#91
