### ISSUE TITLE
Coder Rating color is not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#882]
## Description

Coder Rating color is not visible
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Select a Match
http://qa.arena.topcoder.com/#/u/contests/16248/
Click ENTER
Go to Chat Window
Check the user handle in 'Who's here (x)
## Expected Result

Must fix the Issue, 
- Must display the user rating color
## Actual Result

Coder Rating color is not visible
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![47](https://cloud.githubusercontent.com/assets/4592712/4709658/3731c376-58a1-11e4-9a46-07fdb9b48443.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#98
