### ISSUE TITLE
'Rating Key' Scroll bar Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#883]
## Description

'Rating Key' Scroll bar Layout Issue
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Select a Match
http://qa.arena.topcoder.com/#/u/contests/16248/
Click ENTER
Go to Chat Window
in the 'Rating Key' section
Scroll the list down
## Expected Result

Must fix the Issue, 
- When we scroll the list to the bottom, Must display the bottom edge of the scroll bar
- Now it is hidden
## Actual Result

'Rating Key' Scroll bar Layout Issue
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![48](https://cloud.githubusercontent.com/assets/4592712/4709663/443acdce-58a1-11e4-8d7a-ac2dde67cfff.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#99
