### ISSUE TITLE
Can't enter answer to the 'Eligibility Requirements' Question

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#885]
## Description

Can't enter answer to the 'Eligibility Requirements' Question
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the registration phase is on
Click Register
Try to enter answer to the 'Eligibility Requirements' Question
## Expected Result

Must fix the Issue, 
- Able to enter text to the textbox
## Actual Result

Can't enter answer to the 'Eligibility Requirements' Question
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![50](https://cloud.githubusercontent.com/assets/4592712/4713063/64eed6f4-58d9-11e4-8d7e-58332924e076.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
