### ISSUE TITLE
Facebook send button is not working

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#886]
## Description

Facebook send button is not working
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the registration phase is on
Click Register
Fill all the questions
Click Register

Check the message : While you wait, you can challenge friends to participate in the match with you via FB or Twitter
Click on FB button
## Expected Result

Must fix the Issue, 
- Must able to share
## Actual Result

Facebook send button is not working
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![51](https://cloud.githubusercontent.com/assets/4592712/4713105/96747fd4-58da-11e4-833b-48b6ab8a7f6d.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#114
