### ISSUE TITLE
[$50] '1' displayed on the 'Challenges & Leaderboard' page

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#887]
## Description

'1' displayed on the 'Challenges & Leaderboard' page
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Register to a Match
Before the coding phase starts
Click ENTER
Click the 'Challenges & Leaderboard' hyperlink
Check the 'Division I Leaderboard Table' or 'Division I Leaderboard'
## Expected Result

Must fix the Issue, 
- Must not display '1' when there is only one page 
## Actual Result

'1' displayed on the 'Challenges & Leaderboard' page
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![2](https://cloud.githubusercontent.com/assets/4592712/4713162/cc2a25c4-58db-11e4-9c76-5097841ce00a.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
@skyhit @huangqun we should hide the pagination control when there is only one page

**Comment by huangqun** [comment]
@mdesiderio @skyhit I'll include this in the bug bounty

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
