### ISSUE TITLE
Layout issue in the 'Room' Table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#888]
## Description

Layout issue in the 'Room' Table
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Click ENTER in the completed Contest
Click Room in the 'Match Summary'
Check the data and Table headers
## Expected Result

Must fix the Issue, 
- Must align the data with the Column Header
## Actual Result

Layout issue in the 'Room' Table
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![30](https://cloud.githubusercontent.com/assets/4592712/4713190/48640ef2-58dc-11e4-906c-fdcc089e9e7f.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#113
