### ISSUE TITLE
[$50] [a41500000000YNd] When double clicking the name of the class of a problem to copy / paste, more than just the name is selected

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#889]
## Description

[a41500000000YNd] When double clicking the name of the class of a problem to copy / paste, more than just the name is selected
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the contest starts : Register
When the coding starts
Click ENTER
Open the Problem
In the Code editor
Double click on the class name

https://github.com/cloudspokes/arena-web/issues/823
## Expected Result

Must fix the Issue, 
## Actual Result

When double clicking the name of the class of a problem to copy / paste, more than just the name is selected
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![35](https://cloud.githubusercontent.com/assets/4592712/4713209/b424e134-58dc-11e4-9de4-33f37c36aebb.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
