### ISSUE TITLE
handle color should not be white if a user is admin

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#89]
1. login as heffan
2. in the chat area, then choose to Whisper heffan

expected: "heffan" should not be in white color. I should follow the applet arena.

actual: see screenshot

![cl](https://cloud.githubusercontent.com/assets/4590317/3335909/0f68244e-f81f-11e3-8897-a5691d06612b.jpg)

**Comment by skyhit** [comment]
duplicated
