### ISSUE TITLE
[a41500000000XRZ] When we resize the Problem statement area fully by mouse icon won't change to Collapse

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#890]
## Description

[a41500000000XRZ] When we resize the Problem statement area fully by mouse icon won't change to Collapse
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Registratino starts -- > Register
After the Coding Phase starts
Click ENTER
In the Problem section open it
Resize the Problem Statement to the bottom (Full width)
Check the icon

Similar to: https://github.com/cloudspokes/arena-web/issues/801
## Expected Result

Must fix the Issue, 
- Icon Must change to Collapse
## Actual Result

When we resize the Problem statement area fully by mouse icon won't change to Collapse
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![37](https://cloud.githubusercontent.com/assets/4592712/4713230/02c9efe6-58dd-11e4-9578-7c70f7375fd0.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#112
