### ISSUE TITLE
'(c)2003, TopCoder, Inc. All rights reserved.' must --> '(c)2014, TopCoder, Inc. All rights reserved.'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#891]
## Description

'(c)2003, TopCoder, Inc. All rights reserved.' must --> '(c)2014, TopCoder, Inc. All rights reserved.'
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Register to a Match
When the coding phase starts
Open a Problem
Scroll down the 'Problem Area'

Check the copyright : '(c)2003, TopCoder, Inc. All rights reserved.'
## Expected Result

Must fix the Issue, 
- '(c)2003, TopCoder, Inc. All rights reserved.' must --> '(c)2014, TopCoder, Inc. All rights reserved.'
## Actual Result

'(c)2003, TopCoder, Inc. All rights reserved.'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![41](https://cloud.githubusercontent.com/assets/4592712/4713240/2682a5c2-58dd-11e4-9c5d-d872275130b8.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
this is not a problem.
