### ISSUE TITLE
[a41500000000XRZ] Blank coding area displayed when we expand or collapse

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#892]
## Description

[a41500000000XRZ] Blank coding area displayed when we expand or collapse
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Expand the Coding Area --> Code Hides

OR

In the Coding Phase
Expand the Coding area
Enter any code
Collapse the Coding Area --> Code Hides

Related To : https://github.com/cloudspokes/arena-web/issues/783
## Expected Result

Must fix the Issue, 
- Must display the code
## Actual Result

Blank coding area displayed when we expand or collapse
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![52](https://cloud.githubusercontent.com/assets/4592712/4713275/1a2459b4-58de-11e4-9d6e-fe2d4c6b150e.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
this is still happening, it should be fixed.

**Comment by dmessing** [comment]
Is this fixed?

**Comment by skyhit** [comment]
should be, I will double check it.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#111
