### ISSUE TITLE
Go to Line won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#893]
## Description

Go to Line won't work
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Enter 40 in the 'Go To'
Press ENTER
## Expected Result

Must fix the Issue, 
- When we enter an vaue and click enter must go to the exact line number
## Actual Result

Go to Line won't work
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![53](https://cloud.githubusercontent.com/assets/4592712/4713294/ac7a46fc-58de-11e4-9716-8845c16d78c3.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
