### ISSUE TITLE
[a41500000000XRZ] 'Test Report' model goes beyond the screen area

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#895]
## Description

'Test Report' model goes beyond the screen area
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Enter any code
Click Expand !!! Important

Click Compile
Click 'Test Panel
Select All 
Click RUN TEST
Click Collapse

Similar : https://github.com/cloudspokes/arena-web/issues/784
## Expected Result

Must fix the Issue, 
- Must display fully
## Actual Result

Some Error messages in the 'Test Report' is not fully seen
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![55](https://cloud.githubusercontent.com/assets/4592712/4713388/44ddc986-58e0-11e4-90ab-08ebec0c0a37.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#109
