### ISSUE TITLE
[$50] [a41500000000XRZ] Language : Drop down is not closing when we select an item

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#896]
## Description

[a41500000000XRZ] Language : Drop down is not closing when we select an item
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Expand the 'Coding Area'
Click Editor
Click on the Language Drop down
Select a Language

Similar : https://github.com/cloudspokes/arena-web/issues/806
## Expected Result

Must fix the Issue, 
- Language : Drop down must close when we select an item
## Actual Result

Language : Drop down is not closing when we select an item
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![56](https://cloud.githubusercontent.com/assets/4592712/4713428/db0647c6-58e0-11e4-9d47-6d5de0a64bee.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by clevertension** [comment]
i am working on it

**Comment by huangqun** [comment]
fixed
