### ISSUE TITLE
Coding window scroll bar is not match with the other scroll bars

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#898]
## Description

Coding window scroll bar is not match with the other scroll bars
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Click ENTER in the contest
Open the Problem
Check the Coding section scroll bar
## Expected Result

Must fix the Issue, 
- Must have the small gray scroll bar as others
## Actual Result

Coding window scroll bar is not match with the other scroll bars
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/4713531/dd34f554-58e2-11e4-993c-a4f4afc3215b.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
this is a limitation of using code mirror.
