### ISSUE TITLE
Sometimes 'Admin' posts display as lightspeed> (To Admin) heffan: ASAs

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#90]
## Description

Sometimes 'Admin' posts display as lightspeed> (To Admin) heffan: ASAs
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as lightspeed/password

Switch the theme --> Light Theme
In the Chat room
Waitsome time 2-3mins (Idle)
Select 'Admins'
Enter the message : You must also be the first person to report the issue and submit it while submission phase is open.  any issues before and after the submission phase will NOT be counted.
Press ENTER

Stage: When the challenge Phase ends ( 1 min left)
## Expected result

Must fix the Issue. Must display as lightspeed> Admins heffan: ASAs
## Actual result

Sometimes 'Admin' posts display as lightspeed> (To Admin) heffan: ASAs
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![40](https://cloud.githubusercontent.com/assets/4592712/3335903/b471b730-f81e-11e3-8de2-81e331304e94.png)

**Comment by delemach** [comment]
@sdgun - I don't fully understand the bug. Can you please explain a bit more?

**Comment by sdgun** [comment]
When we send a message to the admin; the 'To Admin' text must not display with in the brackets
Like:  lightspeed> Admins heffan: ASAs

**Comment by skyhit** [comment]
can not reproduce anymore? can you double check?

**Comment by sdgun** [comment]
Yes, can not reproduce anymore
