### ISSUE TITLE
Rate buttons are not working

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#900]
## Description

Rate buttons are not working
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Open the Problem
In the Code Editor

Click Rate + or -
## Expected Result

Must fix the Issue, 
## Actual Result

Rate buttons are not working
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![59](https://cloud.githubusercontent.com/assets/4592712/4713569/8e6a7ca4-58e3-11e4-957b-f7d1962c3cad.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
not implemented yet.
