### ISSUE TITLE
Can't enter more than 1 extra Test cases

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#901]
## Description

Can't enter more than 1 extra Test cases
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Open the Problem
In the Code Editor
Enter the code
Click Compile

Click Test Panel
Click Add
Enter data
Click Add again
Try to add Data
## Expected Result

Must fix the Issue, 
- Able to add more than one extra test cases
## Actual Result

Can't enter more than 1 extra Test cases
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![60](https://cloud.githubusercontent.com/assets/4592712/4713599/21885efc-58e4-11e4-9a79-46638a23e040.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
I see there are two Custom Test Case added.

**Comment by sdgun** [comment]
Yes, but can't enter parameter for the 2nd test case

**Comment by huangqun** [comment]
For me it failed on the 3rd test case, 1st and 2nd both worked

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
