### ISSUE TITLE
After Ran the test Report, Check boxes are not resetted in the Test panel

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#902]
## Description

After Ran the test Report, Check boxes are not resetted in the Test panel
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Open the Problem
In the Code Editor
Enter the code
Click Compile

Click Test Panel
Click Select All
Click RUN TEST
Click Test Panel again
## Expected Result

Must fix the Issue, 
- Must reset the Checkboxes, because in the next attemp sometimes we won't run the previous Test cases
- it will cost the time of the coder to uncheck the checkboxes
## Actual Result

After Ran the test Report, Check boxes are not resetted in the Test panel
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![61](https://cloud.githubusercontent.com/assets/4592712/4713653/0a06b8ea-58e5-11e4-92db-bb1750b177f1.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
no need to reset.
