### ISSUE TITLE
[Common] Filter sections remembered what ever we enter into it

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#903]
## Description

[Common] Filter sections remembered what ever we enter into it
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Contest Ends
Click ENTER in the contest
Click 'Challenges & Leaderboard'
Click 'Filter; in Room Leaderboard or Challengers or Challenges
Enter any handle name
Click Filter'
Now expand the filter again
Enter 'asdasdsad'
Close the Filter

Open the Filter again
## Expected Result

Must fix the Issue, 
- Must not display the irrelavent data in the filters
## Actual Result

[Common] Filter sections remembered what ever we enter into it
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![Uploading 20.png . . .]()
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
missing screenshot.
