### ISSUE TITLE
[$50] Coder History pop up layout issue in Date

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#904]
## Description

Coder History pop up layout issue in Date
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Contest Ends
Click ENTER in the contest
Click on a Code History icon of a coder
Check the Time Column
## Expected Result

Must fix the Issue, 
- Must display the Date in one line
- The Column name must Date/Time
## Actual Result

Coder History pop up layout issue in Date
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![12](https://cloud.githubusercontent.com/assets/4592712/4713874/d1bbb144-58e8-11e4-86d7-32f06d584390.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
