### ISSUE TITLE
[$50] Layout issue when we sort the column by '#' in Challenges Table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#905]
## Description

Layout issue when we sort the column by '#' in Challenges Table
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Contest Ends
Click ENTER in the contest
eg: http://qa.arena.topcoder.com/#/u/contests/15184/
Click 'Challenges & Leaderboard'
Click '#' in the Challenges Table
## Expected Result

Must fix the Issue, 
- Must display the Sort icon and '#' in one line
## Actual Result

Layout issue when we sort the column by '#' in Challenges Table
## Environment

Chrome 37.0.2062.102 m in Windows 7
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/4713887/f312404c-58e8-11e4-9f4c-743599e2d1b5.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by clevertension** [comment]
i am working on it

**Comment by huangqun** [comment]
fixed
