### ISSUE TITLE
[$50] Search Icon in the 'Challenges' Table won't work

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#906]
## Description

Search Icon in the 'Challenges' Table won't work
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Contest Ends
Click ENTER in the contest
Click 'Challenges & Leaderboard'
Click 'Search' icon in the Challenges Table
## Expected Result

Must fix the Issue, 
- Search icon must work
## Actual Result

Search Icon in the 'Challenges' Table won't work
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![15](https://cloud.githubusercontent.com/assets/4592712/4713905/1b18ca8e-58e9-11e4-8115-4056ac433441.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
@huangqun  @mdesiderio  what is the expected result ?

**Comment by dedywahyudi** [comment]
Magnifying icon should access Coder History Modal Window
https://www.dropbox.com/sh/ffdyw947556z9ym/AADNH0c77ymmaevKPk01NCVDa?dl=0

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
