### ISSUE TITLE
[$30] Won't have hand cursor in the clickable column data in the 'Coder History' pop up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#907]
## Description

Won't have hand cursor in the clickable column data in the 'Coder History' pop up
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Contest Ends
Click ENTER in the contest
Click 'Challenges & Leaderboard'
Go to 'Room Leaderboard'
Click on 'Coder History' icon
Click on column data; Columns : Time, Action, R, Handle, Problem, Score
## Expected Result

Must fix the Issue, 
- Must have hand cursor in the clickable data columns
- Columns : Time, Action, R, Handle, Problem, Score
## Actual Result

Won't have hand cursor in the clickable column data in the 'Coder History' pop up
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![18](https://cloud.githubusercontent.com/assets/4592712/4713921/5577683e-58e9-11e4-8537-53140544abec.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
