### ISSUE TITLE
Message display Order issue in Notification center

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#908]
## Description

Message display Order issue in Notification center
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Open the Problem
Enter a code and compile
Wait till System test phase comes
After that close the Pop up notification
Click Message icon
Check the order

Challenge Phase is ending displayed before Pending System Phase started
This happens if the messages are posted same time
## Expected Result

Must fix the Issue, 
- Must display the Latest first
## Actual Result

Message display Order issue in Notification center
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![62](https://cloud.githubusercontent.com/assets/4592712/4713976/67491ca0-58ea-11e4-8981-2ba2f16944b3.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
looks like it is related to backend logic.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#107
