### ISSUE TITLE
"System test" and "System tests" should be consistent

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#91]
1. load an SRM
2. register as ksmith
3. submit a solution and wait for system test

expected: the text "System test" and "System tests" should be consistent
actual: see screenshot
![sy](https://cloud.githubusercontent.com/assets/4590317/3335993/cafe93ae-f820-11e3-8cea-25b4b611ff74.jpg)

**Comment by skyhit** [comment]
known issue, and being fixed in another contest.
