### ISSUE TITLE
Layout Issue when we have Long test Case in Test Report

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#911]
## Description

Layout Issue when we have Long test Case in Test Report
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase
Open the Problem
Enter a code and compile
Click Test Panel
Select All
Click RUN TEST
Check the Test Report (eg: Test case 4)
## Expected Result

Must fix the Issue, 
- Must maintain the 'Executed', 'x.xxMB' and 'xx ms' in one line
## Actual Result

Layout Issue when we have Long test Case in Test Report
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![63](https://cloud.githubusercontent.com/assets/4592712/4717274/bf0a0ee0-5912-11e4-9cf5-192cc6888649.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#105
