### ISSUE TITLE
[a41500000000XRZ] When we click 'Yes' to the Room Assignment Notification in Messages section, it redirect the page to wrong place

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#912]
## Description

When we click 'Yes' to the Room Assignment Notification in Messages section, it redirect the page to wrong place
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click Messages
Click Yes in the Room Assignment Notification in Messages

Related to : https://github.com/cloudspokes/arena-web/issues/777
## Expected Result

Must fix the Issue, 
- Must go to the Assigned Room page
## Actual Result

When we click 'Yes' to the Room Assignment Notification in Messages section, it redirect the page to wrong place
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![64](https://cloud.githubusercontent.com/assets/4592712/4719019/4015a9be-5926-11e4-922d-1e4572ea7163.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
