### ISSUE TITLE
Notifications goes beyond the Browser area

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#913]
## Description

Notifications goes beyond the Browser area
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Do the Coding and Wait till the Match Completed
Don't close any notifications

Check them
## Expected Result

Must fix the Issue, 
- If the max notification reached, Last Notification must remove automatically 
## Actual Result

Notifications goes beyond the Browser area
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![65](https://cloud.githubusercontent.com/assets/4592712/4721124/6a62d3e4-5936-11e4-8ea3-afc3cfcfb64e.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#104
