### ISSUE TITLE
[a41500000000YNd] Full content is not visible

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#914]
## Description

[a41500000000YNd] Full content is not visible
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Go to completed Match
Click ENTER
Click 'Coder History' in 'Match Summary' (eg: sdgunqabughunt1)
Click 'System Tester' on 10-21-2014 10:26:59  
Check the Model
All the content is not shown

https://github.com/cloudspokes/arena-web/issues/722
## Expected Result

Must fix the Issue, 
- Must display the full content, If there is no room must implement scroll bars
## Actual Result

Full content is not visible
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![36](https://cloud.githubusercontent.com/assets/4592712/4721195/04c34a18-5937-11e4-8c18-12eec01c25b0.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
