### ISSUE TITLE
[$25] [Light Theme] Can't see the Selected Match from the 'Active Matches'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#915]
## Description

[Light Theme] Can't see the Selected Match from the 'Active Matches'
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
In the 'Active Matches' section
Click on the pagination number
## Expected Result

Must fix the Issue, 
- Must use contrast color
- Little Darker 
## Actual Result

[Light Theme] Can't see the Selected Match from the 'Active Matches'
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![66](https://cloud.githubusercontent.com/assets/4592712/4721995/a1d5ea54-593c-11e4-9a2a-b7fc5d1c09c9.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by ghost** [comment]
working on it

**Comment by huangqun** [comment]
fixed
