### ISSUE TITLE
[Light Theme] 'Yellow' rated user handles are not display properly

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#916]
## Description

[Light Theme] 'Yellow' rated user handles are not display properly
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Click ENTER in the completed Contest
Go to Chat Room section

Check the background color in the 'Registrants' section
## Expected Result

Must fix the Issue, 
- Must use different background color in the 'Registrants' section
## Actual Result

[Light Theme] 'Yellow' rated user handles are not display properly
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![31](https://cloud.githubusercontent.com/assets/4592712/4723181/8e6e593e-5945-11e4-9552-933b388c5cef.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
it is fine for current situation.
