### ISSUE TITLE
RegressionTest Plan #1 : Not able to login

### ISSUE THREAD

**Issue by tejeswarbharath** [cloudspokes/arena-web#919]
After getting verified from the email , when hit the url : https://qa.arena.topcoder.com/#/a/home ,it is automatically logging in.Since in the alternate tab we have verified the email. Now if logged out and try to log in again, it's showing "invalid username/password.please try again"

**Comment by skyhit** [comment]
what is your testing handle?

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#103
