### ISSUE TITLE
Regression Test Plan #2 : Facebook Credentials Validation

### ISSUE THREAD

**Issue by tejeswarbharath** [cloudspokes/arena-web#920]
With Facebook credentials taken into account for Sign up.The Sign Up form validation some times do not satisfy Facebook details such as the length of Username should be between 2 to 15.
Suppose if taken into consideration increase the length of username to maximum extent in sign up if Facebook credentials are taken into consideration.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#102
