### ISSUE TITLE
[$50] Room pagination and Active Matches pagination overlaps

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#921]
## Description

Room pagination and Active Matches pagination overlaps
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to Past Completed Match : Single Round Match 547
In the 'Active Matches' section
Click Rooms
## Expected Result

Must fix the Issue, 
- Must not overlap
## Actual Result

Room pagination and Active Matches pagination overlaps
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![67](https://cloud.githubusercontent.com/assets/4592712/4741427/15c88f1e-5a16-11e4-84b7-7123ca23fbc2.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by gus-costa** [comment]
working

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#101
