### ISSUE TITLE
[Common] 'Room  Leaderboard' List disappears when we scroll up

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#922]
## Description

[Common] 'Room  Leaderboard' List disappears when we scroll up
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Open a completed Contest (Click ENTER)
Click 'Challenges & Leaderboard '
In the 'Room  Leaderboard'
Filter the list from a handle
Now Click Expand 
Now Click Collapse
Click Filter and Select 'All Handles'
Click Filter
Scroll the List up
Check the 'Room  Leaderboard' List
## Expected Result

Must fix the Issue, 
- Must not hide the List
## Actual Result

 'Room  Leaderboard' List disappears when we scroll up
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![23](https://cloud.githubusercontent.com/assets/4592712/4741493/d43bfa62-5a16-11e4-83b7-9034e90aee0d.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
