### ISSUE TITLE
'Opened', 'Unopened' and 'Unopened' text are not sorted properly in the 'Room Leaderboard' Table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#923]
## Description

'Opened', 'Unopened' and 'Unopened' text are not sorted properly in the 'Room Leaderboard' Table
## Steps

Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
When the Contest Ends
Click ENTER in the contest
Click 'Challenges & Leaderboard'
Go to 'Room Leaderboard'
Click on the '500', '1000, abd '250' scores
Sort Desc by above columns
## Expected Result

Must fix the Issue, 
- Must properly sort 'Opened', 'Unopened' and 'Unopened' text
## Actual Result

'Opened', 'Unopened' and 'Unopened' text are not sorted properly in the 'Room Leaderboard' Table
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![16](https://cloud.githubusercontent.com/assets/4592712/4741564/80f4f9f2-5a17-11e4-9558-39ba2f2b0afb.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
the sorting is based on score, not text.
