### ISSUE TITLE
cannot sort the table by column "Problem" header on coder history table

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#927]
mac 10.10, chrome 38
1. login, go into a room for a completed match
2. view coder history
3. click the column header "Problem"

expected: should be sortable by column header "Problem" like in the applet arena.

actual: not sortable, see screenshots.

![qq20141023-4](https://cloud.githubusercontent.com/assets/4590317/4751310/411c589a-5a9c-11e4-8822-6bd9437a254b.jpg)

![qq20141023-5](https://cloud.githubusercontent.com/assets/4590317/4751318/65ec9892-5a9c-11e4-9558-4037d84694a0.jpg)

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / #979
