### ISSUE TITLE
notification misses a word "Test"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#928]
mac 10.10, chrome 38
1. login, wait for the notification of system test phase
2. observe the top right

expected: it should include the word "Test"

actual: see screenshot

![qq20141023-6](https://cloud.githubusercontent.com/assets/4590317/4751344/ced371b4-5a9c-11e4-893d-de2cec323af1.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#96
