### ISSUE TITLE
text should be aligned left in the coder history info modal

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#929]
mac 10.10, chrome 38
1. login, go into a room of a completed match
2. view coder history
3. click on a handle, observe

expected: the text should be aligned left, like in the applet arena does.

actual: see screenshot.

![qq20141023-8](https://cloud.githubusercontent.com/assets/4590317/4751440/3a9fde9a-5a9e-11e4-9601-56ab2f25663c.jpg)

**Comment by skyhit** [comment]
not needed. it is purposed to be center aligned.
