### ISSUE TITLE
date/time format should be consistent

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#930]
mac 10.10, chrome 38
1. login, go into a room of a completed match
2. view coder’s history
3. wait for a notification to appear, compare the date/time format

expected: date/time format should be consistent

actual: see screenshot.

![qq20141023-9](https://cloud.githubusercontent.com/assets/4590317/4751491/cee08fa0-5a9e-11e4-8b8b-5807331df0f6.jpg)

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#95
