### ISSUE TITLE
Pop up displayed when we sort the table

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#931]
## Description

Pop up displayed when we sort the table
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on a Column Header
## Expected Result

Must fix the Issue, 
- Must not display a pop up for sorting
## Actual Result

Pop up displayed when we sort the table
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![68](https://cloud.githubusercontent.com/assets/4592712/4753284/c20be24a-5ab5-11e4-99ae-7cb9dcd1f622.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
this is correct, the sorting is backend service.
