### ISSUE TITLE
Search won't work in Practices Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#932]
## Description

Search won't work in Practices Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on the Search
Enter : GraphWalkWithProbabilities
Click Search Icon
## Expected Result

Must fix the Issue, 
- Search must work
## Actual Result

Search won't work in Practices Room
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![69](https://cloud.githubusercontent.com/assets/4592712/4753304/fd2b737c-5ab5-11e4-9848-fbbf414b179b.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
click enter will trigger the search.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#94
