### ISSUE TITLE
Clear button shows when we paste a text to Search in Practices Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#933]
## Description

Clear button shows when we paste a text to Search in Practices Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on the Search
Enter : GraphWalkWithProbabilities
Press ENTER

Now click Clear
Now paste the 'GraphWalkWithProbabilities' in Search box
Check the 'Clear' button
## Expected Result

Must fix the Issue, 
- Must not display the Clear icon
## Actual Result

Clear button shows when we paste a text to Search in Practices Room
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![Uploading 70.png . . .]()
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
missing image, incomplete.
