### ISSUE TITLE
'Points' Drop Down is too large in Practices Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#934]
## Description

'Points' Drop Down is too large in Practices Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on the 'Filter'
Expand the 'Points' Drop down
## Expected Result

Must fix the Issue, 
- Must fix the width to the Controller size or max content size
- Now it has fixed width and it is very large
## Actual Result

'Points' Drop Down is too large in Practices Room
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![71](https://cloud.githubusercontent.com/assets/4592712/4753430/f917be98-5ab6-11e4-86a9-e5a6b5452acc.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#93
