### ISSUE TITLE
Delete the text in search box won't reset the Search list in Practices Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#935]
## Description

Delete the text in search box won't reset the Search list in Practices Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on the 'Search'
Enter : CucumberMarket
Press ENTER: CucumberMarket
Check the List
## Expected Result

Must fix the Issue, 
- Must reset the search list
## Actual Result

Delete the text in search box won't reset the Search list in Practices Room
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![72](https://cloud.githubusercontent.com/assets/4592712/4753483/65d7d018-5ab7-11e4-9c67-b813c6c20ed5.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
we are not support instant search, you should click enter button
