### ISSUE TITLE
Table sorting happens when we click above the Column headers

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#936]
## Description

Table sorting happens when we click above the Column headers
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on the marked area in the screen shot
## Expected Result

Must fix the Issue, 
- Must sort the table if user click on the column header name
## Actual Result

Table sorting happens when we click above the Column headers
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![74](https://cloud.githubusercontent.com/assets/4592712/4753604/74fc531a-5ab8-11e4-9b19-ae3d949e74cc.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
that is fine.
