### ISSUE TITLE
250-1000 Filter won't display in Practices Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#937]
## Description

250-1000 Filter won't display in Practices Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on the 'Filter'
Type : Single
Difficulty : Easy
Status : Viewed
Points : 250-1000

Click Filter

Check the Search bar
## Expected Result

Must fix the Issue, 
- Must display the 250-1000
## Actual Result

250-1000 Filter won't display in Practices Room
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![73](https://cloud.githubusercontent.com/assets/4592712/4753617/881f6c66-5ab8-11e4-8b2f-486e53f7de30.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#66
