### ISSUE TITLE
Coding Area issue in Practices Room

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#938]
## Description

Coding Area issue in Practices Room
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Go to 'Practices Room'
http://qa.arena.topcoder.com/#/u/practiceProblemList

Click on a Status: New Problem Name
eg: CandidatesSelection

http://qa.arena.topcoder.com/#/u/practiceCode/16243/39940/1/322209

Enter dummy data
eg: sajhkasdhkashda

Click Compile
Click Submit
## Expected Result

Must fix the Issue, 
- Must restrict dummy data compilation
- Must restrict dummy data Cubmit
- Able to add test data and Run the Test
## Actual Result

Coding Area issue in Practices Room
- Can enter dummy code and Compile
- Can submit dummy code 
- No Test Data in the Panel, or can add new one
- Overall this section is not properly designed as Coding in Arena space
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7
## Image

![75](https://cloud.githubusercontent.com/assets/4592712/4753726/71b49234-5ab9-11e4-8ebf-07bea01ae859.png)
## Bug Hunt

Web Arena QA for 201410 Release

**Comment by skyhit** [comment]
this is same as practice room in arena. the detection is not easy.
