### ISSUE TITLE
'admin' in the Chat area must --> 'Admins'

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#94]
## Description

'admin' in the Chat area must --> 'Admins'
## Steps

Open the Web Areana : http://arena.cloud.topcoder.com:3000
Login as twight/password

Switch the theme --> Light Theme
In the Chat room
Select : 'Admins' from the First Drop Down
Then Enter text
Press Enter

Check the Text : admins
## Expected Result

Must fix the Issue. Must 'Admins'
## Actual Result

'admin' 
## Environment

Chrome 35.0.1916.114 m, FF 29.0.1, IE 10+, Safari 5.1.7 in Window 7
## Image

![43](https://cloud.githubusercontent.com/assets/4592712/3338408/63bc4412-f85b-11e3-99b9-56686353ef1c.png)

**Comment by skyhit** [comment]
same as arena applet.
