### ISSUE TITLE
Contest Creation Wizard popup shows at the bottom of the page

### ISSUE THREAD

**Issue by huangqun** [cloudspokes/arena-web#949]
It should be shown in the center, NOT at the bottom of the page.

**Comment by flytoj2ee** [comment]
As I remember, I have changed the popup location several times.  

Do you mean the center of page? Or the center of screen?

At first, it's used the center of screen, and then it's changed to top of page for small window size, and it changed to center of page now.

**Comment by ananthhh** [comment]
In hotfix branch, popup is coming at bottom of the window. This is due to some changes in middle. 
I have fixed this in pull request #939 So it should work as expected in dev branch

**Comment by huangqun** [comment]
fixed in https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30046752 / https://github.com/cloudspokes/arena-web/pull/979
