### ISSUE TITLE
it will remove spaces between words and leave only 1 space between words

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#95]
1. login as lightspeed
2. in chat area, enter some text like "hello <20 spaces> hi <20 spaces> hi", post the text

expected: it should not remove spaces in the text

actual: see screenshots
Initial text:
![hi](https://cloud.githubusercontent.com/assets/4590317/3341308/09c80c62-f887-11e3-9f5f-371c3d1de7f8.jpg)

Final:
![wo](https://cloud.githubusercontent.com/assets/4590317/3341315/1addc366-f887-11e3-9a8f-4b0c8b6fd381.jpg)

**Comment by delemach** [comment]
This may be happening on the backend. If so it may not be worth fixing. Check it please in the applet arena.

**Comment by skyhit** [comment]
no, this is happens specific in browser, we need to do conversion, in html, many spaces are displayed as one, we need to convert it into @nbsp; notition
