### ISSUE TITLE
[$50] Empty 'Problem Area' displayed when we expand it and then collapse it

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#957]
1. Hit topcoder QA arena url 
2. Login through valid user 
3. Register for a contest 
4. Enter the coding phase and open a problem 
5. Scroll to the bottom of problem area 
6. Then expand and collapse the problem area

**Comment by shubhendusaurabh** [comment]
@huangqun can't reproduce this issue

**Comment by huangqun** [comment]
@shubhendusaurabh might have been fixed already.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#67
