### ISSUE TITLE
 "Who's here" should be moved up if there are much spaces unused

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#96]
win8, IE11
1. login as ksmith and lightspeed
2. register for an SRM and enter the room
3. first collapse all menus, then click "Registrants"

expected: "Who's here" should not move to bottom.

actual: see screenshots.

Initial:
![initial](https://cloud.githubusercontent.com/assets/4590317/3342210/2311c09c-f890-11e3-9f3a-855e17a946cf.jpg)

Final:
![final](https://cloud.githubusercontent.com/assets/4590317/3342220/32710ee4-f890-11e3-8ee5-1e1d304306d3.jpg)

**Comment by skyhit** [comment]
implement in purpose.
