### ISSUE TITLE
[$30] Hovering mouse on the username changes the color of it, when am on light theme

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#960]
1. Hit url : qa.arena.topcoder.com 
2. Login with valid user 
3. Change to light theme 
4. Hover the mouse on the username

Text color changes 

Screencast : http://screencast.com/t/mWKrr9mfb

**Comment by ghost** [comment]
working on it

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#69
