### ISSUE TITLE
[$10] "Preparing for System test phase" message needs to be modified to remove mentioning of view details

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#961]
1. Hit url : qa.arena.topcoder.com 
2. Login with valid user 
3. Open a Complete match 
4. Once the System phase starts check the message displayed under Competition Status

This message "Please click View Details link in Room Summary to do further actions." needs to be modified to remove mentioning of view details

Scrrencast : http://screencast.com/t/smHTMsyz

**Comment by shubhendusaurabh** [comment]
@huangqun what should the message say?

**Comment by huangqun** [comment]
@mdesiderio what message should we use here? Thanks!

**Comment by mdesiderio** [comment]
We have changed the "View Details" link to "Challenges & Leaderboard". So it should say:

Please click the Challenges & Leaderboard link in Room Summary for details.

FYI @huangqun @shubhendusaurabh

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
