### ISSUE TITLE
[$50] Problem list should not squeeze when current page have less results

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#962]
1. Go to Practice room on web arena
2. Go to last page of the list and notice

List should not be squeezed and pagination should stay at bottom

List squeezes and pagination options are displayed right under the list items

Screencast : http://screencast.com/t/oeOrO1yRLrxy

**Comment by ghost** [comment]
working on it

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#70
