### ISSUE TITLE
[$10] Cosmetic issues on Practice room page

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#963]
Steps to Reproduce  
Go to Practice room on web arena and notice
Expected Result 
1. Page should be labelled as Practice Room 
2. Table header should say "Topcoder Matches Problem List"
Actual Result  
1. Page labelled as Practices Room 
2. Table header says "Topcoder Contests Problem List" 

Screencast : http://screencast.com/t/YA2LyiSBy33m

**Comment by ghost** [comment]
working on it

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#71
