### ISSUE TITLE
[$50] Coder history info page giving error

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#964]
Steps to Reproduce  
1. Hit topcoder QA arena url 
2. Login through valid user 
3. Register for a contest 
4. Enter the coding phase and open a problem 
5. Compile and submit 
6. Wait for challenge phase, challenge some coder and go to Challenges and leaderboard 
7. Click Handle
Expected Result 
Coder history pop up should display
Actual Result  
Page throwing error 

Screencast : http://screencast.com/t/eeU2Nz4thg

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by shubhendusaurabh** [comment]
@huangqun i checked with default usernames. all worked

**Comment by huangqun** [comment]
fixed
