### ISSUE TITLE
[$40] Cosmetic issues int the Test Report window

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#966]
Steps to Reproduce  
1. Hit url : qa.arena.topcoder.com 
2. Login using non admin user 
3. Enter the coding phase for one of the contests 
4. Open any problem and write your code 
5. Compile it then click Test Panel 
6. Mark several or all and click test 
7. Once test report is generated notice
Expected Result 
1. Test report window should be in center like others (coder info,etc) 
2. Test report header should be blue in color
Actual Result  
1. User needs to scroll to bottom to look at the report 
2. Headers background is black

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
