### ISSUE TITLE
[$40] Problem Statement area sometimes gets empty when the area is expand or collapsed

### ISSUE THREAD

**Issue by mdesiderio** [cloudspokes/arena-web#968]
Steps to Reproduce  
1. Hit url : qa.arena.topcoder.com 
2. Login using non admin user 
3. Enter the coding phase for one of the contests 
4. Open any problem and expand collapse the Problem Statement area
Expected Result 
Text displayed in Problem Statement area should not be empty in any case
Actual Result  
Sometimes it displays blank window

**Comment by shubhendusaurabh** [comment]
@huangqun can't reproduce this either

**Comment by sohelH** [comment]
I am also facing the same issue.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#74
