### ISSUE TITLE
"1 minutes" should be "1 minute"

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#98]
1. login as ksmith
2. register for the SRM
3. wait for the challenge phase starts, observe the countdown time

expected: "1 minutes" should be "1 minute"

actual: see screenshot

![1](https://cloud.githubusercontent.com/assets/4590317/3348533/658b2b4a-f933-11e3-814a-0b451f1d2d0c.jpg)

**Comment by skyhit** [comment]
known issue.
