### ISSUE TITLE
auto suggestion feature is needed in the chat room

### ISSUE THREAD

**Issue by winterflame** [cloudspokes/arena-web#99]
1. login as lightspeed and ksmith
2. in the chat text box, enter "ks"

expected: it should automatically display the available user "ksmith" and highlight "ks".

actual: no such feature in the new arena, but its available in the applet arena. See screenshots.

In the applet:
![arena](https://cloud.githubusercontent.com/assets/4590317/3348697/20e15e20-f93c-11e3-843a-36f4d5789713.jpg)
In the new arena:
![auto](https://cloud.githubusercontent.com/assets/4590317/3348699/29a78a34-f93c-11e3-854a-329a6d5292b9.jpg)

**Comment by skyhit** [comment]
not implemented yet.
