### ISSUE TITLE
Typo - "Please wait while the requested problem is loaded. This may take several minutes ..."

### ISSUE THREAD

**Issue by sohelH** [cloudspokes/arena-web#994]
several minutes?

**Comment by Goodwine** [comment]
I don't see any typo tho, do you mean like... the space between "minutes", and "..." ?

**Comment by skyhit** [comment]
any update?

**Comment by sohelH** [comment]
should it be minutes or seconds?

**Comment by Goodwine** [comment]
Welp, that wouldn't be a typo

**Comment by mdesiderio** [comment]
@Goodwine and @sohelH, if you try to open a really old problem, from some of the first SRMs, it could take a couple of minutes for it to load. We are trying to improve the performance, but this message is true in the sense that it sets the right expectation with the users.

I am closing this for now. Thanks!
